### ISSUE TITLE
Unneccessary substitution in dependent pattern matching

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#1018]
In the following example of a type family match, the index is substituted in both cases, breaking the first case. This can be fixed with `generalizing := true` as in the comment, but it would be nicer if the substitution is avoided (or done in the other direction) when possible.
```lean
inductive Fam : Type → Type 1 where
  | any : Fam α
  | nat : Nat → Fam Nat

example (a : α) : Fam α → α /-:= fun x => match (generalizing := true) x with-/
  | Fam.any   => a  -- type mismatch, a has type α : Type but is expected to have type x : Type
  | Fam.nat n => n
```
For a slightly more complex example where the index is not completely unconstrained, here I would hope for the goal `⊢ α`:
```lean
inductive Fam2 : Type → Type → Type 1 where
  | any : Fam2 α α
  | nat : Nat → Fam2 Nat Nat

example (a : α) : Fam2 α β → β /-:= fun x => match (generalizing := true) x with-/
  | Fam2.any   => _
  | Fam2.nat n => n
```

**Comment by Kha** [comment]
@leodemoura Another interesting issue: the underscore does not show the expected type on hover. Apparently the mvar context in the info tree is wrong?
```
inductive Fam : Type → Type 1 where
  | any : Fam α
  | nat : Nat → Fam Nat

set_option pp.rawOnError true
set_option trace.Elab.info true
example (a : α) : Fam α → α /-:= fun x => match (generalizing := true) x with-/
  | Fam.any => _
  | Fam.nat n => n
```
```
...
        [Error pretty printing expression: unknown metavariable '?_uniq.31828'. Falling back to raw printer.]
        ?_uniq.31828 : <failed-to-infer-type> @ ⟨93, 15⟩-⟨93, 16⟩ @ Lean.Elab.Term.elabHole
```

**Comment by leodemoura** [comment]
Preliminary analysis. I found two issues that should be fixed to improve the user experience here.
1- The "discriminant refinement" feature is not refining dependencies. In the first example, it converts 
```lean
example (a : α) (x : Fam α) : α := 
  match x with
  | Fam.any   => a  
  | Fam.nat n => n
```
into
```lean
example (a : α) (x : Fam α) : α := 
  match α, x with
  | _, Fam.any   => a  
  | _, Fam.nat n => n
```
This is sufficient to make sure all patterns can be elaborated, but it does not include the dependency `a : α` as a new discriminant.

2- The variable names for refined variables are often inaccessible. Example: we get `x✝ : Type` in the context instead of ` α : Type`.

**Comment by leodemoura** [comment]
Issue 1 can be addressed by making `generalizing := true` the new default. Note that if the expected type is a proposition, then it is already the default. We didn't do it in the actual code because 

> Motivation: users should have control over the actual `match`-expressions in their programs.

I think this is a good change and make the `match` behavior more uniform.

**Comment by leodemoura** [comment]
Pending: issue 2 & InfoView issue above
