### ISSUE TITLE
Server should identify occurrences of the same mutable variable

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#1036]
Depending on which `x` the cursor is on in the following example, not all `x`s may be highlighted:
```
example : Nat := Id.run do
  let mut x := 1
  x := x + 1
  x
```
When the definition of an fvar overlaps with the use of another fvar, we should conservatively identify them with each other.

Coincidentally, this should also "fix" the highlighting in https://proofassistants.stackexchange.com/a/848/24.

**Comment by larsk21** [comment]
This was fixed in https://github.com/leanprover/lean4/pull/1145, wasn't it?

**Comment by Kha** [comment]
Yes!
