### ISSUE TITLE
RFC: `eapply` and `fapply`

### ISSUE THREAD

**Issue by EdAyers** [leanprover/lean4#1045]
Is it sensible to have `eapply` and `fapply` in core Lean 4? I found a todo in the method body of apply to support the config options needed to implement eapply and fapply. I am happy to implement this todo.

Having eapply and fapply is important for the mathlib port, but they can be implemented in mathlib if they are not wanted in core lean. In any case the implementation of accepting an `ApplyNewGoals` argument to `apply` seems worth doing.

I propose modifying `apply` to accept a default argument `(cfg : ApplyConfig := {})` where ApplyConfig is a structure with one item (so more can be added later). 

```
structure ApplyConfig :=
(newGoals := ApplyNewGoals.nonDependentFirst)

inductive ApplyNewGoals where
  | nonDependentFirst | nonDependentOnly | all
```

Then add additional syntax for `fapply` (`all`) and `eapply` (`nonDependentOnly`) in the same way that the syntax is defined for `apply`. I will copy the docstrings from lean3 

I've implemented this in https://github.com/EdAyers/lean4/tree/ApplyNewGoals

**Comment by arthurpaulino** [comment]
Shortcuts to the commits:
* ["Implement ApplyNewGoals"](https://github.com/EdAyers/lean4/commit/bbf30469c4c741adae08a1b987c46f8ad8afb117)
* ["Add eapply, fapply"](https://github.com/EdAyers/lean4/commit/ee0c606b23699caadc6a28812df9022e14dc865d)

**Comment by leodemoura** [comment]
Thanks for the RFC.

> Is it sensible to have eapply and fapply in core Lean 4?

Sure. Do think they are useful and have good names? I never really liked these names and chose them without too much thinking when we were implementing Lean 3. 

Regarding the actual PR, could you please use the Lean 4 code conventions?
I noticed two things.
- We indent the definition bodies in Lean 4.
- We write structures as follows
```lean
structure ApplyConfig where
  newGoals := ApplyNewGoals.nonDependentFirst
```

**Comment by digama0** [comment]
I have never had cause to use these tactics, and use more structured tactics instead. So I wouldn't mind if this was only exposed in core as `apply (config := {new_goals := .nonDependentFirst})`, and downstream libraries like mathlib4 can add shortcuts for this pattern if desired.

**Comment by EdAyers** [comment]
@digama0 yes I think it's a better idea to expose as a config and then add eapply and fapply in mathlib4 for porting reasons.
