### ISSUE TITLE
invalid mutual definition

### ISSUE THREAD

**Issue by fpfu** [leanprover/lean4#1050]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

mutually recursive definitions produce some unclear error message

### Steps to Reproduce

```lean
universe u

inductive Foo : Type u → Type u → Type (u+1)
| foo {as bs cs: Type u}: Foo as bs → Foo bs cs → Foo as cs               

namespace Foo
  mutual
    def bar    : {as bs: Type u} → Foo.{u} as bs → bs := bar_aux
    def bar_aux: {as bs: Type u} → Foo.{u} as bs → bs 
    | as, bs, foo _ x => x.bar
  end
  termination_by 
    bar     => 0
    bar_aux => 0
  decreasing_by sorry
end Foo
```

**Expected behavior:** this example should be accepted or produce a clearer message

**Actual behavior:** got error

```
invalid mutual definition, result types must be in the same universe level
```

**Reproduces how often:** 100%

### Versions

`nightly-2022-03-17`

### Additional Information

corresponding lean3 code doesn't work either

```lean
universe u

inductive Foo : Type u → Type u → Type (u+1)
| foo {as bs cs: Type u}: Foo as bs → Foo bs cs → Foo as cs               

namespace Foo
  mutual def bar, bar_aux
  with bar     : ∀{as bs: Type u}, Foo as bs → bs | as bs           := bar_aux
  with bar_aux : ∀{as bs: Type u}, Foo as bs → bs | as bs (foo _ x) := x.bar
end Foo
```

**Comment by leodemoura** [comment]
The error message has been improved. It is now
```lean
 error: invalid mutual definition, result types must be in the same universe level, resulting type for `Foo.bar` is
  Foo as bs → bs : Type (u + 1)
and for `Foo.bar_aux` is
  bs : Type u
```
It makes it clear that `Foo.bar` is being interpreted by Lean as a function that returns  `Foo as bs → bs : Type (u + 1)`.

You can write the function as
```lean
namespace Foo
  mutual
    def bar2    : Foo as bs → bs
      | x => bar_aux2 x

    def bar_aux2 : Foo as bs → bs
      | foo _ x => x.bar2

  end
  termination_by
    bar2     x => (sizeOf x, 1)
    bar_aux2 x => (sizeOf x, 0)
end Foo
```
