### ISSUE TITLE
Interactive `#eval` broken

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#106]
Any(?) use of `#eval` currently breaks `lean4-mode` because it generates invalid JSON:
```
#eval 33
```
```
$ bin/lean --json scratch.lean
33{"caption":"eval result","end_pos_col":8,"end_pos_line":1,"file_name":"/home/sebastian/lean/lean/scratch.lean","pos_col":0,"pos_line":1,"severity":"information","text":""}
```
@cipher1024 I'm afraid your recent changes to `IO.println` broke this because `#eval` depends on redirecting `std::cout`:
https://github.com/leanprover/lean4/blob/670243400b5ce744e0ad925d98c55649eeeba737/src/frontends/lean/builtin_cmds.cpp#L386

**Comment by cipher1024** [comment]
Is there a way to do the same with `FILE *`?

**Comment by cipher1024** [comment]
I think what we could do is use `pipe` to capture the output of `IO.println` and then read it. What do you think?

**Comment by Kha** [comment]
Wouldn't `fmemopen` be more appropriate?

**Comment by cipher1024** [comment]
That's a cool function, I didn't know about it! I don't think I would use it here though because the buffer being written to cannot be resized dynamically. I think `open_memstream` could work though.

**Comment by Kha** [comment]
Yes, that's the one!

**Comment by cipher1024** [comment]
Cool! You want me to set it up?

**Comment by Kha** [comment]
That would be great. A part of our paper artifact uses `#eval`.

**Comment by leodemoura** [comment]
@cipher1024 The fix is a maximum priority.

**Comment by cipher1024** [comment]
I'm on it.

**Comment by leodemoura** [comment]
It was fixed by reverting broken changes.
