### ISSUE TITLE
Higher-resolution `monoMsNow`

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lean4#1095]
I'd like to have a `monoNsNow` (with nanosecond resolution) in addition to the existing `monoMsNow` (with millisecond resolution). This is for profiling Aesop: I want to be sure that if I measure the cumulative elapsed time of different parts of the tactic, the results are not dominated by rounding errors.

If you agree this is desirable, I'd be happy to send a PR.

**Comment by Kha** [comment]
Sounds reasonable to me, though I'm curious if you've tried using `perf` or similar first before rolling your own profiling

**Comment by leodemoura** [comment]
+1 for using `perf`. I found `perf`+`hotspot` is very effective for finding performance bottlenecks in Lean. Example:
```
perf record --call-graph dwarf build/release/stage1/bin/lean file.lean
hotspot
```

**Comment by JLimperg** [comment]
Thank you for the `perf` tip, I'll try it. Still, some profiling info might be useful for Aesop power users as well, to help them optimise the rule set, so I'll do the PR too.
