### ISSUE TITLE
`isDefEq` throws unexpected bound variable #0

### ISSUE THREAD

**Issue by casavaca** [leanprover/lean4#1104]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * [X] Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * [X] Reduced the issue to a self-contained, reproducible test case.

### Description

I'm learning how to write Tactics. Given the goal `Q`, the following code tries to find `P -> Q` in context, and if so, replace the goal with `P`

In the code below, `isDefEq s t` failed, because the first assumption of form `. -> .` is `∀ (P Q : Prop), (P → Q) → P → Q`. And its bindingBody! is `(Q : Prop) → (#0 → Q) → #0 → Q`. `isDefEq` calls ... which calls `isDefEqUnitLike` which calls `inferType` which throws exception about unbound variable.

However, `isDefEq t s` works.

Did I misuse the code? Or perhaps we should make `isDefEqUnitLike` more robust?

```lean
import Lean
import Lean.Meta
import Lean.Meta.Tactic

open Lean Elab Elab.Tactic Meta

set_option trace.debug true

def apply_assumption : TacticM Unit := do
  let m := (←getLCtx)
  let goal ←getMainGoal
  let target ← getMVarType goal
  trace[debug] "target is {target}"

  for o in m.decls do
    if o.isSome && o.get!.type.isForall then
      let Expr1 := o.get!.type.bindingDomain!
      let Expr2 := o.get!.type.bindingBody!

      trace[debug] "o is {o.get!.type}"
      trace[debug] "expr1 is {Expr1}"
      trace[debug] "expr2 is {Expr2}"

      let (t, s) := (target, Expr2)

      -- if (t == s) then       -- works
      -- if (←isDefEq t s) then -- works
      if (←isDefEq s t) then    -- doesn't work
        let newGoal ← mkFreshExprSyntheticOpaqueMVar Expr1
        let theapp := mkApp o.get!.toExpr newGoal
        assignExprMVar goal theapp
        appendGoals [newGoal.mvarId!]

  return ()

elab "apply_assumption" : tactic => apply_assumption

example (P Q : Prop) (h : P → Q) (p : P) : Q := by
  apply_assumption
  exact p
```

```lean
Messages below (5)
39:2: 
[debug] target is Q
39:2: 
[debug] o is ∀ (P Q : Prop), (P → Q) → P → Q
39:2: 
[debug] expr1 is Prop
39:2: 
[debug] expr2 is (Q : Prop) → (#0 → Q) → #0 → Q
39:2: 
unexpected bound variable #0
```

### Steps to Reproduce

**Expected behavior:** `isDefEqUnitLike` returns false

**Actual behavior:** `isDefEqUnitLike` throws exception

**Reproduces how often:**

### Versions

Lean (version 4.0.0, commit c2c2783f32b8, Release)

**Comment by Kha** [comment]
> Did I misuse the code?

Yes, functions in `MetaM` etc. generally expect all expressions to be closed. You use `forallBoundedTelescope` to move a function type's binder into the local context, see e.g. tests using it in the repo.
