### ISSUE TITLE
`MapDeclarationExtension.find?` bug

### ISSUE THREAD

**Issue by EdAyers** [leanprover/lean4#1111]
I think there is a bug in [`MapDeclarationExtension.find?`](https://github.com/leanprover/lean4/blob/7797fa3e2dbdabbef301b4f66a6ca9e2307882da/src/Lean/Environment.lean#L496) which means that if the attribute was made in a different module to the declaration it will miss.

```
-- File 1
initialize translations : MapDeclarationExtension Name ← mkMapDeclarationExtension `translations
```

```
-- File 2
import File1

#eval (do
  translations.insert (← getEnv)`Mul `Add |> setEnv
  return ()
  : CoreM Unit
)

#eval (do
  dbg_trace (translations.getState (←getEnv)).find? `Mul -- prints some `Add
  dbg_trace translations.find? (←getEnv) `Mul                   -- prints none
  return ()
  : CoreM Unit
)
```

This can be fixed by implementing ``translations.find? env n `` as `(translations.getState env).find? n` instead of trying to find the decl name directly from the oleans as in the definition of `translations.find?`.

**Comment by EdAyers** [comment]
Also 

```
-- File 3
import File2

#eval (do
  dbg_trace (translations.getState (←getEnv)).find? `Mul -- prints none
  dbg_trace translations.find? (←getEnv) `Mul                   -- prints none
  return ()
  : CoreM Unit
)
```

It seems that both should be printing `some Add` here?

**Comment by Vtec234** [comment]
Noting that `TagDeclarationExtensions` seems to have a [similar limitation](https://github.com/leanprover/lean4/blob/7797fa3e2dbdabbef301b4f66a6ca9e2307882da/src/Lean/Environment.lean#L450).

**Comment by leodemoura** [comment]
This is by design. We can add assertions to make sure these extensions are not being misused. 
The main advantage of these extensions is that they do not require any post-processing after we memory map the .olean files. To retrieve an entry, we just perform a binary search in the array stored in the memory mapped .olean.
Example:
https://github.com/leanprover/lean4/blob/7797fa3e2dbdabbef301b4f66a6ca9e2307882da/src/Lean/Environment.lean#L499

**Comment by leodemoura** [comment]
I updated the comment of `MapDeclarationExtension`, and added the assertions. You should now get an assertion violation (i.e., panic message) with the example above.

**Comment by EdAyers** [comment]
I understand thanks for explaining 🙂
