### ISSUE TITLE
Missing references to mutable variable

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lean4#1137]
### Description

The highlighting of references to a `mut` variable does not include its definition, as well as some of the previous usages. I am assuming this is due to how join points are introduced during compilation.

![screenshot](https://user-images.githubusercontent.com/13901751/166335649-523425b1-37aa-4345-aabc-2bebe59f50fe.png)

Standard `let`-bindings seem to work.

![screenshot](https://user-images.githubusercontent.com/13901751/166335110-219d3dc9-fbbd-478c-9655-6f8d26f784f8.png)

**Expected behavior:** All references to `xyz` are highlighted.

**Actual behavior:** Only some references are highlighted.

**Reproduces how often:** 100%

### Versions

94abfdba6c75b6efee68c1838f05fa26efee9a2d

**Comment by Kha** [comment]
This is also an issue for an unused-variables linter
