### ISSUE TITLE
Tactics can insert sorry without warning

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#1163]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Tactics (and term elaborators) can insert sorry without triggering any warnings.  See https://github.com/leanprover-community/mathlib4/issues/272

### Steps to Reproduce

```lean
macro "obviously" : tactic => `(exact sorryAx _)

theorem result : False := by obviously
```

(There are plenty of other "admit" functions in core that are not as obvious.  The issue in mathlib4 used `Lean.Meta.admit`.)

**Expected behavior:** A warning "declaration uses 'sorry'" is produced.

**Actual behavior:** No error or warning is produced.

### Versions

Nightly from May 21.

**Comment by leodemoura** [comment]
@gebner  We now print the warning for any declaration that contains a non-synthetic `sorry`.

**Comment by leodemoura** [comment]
BTW, we can avoid the issue by changing the default value at
```lean
def admit (mvarId : MVarId) (synthetic := true) : MetaM Unit :=
```
It looks fishy to me because most of the time `admit` is used to close a pending goal.

**Comment by digama0** [comment]
Is it possible to explicitly determine whether an error message has been sent on the current definition yet? The synthetic flag seems like something a poorly written tactic could easily mess up, and I would hope for something a little more foolproof.

**Comment by gebner** [comment]
> I noticed only a minor problem.

#1178 ?
