### ISSUE TITLE
Priority for custom simp attribute

### ISSUE THREAD

**Issue by lecopivo** [leanprover/lean4#1164]
The priority for custom simp attribute is ignored. An example:

```
@[simp low, mysimp low]
theorem expand_mul_add (x y z : Nat) : x * (y + z) = x * y + x * y := sorry
@[simp high, mysimp high]
theorem expand_add_mul (x y z : Nat) : (x + y) * z = x * z + y * z := sorry
@[simp, mysimp]
theorem lassoc_add (x y z : Nat) : x + (y + z) = x + y + z := sorry

set_option trace.Meta.Tactic.simp.rewrite true

-- Rewrites: expand_mul_add -> expand_add_mul -> lassoc_add
example (x : Nat) : (x + x) * (x + x) = x * x + x * x + x * x + x * x := by simp only [mysimp]

-- Rewrites: expand_add_mul -> expand_mul_add -> lassoc_add
example (x : Nat) : (x + x) * (x + x) = x * x + x * x + x * x + x * x := by simp
```

The problem is that the normal simp attribute is using [`Lean.Parser.Attr.simp`](https://github.com/leanprover/lean4/blob/56cd6c1ff519d8be39f35875b5bf8719e6101c20/src/Init/Tactics.lean#L419) parser and the custom simp attribute is using [`Lean.Parser.Attr.simple`](https://github.com/leanprover/lean4/blob/56cd6c1ff519d8be39f35875b5bf8719e6101c20/src/Lean/Parser/Attr.lean#L35) parser. This also means that pre/post can't be specified for a theorem with a custom simp attribute.

The final problem is in [`Lean.Meta.mkSimpAttr`](https://github.com/leanprover/lean4/blob/56cd6c1ff519d8be39f35875b5bf8719e6101c20/src/Lean/Meta/Tactic/Simp/SimpTheorems.lean#L286) which assumes the `Attr.simp` parser.

Tested on: leanprover/lean4:nightly-2022-05-21

**Comment by leodemoura** [comment]
The fix above assumes the user is using the command `register_simp_attr`.
For users invoking the function `registerSimpAttr`, they should declare the attribute parser themselves. We can try to improve this in the future if it is too inconvinient.

**Comment by lecopivo** [comment]
Using `register_simp_attr` is absolutely sufficient for me. Thanks a lot for fixing this!
