### ISSUE TITLE
Go to definition jumps to incorrect file

### ISSUE THREAD

**Issue by ammkrn** [leanprover/lean4#1170]
If there are two different files that contain declarations with the same name, the go to definition feature will sometimes jump to the declaration in the wrong file. This seems to happen consistently if the offending files are all open in a particular editor group (in tabs). 

Example: If I make a file `x.lean`

```
structure User where
  name : String
```

Then another file `y.lean`

```
structure User where
  name : Unit

example : User -> User := id
```

Right clicking on the `User` in the `example` declaration and selecting go to definition will take me to the declaration in `x.lean`.

I'm using vscode 1.67,  v0.0.75 of the extension, and  lean 4 nightly-2022-05-19.

**Comment by kbuzzard** [comment]
Here's a real-world example where this is quite annoying. Right now sometimes in mathlib development we run into problems with the typeclass inference system. Currently there is no tool available for automatically minimising (i.e. stripping out mathlib from) these problems. So I tend to work on them manually, and this involves making new files with scaled-down definitions of things like `Group` and `Ring` and with no imports, but also having mathlib on hand because I want to be able to see the problem and then slowly strip away imports. This issue can lead to a slightly frustrating experience here, because during the minimisation process you are sometimes dealing with mathlib rings and sometimes with these home-rolled rings.

**Comment by m4lvin** [comment]
I also run into this problem in [this project](https://github.com/m4lvin/lean4-pdl) which has two main parts in `src/Bml` and `src/Pdl` and where many names are used in both parts. Using "go to definition" in the `Pdl` section often sends me to the `Bml` stuff, even when no `Bml` files are open.

Which function is actually doing the work relevant for this? I guess [`GoTo.lean`](https://github.com/leanprover/lean4/blob/master/src/Lean/Server/GoTo.lean) which then uses [`findModuleOf`](https://github.com/leanprover/lean4/blob/c66c5bb45b5e7f34f7c75d832f4101bd6727d71d/src/Lean/MonadEnv.lean#L137) which uses ``getModuleIdxFor` after which I am lost :wink: Is there a way to run these functions manually using `#eval` or so to debug this issue further?

And a naive question: Given that the file compiles correctly, Lean must be able to find the correct definition in some way, but then "go to def" is using a different way where somehow the scope is wider?

**Comment by xiyuzhai** [comment]
As a newbie, I've digged into this for a limited time.

It seems to me it's not two file problems, it's two separate compilation problems.

If the two file appears in the same compilation, then the compiler would give an error.

So it reduces to Lean's analyzer cannot correctly handle two separate compilations at the same time.

**Comment by xiyuzhai** [comment]
Seems that I've found out the culprit. (I'm a newbie and only spent less than one day in looking at the source code, so I might be totally wrong).
`handleDefinition` is not the function actually being called.
In `Watchdog.lean` the function `handleRequest` is called, then in the wierd if statement before the match statement
```
if method == "textDocument/definition" || method == "textDocument/declaration" then
      let params ← parseParams TextDocumentPositionParams params
      let definitions ← findDefinitions params
      dbg_trace s!"handleRequest method = {method} params = {params} defns = {ToJson.toJson definitions}"
      if !definitions.isEmpty then
        (← read).hOut.writeLspResponse ⟨id, definitions⟩
        return
    match method with
```
Let's not talk about how the above violate clean code principles. Just look at the invokation of `findDefinitions`, which goes to
```
def findDefinitions (p : TextDocumentPositionParams) : ServerM <| Array Location := do
  let mut definitions := #[]
  if let some path := fileUriToPath? p.textDocument.uri then
    let srcSearchPath := (← read).srcSearchPath
    if let some module ← searchModuleNameOfFileName path srcSearchPath then
      let references ← (← read).references.get
      for ident in references.findAt module p.position (includeStop := true) do
        if let some ⟨definitionLocation, _⟩ ← references.definitionOf? ident srcSearchPath then
          definitions := definitions.push definitionLocation
  return definitions
```
Notice that
```
      let references ← (← read).references.get
      for ident in references.findAt module p.position (includeStop := true) do
        if let some ⟨definitionLocation, _⟩ ← references.definitionOf? ident srcSearchPath then
          definitions := definitions.push definitionLocation
```,
the references are got from server context, the type of which is defined by
```
structure ServerContext where
    hIn            : FS.Stream
    hOut           : FS.Stream
    hLog           : FS.Stream
    /-- Command line arguments. -/
    args           : List String
    fileWorkersRef : IO.Ref FileWorkerMap
    /-- We store these to pass them to workers. -/
    initParams     : InitializeParams
    workerPath     : System.FilePath
    srcSearchPath  : System.SearchPath
    references     : IO.Ref References
```
So references is a global variable, shared by all files (I believe with high confidence), then definitions are collected from this references global variable. The type of this global variable is
```
structure References where
  /-- References loaded from ilean files -/
  ileans : HashMap Name (System.FilePath × Lsp.ModuleRefs)
  /-- References from workers, overriding the corresponding ilean files -/
  workers : HashMap Name (Nat × Lsp.ModuleRefs)
```
See the fields `ileans`,  a name is mapped to a file path and a collection of references.
Hence, if two different set of compilations with clashing names exist for the same time, it causes problems.
