### ISSUE TITLE
rfc: moving `Lean.PrettyPrinter.Delaborator.SubExpr` to `Lean.SubExpr`

### ISSUE THREAD

**Issue by EdAyers** [leanprover/lean4#1183]
I have found metaprogramming uses for `Lean.SubExpr` outside of the delaborator. However it feels strange to write new methods for `SubExpr` in the `Lean.PrettyPrinter.Delaborator` namespace. Would you accept a PR to move it to the `Lean` namespace?

**Comment by leodemoura** [comment]
and thanks for asking.
