### ISSUE TITLE
`simp`: hypothesis contains metavariables

### ISSUE THREAD

**Issue by fpfu** [leanprover/lean4#1184]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Steps to Reproduce

```lean
set_option trace.Meta.Tactic.simp true
@[simp] theorem one_le_of_lt (h: n < m) : 1 ≤ m := Nat.lt_of_le_of_lt (Nat.zero_le _) h
example                      (h: n < m) : 1 ≤ m := by simp[h]
```

**Expected behavior:** example should work

**Actual behavior:** get an error:

```
unsolved goals
n m : Nat
h : n < m
⊢ 1 ≤ m
```

with message:

```
[Meta.Tactic.simp.discharge] one_le_of_lt, hypothesis contains metavariables
  ?n < ?m
```

**Reproduces how often:** 100%

### Versions

`nightly-2022-06-03`

**Comment by leodemoura** [comment]
@fpfu Are you on Zulip? If yes, what is your alias there? Just curious :)
Thanks again for finding all these problems.

**Comment by fpfu** [comment]
Thank you for the attention you pay to each issue or question)
And I'm impressed with the speed of Lean development.
My name is Evgeniy Kuznetsov and that's how I signed up on Zulip.
