### ISSUE TITLE
Bloated binaries because (implicit) usage of `Init.LeanInit` leads to inclusion of `lean_initialize`

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#119]
`tests/compiler/qsortBadLt.lean` compiles to a 26MB binary because it uses `Lean.mkAppStx._closed_9`, an extraction of the empty array!

**Comment by Kha** [comment]
Suggested fix that also gets rid of `usesLeanNamespace`:
* introduce `Init.Lean.Init` (definitely not to be confused with `Init.LeanInit`)
* add `[init]` decl there that calls `lean_initialize`
* make sure everything in `Init.Lean` depends on `Init.Lean.Init`

**Comment by leodemoura** [comment]
I am trying to fix this. I have to tweak a bit to make sure the modules are initialized in the right order.
