### ISSUE TITLE
Spurious unused variable warning when using induction tactic

### ISSUE THREAD

**Issue by imbrem** [leanprover/lean4#1196]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The function `T.zero_bad` has a spurious unused variable warning on the ignored binding `_`. This is not the case when using the `cases` tactic. Reduced from an example with a bunch of spurious warnings when, e.g., only the inductive hypothesis but not the majority of the constructor arguments are necessary.
```lean
inductive T: Type
| mk: Nat -> T

theorem T.zero: T -> T
:= by {
  intro H;
  cases H with
  | mk _ => exact T.mk 0
}

theorem T.zero_bad: T -> T
:= by {
  intro H;
  induction H with
  | mk _ => exact T.mk 0
}
```

### Steps to Reproduce

Input the above code into VSCode with the Lean4 extension

**Expected behavior:** No warning

**Actual behavior:** A warning at the `mk _` branch in `T.zero_bad`

**Reproduces how often:** Always

### Versions

Lean (version 4.0.0-nightly-2022-06-06, commit 7428dc5e71a9, Release)
OS: Arch Linux

**Comment by leodemoura** [comment]
Fixed by #1191
