### ISSUE TITLE
`conv` command `enter` miscounts function arguments

### ISSUE THREAD

**Issue by javra** [leanprover/lean4#1201]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

In the following code, the `enter` command should focus on `f`'s second argument instead of failing:
```lean
example (α : Type) (β : α → Type) (f : (a : α) → β a → Nat) (a : α) (b b' : β a) :
  f a b = f a b' := by
  conv => 
    enter [1, 2]
```
This is because arguments with forward dependencies are skipped, but this is not obvious to the user.

**Comment by javra** [comment]
I would propose changing `enter` and `arg`'s syntax to have numbers refer to all explicit arguments and have something like `@3` to count implicits, too.

**Comment by fpfu** [comment]
It also seems natural to use argument names in `enter` and `arg`

**Comment by leodemoura** [comment]
Closed by PR above.
