### ISSUE TITLE
 Spurious unused variable warning when using intro/intros tactic

### ISSUE THREAD

**Issue by imbrem** [leanprover/lean4#1204]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Out of the following four programs
```lean
theorem unused_intro: (n m: Nat) -> (m >= 0) :=
  by
    intro _ m; simp
    
theorem unused_intros: (n m: Nat) -> (m >= 0) :=
  by
    intros _ m; simp
    
theorem unused_intro': (n m: Nat) -> (m >= 0) :=
  by
    intro _ _; simp
    
theorem unused_intros': (n m: Nat) -> (m >= 0) :=
  by
    intros; simp
```
the first three give a spurious unused variable warning about the first variable (`n`), but, strangely, not the second variable (`m`). The final program gives no warning.

### Steps to Reproduce

Input the above code into VSCode with the Lean4 extension

**Expected behavior:** No warnings

**Actual behavior:** The first three programs warn "unused variable `n._@.LeanExperiments.PropRw._hyg.#`" where `#` is some number

**Reproduces how often:** Always

### Versions

Lean (version 4.0.0-nightly-2022-06-09, commit d0499ebf4d92, Release)
OS: Arch Linux

**Comment by Kha** [comment]
> but, strangely, not the second variable (`m`).

Yes, it is not technically feasible to check whether variables can be "unnamed" in arbitrary tactic proofs (without re-running the proof). Thus we only report variables as unused that are not involved in the proof term at all (which is not true for `m` as it occurs in the goal).

**Comment by digama0** [comment]
> > but, strangely, not the second variable (`m`).
> 
> Yes, it is not technically feasible to check whether variables can be "unnamed" in arbitrary tactic proofs (without re-running the proof).

At least for "hygienic" tactics, you can look for the presence of the identifier in the input syntax object. I wonder if there is a way to have tactics opt in or out of a general system for doing bound variable analysis at the level of tactic syntax... There already seems to be a decent amount of such information in order to support "find references" queries.
