### ISSUE TITLE
Can't hide applied monad behind abbreviation

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#121]
This breaks in both the old and new frontend. Is it a bad idea? It seems to work in Lean 3.
```lean
abbrev DelabM := Id
abbrev Delab := DelabM Nat
example : DelabM Nat := pure 1  -- works
example : Delab := pure 1  -- doesn't work
```

**Comment by leodemoura** [comment]
@Kha This is a side effect of the following approximation 
`?m Nat =?= Delab` ==> `?m := fun _ => Delab`
I will explore alternatives. One option is to always unfold before applying it.

**Comment by leodemoura** [comment]
Lean3 does not use this approximation.
