### ISSUE TITLE
Resolution with duplicated namespaces

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lean4#1224]
### Description

In the following snippet, should the definition that fails actually succeed in resolving `Bar`?

```lean
set_option autoImplicit false

namespace Foo.Bar
abbrev Bar := Nat
end Foo.Bar

open Foo Bar in
def myNat1 : Bar := 10 -- good

namespace Bar
end Bar

open Foo Bar in
/- unknown identifier 'Bar' -/
def myNat2 : Bar := 10

open Foo.Bar in
def myNat3 : Bar := 10 -- good

open Foo Bar in
def myNat4 : Bar.Bar := 10 -- good
```

A concrete instance of this occurs with `Lean.Elab.Tactic.Tactic` and a top-level `Tactic` namespace defined in mathlib4. Another possible solution to avoid confusion might be to ~~forbid defining symbols with the same name as the innermost namespace, in that namespace. For example `def Foo.Foo` would be forbidden~~ throw an error when an `open` statement is ambiguous due to multiple possible namespaces (in this case `Foo.Bar` and `Bar`) that could be opened.

### Steps to Reproduce

1. Run the snippet

**Expected behavior:** `Bar` is resolved in all cases, maybe. I am not certain what namespace resolution should do here.

**Actual behavior:** The first definition fails.

**Reproduces how often:** 100%

### Versions

`nightly-2022-06-13`

**Comment by Vtec234** [comment]
My apologies, false alarm. It is actually a mathlib4 issue.

**Comment by leodemoura** [comment]
@Vtec234  The behavior is consistent with the spec we have at `resolveNamespace?`.
```
/--
Given a name `id` try to find namespace it refers to. The resolution procedure works as follows
1- If `id` is in the scope of `namespace` commands the namespace `s_1. ... . s_n`,
   then return `s_1 . ... . s_i ++ n` if it is the name of an existing namespace. We search "backwards".
2- If `id` is the extact name of an existing namespace, then return `id`

3- Finally, for each command `open N`, return `N ++ n` if it is the name of an existing namespace.
   We search "backwards" again. That is, we try the most recent `open` command first.
   We only consider simple `open` commands.
-/
```
It would be great to get community consensus before changing it.

**Comment by Kha** [comment]
To be honest, for the longest time I wasn't even aware that, unlike with `import`, we allow relative `open`s. I'm not really bothered by the verbosity, though I guess @gebner wouldn't be happy with further *increasing* it :smile: .
One alternative way to decrease it could be to allow more expressive `export`s after all, such that you e.g. get `Lean.Meta` for free when opening `Lean.Tactic` as that is basically always the right thing to do. Not sure what the best practices on module structuring and reexporting in e.g. Rust would say about this.

**Comment by Kha** [comment]
This change seems to have broken a few documentation examples of the form
```
namespace Ex
class Inhabited (a : Type _) where
 default : a
export Inhabited (default)

#eval (default : Nat)  -- error: ambiguous, possible interpretations Inhabited.default : Nat, _root_.Inhabited.default : Nat
```
(which I only found out because I was wondering why the Nix cache was empty :laughing: ).

**Comment by leodemoura** [comment]
@Kha I will fix the issue above.
