### ISSUE TITLE
Show expected type if cursor is to the immediate right of a hole

### ISSUE THREAD

**Issue by EdAyers** [leanprover/lean4#1239]
Often I'll be in term mode, and I write something like `fun x => _` with my cursor to the right of the hole, and I have to back up a character to see the expected type at the hole. Please could we change the behaviour of the infotree to give the hole info even if we are immediately after the hole? 🙂

**Comment by Kha** [comment]
This should be fixed in the termGoal request, not in the infotree, no? Analogously to https://github.com/leanprover/lean4/pull/1172.

**Comment by gebner** [comment]
Term goals use a different function though.

**Comment by Kha** [comment]
> Term goals use a different function though.

Fixed

**Comment by lovettchris** [comment]
ha ha there was an unexpected change of behavior here that broke a vscode test: https://github.com/leanprover/lean4/issues/1262#event-6902216062

Namely cursor to the right of a list close bracket `["a", "b", "c", "d", "e"]|` now says expected type "List String" whereas before it said nothing.  I still think this is a good fix though, goto-definition is now much improved, thanks.  I fixed the vscode test by adding a space at the end of the line after the list close bracket.
