### ISSUE TITLE
Function induction rules

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#1243]
For recursive functions, especially ones that are not trivially structurally recursive, we want to automatically generate induction rules that reflect the function's recursion structure so that proofs over the function do not have to reconstruct this structure manually. For reference, see Sections 2.2 & 5.1 of https://isabelle.in.tum.de/doc/functions.pdf for how this works in Isabelle.

**Comment by nomeata** [comment]
May have been low priority, but we do have these since 4.8 :-)
