### ISSUE TITLE
PANIC at Lean.EnvExtensionInterfaceUnsafe.getState Lean.Environment:236:4: invalid environment extension has been accessed

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#1260]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I see lots of new error output in VS code using Lean 4.0.0-nightly-2022-06-28.   This does not happen in Lean (version 4.0.0-nightly-2022-06-24, commit 09c4af26fce8, Release).

Lean (version 4.0.0-nightly-2022-06-28, commit e49a81bb563f, Release)
PANIC at List.getLast! Init.Data.List.BasicAux:63:13: empty list
PANIC at List.head! Init.Data.List.BasicAux:31:12: empty list
PANIC at Lean.EnvExtensionInterfaceUnsafe.getState Lean.Environment:236:4: invalid environment extension has been accessed
PANIC at Lean.ScopedEnvExtension.getState Lean.ScopedEnvExtension:157:16: unreachable code has been reached
PANIC at Lean.EnvExtensionInterfaceUnsafe.getState Lean.Environment:236:4: invalid environment extension has been accessed
Error: index out of bounds
PANIC at Lean.EnvExtensionInterfaceUnsafe.getState Lean.Environment:236:4: invalid environment extension has been accessed
PANIC at Lean.ScopedEnvExtension.getState Lean.ScopedEnvExtension:157:16: unreachable code has been reached
PANIC at Lean.EnvExtensionInterfaceUnsafe.getState Lean.Environment:236:4: invalid environment extension has been accessed
Error: index out of bounds
...
and much more...

### Steps to Reproduce

1. Install Lean 4.0.0-nightly-2022-06-28
2. Install VS Code extension lean4 v0.0.79
3. Clone https://github.com/leanprover/lean4-samples
4. cd HelloWorld
5. code .     -- to load HelloWorld folder in VS Code

**Expected behavior:** 
no such errors.

**Actual behavior:** 
see above.

**Reproduces how often:**
every time.

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by leodemoura** [comment]
It should have been fixed by https://github.com/leanprover/lean4/pull/1259
See https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/nightly.20updates/near/287747544

**Comment by lovettchris** [comment]
Ok, I'll try that PR #1259 and see if it works, it hasn't been merged yet.

**Comment by lovettchris** [comment]
I have verified that https://github.com/leanprover/lean4/pull/1259 does indeed fix the problem.
