### ISSUE TITLE
Change in behavior on LSP Expected Types

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#1262]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Yesterday the Expected types and Messages returned from this lean program in the VS code extension:

```lean
#eval [1, 1+1, 1+1+1]
```
when the cursor is placed at the end of the line outside the closing `]` was:

![image](https://user-images.githubusercontent.com/18707114/176317035-12184bfe-ff1d-425f-9b73-2f2c11c83771.png)

Today we get back an expected type of `List Nat`:

![image](https://user-images.githubusercontent.com/18707114/176317083-d16fa891-cb8c-4e3d-bd69-81e7101da98d.png)

Unless I add a space at the end of the line, then I get back an empty list of expected types again.  
### Steps to Reproduce

https://github.com/leanprover/vscode-lean4/actions/runs/2579580704

**Expected behavior:** 
I don't know if this change was deliberate or which is correct, but it was found by a vscode test failure, so I'd like which is "correct" and will this new behavior remain?

**Actual behavior:** 
See above

**Reproduces how often:** 
100%

### Versions

- Lean (version 4.0.0-nightly-2022-06-28, commit e49a81bb563f, Release)
- Windows 11

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by gebner** [comment]
Yes, this was on purpose!  See #1239 and #1244.

**Comment by lovettchris** [comment]
Ah, part of fixing goto-definition, thanks.  goto-definition is now much improved, so this is a small price to pay.  The vscode test was fixed by simply adding a space after the list close bracket.
