### ISSUE TITLE
maximum recursion depth has been reached (use `set_option maxRecDepth <num>` to increase limit)

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#1263]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

![image](https://user-images.githubusercontent.com/18707114/176318563-c5733b02-adb1-4bdb-a0a8-1eac8678d9ec.png)

### Steps to Reproduce

Open https://github.com/leanprover/lean4-samples/tree/main/HelloWorld

Paste `#eval [1, 1+1, 1+1+1]` on line 4 while the Lean --server and info view are still loading.

**Expected behavior:**

Should have no such error.

**Actual behavior:**
See above

**Reproduces how often:**

It is happening in 100% in [automated tests](https://github.com/leanprover/vscode-lean4/runs/7102425050?check_suite_focus=true)

10% on my own Windows dev box, but I was able to capture it -- see above screen shot.

### Versions

- Lean (version 4.0.0-nightly-2022-06-28, commit e49a81bb563f, Release)
- Windows 11

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Kha** [comment]
Does this still occur with #1259?

**Comment by lovettchris** [comment]
I'll be monitoring https://github.com/leanprover/vscode-lean4/actions and see if it stops reporting this error randomly.  Should this change have impacted the error `maximum recursion depth has been reached` ? What does the error mean and what caused it?  Just curious...

**Comment by lovettchris** [comment]
Great, good to know, I do see 10 clean builds on https://github.com/leanprover/vscode-lean4/actions since the last `maximum recursion depth has been reached` -- so far, so good, I think.  So you can optimistically close this, I will reopen it if we see the errors again.
