### ISSUE TITLE
Unused variables warning on macros/elaborators that expand to `opaque`

### ISSUE THREAD

**Issue by tydeu** [leanprover/lean4#1266]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Macros and elaborators which expand syntax to opaque declarations  with named parameters produce unused variable warnings on the parameter names.

### Steps to Reproduce

```lean
macro "opaque' " id:declId sig:declSig : command => `(opaque $id $sig)
opaque' foo (x : UInt32) : UInt32 -- warning: unused variable `x`
```

**Expected behavior:**

No warning.

**Actual behavior:**

Unused variable warning.

**Reproduces how often:**

Always.

### Versions

Windows 20H2
`Lean (version 4.0.0-nightly-2022-06-17, commit f0e2696ec82b, Release)`

### Additional Information

I stumbled onto this because of [Alloy](https://github.com/tydeu/lean4-alloy) which expands its `extern` definitions to opaque declarations and thereby produces lots of unused variable warnings.

**Comment by leodemoura** [comment]
@Kha We could allow users to register additional `SyntaxNodeKind`s to be ignored by the Linter. Right now, it seems they are hardcoded.

**Comment by Kha** [comment]
We should allow that in any case (though it would likely need to be arbitrary callbacks, see e.g. implementation of the check for `opaque`: https://github.com/leanprover/lean4/blob/5d0ddb44be5ac0d2e88128abf6d710e48630cae8/src/Lean/Linter/Basic.lean#L152-L155). But in the macro case as above, it would be nicer to handle this automatically by also checking all macro-generated syntax in the info tree against the built-in blacklist, which I hope wouldn't be too expensive. /cc @larsk21

**Comment by larsk21** [comment]
Allowing users to register additional ignore functions should be easy. I will take a look at how we can include macro-generated syntax when searching for the uses of a declared variable.
