### ISSUE TITLE
`set_option codegen false` breaks subsequent definitions

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#1288]
```lean
inductive Exp
  | var (i : Nat)
  | app (a b : Exp)

set_option codegen false in
def Exp.hash1 : Exp → Nat
  | .var i => i
  | .app a b => a.hash1 + b.hash1

def Exp.hash2 : Exp → Nat
  | .var i => i
  | .app a b => a.hash2 + b.hash2
```

**Expected behavior:** The definition `Exp.hash2` is accepted without error.

**Actual behavior:** `failed to compile definition, consider marking it as 'noncomputable' because it depends on 'Exp.hash1.match_1', and it does not have executable code`

Weirdly enough, this doesn't happen if the first definition is marked `noncomputable` instead of using `set_option codegen false`.

**Comment by leodemoura** [comment]
Thanks for raising this issue. I going to remove the option `codegen`, it is an old option implemented in C++.  We should use `noncomputable` instead.
