### ISSUE TITLE
Miscompilation of `filterMap`

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lean4#1292]
### Description

In the following snippet, the second `#eval` returns a nonsensical value (`0x7f3b9f841ee0`, which looks like a heap or code pointer).

```lean
def test : Nat :=
  let inp : Array (Option Nat × Nat) := #[(some 0, 0), (none, 0)]
  let fvars : Array Nat := inp.filterMap fun
    | (some _, _) => none
    | (none, fv)  => fv
  fvars.size

/- 1 -/
#eval test

def test2 : Nat :=
  let inp : Array (Option Nat × Nat) := #[(some 0, 0)]
  let fvars : Array Nat := inp.filterMap fun
    | (some _, _) => none
    | (none, fv)  => fv
  fvars.size

/- 139894056034016 ?! -/
#eval test2
```

### Steps to Reproduce

1. Run the snippet.

Note that this only happens if both definitions are present. Removing `test` makes `#eval test2` show the correct value. Also factoring out the anonymous `fun` into a definition seems to fix the issue.

**Expected behavior:** The second value is `0`.

**Actual behavior:** The value is incorrect.

**Reproduces how often:** 100%

### Versions

db47664d4a8586b46923eb095398bc48975e6aaa on Linux 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by leodemoura** [comment]
This is a bug in the code specialization module.
