### ISSUE TITLE
Array coercion hangs Lean

### ISSUE THREAD

**Issue by ammkrn** [leanprover/lean4#1293]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

In defining a coercion of the type `Array A -> Array B`, the surrounding context seems to cause Lean to hang if the function used to modify the underlying array is a lambda, but it works fine if the modification is a def. I'm not sure whether this kind of coercion is discouraged, but I saw some similar uses in the lean4 repo's tests, so I figured I would try it out. 

### Steps to Reproduce

This should reproduce the behavior:

```
theorem modifySize {A : Type u} (as : Array A) (f : A → A) (n : Nat) : (as.modify n f).size = as.size := by 
  simp [Array.modify, Array.modifyM, Id.run]; split <;> simp [Id.run]

structure Idx (p : Array String) where
  n : Fin p.size

structure Store where
  arr : Array String
  -- integer pointers into `arr`, type-indexed by `arr`
  ids : Array (Idx arr)

instance {arr : Array String} {f : String → String} {n : Nat} : Coe (Array (Idx arr)) (Array (Idx (arr.modify n f))) where
  coe xs :=
    xs.map (fun x => Idx.mk ((modifySize arr f n) ▸ x.n))

def store1 : Store := {
  arr := #["a", "b", "c", "d", "e"]
  ids := #[⟨2, by simp⟩]
}

def tryCoeStore := { 
  store1 with 
  -- using a lambda here hangs
  -- arr := store1.arr.modify 2 (fun _ => "Z")
  -- but `id` works fine. Moving the lambda into a separate def also works.
  arr := store1.arr.modify 2 id
}
```

**Expected behavior:** 
`ids` coerces to `Array (Idx (arr.modify n f))`

**Actual behavior:** 
Yellow bars/hanging in the editor, heavy processor use. Trying to build with `lake build` hangs the compiler.

**Reproduces how often:** 
Consistently

### Versions

Lean version: leanprover/lean4:nightly-2022-07-06
VScode extension version: v0.0.82
VScode version: 1.68.1

**Comment by gebner** [comment]
@leodemoura It looks like the fix didn't work (completely).  CI is now failing on master in the debug configuration.
