### ISSUE TITLE
RFC: API for tracking introduced and assigned metavariables

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lean4#1295]
For Aesop, I need to track precisely which metavariables are declared and assigned by a tactic. (This is because Aesop uses best-first search rather than the usual depth-first and so I need to handle goals in the search tree that are 'coupled' by a metavariable.) So far I've written bespoke code for each tactic to figure out the declared and assigned metavariables, but that's complicated and error-prone. E.g. `cases` can introduce metavariables which are not reported in the returned `Array MVarId`. So I'd like to have a general function that, given a tactic `x : MetaM α`, runs `x` and reports the newly declared and assigned metavariables. It is possible to implement this with the current API by diffing the `MetavarContext`s before and after `x`, but this is very wasteful.

So, I would love to have a new, efficient API for this. I'm thinking of something like this:

- `MetavarContext` gets new fields
  - `trackAssignedMVars : Bool`
  - `trackDeclaredMVars : Bool`
  - `declaredMVars : Array MVarId` (or `PersistentArray`?)
  - `assignedMVars : Array MVarId`
- `addExprMVarDecl` pushes onto `declaredMVars` if `trackDeclaredMVars = true`, and similar for the various assignment functions.
- `trackingDeclaredMVars (x : MetaM α) : MetaM (α x Array MVarId)` resets `declaredMVars`, sets `trackDeclaredMVars := true`, runs `x` and `finally` resets `trackDeclaredMVars` and `declaredMVars`.

Code that does not use this API would not be impacted except for the performance cost of the additional branch in `addExprMVarDecl` etc.

Would you take a PR implementing this API?

**Comment by gebner** [comment]
I think it would be easier to just look at the metavariables reachable from the tactic state (which is easy and fast to compute, and is usually a single-digit number of metavariables).  Then e.g. "metavariables reachable from new state \ metavariables reachable from old state" is your set of declared metavariables.

**Comment by JLimperg** [comment]
Right, something like this is what I've been doing so far. I thought this was unreliable because I have a case where a tactic seems to introduce mvars which are not reachable from the tactic state. But this is probably just a bug in the tactic. I'll isolate and report that issue and if it turns out to be a bug, I don't need this API any more.

**Comment by gebner** [comment]
@JLimperg Did the approach with collecting the reachable metavariables work out?

**Comment by JLimperg** [comment]
Yes, the approach works (and any bugs turned out to be mine). Thanks for the help!
