### ISSUE TITLE
Improve `do` notation + Info tree interaction

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#1343]
Info view and VS Code code block highlight are not behaving properly for `do` blocks.
This issue was reported by Patrick Massot during the Lean Hackton.
Example:
![image](https://user-images.githubusercontent.com/2778936/180314630-a9e79dcc-1556-4445-b28f-c36043e628e1.png)

**Comment by gebner** [comment]
Duplicate of #1248.
