### ISSUE TITLE
Dot-notation helper abbreviations

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#1346]
During the ICERM after-party hackton, @digama0 suggested we add helper abbreviations such as
```lean
abbrev MVarId.getType (mvarId : MVarId) : MetaM Expr 
```
They are great for discoverability when using dot-notation.

**Comment by leodemoura** [comment]
@digama0 Any other functions to rename?

**Comment by digama0** [comment]
I'm going to be making an in depth pass over everything in the coming weeks, so I'll keep an eye out for dot-notation candidates. But I don't have any suggestions at the moment.

**Comment by leodemoura** [comment]
Closing this issue for now. We can open a new issue for adding new helper abbreviations if someone has suggestions.
