### ISSUE TITLE
Messages are no longer printed on command line

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lean4#1358]
### Description

The following code
```lean
import Lean.Elab.Tactic

open Lean Elab Tactic in
elab "print!" : tactic => do
  logInfo "foo"
  throwError "error"

example : True := by
  print!
  admit
```
shows both the message and the error in the editor, but only the error is shown on the command line.

Before `nightly-2022-07-20` we saw
```shell
$ lake env lean Test.lean
foo
Test.lean:11:2: error: error
```
while after we get
```shell
$ lake env lean Test.lean
Test.lean:11:2: error: error
```

### Steps to Reproduce

**Expected behavior:** Both messages are shown.

**Actual behavior:** Only the error is shown.

**Reproduces how often:** 100%

### Versions

It works until `nightly-2022-07-19` and broke in `nightly-2022-07-20`.

**Comment by Kha** [comment]
Out of the commits between those versions, I can only assume it's due to https://github.com/leanprover/lean4-nightly/commit/3846dd60fd5bbb7901b432066234037c35b872a0
