### ISSUE TITLE
Leaky abstraction from structures to instances in error messages

### ISSUE THREAD

**Issue by david-christiansen** [leanprover/lean4#1366]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

When defining an instance, error messages describe structures rather than classes. In particular, a typo in a method name yields an error about structure fields rather than class methods, which could be confusing to those who don't understand the dictionary-passing translation.

### Steps to Reproduce
Enter the following code:
```
inductive T where

instance : ToString T where
  bogus := fun x => ""
```

**Expected behavior:** [What you expect to happen]
The error message is:
```
'bogus' is not a method of class 'ToString'
```

**Actual behavior:** [What actually happens]
The error message is:
```
'bogus' is not a field of structure 'ToString'
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

`Lean (version 4.0.0-nightly-2022-07-03, commit 7326c817d22e, Release)` on Fedora 36

**Comment by Kha** [comment]
Mmh. I understand where you're coming from, but I wouldn't say that Lean even considers classes as an abstraction of structures. `#print`, TPiL, and any many other parts are quite open about it being merely a modifier on structures. And even if you may want to delay the discussion of *why* it is that way to the end of the chapter, wouldn't it be helpful to immediately point out to beginners that classes are just structures with a different keyword, so so they do not have to learn any new syntax (except for `def/instance ... where`, I can understand if you don't want to introduce that in the structures chapter).

**Comment by david-christiansen** [comment]
Great, so this is a matter of what the intention is. If the realization of type classes as structures is part of their semantics, rather than a part of their implementation that might one day be changed, then I think that the current situation makes sense, and this error message is a teachable moment rather than an eager source of confusion. I had not understood that this was the case. Thanks for clearing it up!
