### ISSUE TITLE
doc strings on more obscure commands 

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#1374]
There was another report about missing doc commands, so I did a more thorough search for obscure commands that we have forgotten to allow docstrings for.

* `register_simp_attr` (reported in https://github.com/leanprover-community/mathlib4/pull/331#issuecomment-1196146104)
* `register_(builtin_)option`
* `elab_stx_quot`? This one might be internal-use-only
* `declare_config_elab`
* `declare_syntax_cat`
* `init_quot`: this is a one-off but it definitely needs an explanation (and it has one in a plain comment)

Here are the other builtin commands that lack a doc comment but probably don't need one:
* `namespace`, `section`: Probably best to keep it that way and use a module doc instead, although I can imagine people wanting to associate the comment with a named section
* `end`: this one is a stretch
* `mutual`: this one is like `section`, although I can imagine wanting a doc comment to talk about the whole group of definitions
* `universe`, `variable`, `open`, `export`, `set_option`, `attribute`, `deriving`: Unless these are shown in doc-gen it would be unclear what to do with a doc comment on them
* `#check`, `#check_failure`, `#eval`, `#reduce`, `#synth`, `#print`, `#resolve_name`, `#widget`: temporary (`#`) commands would probably only get documentation in tutorials, in which case you are looking at the code anyway

**Comment by leodemoura** [comment]
@digama0 This is great. Do you have time to write these doc strings?

**Comment by digama0** [comment]
I might not have been clear: I mean that these commands should *accept* doc strings, not that they should have doc strings explaining what they do. (That is of course also useful, but it is a separate issue.)

**Comment by leodemoura** [comment]
The commit above addresses some of the commands above. Note that we currently can only associate doc strings to kernel declarations, and files/modules.

Commands in the first list that were skipped:

- `elab_stx_quot` only declares a definition with an inaccessible name
- `declare_syntax_cat` only updates the parser environment extension. It does not create any new declaration in the environment. 
- `init_quot` creates 4 declarations in the kernel. I think we should probably have a command for attaching doc strings to declarations created by the kernel.

For the second list, none of them generate declarations, but I am not sure about `#widget`.

**Comment by digama0** [comment]
For `declare_syntax_cat`, it's too bad we can't have a doc string there since it would make sense to have hover on things like `attr` and `command` show it. If we were to implement that anyway would you prefer making a dummy definition for it, or having a docstring field in the parser environment extension? We'd probably want to associate a span to it as well for go-to-def.

**Comment by Kha** [comment]
If/when we either get rid of `ParserDescr` or restrict it to bootstrapping, it would make sense for `declare_syntax_cat foo` to declare `foo : Parser`, at which point we could attach the docstring.

**Comment by leodemoura** [comment]
The commits above address the remaining issues above. Support
- Doc strings at attribute parsers
- User-defined simp attribute support
- `add_decl_doc` command.
- Doc strings at `declare_syntax_cat` and hovering info for them.

So, I am closing this issue.
