### ISSUE TITLE
charToHex is incomplete

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#1404]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
```lean
def dump_chars (s : String) : IO Unit :=
  for c in String.data s do
    IO.println (charToHex c)

#eval dump_chars "😵‍💫"
```

### Steps to Reproduce

Run the above

**Expected behavior:** 

charToHex should produce full hex values:

```lean
/-
1f635
200d
1f4ab
-/
```

**Actual behavior:** 

```lean
/-
*5
*d
*b
-/
```

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

"4.0.0, commit 9a401c852c7561a8f98ae83ada9d3107f74616df"

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lovettchris** [comment]
Looks like you fixed it by removing it!  Can you provide a charToHex that works in all cases?  That seems like a basic fundamental that should be there.

**Comment by leodemoura** [comment]
> Can you provide a charToHex that works in all cases? That seems like a basic fundamental that should be there.

We don't need it to implement Lean. It should be part of the standard library.

**Comment by lovettchris** [comment]
can this bug be a reminder to add it to the standard library?

**Comment by leodemoura** [comment]
> can this bug be a reminder to add it to the standard library?

I don't think so. The developers working on the standard library for `Char` will discuss what APIs should be supported or not. We should not keep reminders in this repo.

From the point of view of this repo, `charToHex` was an auxiliary function that had a misleading name. We corrected the problem, and it will hopefully prevent similar misunderstandings in the future.

**Comment by lovettchris** [comment]
I see, I didn't realize `The developers working on the standard library` was such a separate process.  Where can one track the development of the standard library?

**Comment by digama0** [comment]
@lovettchris https://github.com/leanprover-community/mathlib4/ is collecting standard library tools and requirements, and it's open for PRs and issues to track missing features. The plan is to split off a standard library once the stuff we have has demonstrated its usefulness on the as-yet unported part of mathlib.
