### ISSUE TITLE
Structure decidable instance not synthesized in do block

### ISSUE THREAD

**Issue by ammkrn** [leanprover/lean4#1450]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I might be out of line since I'm not actually sure whether this pattern is actually supported, but when using StateT where the state parameter is a struct with fields for a proposition and subsequent decidable instance, inference/synthesis generally doesn't find the decidable instance. I found the failure of `guard` in the first do block example below to be a little bit surprising. Thanks for your time.

### Steps to Reproduce
```
@[reducible]
structure Foo where
  r : Nat → Nat → Prop
  [inst : DecidableRel r]

-- The first example below works if this is declared explicitly
-- instance (f : Foo) : DecidableRel (f.r) := f.inst

-- This fails
-- instance (f : Foo) : DecidableRel (f.r) := inferInstance
/-
failed to synthesize instance
  Decidable (Foo.r a✝ x y)
-/
example (x y : Nat) : StateT Foo Option Unit := do
  guard ((← get).r x y)
  return

/-
application type mismatch
  @guard ?m.9856 ?m.9857 (Foo.r a✝¹ x y) (Foo.inst a✝ x y)
argument
  Foo.inst a✝ x y
has type
  Decidable (Foo.r a✝ x y) : Type
but is expected to have type
  Decidable (Foo.r a✝¹ x y) : Type
-/
example (x y : Nat) : StateT Foo Option Unit := do
  @guard _ _ ((← get).r x y) ((← get).inst x y) (r x y)
  return

-- works
example (x y : Nat) : StateT Foo Option Unit := do
  let a ← get
  let R := a.r
  let _ := a.inst
  guard (R x y)
  return
```

**Expected behavior:** 
I expected the structure field `Foo.inst` to be found.

**Actual behavior:**
Synthesis of `Decidable r x y` fails

### Versions
leanprover/lean4:nightly-2022-08-08
vscode 1.70

**Comment by leodemoura** [comment]
The example above fails because the following instance is not created automatically
```lean
instance (x : Foo) (a b : Nat) : Decidable (x.r a b) :=
  x.inst a b
```
After we add it, the example works as expected. The annotation `[inst : DecidableRel r]` in `Foo`'s declaration only instructs Lean that the field `inst` should be synthesized using type class resolution. See:
```lean
#check Foo.mk
-- Foo.mk : (r : Nat → Nat → Prop) → [inst : DecidableRel r] → Foo
```
The annotation also influences the `{ ... }` notation which is just sugar for `Foo.mk`
```lean
example : Foo := {
  r := fun _ _ => True
}
```
Finally, the example 
```lean
example (x y : Nat) : StateT Foo Option Unit := do
  @guard _ _ ((← get).r x y) ((← get).inst x y) (r x y)
  return
```
does not work because the `do` block above is expanded to
```lean
example (x y : Nat) : StateT Foo Option Unit := 
  get >>= fun s1 =>
  get >>= fun s2 =>
    @guard _ _ (s1.r x y) (s2.inst x y) (r x y)
```
That is, after expansion, we have to different states, and the type class resolution does not know they are equal.

**Comment by leodemoura** [comment]
@ammkrn Does the explanation above make sense? I am planning to close this issue.

**Comment by ammkrn** [comment]
Yes, thanks!
