### ISSUE TITLE
Feature request: More `Float` primitives.

### ISSUE THREAD

**Issue by EdAyers** [leanprover/lean4#1457]
Please could we have the following primitives available for `Float`. I think they can all be implemented in terms of the other primitives but they would be nice to have explicitly. The particular problem I am trying to solve is writing a JSON encoding for `Float` (ideally without going via a string). I had a go at adding these but I couldn't get the bootstrapping to work.

- `isinf`
- `isnan`
- `isfinite`
- [`frexp`](https://en.cppreference.com/w/cpp/numeric/math/frexp)
- I'm not sure what the appropriate primitive is, but getting the integer mantissa and exponent from a `Float` in a platform-safe way.

**Comment by digama0** [comment]
I can try to implement this if the devs are okay with it.

**Comment by leodemoura** [comment]
> I can try to implement this if the devs are okay with it.

@digama0 Thanks for volunteering. Please go ahead.
