### ISSUE TITLE
#eval String.fromUTF8Unchecked (ByteArray.mk #[0xab, 0xea]) hangs

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#1470]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

This program hangs the LSP server in VS Code:
```
#eval String.fromUTF8Unchecked (ByteArray.mk #[0xab, 0xea])
```

Sebastian says: "Oh that's funny, it looks like it overshoots the following condition, trapping itself in an infinite loop:

https://github.com/leanprover/lean4/blob/185829d089080b290c012adb380beddfd49a4712/src/Init/Data/String/Basic.lean#L312

### Steps to Reproduce

See above.

**Expected behavior:** 

It should return the valid bytes that could be decoded from UTF-8 and drop the bytes that cannot be.

**Actual behavior:** 

Hang.

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Kha** [comment]
See https://github.com/leanprover/lean4/issues/1462

**Comment by lovettchris** [comment]
cool, now when you fix it you can close 2 issues...

**Comment by Kha** [comment]
We have a "duplicate" button for that :)

**Comment by lovettchris** [comment]
But hang on this doesn't seem to be a bug in the name of fromUTF8Unchecked, instead it's a bug in https://github.com/leanprover/lean4/blob/185829d089080b290c012adb380beddfd49a4712/src/Init/Data/String/Basic.lean#L312 right?

**Comment by Kha** [comment]
The linked issue removes the primary(*) way to create a `String` that is not valid UTF-8. Under the, very reasonable, assumption that such strings do not exist (like Rust makes), that implementation is correct.

(*) There are probably some IO functions like `lean_io_prim_handle_get_line` that we should harden as well

**Comment by lovettchris** [comment]
I see so you are saying the new `fromUTF8` would never return an invalid UTF-8 encoding in a string and that would stop this `foldlAux`` from ever getting stuck while folding strings?  I guess the problem with `foldlAux` is that this returns 4
```lean
#eval (String.fromUTF8Unchecked (ByteArray.mk #[0xab, 0xea])).next {byteIdx := 1}
```
which is off the end of the sting, so it never hits `if i == stopPos then a`, but if we changed this to `if i >= stopPos then a` then it would never get stuck no matter where the string came from... you don't think that's also a safe fix?

**Comment by lovettchris** [comment]
I guess the problem is there's a LOT of `pos == stopPos` tests in Basic.lean and we'd have to fix all of them...
