### ISSUE TITLE
Workspace symbol search returns internal definitions

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#1510]
The workspace symbol search (`ctrl-p #` in vscode) returns all kinds of internal definitions.  Example queries:
 - `_sunfold` returns smart unfolding lemmas
 - `_unsafe_rec` returns helper definitions used to compile recursive definitions

These should be filtered out.

Nightly from August 25.

**Comment by Kha** [comment]
Solved by series of commits starting at 4d51cdd1b739dda3f99f13b1b5eec21277b5223c
