### ISSUE TITLE
Unexpected workspace symbol search results

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#1546]
Gonna use this issue to collect a few unexpected results I've encountered
* searching for `smap` or `SMap` does not find the actual type

**Comment by gebner** [comment]
See also #1510.

**Comment by rish987** [comment]
I can take this one on. My investigation thus far shows that there may be a bug or some score weighting tweaking necessary in `fuzzyMatchCore`. If you add
```
  for ((name, score), _) in symbols.qsort (fun ((_, s1), _) ((_, s2), _) => s1 > s2) do
    dbg_trace s!"{name}: {score}"
```
to `handleWorkspaceSymbol` to print out the results in order of score, you'll find that when you query by `SMap`, the symbol `Lean.SMap` is there, but its score is too low to show up in the top 100 results.

**Comment by Kha** [comment]
Nice, sounds like the right direction!

**Comment by Kha** [comment]
We would probably expect matches with exact `extract` components to be at the top here? 
![image](https://user-images.githubusercontent.com/109126/201048386-d588bf77-32b9-4749-9e03-dc2b028fba6d.png)
