### ISSUE TITLE
Implicit lambda features reduces semireducibly

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#1547]
Inspired by the recent talk of using implicit arguments for thunks, I decided to try it out and immediately ran into issues with monads:
```lean
def foo (x : {_ : Unit} → StateM Nat Nat) : Nat :=
  (@x () 0).1

def bar := foo (return 42)
```

Unfortunately, the implicit lambda feature reduces `StateM` here and we get the error message:
```
invalid `do` notation, expected type is not a monad application
  Nat → Id (Nat × Nat)
You can use the `do` notation in pure code by writing `Id.run do` instead of `do`, where `Id` is the identity monad.
```

(I would expect the function to compile fine.)

**Comment by Kha** [comment]
(but also now that we have struct eta, I really think those monads should be structs)
