### ISSUE TITLE
Pretty printing bug

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#1571]
```lean
#check True → (∃ a : Nat, a = a)
-- ∀ (a : True), ∃ a, a = a : Prop

#check True → (∃ b : Nat, b = b)
-- True → ∃ b, b = b : Prop
```
Only the pretty printer is affected AFAICT, but the determination of whether to use a dependent arrow or not seems to be misled by the name of the inner binder in this case.

**Comment by leodemoura** [comment]
This is not the `a` bug. It is a pretty printing issue. The raw pretty printer produces the expected result.
```
set_option pp.raw true

#check True → (∃ a : Nat, a = a)

#check True → (∃ b : Nat, b = b)
```

**Comment by digama0** [comment]
(The title was a joke. It is the `a` bug only insofar as it is a bug relating to unhygienic names and the fact that anonymous binders have the name `a`.)

**Comment by leodemoura** [comment]
> (The title was a joke. It is the `a` bug only insofar as it is a bug relating to unhygienic names and the fact that anonymous binders have the name `a`.)

I assumed it was a joke, but I wanted to clarify before users get concerned about it and/or missed the joke. The Lean 3 `a` bug was painful to many users.
