### ISSUE TITLE
subst produces type incorrect term

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#1575]
```lean
example [Subsingleton α] (p : α → Prop) : Subsingleton (Subtype p) :=
  ⟨fun ⟨x, _⟩ ⟨y, _⟩ => Subsingleton.elim x y ▸ sorry⟩
```
```
application type mismatch
  { val := x, property := property✝ }
argument has type
  p y
but function has type
  p x → Subtype p
```
It's not a kernel error, but it appears that the `▸` elaborator is producing a type incorrect term (the `sorry` goal is type incorrect) which is caught only later. This is the same kind of goal that would normally produce the "motive is not type correct" error in `rw` (and indeed it does if you try it in this example), but it seems that `▸` goes ahead and rewrites anyway.

**Comment by leodemoura** [comment]
I agree with your analysis. 
Please flag if this bug is blocking progress on the Mathlib port.

**Comment by digama0** [comment]
No blocker, just something I noticed.
