### ISSUE TITLE
config elab errors are not reported

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#1576]
```
example : True := by rw (config := non / sense) []
-- (kernel) declaration has metavariables '_tmp._@.Test._hyg.377'
```
The same issue occurs in `simp` and other config-taking tactics. More importantly, if you type `_` in the config you do not get subgoal information to help complete the expression. I think this is a recent regression in `declare_config_elab`, since I recall being able to get info in this position before.

The culprit seems to be the `withoutModifyingState` here:
https://github.com/leanprover/lean4/blob/5514339ffdff3cce3919cb8075354e0966783353/src/Lean/Elab/Tactic/Config.lean#L22-L26

That said I'm not sure exactly how to fix the issue. Obviously we do want to revert the state here, but if there are any elaboration errors then I think the tactic should just keep the messages posted so far and return a synthetic sorry. To complicate matters, the config elaboration isn't even throwing an exception in this example, it just keeps going with some synthetic sorries stuck in, which cause an ugly error later when the term is passed to the compiler for evaluation.

**Comment by leodemoura** [comment]
Thanks for investigating the issue. 

> That said I'm not sure exactly how to fix the issue.

Let's try to use `withoutModifyingStateWithInfoAndMessages`. AFAIR, we have introduced this combinator for a similar issue.
