### ISSUE TITLE
Request: move `WriterT` to core?

### ISSUE THREAD

**Issue by EdAyers** [leanprover/lean4#1587]
We've got `StateT` and `ReaderT` in core. I find myself wanting to use `WriterT` a lot, including for https://github.com/leanprover/lean4/issues/1469 in core. I previously added it to mathlib4 in https://github.com/leanprover-community/mathlib4/pull/281. Is there any objection to moving it to core?

**Comment by digama0** [comment]
I think the `Monoid ω` class is a bit of a landmine here. To avoid clashes with other stuff, I think it should just be `MonadWritable ω` or some-such. Also, it might be necessary for those operations to themselves be monadic?

You didn't link any code that actually uses the typeclass though. Personally it is very rare for me to need `WriterT` although I have used it occasionally in Haskell; in particular it generally leads to performing lots of appends which performs worse than just mutating a linear object such as you would get with the equivalent `StateRefT` monad.

**Comment by EdAyers** [comment]
ok I'll do it with `StateT` instead.
