### ISSUE TITLE
Pretty-printing issue

### ISSUE THREAD

**Issue by djvelleman** [leanprover/lean4#1619]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

In this example:
```
example : ∀ n : Nat, ∃ y : Fin n, y = y := by
```
in the tactic state, the goal displays as `ℕ → ∃ y, y = y`.  However, the arrow here is dependent, because the type of `y` depends on `n`, so it should be displayed with a universal quantifier.

### Steps to Reproduce

Just type in the example.

**Expected behavior:** Goal should be `∀ n : ℕ, ∃ y : Fin n, y = y`

**Actual behavior:** Goal is ``ℕ → ∃ y, y = y`

**Reproduces how often:** Always

### Versions

Lean (version 4.0.0-nightly-2022-08-25, commit d4799eaf3a74, Release)
MacOS 12.5.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by leodemoura** [comment]
AFAICT, this issue has been fixed by https://github.com/leanprover/lean4/commit/10a56bf4a1600775b8e05a75bbaae4af04ac830d
