### ISSUE TITLE
LSP: completion bug

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#1640]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Completion is missing function starting with underscore.
It seems the problem is that it ends up being marked as "blacklisted"  by [isBlackListed](https://github.com/leanprover/lean4/blob/master/src/Lean/Server/Completion.lean#L29).

The reason is that this method is considered `isInternal` because of the leading underscore,
but is not considered `isPrivateName` because it has no `private` access modifier.  So if you
add `private` then intellisense starts working, but we shouldn't have to do that.  It should 
show symbols in "my" project that start with underscore.

Of course, the reason for `isInternal` is that there are a bunch of compiler generated names
like `_sizeOf_n` and `_cstage1` and `_cstage2` and so on and we seem to have no good way
of identifying these `built in` names.  It would be nice if ConstantInfo contained a boolean
somewhere saying this was a compiler generated construct, then we could use that instead
as a better way to filter out unwanted intellisense completions.

PS: LLVMFunctions have a nice way of attaching any metadata you want to them which we
used in the ELL project to do something like this.  .NET also has a metadata system for 
identifying "special" built in names.

### Steps to Reproduce

```lean
def _foo : List String := ["apple", "orange"]

#eval main _foo
             --^ textDocument/completion
```
**Expected behavior:** 

It should find my `_foo` function defined immediately above the eval.

**Actual behavior:**

![image](https://user-images.githubusercontent.com/18707114/191871807-b144bbbc-25cc-4090-9ecb-94cd471350d2.png)

![image](https://user-images.githubusercontent.com/18707114/191871697-d327f8da-9387-41c3-ac2e-f67d51b135a3.png)

**Reproduces how often:**

100%

### Versions

"4.0.0-nightly-2022-09-20"

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by digama0** [comment]
In lean 3, you weren't even allowed to write definitions with an initial underscore. These are deliberately hidden and used for internal purposes.

**Comment by lovettchris** [comment]
Yes I see the reason for isInternal is that there are a bunch of compiler generated names like _sizeOf_n and _cstage1 and _cstage2 and so on and we seem to have no good way of identifying these built in names. It would be nice if ConstantInfo contained a boolean somewhere saying this was a compiler generated construct, then we could use that instead as a better way to filter out unwanted intellisense completions.

LLVMFunctions have a nice way of attaching any metadata you want to them which we used in the ELL project to do something like this. .NET also has a metadata system for identifying "special" built in names.  So I'm just filing this as an FYI suggesting there may be a better way than hard coding a check for names starting with underscore.

**Comment by Kha** [comment]
Let's close this in favor of https://github.com/leanprover/lean4/issues/1641 then
