### ISSUE TITLE
Vague import error

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#1669]
Some more investigation is required, this may be either a lean or lake problem, but when a lean file imports a file that doesn't exist you get the following error:
```
$ lake build
error: no such file or directory (error code: 2)
  file: ./././Test/IDontExist.lean
```
This says the file that doesn't exist, which is useful, but it does not say the even more useful information of what file produced the import error.

**Comment by gebner** [comment]
This is https://github.com/leanprover/lake/issues/25
