### ISSUE TITLE
Regression in name delaboration

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#1675]
```lean
import Lean
open Lean Parser.Tactic
def trLoc : MacroM (TSyntax ``location) := `(location| at *)
  --^ textDocument/hover

-- trLoc : MacroM (TSyntax (Name.mkStr4 "Lean" "Parser" "Tactic" "location"))
```
It seems that a recent change has made the elaborator produce `mkStr4` expressions instead of using `mkStr`, presumably related to the recent work on compiler constant-folding.

My recommendation is do to one of:
* Revert to using `mkStr` and convert to `mkStr4` in the compiler only. This results in slightly larger terms in exprs but also makes things simpler for simp lemmas, delaborators etc
* Implement a delaborator for `mkStr4` so that it displays as `` `Lean.Parser.Tactic.location`` above.

**Comment by gebner** [comment]
This is due to 126da8185d8d71bb85610d9422c2e4b7248fc8ac.  The same issue also applies for arrays BTW.

**Comment by leodemoura** [comment]
> Implement a delaborator for mkStr4 so that it displays as `Lean.Parser.Tactic.location above.

I prefer this solution.
