### ISSUE TITLE
lexicographic order on Prod will conflict with mathlib

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#1683]
Lean4 defines a lexicographic order on `Prod` in `src/Init/Core.lean`.
In mathlib3 we prefer to hide this order behind a type synonym, and instead use the componentwise partial order as the default instance on products.

Eventually this instance in core will clash with mathlib4, and one of them will have to go.

The lexicographic order on `Prod` is currently used, at least in `Lean/Data/Position.lean`.

**Comment by Kha** [comment]
Changing it to a `def` would be in line with https://github.com/leanprover/lean4/commit/71e647049f1273681d65ba1750ca67372ae9c514
