### ISSUE TITLE
`Kernel.isDefEq` throws C++ exceptions into lean code

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#1756]
```lean
import Lean
open Lean

#eval show CoreM _ from do
  pure <| Kernel.isDefEq (← getEnv) {} (.bvar 0) (.bvar 1)
```
crashes lean with:
```
libc++abi: terminating with uncaught exception of type lean::kernel_exception: type checker does not support loose bound variables, replace them with free variables before invoking it
```
While it's probably a bad idea to use `Kernel.isDefEq` at all, seeing as it is marked "for debugging only", it should still ideally be usable from lean - it's not marked unsafe so crashing the runtime doesn't sound like a good idea. This is an issue for mathport, which uses the kernel typechecker since it doesn't need to work on metavariables. I would like to have a `Kernel.isDefEqGuarded` but there isn't any way to implement that in lean because of this issue.

**Comment by gebner** [comment]
Relatedly, you can get an internal panic with very innocent safe Lean code:
```lean
import Lean

def constInfo : Lean.ConstantInfo :=
  .axiomInfo {
    name := `foo
    levelParams := [`u]
    type := .sort (.param `u)
    isUnsafe := false
  }

#eval constInfo.instantiateTypeLevelParams []
```

I'm pretty sure I've seen this in mathport as well, when we try to align declarations with different number of universe parameters.
