### ISSUE TITLE
square braces can cause exponential time/memory consumption 

### ISSUE THREAD

**Issue by dwrensha** [leanprover/lean4#1760]
The following input (found via fuzz testing) causes `lean` to take 140 seconds and consume 11.6 GB:
```lean
def foo : [[[[[[[[[[[[[
```
Adding more braces seems to make it exponentially worse.
My expectation is that, even if lean must perform exponential work in some situation, some kind of heartbeat will trigger before things get out of hand like this.

```
Lean (version 4.0.0-nightly-2022-10-18, commit faa612e7b79a, Release)
```

**Comment by leodemoura** [comment]
Plan: add cache to parser, no choice when there are errors
