### ISSUE TITLE
False hovering information for nil

### ISSUE THREAD

**Issue by zStruCat** [leanprover/lean4#1764]
![图片](https://user-images.githubusercontent.com/98123484/197274121-5752fb6b-55b9-4f73-bf17-6513c9316e28.png)
I suppose nil here mean any pattern.

**Comment by leodemoura** [comment]
Yes, `nil` is a pattern variable. Note that it is light blue. Constants are white in your color scheme.
Try: `List.nil` or `[]`.

**Comment by zStruCat** [comment]
> Yes, `nil` is a pattern variable. Note that it is light blue. Constants are white in your color scheme. Try: `List.nil` or `[]`.
Yes, I realized that. I just figured that the hovering info is misleading.

**Comment by gebner** [comment]
Ah, I got mislead by the highlighting here.  I thought we had a hover over the redundant alternatives (because it is highlighted in the screenshot).

The behavior you're seeing here is intentional.  If it was a constant, we'd show the full name in the hover: `List.nil`.

**Comment by zStruCat** [comment]
> Ah, I got mislead by the highlighting here. I thought we had a hover over the redundant alternatives (because it is highlighted in the screenshot).
> 
> The behavior you're seeing here is intentional. If it was a constant, we'd show the full name in the hover: `List.nil`.

You're right. I misunderstood. You may close the issue.

**Comment by zStruCat** [comment]
> Ah, I got mislead by the highlighting here. I thought we had a hover over the redundant alternatives (because it is highlighted in the screenshot).
> 
> The behavior you're seeing here is intentional. If it was a constant, we'd show the full name in the hover: `List.nil`.
