### ISSUE TITLE
Unknown package 'Mathlib'

### ISSUE THREAD

**Issue by u7122029** [leanprover/lean4#1792]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
Attempting to import Mathlib in VSCodium fails with error "Unknown package 'Mathlib'" in the infoview.

### Steps to Reproduce
Follow the instructions from this video https://www.youtube.com/watch?v=DXvA1qaQFtY until 1:25. Instead of using VSCode, use VSCodium. EDIT: recently tried in VSCode and the same problem happens.

**Expected behavior:** Mathlib package imports normally and automatically builds.
**Actual behavior:** Mathlib package not recognised and processing is stopped.

**Reproduces how often:** 100% of the time, even after closing and reopening VSCodium.

### Versions
Lean (version 4.0.0-nightly-2022-10-30, commit 8b9fe9b6c271, Release),
OS Name: Microsoft Windows 10 Home
Version: 10.0.19044 Build 19044

### Additional Information

None.

**Comment by Kha** [comment]
I believe this was solved in https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Issues.20importing.20mathlib4

**Comment by A-BCDe** [comment]
I also have the same issue.
The error message shows that `default_target` is an unknown attribute, and it is, as `lakefile.lean` contains `defaultTarget` as an attribute.
Thus, I think the mathlib should update their attribute to camelcase, or there is something wrong with the recent build.

**Comment by digama0** [comment]
The attributes have recently been updated from camel case to snake case. If you get that error it probably means you are using an out-of-date version of lean: you should use the same version of lean specified in the `lean-toolchain` of mathlib in your own `lean-toolchain` file.
