### ISSUE TITLE
Formatting `Syntax` objects in trace and error messages

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#182]
We should use the parenthesizer and formatter in `Syntax` objects before we print them. We should also hide macro scopes.
Example:
```lean
set_option pp.macroStack true

def f (x : List String) :=
if x + 1 > 0 then 1 else 2
```
One of the error messages is
```
error: failed to synthesize instance
  HasOfNat (List String)
with resulting expansion
  Greater._@._internal._hyg.0 x + 1 0 
while expanding
  x + 1 > 0 
while expanding
  if x + 1 > 0 then 1 else 2 
```
In the message, `Greater._@._internal._hyg.0 x + 1 0` should be printed as `Greater✝¹  (x + 1) 0`.  

Here is the ideal place to invoke formatter, parenthesizer, ...
https://github.com/leanprover/lean4/blob/d33f7c78852ba99a153e5f9f3da23144ac702d89/src/Lean/Message.lean#L72-L73

@Kha We should make sure that sanitized names in the `Syntax` object (e.g., `Greater✝¹`) do not collide with sanitized names at `ctx.lctx`.

**Comment by Kha** [comment]
> @Kha We should make sure that sanitized names in the Syntax object (e.g., Greater✝¹) do not collide with sanitized names at ctx.lctx.

Could you give an example of such a conflict? AFAICS, we do not have any messages containing both `ofSyntax` and `ofGoal` atm.

**Comment by leodemoura** [comment]
> Could you give an example of such a conflict? AFAICS, we do not have any messages containing both ofSyntax and ofGoal atm.

We can have messages containing `ofExpr` and `ofSyntax` with a surrounding `withContext`.
This is not a hypothetical problem, it happens when we set `pp.macroStack true`.
