### ISSUE TITLE
Proof inside the function

### ISSUE THREAD

**Issue by halazi1** [leanprover/lean4#1836]
**contradictory conditions, but do not report borrowing**

<img width="424" alt="Screenshot 2022-11-16 124700" src="https://user-images.githubusercontent.com/100744142/202086666-ab0ae321-7ed0-4638-902c-561778bd5227.png">

### Versions

> lean --version
Lean (version 4.0.0-nightly-2022-11-14, commit a2199d6d57b7, Release)

**Comment by digama0** [comment]
This is not a bug, the language is working as designed. To discuss this example in more detail, I encourage you to re-post this on our discussion forum https://leanprover.zulipchat.com/ .
