### ISSUE TITLE
initialization code in the interpreter

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#185]
The following code produces a segfault in the interpreter

```lean
def mkNatRef : IO (IO.Ref Nat) :=
IO.mkRef 0

@[init mkNatRef]
constant myRef : IO.Ref Nat := arbitrary _

def tst : IO Unit := do
myRef.modify Nat.succ;
myRef.get >>= IO.println

#eval tst
```

**Comment by leodemoura** [comment]
@Kha We discussed this issue in the past, but I don't remember the details anymore. Do you remember them? If yes, could you please summarize them here? I even forgot the bug existed. I re-discovered the issue yesterday when I was adding the notation `initialize myRef : IO.Ref Nat <- IO.mkRef 0` :)
BTW, the segfault occurs even if the `[init]` is in a different module. 
I think it is reasonable to produce an error in the example above where the `[init]` for `myRef` and the code that uses `myRef` (i.e., `tst`) are in the same file. That being said, we should be able to handle the case where the `[init]` code is in an imported file, but we do not have native code for it. I think this was the compromise we considered last time. That is, 
we wanted to interpret the initialization code for module `A` whenever we import `A` and we don't have native code for it.

**Comment by Kha** [comment]
> That is, we wanted to interpret the initialization code for module A whenever we import A and we don't have native code for it.

Yes, this should be safe. But we probably don't want to do this in the stdlib, do we? What's the best way to check for that?
