### ISSUE TITLE
Widgets: Mousing over parentheses should highlight the term inside the parentheses

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean4#1854]
### Description

When mousing a parenthesis in an output window, I would like that only the term inside those parentheses is highlighted, not the term containing the parentheses.

### Steps to Reproduce

In 
```lean
theorem foo (a b c : Nat) : a + (b + c) = a + (b + c) := rfl
```
Navigate to the `rfl` and hover your mouse over any parenthesis in the output view

**Expected behavior:** Only `(b + c)` is highlighted and you receive a pop-up for that term. 

**Actual behavior:** `a + (b + c)` is highlighted.

The expected behavior is better. On large terms, it can be hard to find the infix that corresponds to the expression inside the parentheses.

**Comment by Vtec234** [comment]
@fpvandoorn by output view do you mean the goal panel in VScode or something else?

**Comment by fpvandoorn** [comment]
Yes, I mean the goal panel
