### ISSUE TITLE
Namespace prefix opens constants but not scoped syntax

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lean4#1874]
### Description

In the example below, I would expect `mk_eq_mk₃` to parse successfully, as the other ones do.
```lean
namespace Foo

axiom Foo : Type
axiom mk : Foo
axiom rel : Foo → Foo → Prop

scoped infixl:50 " ~ " => rel

theorem mk_eq_mk₁ : mk ~ mk := sorry -- works

end Foo

theorem Foo.mk_eq_mk₂ : rel mk mk := sorry -- works

/- expected token -/
theorem Foo.mk_eq_mk₃ : mk ~ mk := sorry

open Foo in
theorem Foo.mk_eq_mk₄ : mk ~ mk := sorry -- works
```

**Expected behavior:** `Foo.mk_eq_mk₃` parses successfully like the other ones.

**Actual behavior:** The scoped notation is not recognized.

**Reproduces how often:** 100%

### Versions

cbf7da0f6ef35774407132cf8f5802daf2c9a39b

**Comment by leodemoura** [comment]
This is the expected behavior. 
Recall that `theorem Foo.mk_eq_mk₃ : mk ~ mk := sorry` is expanded into 
```lean
namespace Foo 
theorem mk_eq_mk₃ : mk ~ mk := sorry
end Foo
```
**after** we have parsed the command.
