### ISSUE TITLE
Missing API for instance attributes

### ISSUE THREAD

**Issue by mcdoll** [leanprover/lean4#1878]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The file `Lean/Meta/Instances.lean` misses API to get the priority and attribute kind of existing instances.

```lean
def getPriority (declName : name) : CoreM (Option Nat) := sorry

def getAttrKind (declName : name) : CoreM (Option AttributeKind) := sorry
```

### Steps to Reproduce

n/a

### Versions

commit: [1b0c2f7](https://github.com/leanprover/lean4/commit/1b0c2f7157e4d023bab91ca797366741f6d048f9)

**Comment by leodemoura** [comment]
Added the APIs.
```
def getInstancePriority? (declName : Name) : CoreM (Option Nat)
def getInstanceAttrKind? (declName : Name) : CoreM (Option AttributeKind)
```
