### ISSUE TITLE
Linter performance issue on tactic proofs

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#1899]
The unused variable linter is a performance bottleneck on big proofs created using tactics.
I noticed this problem while investigating `simp` performance issues raised by @bollu.
Here is a random example where the linter takes 3.1 seconds on my machine.
```lean
universe u

@[simp↓] axiom not_exists {α : Sort u} (p : α → Prop) : (¬ (∃ (x : α), p x)) = ∀ (x : α), ¬ p x
opaque P {α : Sort u} : α → Prop
@[simp] axiom P_eq {α : Sort u} (a : α) : P a = false

-- set_option linter.unusedVariables false
set_option profiler true
theorem ex : ¬ ∃ (x1 _x2 _x3 _x4 _x5 _x6 _x7 _x8 _x9 _x10 _x11 _x12 _x13 _x14 _x15 _x16 _x17 _x18 _x19 _x20 : α)
                 (_x1 _x2 _x3 _x4 _x5 _x6 _x7 _x8 _x9 _x10 _x11 _x12 _x13 _x14 _x15 _x16 _x17 _x18 _x19 _x20 : α)
                 (_x1 _x2 _x3 _x4 _x5 _x6 _x7 _x8 _x9 _x10 _x11 _x12 _x13 _x14 _x15 _x16 _x17 _x18 _x19 _x20 : α)
                 (_x1 _x2 _x3 _x4 _x5 _x6 _x7 _x8 _x9 _x10 _x11 _x12 _x13 _x14 _x15 _x16 _x17 _x18 _x19 _x20 : α)
                 (_x1 _x2 _x3 _x4 _x5 _x6 _x7 _x8 _x9 _x10 _x11 _x12 _x13 _x14 _x15 _x16 _x17 _x18 _x19 _x20 : α)
                 (_x1 _x2 _x3 _x4 _x5 _x6 _x7 _x8 _x9 _x10 _x11 _x12 _x13 _x14 _x15 _x16 _x17 _x18 _x19 _x20 : α)
                 (_x1 _x2 _x3 _x4 _x5 _x6 _x7 _x8 _x9 _x10 _x11 _x12 _x13 _x14 _x15 _x16 _x17 _x18 _x19 _x20 : α)
                 (_x1 _x2 _x3 _x4 _x5 _x6 _x7 _x8 _x9 _x10 _x11 _x12 _x13 _x14 _x15 _x16 _x17 _x18 x19 x20 : α)
                 , P x1 ∨ P x20 ∨ P x19 := by
  simp
```

**Comment by Kha** [comment]
Almost all the time is spent in `Expr.forEach` from https://github.com/leanprover/lean4/blob/5286c2b5aa30403cbf75f9e67d406edbfca12b67/src/Lean/Linter/UnusedVariables.lean#L182. When deactivating the `forEach` cache, linting falls to 17ms.

**Comment by leodemoura** [comment]
@Kha Yes, I just used `perf` and 93% of the time is being spent at `expr_eq_fn`. 
- `expr_eq_fn` function uses pointer equality. 
- You observed that disabling the cache dramatically improved the runtime. Thus the proof should not have a lot of sharing.

So, I think the performance issue is due to hash collisions. There are big (and very similar but different) terms with the same hash code.

**Comment by Kha** [comment]
In essence there are three possible variants of `forEach`:
* guarantee to visit only unique subterms (current implementation, expensive cache)
* best-effort to avoid redundant visits with ptr cache like in `replace`/...
* no cache
Any of the latter two should work for the linter as its action is idempotent, but hard to say which one is more appropriate.

**Comment by Kha** [comment]
I got slightly more varied timings: 
![image](https://user-images.githubusercontent.com/109126/204855653-e64885c0-eaed-4c63-9722-9eb54cb92d79.png)

**Comment by leodemoura** [comment]
> best-effort to avoid redundant visits with ptr cache like in replace/...

The ptr cache is not always safe for `forEach`. It depends on the function `f`. 
However, the instance at the unused variable linter is safe.

> no cache

It will be slow if there is a lot of sharing.

**Comment by leodemoura** [comment]
I used the following `perf` command
```
perf record --call-graph dwarf,60000 stage1/bin/lean 1899.lean
```

**Comment by leodemoura** [comment]
Most (if not all) `forEach` instances use a function `f` that can be written as `fun e => if p e then ...`. The predicate `p` is pure. In many cases `p e` holds only for very small `Expr`s (e.g., free variables). Thus, I am going to add a `e.forEachIf p f` which applies `f` to sub-expressions that satisfy `p`. The new combinator uses two caches:
- A pointer equality one like the one at `replace`.
- A regular cache that is used only for expressions that satisfy `p`.

I am going to add it today.

**Comment by leodemoura** [comment]
BTW, the same hash collision issue may happen in other places where we want to use the (potentially) expensive cache. Example: `simp`.

**Comment by leodemoura** [comment]
The new hash at https://github.com/leanprover/lean4/commit/e5681ac141018e2fee4bcaf46b479e12900abecd
addresses the performance issue.
I will also add `forEachIf` combinator.
