### ISSUE TITLE
Incorrect or out of date docs on MonadReaderOf

### ISSUE THREAD

**Issue by david-christiansen** [leanprover/lean4#1902]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The docstring for `MonadReaderOf` includes the following:
```
An implementation of [`MonadReader`]. It does not contain `local` because this
function cannot be lifted using `monadLift`. Instead, the `MonadReaderAdapter`
class provides the more general `adaptReader` function.
```

However, neither `MonadReaderAdapter` nor `adaptReader` occur elsewhere in the source tree. Jannis Limperg pointed me to `withReader` in `MonadWithReaderOf` as the way to accomplish what `local` does in Haskell's `MonadReader` class.

### Steps to Reproduce

1. "Go to definition" or hover on `MonadReaderOf`
2. Read the inline API docs
3. Grep the source for `MonadReaderAdapter`, and find nothing other than the docs

**Expected behavior:** 
1. "Go to definition" or hover on `MonadReaderOf`
2. Read the inline API docs
3. See a reference to `MonadWithReaderOf`, and use it successfully

**Actual behavior:**

The reference is not found.

**Reproduces how often:**

100%

### Versions

This is on Fedora 37:
```
» lean --version
Lean (version 4.0.0-nightly-2022-11-26, commit 42a080fae2ef, Release)
» uname -a
Linux localhost.localdomain 6.0.9-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov
```

### Additional Information

None needed.

**Comment by david-christiansen** [comment]
af5efe0b2d0837b9846a32b32c382d8135ddcd76 seems to have fixed this.

**Comment by Kha** [comment]
Ah, I did link `MonadWithReader` without the `Of` though... if I were to rewrite all these docstrings, I would probably present the `Of`-less classes as the "main interfaces" as use of the `Of` variants is quite rare. For instance definitions however you usually want the `Of` variant as you then get the other instance for free.

**Comment by david-christiansen** [comment]
Ideally, the docstring syntax would have identifiers resolved to their sites, so a linter could complain when the reference is busted. At some point, I should show you a demo of how docstrings worked in Idris 1 - I think there's some useful experiences to take from that.
