### ISSUE TITLE
Dot notation and `CoeFun`

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lean4#1910]
### Description

This is a question that came up in mathport, resulting from an incompatibility between how dot notation is elaborated in Leans 3 and 4.

In Lean 3, we can (mis?)use dot notation in cases where the applied constant is in the right namespace but does not have an argument of the right type. In the `example` below
```lean
structure equiv (α : Sort*) (β : Sort*) :=
(to_fun    : α → β)
(inv_fun   : β → α)

infix ` ≃ `:25 := equiv

instance {α : Sort*} {β : Sort*} : has_coe_to_fun (α ≃ β) (λ _, α → β) :=
  ⟨equiv.to_fun⟩

def foo := nat
def bar := nat
def foo.to_bar : foo ≃ bar := ⟨id, id⟩

example (f : foo) : f.to_bar = f.to_bar := rfl
```
the term `f.to_bar` is first transformed to `foo.to_bar f`, at which point the standard function application elaborator kicks in and finds a `has_coe_to_fun` instance. The current community edition implementation is described in the last paragraph [here](https://github.com/leanprover-community/lean/commit/f2b2beefe2e9ab200d23e1c99dc20879eb32e9fa). In practice, this is used for applying bundled morphisms (with equivalences being a special case) as if they were functions, for example [`enat.to_nat`](https://leanprover-community.github.io/mathlib_docs/data/enat/basic.html#enat.to_nat).

In Lean 4, this does not work.
```lean
structure Equiv (α β : Sort _) where
  toFun : α → β
  invFun : β → α

infixl:25 " ≃ " => Equiv

instance: CoeFun (α ≃ β) fun _ => α → β where
  coe := Equiv.toFun

def Foo := Nat
def Bar := Nat
def Foo.to_Bar : Foo ≃ Bar := ⟨id, id⟩

/- invalid field notation, function 'Foo.to_Bar' does not have argument with type (Foo ...)
that can be used, it must be explicit or implicit with an unique name -/
example (f : Foo) : f.to_Bar = f.to_Bar := sorry
```

From the [Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Field.20notation.20and.20.60CoeFun.60) it seems that this is useful to have but it is not immediately clear whether Lean 4 should definitely have this feature, so this is a request for feedback.

**Comment by jcommelin** [comment]
Another example from mathlib: `Multiset.card {α} : Multiset α →+ ℕ`
