### ISSUE TITLE
Random test segfaults in Linux Debug CI

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#1914]
- [`floatarray`](https://github.com/leanprover/lean4/actions/runs/3603631597/jobs/6072071151)
- [`struct1`](https://github.com/leanprover/lean4/actions/runs/3605739900/jobs/6076430231)
- [`foldConsts`](https://github.com/leanprover/lean4/actions/runs/3608675322/jobs/6081417888)

**Comment by leodemoura** [comment]
I executed `struct1` with debug build and valgrind. Valgrind did not report any problems. BTW, I had to compile Lean using g++. It seems there is some compatibility issue with clang. I got the following error messages when using clang.
```
~/projects/lean4/build/debug (master) $ valgrind stage1/bin/lean ../../tests/lean/run/struct1.lean
==252223== Memcheck, a memory error detector
==252223== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==252223== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==252223== Command: stage1/bin/lean ../../tests/lean/run/struct1.lean
==252223== 
### unhandled dwarf2 abbrev form code 0x25
### unhandled dwarf2 abbrev form code 0x25
### unhandled dwarf2 abbrev form code 0x25
### unhandled dwarf2 abbrev form code 0x1b
get_Form_szB: unhandled 27 (DW_FORM_addrx)
--252223-- WARNING: Serious error when reading debug info
--252223-- When reading debug info from /home/leodemoura/projects/lean4/build/debug/stage1/bin/lean:
--252223-- get_Form_contents: unhandled DW_FORM
### unhandled dwarf2 abbrev form code 0x25
### unhandled dwarf2 abbrev form code 0x25
### unhandled dwarf2 abbrev form code 0x25
### unhandled dwarf2 abbrev form code 0x1b
### unhandled dwarf2 abbrev form code 0x25
### unhandled dwarf2 abbrev form code 0x25
### unhandled dwarf2 abbrev form code 0x25
### unhandled dwarf2 abbrev form code 0x1b
==252223== Valgrind: debuginfo reader: ensure_valid failed:
==252223== Valgrind:   during call to ML_(img_get)
==252223== Valgrind:   request for range [149281984, +4) exceeds
==252223== Valgrind:   valid image size of 138890064 for image:
==252223== Valgrind:   "/home/leodemoura/projects/lean4/build/debug/stage1/lib/lean/libleanshared.so"
==252223== 
==252223== Valgrind: debuginfo reader: Possibly corrupted debuginfo file.
==252223== Valgrind: I can't recover.  Giving up.  Sorry.
==252223== 
```

**Comment by leodemoura** [comment]
Found this link, but did not explore it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1758782

**Comment by leodemoura** [comment]
Valgrind also did not report any issues for `floatarray.lean`

**Comment by gebner** [comment]
Yet another segfault yesterday: [`foldConsts`](https://github.com/leanprover/lean4/actions/runs/3608675322/jobs/6081417888)

**Comment by leodemoura** [comment]
@gebner Have you managed to reproduce the failure on your machine?

**Comment by gebner** [comment]
I believe this might be triggered by the [recent upgrade of `ubuntu-latest` to Ubuntu 22.04](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/).

We've had a similar issue in Lean 3: https://github.com/leanprover-community/lean/pull/791  I've managed to set up the coredumps in github actions, but the backtrace didn't point to an obvious fix.  Downgrading to `ubuntu-20.04` seemed to fix the issue though.

**Comment by gebner** [comment]
And yet another one: [`calcInType`](https://github.com/leanprover/lean4/actions/runs/3645258068), now in Linux release!

**Comment by Kha** [comment]
And stage3, wow https://github.com/leanprover/lean4/actions/runs/3647478628/jobs/6159757243#step:17:916

**Comment by gebner** [comment]
And Linux aarch64 as well
https://github.com/leanprover/lean4/actions/runs/3673519105/jobs/6210733920

And of course it happens in the configuration where I didn't set up the coredumps...

**Comment by Kha** [comment]
> I've managed to set up the coredumps in github actions, but the backtrace didn't point to an obvious fix. Downgrading to `ubuntu-20.04` seemed to fix the issue though.

So do we expect this to be different here or should we just downgrade?

**Comment by gebner** [comment]
> > I've managed to set up the coredumps in github actions, but the backtrace didn't point to an obvious fix. Downgrading to `ubuntu-20.04` seemed to fix the issue though.
> 
> So do we expect this to be different here or should we just downgrade?

Downgrading doesn't seem like a sustainable solution.  For Lean 3 it makes sense, since Lean 3 is hopefully EOL before Ubuntu 20.04.  But I'm keeping my fingers crossed that Lean 4 will survive a bit longer.

> but the backtrace didn't point to an obvious fix.

In Lean 3, the backtrace showed a crash in `std::condition_variable` while initializing the options (which are guarded by a `shared_mutex` which is implemented using condition variables).  I didn't see anything obviously wrong in the `shared_mutex` code.

We don't have the `shared_mutex` code in Lean 4 anymore, so the core dumps should show a different issue, which would ideally allow us to figure out what's going on with the Ubuntu 22.04 upgrade.

**Comment by Kha** [comment]
By the way, given the solution, it probably wasn't the Ubuntu upgrade but the switch to murmurhash, which simply happened to result in one particularly unfortunate new hash for a module name.

**Comment by Kha** [comment]
Like, extremely unfortunate: out of 920 module names, we happened to hash one into the top 0.008% of the address space
