### ISSUE TITLE
pretty printer: `Name.anonymous` in binders

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#193]
Repro:
```lean
import Lean
new_frontend
open Lean

set_option trace.Meta.debug true 

def test1 : MetaM Unit :=
trace! `Meta.debug (mkLambda Name.anonymous BinderInfo.default (mkSort levelZero) (mkBVar 0))

#eval test1 -- [Meta.debug] fun ([anonymous] : Prop) => [anonymous]
```

**Comment by Kha** [comment]
It looks like Lean 3 used the same output. What would be a more desirable one?

**Comment by leodemoura** [comment]
> It looks like Lean 3 used the same output. 

In Lean3, we didn't have the ambition of being able to re-elaborate the output produced by the pretty-printer.
The test above is artificial, but the `[anonymous]` appears in actual examples. I found it yesterday while debugging the new frontend.

> What would be a more desirable one?

A fresh name of the form `a_<idx>` or something similar to this.
