### ISSUE TITLE
Bug in Json parser

### ISSUE THREAD

**Issue by AliasQli** [leanprover/lean4#1985]
`Lean.Json.parse` can't parse `\u`-escaped caharacters correctly. For example, `\u79d1` is "科", but `Lean.Json.parse "\"\\u79d1\""` is `"礱"`, which is `\u7931`. The bug seems to be caused here:

https://github.com/leanprover/lean4/blob/a2f59591189824f30a7a512d6a72d24df3a7bfc7/src/Lean/Data/Json/Parser.lean#L14-L24

And this should fix it:

```lean
 @[inline] 
 def hexChar : Parsec Nat := do 
   let c ← anyChar 
   if '0' ≤ c ∧ c ≤ '9' then 
     pure $ c.val.toNat - '0'.val.toNat 
   else if 'a' ≤ c ∧ c ≤ 'f' then 
     pure $ c.val.toNat - 'a'.val.toNat + 10 
   else if 'A' ≤ c ∧ c ≤ 'F' then 
     pure $ c.val.toNat - 'A'.val.toNat + 10 
   else 
     fail "invalid hex character" 
```

**Comment by gebner** [comment]
Fixed by d19033e44326ce9323f4c0e80f030f3051ba4c26
