### ISSUE TITLE
Wrong goal shown after space when focussing with `·`

### ISSUE THREAD

**Issue by javra** [leanprover/lean4#1989]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

In the following example, in line 3, col 5, the focussed goal (`p`) should be displayed instead of the other one.
```lean
example (hp : p) (hq : q) : p ∧ q := by
  constructor
  · -- place cursor here
``` 

### Version

4.0.0-nightly-2022-12-20

**Comment by Kha** [comment]
Seems to be fixed
