### ISSUE TITLE
Feature suggestion: Alternation syntax in patterns

### ISSUE THREAD

**Issue by SabrinaJewson** [leanprover/lean4#1993]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Sometimes in patterns it is useful to select one of a couple constructors for a single branch, to reduce code duplication. This means that the following code:

```lean
| (constructor₁ _) := (some expression)
| (constructor₂ _) := (identical expression)
| _ := (something else)
```

can be shortened to:

```lean
| (constructor₁ _ | constructor₂ _) := (some expression)
| _ := (something else)
```

I came across wanting this feature when I wanted to define a `<`operation on an inductive data type with a few variants:

```lean
def my_type.lt : my_type → my_type → Prop
| (my_type.c₁ n) (my_type.c₁ m) := n < m
| (my_type.c₁ _) _ := true
| (my_type.c₂) (my_type.c₁ _) := false
| (my_type.c₂) (my_type.c₂) := false
| (my_type.c₂) _ := true
| (my_type.c₃) (my_type.c₁ _) := false
| (my_type.c₃) (my_type.c₂) := false
| (my_type.c₃) (my_type.c₃) := false
| (my_type.c₃) _ := true
-- etc for a few more constructors
```

is much better written as:

```lean
def my_type.lt : my_type → my_type → Prop
| (my_type.c₁ n) (my_type.c₁ m) := n < m
| (my_type.c₁ _) _ := true
| (my_type.c₂) (my_type.c₁ _ | my_type.c₂) := false
| (my_type.c₂) _ := true
| (my_type.c₃) (my_type.c₁ _ | my_type.c₂ | my_type.c₃) := false
| (my_type.c₃) _ := true
```

It would also be good if variables of the same name and type could be bound on either side of the pattern, for example:

```lean
def demo : (ℕ × ℤ) ⊕ (ℤ × ℕ) : ℕ :=
| (sum.inl n (0 | 1)) | (sum.inr (0 | 1 | 2) n) := n
| _ := 5
```

The syntax doesn’t have to exactly use `|` — I only chose that because it’s what I’m familiar with (the Rust syntax).

**Comment by digama0** [comment]
This already exists, although it does not work in nested contexts. 
```lean
def demo : (Nat × Int) ⊕ (Int × Nat) → Nat 
| .inl (n, 0) | .inl (n, 1) | .inr (0, n) | .inr (1, n) | .inr (2, n) => n
| _ => 5
```
