### ISSUE TITLE
Local notation can no longer be named

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#2009]
```lean
local notation (name := foo) "foo" => 42
```
Now fails with `invalid syntax node kind 'foo._@.ln._hyg.3'` after 2b67da285405d71bb2b6b52a78b951199296e1b2.

**Comment by leodemoura** [comment]
I will fix this. My plan is to make sure the user-provided name is used without adding macro scopes in local notations and syntax. Note that it will be an error if two different files define the same local notation with the same user-provided name.
