### ISSUE TITLE
'make test' does not run in parallel

### ISSUE THREAD

**Issue by tobiasgrosser** [leanprover/lean4#2010]
When running 'make test' on a 16-core system, all tests are executed single-threaded. It would be nice if there would be a way to run tests in paralle.

**Comment by Kha** [comment]
There is :) https://leanprover.github.io/lean4/doc/dev/testing.html

**Comment by leodemoura** [comment]
I am closing this issue since there is a way of running tests in parallel. Please reopen if the documentation in the link above is not clear.
