### ISSUE TITLE
Remove `Has` prefix

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#203]
The new naming convention makes the `Has` prefix unnecessary (e.g., `HasAdd`, `HasToString`).
The `Has` is a legacy from the Lean3 naming convention.
Moreover, we have already been dropping the `Has` prefix in new code (e.g, we use `ToExpr` instead of `HasToExpr`).

**Comment by leodemoura** [comment]
We should delete the old frontend before we fix this issue.

**Comment by Kha** [comment]
If the class is a single operation (e.g. `Orelse`) and we also want to expose the operation as such (e.g. `EStateM.orelse`), how should we name the instance?

**Comment by leodemoura** [comment]
> If the class is a single operation (e.g. `Orelse`) and we also want to expose the operation as such (e.g. `EStateM.orelse`), how should we name the instance?

I missed this comment. Right now, we are using very few explicit instance names. If we need to name them, I agree it would be nice to have naming convention. Suggestions: `orElseInst` or `hasOrElse`.
