### ISSUE TITLE
`calc` doesn't unfold target when it is a relation

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#2073]
```lean
def Commute (a b : Nat) := a * b = b * a

example : Commute 1 2 :=
  calc
    1 * 2 = 2 * 1 := by simp
-- invalid 'calc' step, left-hand-side is
--   1 * 2 : ?m.178
-- expected
--   1 : Nat
```
As [reported on Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/calc.20blocks.20and.20heterogeneous.20operators/near/324372265).

**Comment by fgdorais** [comment]
I think this might be the same issue. This used to work:
```lean
example (h : y ≤ x) : 3 + x > 2 + y := calc
  _ < 3 + y := Nat.add_lt_add_right (by decide) y
  _ ≤ 3 + x := Nat.add_le_add_left h 3
```
The quick workaround is:
```lean
example (h : y ≤ x) : 3 + x > 2 + y := 
  show 2 + y < 3 + x from calc
  _ < 3 + y := Nat.add_lt_add_right (by decide) y
  _ ≤ 3 + x := Nat.add_le_add_left h 3
```

**Comment by digama0** [comment]
Yes, that's the same issue. See also https://github.com/leanprover-community/mathlib4/pull/1927/files which has a bunch of examples of the issue.

**Comment by gebner** [comment]
I've reverted the corresponding part of #2066.  It's a bit of a tradeoff, there's a few regressions with coercions but maybe that's better for mathlib overall.
