### ISSUE TITLE
[cmake] Build Files Generator not pinned to Unix Makefiles

### ISSUE THREAD

**Issue by iacore** [leanprover/lean4#2083]
### Description

When building the project, if the default build file generator is, for example, Ninja, then the build files would be generated, but not functional.

### Steps to Reproduce

```
export CMAKE_GENERATOR=Ninja
cmake -B build
```

**Expected behavior:** The build generator should be automatically pinned to "Unix Makefiles"

**Actual behavior:** Generate broken `build.ninja`

**Reproduces how often:** always

### Workaround

Use `cmake -G "Unix Makefiles"`

**Comment by tannal** [comment]
+1

**Comment by nomeata** [comment]
Thanks for this report. Unfortuantely, we don’t have the capacity to support non-standard way of building lean besides those documented in <https://lean-lang.org/lean4/doc/make/index.html>, so I’ll close this. (Very small and obviously not harmful PRs improving things for you may have a chance of getting accepted, but please be mindful that every PR has a cost in terms of attention.)

**Comment by iacore** [comment]
> Thanks for this report. Unfortuantely, we don’t have the capacity to support non-standard way of building lean besides those documented in https://lean-lang.org/lean4/doc/make/index.html, so I’ll close this.

I believe the default CMake codegen target (Unix Makefiles) is assumed, not mentioned in the linked documentation. I have the default set to Ninja since it is faster in all cases of projects being able to be built by it.
