### ISSUE TITLE
LCNF let declaration mismatch

### ISSUE THREAD

**Issue by JamesGallicchio** [leanprover/lean4#2147]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Compiler error: ```LCNF let declaration mismatch at `_x.3`, does not match value in local context```
Raised here: https://github.com/leanprover/lean4/blob/master/src/Lean/Compiler/LCNF/Check.lean#L175

### Steps to Reproduce

MWE:
```
class OMonad (W : Type u → Type v) where

class MonadTrans (T : (Type _ → Type _) → (Type _ → Type _)) where

instance [OMonad m] [MonadTrans T] : OMonad (T m) where

instance : OMonad Id where

instance : MonadTrans (StateT σ) where

class LawfulOMonad (W) [OMonad W] where

instance : LawfulOMonad (StateT σ Id) where
```

**Expected behavior:** should compile

**Actual behavior:** code generator fails

### Versions

`"4.0.0-nightly-2023-03-07"`

**Comment by hargoniX** [comment]
Adding a bunch of debug output the error is the following.
This is the let construct that is in the LCNF expression tree
```
let _x.3 : OMonad fun α => σ → (fun type => type) (α × σ) := @instOMonad (fun type => type) (fun m α => σ → m (α × σ)) _x.1 _x.2
```
```
let _x.3 : OMonad fun α => σ → α × σ                      := @instOMonad (fun type => type) (fun m α => σ → m (α × σ)) _x.1 _x.2
```
this is the one that should be. Given that this error occurs right after the simplification pass I believe that the simplifier reduce the type but forgot to update it in the compilation context. I'll try dig up where in the simplifier this is happening.
