### ISSUE TITLE
[RFC] Do not automatically build dependencies

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#2154]
Currently, if you open a Lean file in a project using Lake, we automatically call `lake print-paths My.Lean.File`.  This command will, as a side-effect, build all dependencies for that file.

In a recent [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/how.20to.20run.20.60lake.20exe.20cache.20get.60.20while.20in.20VSCode), many users have reported that they dislike this feature and that it doesn't fit into their workflow (me included).  This is only one example of the workarounds people have to resort to:
> I usually run `sleep 1; killall lean` in a loop when starting up vscode [...]

(We have had a similar misfeature in Lean 3, often called the "orange bar hell".)

Automatic building of dependencies is a very expensive and destructive operation.  There are plenty of good reasons why you might want to avoid it:
 - You want to run `lake exe cache get` first.
 - You explicitly want to use out-dated `.olean` files (c.f. the `--old` feature in Lean 3).
 - You want to make a temporary change to a Lean file and not destroy its olean file.  (After reverting the change, the old olean is up-to-date again.)

It is very easy to hit the automatic build, e.g. if you want to import `Mathlib.Foo.Bar.Baz` and wait too long after typing `import Mathlib` then Lake will start building everything.

There are also some more reasons that are due to current technical limitations and bugs:
 - Opening multiple files calls `lake print-paths` multiple times in parallel.  Right now this will duplicate builds, and potentially corrupt olean files.
 - You already have `lake build` running and want to avoid duplicate builds.
 - Displaying the last line of the `lake print-paths` output in a diagnostic is terrible UI, and you'd rather see the `lake build` output in a terminal.
 - Closing a file doesn't stop the Lake build.

Note that we already disable automatic builds in Lean core.  I would like to propose to disable them in Lake projects as well.

Concretely, we would change `lake print-paths` so that it no longer builds anything but merely produces a warning/error if the dependencies are out-of-date.  Editors would then offer to call `lake build` with the appropriate arguments if such a warning is detected.

  1. We extend the `LeanPaths` structure used for the `lake print-paths` output to indicate out-of-date dependencies:
```lean
structure NeedsRebuild where
  message : String
  command : String
  deriving ToJson, FromJson

structure LeanPaths where
  oleanPath       : SearchPath
  srcPath         : SearchPath
  loadDynlibPaths : Array FilePath := #[]
  needsRebuild?   : Option NeedsRebuild -- new field
  deriving ToJson, FromJson
```
  The `command` field contains a shell command which rebuilds the dependencies.  Having a shell command here gives us flexibility to change the Lake CLI in the future.
 2. When the file worker sees that the `needsRebuild?` field is some, it reports a diagnostic with an extra `"data": {"rebuildDepsCommand": ...}` field.
 3. When the vscode extension sees such a diagnostic, it shows a popup with a "rebuild dependencies" button (configurable of course).  This is so that new users don't mistakenly miss the error message.  Clicking that button pastes the command into the integrated terminal.

Alternatively/additionally we could also add editor commands to rebuild the dependencies.

**Comment by tydeu** [comment]
While I agree that it would be nice to be able to turn off auto-builds, I would not wish to remove the option entirely. For small (and some medium/large) projects, it is very convenient to not have to manually run a rebuild every time you change between files to get the imports up to date (though, admittedly, it is still currently sometimes necessary to do this via `Refresh File Dependencies`).

**Comment by gebner** [comment]
> it is very convenient to not have to manually run a rebuild every time you change between files to get the imports up to date (though, admittedly, it is still currently sometimes necessary to do this via `Refresh File Dependencies`).

There is no difference when *changing between files*.  With both the old and new behavior, you will need to run `Refresh File Dependencies`.  Only *opening files* has a different behavior.

Maybe this is also a question of workflow.  I usually have many files open (in different tabs), since closing/opening files is a pain when they take multiple seconds (or even minutes) to load.  So, I need to run `Refresh File Dependencies` either way.  And the auto-build just makes things unpredictable (depending on whether I already have a tab for the file or not).

**Comment by tydeu** [comment]
@gebner 

> Maybe this is also a question of workflow. I usually have many files open (in different tabs), since closing/opening files is a pain when they take multiple seconds (or even minutes) to load

Ah, yes. That is probably true. I tend to have very few tabs open as that clutters the tab bar and thereby makes navigation difficult. I also primarily use mouse-based navigation over keyboard shortcuts so the clutter is a particularly acute problem for me. All this translates to closing and reopening files a lot which, in turn, means I don't have to use `Refresh File Dependencies` as much.

**Comment by Kha** [comment]
I'm not opposed to this change, just some minor remarks/clarifications:
* > * You want to run `lake exe cache get` first.

  This could also be considered a technical limitation of `cache` not (yet?) being integrated into Lake
* > * Displaying the last line of the `lake print-paths` output in a diagnostic is terrible UI, and you'd rather see the `lake build` output in a terminal.

  For what it's worth, this is what it looks like in the editor I originally designed the current system for: 
![image](https://user-images.githubusercontent.com/109126/225859668-e60dd5fb-4515-40d6-be3e-02e57471876f.png)

* > The command field contains a shell command which rebuilds the dependencies. Having a shell command here gives us flexibility to change the Lake CLI in the future.

  I'm okay with that, but simply adding a `--rebuild` flag to `print-paths` seems just as appropriate to me. The rebuilding parts seems just as likely to be changed as the entire `print-paths` interface, in which case we have to adjust Lean anyway.

**Comment by gebner** [comment]
> For what it's worth, this is what it looks like in the editor I originally designed the current system for:

It looks the same in vscode or neovim, but only once it has *finished* building.  The ten minutes before while Lake is building, you only see the last line of the output.

> but simply adding a `--rebuild` flag to print-paths seems just as appropriate to me. 

That's hard to implement, since `lake print-paths` requires the module names (of the imports) while the editor only has the file name.  I'm also wary of using a command named `print-paths` primarily to build things.

> The rebuilding parts seems just as likely to be changed as the entire `print-paths` interface, in which case we have to adjust Lean anyway.

Changing Lean itself is not the issue.  But we'd also need to change the editors (and have backwards compatibility for at least a transitionary period).

But I'm warming up to the idea of hardcoding a Lake command in the editors instead of taking it from a diagnostic.  It just needs to be something with a minimal API that we can keep stable longer term, e.g. `lake build-deps-for File/Name.lean`.  This makes it straightforward to implement "refresh file dependencies" (i.e, rebuild and then restart), without needing to wait for the Lean server to start to get the shell command.

**Comment by tydeu** [comment]
@gebner 

> That's hard to implement, since `lake print-paths` requires the module names (of the imports) while the editor only has the file name.

Note that this should change in the future with the implementation of https://github.com/leanprover/lake/issues/147.

**Comment by tydeu** [comment]
My view on this RFC has changed somewhat. I have now experienced the pain of have the server automatically rebuild time-consuming dependencies when making do with what was already built would be fine. As such, I am now of the opinion that making automatic dependencies rebuilds optional or disabling them is a good idea.

**Comment by tydeu** [comment]
> It just needs to be something with a minimal API that we can keep stable longer term, e.g. `lake build-deps-for File/Name.lean`.

Lake now partially supports this via `lake build Foo.Bar:deps`. While this still requires convert the path to a module, once leanprover/lake#147 is addressed, this will be fully supported.

**Comment by Kha** [comment]
This is the most reasonable, minimal interface change I was able to come up with:
* When not opting into auto-build, the extension sends `didOpen` requests with a new parameter `"extraPrintPathsFlags": ["--no-build"]`
* The file worker calls `lake print-paths` with those extra flags
* Lake prints a sensible error when trying to build something under `--no-build`, advising users to use "Refresh File Dependencies" in their editor to force a build
* The extension leaves out `--no-build` in the `didOpen` request triggered by said command

Presenting the interaction in a nicer way is something we can implement later in each editor

**Comment by Kha** [comment]
Fixed by the above, UI possibly to be refined
