### ISSUE TITLE
`conv` cannot enter implication under a binder

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lean4#2156]
### Description

`conv` fails to enter the argument to an implication under a binder.

```lean
example : ∀ (n : Nat), True → True := by
  conv =>
    intro n
    /- 'apply implies_congr' unexpected result -/
    enter [1]
```

### Steps to Reproduce

**Expected behavior:** `enter [1]`/`enter [2]` successfully enters the first/second `True` argument, respectively.

**Actual behavior:** An error occurs.

**Reproduces how often:** 100%

### Versions

`4.0.0-nightly-2023-03-15`

**Comment by kmill** [comment]
Fixed in #5894
