### ISSUE TITLE
delaborating patterns containing `@`

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#220]
Repro: 
```lean
def f : List Nat → List Nat
  | a::xs@(b::bs) => xs
  | _             => []

#print f
/-
def f : List Nat → List Nat :=
fun (x : List Nat) =>
  match x with 
  | a :: b :: bs => xs  -- <<<<
  | x_1 => []
-/
```
Here is a possible plan for fixing this issue:
1- Add an auxiliary function `asPattern`
```lean
abbrev asPattern {α} (x y : α) : α := y
```
2- Modify `src/Meta/Match/Match.lean` to include the `asPattern` in the auxiliary matcher function. In the example, above the new type for `f.match_1` would be
```lean
f.match_1 : 
  (motive : List Nat → Sort u) →
  (x : List Nat) →
  ((a : Nat) → (xs : List Nat) → (b : Nat) → (bs : List Nat) → motive (a :: asPattern xs (b :: bs))) →
  ((x_1 : List Nat) → motive x_1) → motive x
```
3- Modify the `Delaborator` to convert `asPattern xs (b::bs)` into `xs@(b::bs)`

**Comment by Kha** [comment]
Sounds good to me!
