### ISSUE TITLE
An unification fail example

### ISSUE THREAD

**Issue by dannypsnl** [leanprover/lean4#2230]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The following program didn't type check

```lean
inductive Exp {α : Type} : Type → Type
  | var : α → Exp α
  | app : Exp α → Exp α → Exp α
  | lam : (Exp (Option α)) → Exp α
  deriving Repr

#eval Exp.lam (Exp.var (Option.some "a"))
```

NOTE: This maybe be filed, but hard to check from user side

### Steps to Reproduce

1. Copy above code into VSCode
2. Put cursor on `#eval` line

**Expected behavior:** [What you expect to happen]

1. `Exp.var (some "a")` has type `Exp (Option String)` is correct
2. `Exp.lam` should unify `α` with `String` and then expecting `Exp (Option String)`

**Actual behavior:** [What actually happens]

1. `Exp.var (some "a")` has type `Exp (Option String)` is correct
2. `Exp.lam` unify `α` with `Option String` and then expecting `Exp (Option (Option String))`

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

1. Version: leanprover/lean4:nightly-2023-05-18
2. OS: macOS 13.3.1
3. Chip: M2 Max

**Comment by Kha** [comment]
The implicit parameter of `Exp` is leading you astray, you want that type to have one parameter (more specifically, index) only.
```
inductive Exp : Type → Type _
  | var : α → Exp α
  | app : Exp α → Exp α → Exp α
  | lam : Exp (Option α) → Exp α

#check Exp.lam (Exp.var (Option.some "a"))
```
