### ISSUE TITLE
Discrimination trees don't see through beta-redex

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#2232]
```lean
class Foo (α : Type)
instance : Foo (Nat → Nat) where
example : Foo (Nat → Nat) := inferInstance -- works
example : Foo ((x : Nat) → (fun x : Int => Nat) (Int.ofNat x)) :=
  inferInstance -- should work too
```

As reported on Zulip: https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/calc.20and.20isBigO/near/360891924

In the Zulip issue, the beta-redex is introduced during unification, in the implicit argument of the `Trans` type class.

**Comment by urkud** [comment]
Am I right that another solution to the `calc` issue is to beta-reduce types before looking for `Trans` in `calc`?

**Comment by gebner** [comment]
That would be a bandaid fix for this particular calc issue, yes.  (Probably, didn't try it.)
