### ISSUE TITLE
Structural recursion failed when matching combined inputs

### ISSUE THREAD

**Issue by pingiun** [leanprover/lean4#2242]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I made a simple zip implementation and the compiler cannot see that it's structurally recursive.

### Steps to Reproduce

1. Write this function:
```lean
def zip {α β : Type} (xs : List α) (ys : List β) : List (α × β) :=
  match (xs, ys) with
  | ([], _) => []
  | (_, []) => []
  | (x :: xs', y :: ys') => (x, y) :: (zip xs' ys')
```
2. Compiler cannot figure out that this recursion is terminating
```
fail to show termination for
  zip
with errors
argument #3 was not used for structural recursion
  failed to eliminate recursive application
    zip xs' ys'

argument #4 was not used for structural recursion
  failed to eliminate recursive application
    zip xs' ys'

structural recursion cannot be used

failed to prove termination, use `termination_by` to specify a well-founded relation
```

**Expected behavior:**

I expect the compiler to see this trivially terminates

**Actual behavior:**

I need to give a proof of termination (don't know how to do that yet, just started with the book)

**Reproduces how often:**

Not sure, although this function is maybe the simplest case

### Versions

Lean (version 4.0.0-nightly-2023-05-22, commit 8d4dd2311ccf, Release)

On MacOS 13.3.1 (a) (22E772610a), with M1 chip

### Additional Information

I'm new to the language

**Comment by pingiun** [comment]
I'm having the same problem for my simple implementation of `take`:

```lean
def take {α : Type} (n : Nat) (xs : List α) : (List α) :=
  match (n, xs) with
  | (0, xs') => xs'
  | (_, []) => []
  | (Nat.succ k, x :: xs) => x :: take k xs
```

**Comment by digama0** [comment]
The tupling there is unnecessary and also breaks the equation compiler's reasoning because you aren't looking at subterms of the input anymore. Without the tuples it works:
```lean
def take {α : Type} (n : Nat) (xs : List α) : (List α) :=
  match n, xs with
  | 0, xs' => []
  | _, [] => []
  | Nat.succ k, x :: xs => x :: take k xs
```

**Comment by pingiun** [comment]
Ohhh I didn't know you could match on two items at once without tupling. It seemed to me that tupling would be the way to do that. I was just working through the exercises at https://leanprover.github.io/functional_programming_in_lean/getting-to-know/polymorphism.html

**Comment by pingiun** [comment]
Thanks for the quick answer. I'm not sure if this is still an issue, I guess a more advanced compiler could deduce termination even through wrapping with tuples and unwrapping. But the solution you've given me is good.

Maybe this could be clarified in the book, so learners like me can more easily write a natural solution?

**Comment by sullyj3** [comment]
It's worth noting that Simultaneous matching is introduced in the [following chapter](https://leanprover.github.io/functional_programming_in_lean/getting-to-know/conveniences.html#simultaneous-matching).
Possibly the intended solution was a nested `match`? But as a Haskeller, the tuple was my first instinct as well.
