### ISSUE TITLE
incorrect arity calculation for `Parser` parsers in `syntax`

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#2249]
```lean
import Lean

macro (name := fooParser) "foo" x:(ppSpace ident)* : term => 
  `([$(x.map (Lean.mkIdent ·.getId)),*])

namespace Lean.Parser.Term
macro (name := barParser) "bar" x:(ppSpace ident)* : term => 
  `([$(x.map (Lean.mkIdent ·.getId)),*])

variable (a : Nat)
#check foo a -- ok
#check bar a -- unknown identifier '[anonymous]'
```

The reason for the difference is that when `Lean.Parser.Term` is open, `ppSpace` refers to `Lean.Parser.Term.ppSpace` (the actual definition) rather than `ppSpace` (the parser alias), and the arity calculation for parsers is incorrect:

https://github.com/leanprover/lean4/blob/28538fc74889ea2dedbc30e236ce26492e5823ca/src/Lean/Elab/Syntax.lean#L200-L204

this assumes that all `Parser`s have arity 1, which is not true for `ppSpace` and several other parsers. The result is that an extra `group` node is inserted in one of these parsers:
```lean
#print fooParser
-- def fooParser : ParserDescr :=
-- ParserDescr.node `fooParser 1022
--   (ParserDescr.binary `andthen (ParserDescr.symbol "foo")
--     (ParserDescr.unary `many
--       (ParserDescr.binary `andthen (ParserDescr.const `ppSpace)
--         (ParserDescr.const `ident))))

#print barParser
-- def Lean.Parser.Term.barParser : ParserDescr :=
-- ParserDescr.node `Lean.Parser.Term.barParser 1022
--   (ParserDescr.binary `andthen (ParserDescr.symbol "bar")
--     (ParserDescr.unary `many
--       (ParserDescr.unary `group
--         (ParserDescr.binary `andthen (ParserDescr.parser `Lean.Parser.ppSpace)
--           (ParserDescr.parser `Lean.Parser.Term.ident)))))
```
 
My suggestion to fix this is to move the arity declaration from the alias to the `ParserInfo`.

cc: @Kha

**Comment by Kha** [comment]
Would it be reasonable to try aliases before declarations? I don't want to touch `Parser` or `ParserDescr` before (trying to) unify the two.

**Comment by digama0** [comment]
I think that would make sense, at least as long as e.g. fully qualified names or `_root_` can be used to select the `Parser`. (Currently there is no way to refer to the alias if the `Parser` is in scope.)
