### ISSUE TITLE
`termination_by` fails with dependent matching

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#2260]
The well-founded recursion module gives a surprising error with some dependent pattern matches:
```lean
def Option.attach (o : Option α) : Option { x : α // o = x } :=
  match o with
  | some x => some ⟨x, rfl⟩
  | none => none

def foo (xs : List α) : Option (List α) := do
  if h : xs.length < 10 then
    pure (xs.take 2)
  else
    have : sizeOf (xs.drop 5) < sizeOf xs := sorry
    let ⟨res, h⟩ ← .attach (foo (xs.drop 5))
    pure (res ++ res)
termination_by foo => xs

/-
type mismatch
  xs
has type
  List α : Type u_1
but is expected to have type
  ?β : Sort ?u.938
-/
```

Weirdly enough, it complains that the termination measure does not type check.  The crux is the `let ⟨res, h⟩ ← .attach (foo (xs.drop 5))` line; it works just fine with `let res ← .attach (foo (xs.drop 5))` or `let res ← foo (xs.drop 5)`.

**Comment by gebner** [comment]
It also works with `termination_by foo => sizeOf xs`.

**Comment by Vtec234** [comment]
The following well-founded recursion on an indexed inductive type fails in a similar way:
```lean
inductive DNat : Nat → Type
  | zero : DNat 0
  | succ : DNat n → DNat (n+1)

@[reducible]
def DNat.proj : DNat i → Nat := fun _ => i

def DNat.size₁ : DNat i → Nat
  | zero => 0
  | succ n => size₁ n
  termination_by size₁ n => n.proj -- works

def DNat.size₂ : DNat i → Nat
  | zero => 0
  | succ n => size₂ n
  termination_by size₂ n => sizeOf n -- works

def DNat.size₃ : DNat i → Nat
  | zero => 0
  | succ n => size₃ n
  /- type mismatch
    n
  has type
    DNat i : Type
  but is expected to have type
    ?β : Sort ?u.5000 -/
  termination_by size₃ n => n
```

**Comment by leodemoura** [comment]
@nomeata Any ideas?

**Comment by nomeata** [comment]
The termination argument’s type must not depend on the function parameters, as we need to run type inference to find a `WellFoundedRelation β` for it.

I wonder if we can detect this dependency at the suitable point and give an error message like

> The type of the termination argument,
>   DNat i
> depends on one or more of the function’s parameters.
> Hint: Try using `sizeOf`.

Trying that in #3414.

**Comment by nomeata** [comment]
BTW, the issue @gebner reported initially is a consequence of the combination of @Vtec234 ’s issue with #2102. If you change it to
```
def Option.attach (o : Option α) : Option { x : α // o = x } :=
  match o with
  | some x => some ⟨x, rfl⟩
  | none => none

def foo (xs : List α) : Option (List α) := do
  if h : xs.length < 10 then
    pure (xs.take 2)
  else
    let r := foo (xs.drop 5)
    have : sizeOf (xs.drop 5) < sizeOf xs := sorry
    let ⟨res, h⟩ ← .attach r
    pure (res ++ res)
termination_by xs
decreasing_by sorry
```
it works.

The problem is that due to #2102, the matcher abstracts over `foo`. This means that `α` is no longer a “fixed” parameter, and the termination argument may no longer depend on it.
