### ISSUE TITLE
How to run Lean code?

### ISSUE THREAD

**Issue by notooth1** [leanprover/lean4#228]
Hello,

I am new to Lean, and I have some questions:
- How can I compile Lean code and run it on Terminal?
- Is there a Lean forum that I can get support?

**Comment by jcommelin** [comment]
@notooth1 This repository is for Lean 4, which is under heavy development. So for now it's best to use Lean 3. You're welcome to come and chat with us over at: https://leanprover.zulipchat.com/
For the community supported version of Lean 3, see: https://leanprover-community.github.io/.
