### ISSUE TITLE
PANIC at Lean.MetavarContext.getLevelDepth

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2283]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

A panic in `Lean.MetavarContext.getLevelDepth`.

### Steps to Reproduce

```
-- This file produces:
-- PANIC at Lean.MetavarContext.getLevelDepth Lean.MetavarContext:839:14: unknown metavariable

-- from Mathlib.CategoryTheory.Category.Basic
class Category.{v, u} (obj : Type u) : Type max u (v + 1) where

-- from Mathlib.CategoryTheory.Functor.Basic
structure Functor' (C : Type u₁) [Category.{v₁} C] (D : Type u₂) [Category.{v₂} D] : Type max v₁ v₂ u₁ u₂ where

-- from Mathlib.CategoryTheory.Types
instance : Category (Type u) := sorry

-- from Mathlib.CategoryTheory.Limits.HasLimits
section

variable {J : Type u₁} [Category.{v₁} J] {C : Type u} [Category.{v} C]

class HasLimit (F : Functor' J C) : Prop where
class HasLimitsOfSize (C : Type u) [Category.{v} C] : Prop where
  has_limit : ∀ (J : Type u₁) [Category.{v₁} J] (F : Functor' J C), HasLimit F

instance {J : Type u₁} [Category.{v₁} J] [HasLimitsOfSize.{v₁, u₁} C] (F : Functor' J C) : HasLimit F :=
  sorry

def limit (F : Functor' J C) [HasLimit F] : C := sorry
def limit.π (F : Functor' J C) [HasLimit F] (j : J) : sorry := sorry

end

-- from Mathlib.CategoryTheory.Limits.Types
instance hasLimitsOfSize : HasLimitsOfSize.{v} (Type max v u) := sorry

theorem pi_lift_π_apply {C : Type v} [Category.{v} C] (f : Functor' C (Type max v u)) :
    (limit.π sorry sorry : (limit f) → sorry) sorry = sorry :=
  sorry
```

**Expected behavior:**

A typechecking error in the last declaration perhaps (from too many sorries), but no panic.

**Actual behavior:**

```
PANIC at Lean.MetavarContext.getLevelDepth Lean.MetavarContext:839:14: unknown metavariable
```

**Reproduces how often:**

Consistently.

### Versions

* Lean (version 4.0.0-nightly-2023-06-22, commit 32e93f1dc1b2, Release)
* Lean (version 4.0.0-nightly-2023-08-15, commit b5a736708f40, Release)

### Additional Information

Minimized from an appearance in the wild on [this branch](https://github.com/leanprover-community/mathlib4/tree/panic-for-investigation) ([build log](https://github.com/leanprover-community/mathlib4/actions/runs/5316281051/jobs/9625632465#step:7:28)), while trying to forward port https://github.com/leanprover-community/mathlib/pull/19153, needed for defining meromorphic functions on complex manifolds! This panic is not actually blocking progress on that goal!

In the original appearance the PANIC was actually
```
PANIC at Lean.isLevelMVarAssignable Lean.MetavarContext:393:14: unknown universe metavariable
```
but during minimization it changed to a different panic without me noticing... If we can fix this but the other persists I can minimize again.

**Comment by djvelleman** [comment]
I have experienced this problem as well.
