### ISSUE TITLE
`let_fun` elaboration

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#2289]
`let_fun x := v; e` is currently elaborated using `Expr.MData`.  It triggers a few problems: 

- Discrimination trees will beta-reduce them while retrieving candidate matches
- `simp` beta-reduces them. We can disable beta-reduction, but if we do it `simp` will also not reduce `(fun x => e) v`. 

Alternative design: add a `def lefFun (a : α) (f : α → β) := f a` and use it to elaborate the `let_fun` notation.

**Comment by Vtec234** [comment]
The old discussion on #1449 may also be relevant.

**Comment by leodemoura** [comment]
Implemented by https://github.com/leanprover/lean4/pull/2973
