### ISSUE TITLE
error of syntax in structure declaration

### ISSUE THREAD

**Issue by RemyCiterin** [leanprover/lean4#2308]
### Description
```lean
declare_syntax_cat foo
syntax " bar " term : foo

structure BarFoo where
  bar: Nat
```

### Steps to Reproduce

write the previous program into a `.lean` file, run `lean YOUR_FILE.lean`, is work also with other syntax categories than term, like foo, ident...

**Expected behavior**
no error

**Actual behavior**
an `expected command` error at line 5

### Versions

I use `leanprover/lean4:nightly-2023-06-28`

**Comment by digama0** [comment]
This is expected behavior. Using `bar` in syntax category `foo` makes it into a keyword, which means it is no longer legal to be used in identifier position unless you write it like `«bar»`.
