### ISSUE TITLE
Lake package name should not be specified by dependent

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#2324]
I noticed this issue while reimplementing the package resolution logic in Nix: currently, package names are specified both in the actual package as well as in any dependents
```lean
require std from git "https://github.com/leanprover/std4"
```
Not only is this redundant information (which I think has been discussed before), it is also brittle: if two packages disagree on the name of a dependency, we will end up with duplicate imports.

It is understandable why the current solution was easier to implement, but if the only missing ingredient is a directory move primitive, then let's add that.

**Comment by tydeu** [comment]
Yeah, the only thing required for this to work is a proper way to generate and rename the package directory.

**Comment by tydeu** [comment]
@Kha Upon further investigation, it appears I was wrong about this. While `IO.FS.rename` is sufficient to generate a package directory with a temporary name (e.g., a hash of the git url) and rename it to the proper one, that is not the only use case of the require name. 

Lake also uses the name to index the map of downloaded dependencies to verify if the package has already been downloaded to avoid downloading it again (e.g., if a multiple packages share the same dependency, we do not to download it twice). Without the name, Lake has nothing to uniquely identify the package to check in the map to determine whether Lake needs to downlead it (as we can only get the name after the download).

**Comment by tydeu** [comment]
@Kha Upgrading the warning to an error is certainly a change worth considering. I choose a warning because it will break any current packages and the name match is not technically required, though it is generally a mistake.
