### ISSUE TITLE
LLVM backend: implement the equivalent of `-fstack-clash-protection`

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#2373]

**Comment by bollu** [comment]
From [reading the patch set that upstreamed stack clash protection in Clang](https://reviews.llvm.org/D68720#change-qduUUvod0R72), it suffices to set `probe-stack=inline-asm`. This can be verified [via a godbolt example](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyahUAUgBMAIUtXyKxqiIEh1ZpgDC6egFc2TEAtydwAZAiZsADk/ACNsUhBZAAd0JWIXJi9ff0DyFLTnITCI6LY4hNkHbCcMkSIWUiIsvwCgqpqhOoaiYqjY%2BMT7esbmnLbhnvC%2BsoHpAEp7dB9SVE4uAHp1gGoAFQBPJOwtvaXSLYwcLaR47HItsi36dBZMLeMt7HV2JMYAOjMtABBcJELaCdAQEFbJh%2BOZbMwAdhsQK2qK2pGwRGWTGhfjMAGZkYDEQARLgLejcACs/ACXB05HQ3A8tlsWyUp1W8Is%2BL45CI2nJCwA1iAqTxfviqVoERYAGzSOU86QIgCcQUpXGk/DYUi0WnIdIZTK4/CUIANAvp5PIcFgKAwbCSDHilGojudjASqCMJgA%2BkRSD4mMLyDgAG4EVYANQI2AA7gB5Q50vl0ehEeLmiAxQXkGLhBp7bh8gusUh7RMxXTVK18x0cYSJpj0YvWsPYGI%2BYAeCT0c28fg4NjGYCSduEDE1cPYAcMz7VHyZkv8EHYTUM%2BgEGKkIteHB5wMEXWDhY0IzAJSxhPJ5gruTCMQSTgyB%2BKFQaPP6HiGUdoVnWIY27mpACzoEkhRMAOAC0IhbNB2BsMQ0H0PQ4ZsPBNBKPUqDCtBPosEoSDQUkpDoJmHRMPw6AzqQpAEDgIEQAs7SQW4TCeN4LQGKEUylOUBj5OkQijAEP5CZBvT8QMP6sbUEyiQYcmdBMUn9AkskKVxOSad0akzBpLGci%2BFLUrSeYmls6gABxytBCrnL6wBbBAgbBsKcIQPgxAPJYvJzPwVo6AsEAOugTouhQVAQB6kVoE5AZBiGHaRjGcZJim97ppmpDZrm7ZlkW96FRWVY1k494NswRDNq2eY4F2PZ9gOfLDqO44MpOtYEDOc78AuqBLmsfJrhu/Bbjue5YGsDJHiefBnheV7pbeqb8IIj7iJIr4be%2BaiaO2%2Bgan%2B5jWLYQExExYEQRkMFwQhSFEChaFsNRtH0Yx8Aseu3WuBA7iKT%2BvElOpgmpMJmTaWJeTg5JfGg7JP2UV0IxQ0pSOQSjkwgwZSladk0PYXp8O4zwRnLKsUimVwNKGhZ3BWbZ9nSI5o4uW5Iaed5JBnH5ZOBYKIUoIQNA0G6tDyE%2B22yLtyj7Xm9BIOaP6K0oIs0EQBycAaqufIGLDgWxprkKQSsGKbasEKLmuHBaJtK3ru6Gxk3A2pqtNGtR3AklbNBbNe8bxIzdkOQRJjs0lHlbOGSjB8zrPh65kcBfygsiok1m/Aq6oIlK%2BIInKVIWFotmGNw2rkLqPD6nT7YmmaBhBUKZdcBYOqJPikr4rZ1n59Z1k8BYPCqqqtfGq7qfWiFiChSA6vi7tUsvjL8hy5%2B7aqwYqvqzb2uGA76j687rjGxbuQWzvWt2xbjsGzdJ9u2ZY9e1wPui/76VBzZIcs2HzlJ%2B5OEMc46hychHQBAsp4LGuC8AYzEW4V11FSOUWc5Q8F5EqHgPBrIImsloH8ntGQT3NJaNOLd8TmTrhPJucwFi0TSK4aQQA%3D).  The attribute line changes as:

```diff
-attributes #0 = { mustprogress noinline nounwind optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
+attributes #0 = { mustprogress noinline nounwind optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "probe-stack"="inline-asm" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
```

The LLVM code to make this change is:

```cpp
const char *probeStack = "probe-stack";
const char *inlineAsm ="inline-asm";
LLVMAttributeRef stackClashProtect = LLVMCreateStringAttribute(probeStack , strlen(probeStack),
  inlineAsm, strlen(inlineAsm));
LLVMAddAttributeAtIndex(fn, LLVMAttributeFunctionIndex, stackClashProtect);
```
