### ISSUE TITLE
`lake build` doesn't report in which file an error occurs

### ISSUE THREAD

**Issue by robertylewis** [leanprover/lean4#2415]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I just tried to `lake build` a large project where one file has an import error:
```bash
$ lake build LoVe
error: no such file or directory (error code: 2)
  file: ./././LoVe/Love10_HoareLogic_DemoMaster.lean
```
It took me a few minutes to figure out what the problem was. (The file name is `LoVe10_`, oops, but spelled correctly in other places.) It would be super helpful if the output could report which file the error appears in. Based on where the error message comes from, and Sebastian's suggestion on Zulip, I think this is a `lean` issue and not a `lake` issue. But I'm not certain.

Zulip: https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/could.20lake.20report.20the.20file.20where.20a.20build.20error.20appears.3F

### Steps to Reproduce

1. Save a file `Project/A.lean` in a Lean project with an error in it, say, an import error, `import Project.B`
2. `lake build`

**Expected behavior:** [What you expect to happen]

I'd expect an error message along the lines of
```bash
error (Project/A.lean): no such file or directory (error code: 2)
  file: ./././Project/B.lean 
```

**Actual behavior:** [What actually happens]

There is no reference to the file `A.lean` where the error occurs:

```bash
error: no such file or directory (error code: 2)
  file: ./././Project/B.lean 
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by tydeu** [comment]
Thanks for the detailed report! leanprover/lake#25 also touches on this issue.
