### ISSUE TITLE
lake: flag to silence `lake_lock` warning

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2426]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I want to call `lake exe ...` from `parallel`, to run many jobs in parallel. This results in many
```
warning: waiting for prior `lake build` invocation to finish... (remove './build/lake.lock' if stuck)
```
as the tasks wait for each other (no actual building is taking place).

I'd like to be able to disable just the printing of this message, and it seems `lake --quiet` does not.

> Could these be silenced by `--quiet`, or alternatively provide another mechanism?

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Kha** [comment]
> no actual building is taking place

Ideally we shouldn't even lock the build directory then. But also, you should probably call the binary in `build/` directly in such a use case as otherwise you pay for lakefile elaboration in every single invocation.

**Comment by tydeu** [comment]
@semorrison, Sebastian is correct, if you are sure you are not building `lake exe` is not advisable as it introduces significant overhead (configuration elaboration, dependency hashing, and locking) for no reason.

**Comment by semorrison** [comment]
I will close shortly. @tydeu, do you think there's anything to track separately here about not acquiring a lock until later, to avoid locking in cases where no `build` files are actually being modified?

**Comment by tydeu** [comment]
@semorrison I think the feature request of this issue is fine and implementable (`--quiet` hiding the warning), so I would leave it open. Our point was that your use case should hopefully not care one way or the other. 

As to your question, given the way the Lake build system works, there is not a clean way to determine if something is to be built by a run, so I think the lock is a fine grain as it can be with the current setup.

**Comment by semorrison** [comment]
@tydeu, this is obsolete now, right?

**Comment by tydeu** [comment]
@semorrison I believe so, yes. I don't think we will be returning to the lock file anytime soon and if we do, it will probably undergo an overhaul, so it is unlikely that this issue will apply in the same way.
