### ISSUE TITLE
lake reports manifest out of date, even after lake update

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2427]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

`lake build` is reporting that the manifest is out of date, even after running `lake update`.

### Steps to Reproduce

Checkout a local copy of either https://github.com/leanprover-community/mathlib4/pull/6610 or https://github.com/JLimperg/aesop/pull/64, and observe that after a successful `lake update`, `lake build` still complains about the manifest being out of date.

Here's the link to the build showing the warning for Mathlib and for [Aesop](https://github.com/JLimperg/aesop/actions/runs/5876674899/job/15935304797?pr=64#step:5:5).

This is actually failing the bump PR for Aesop, because this warning is not expected during the testing run.

### Versions

New regression on nightly-2023-08-16

**Comment by tydeu** [comment]
@semorrison  I saw this earlier and fixed it as part of #2425.

**Comment by Kha** [comment]
> @semorrison I saw this earlier and fixed it as part of #2425 (the `rev` -> `inputRev?` change).

Is that covered by the single test in the PR?

**Comment by tydeu** [comment]
@Kha Sadly, no.
