### ISSUE TITLE
RFC: per-package server options

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#2455]
Currently, if you open std from mathlib, the server throws many errors, because it uses the server options from the mathlib package even though std was not built with those options. In CI everything works fine because it uses `moreLeanArgs` for the specified package, but `moreServerArgs` are set globally.

This has been discussed previously on zulip: [(1)](https://leanprover.zulipchat.com/#narrow/stream/348111-std4/topic/std.20doesn't.20work.20within.20mathlib.20any.20more/near/386560289) [(2)](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Lake.20server.20uses.20options.20from.20the.20wrong.20package/near/376826199)

My proposal to solve this works as follows:

* `lean --server` calls `lake get-pkg-args` on startup, which returns an augmented search path annotated with package names and a map from package names to extra lean options.
* When starting a new file worker, the server uses the options for the package containing the file.
* If the file cannot be found (e.g. it is outside the workspace) or `lake get-pkg-args` fails, it just uses the server options as is done currently.

An implementation is available at #2456.

**Comment by Kha** [comment]
Note that per-file server options would also cover this, in which case they could be part of the existing but decreasingly appropriately-named `print-paths` interface.

**Comment by digama0** [comment]
I thought of extending `print-paths` for this, but currently the interface is that you pass the list of *imports* to the current file to `lake print-paths`, which means it doesn't actually know what file you are actually building.

**Comment by Kha** [comment]
Oops, you are right!
