### ISSUE TITLE
If `lake` detects the manifest is out of date, it should suggest `lake update X` rather than `lake update`.

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2525]
Now that there is a `lake update X` command to just update one dependency, the automatic suggestion to run `lake update` should specify the relevant dependency.

This will lessen the frequency of users breaking their project by unintentionally updating other dependencies.

**Comment by tydeu** [comment]
Kyle also had [some suggestions on Zulip](https://leanprover.zulipchat.com/#narrow/stream/303200-sphere-eversion/topic/Lean.204.20port/near/388275882) for better manifest-related errors,
