### ISSUE TITLE
`lake` command that reports whether `lake build` will do any work

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2528]
I would like to be able to add a CI step for downstream projects, e.g. Mathlib, that verify that the cache has really worked, i.e. that after `lake exe cache pack && lake exe cache get`, `lake build` does no work.

But as far as I'm aware, there is not currently a mechanism to find out if there is any work to do.

**Comment by tydeu** [comment]
@semorrison While this feature may be a nice to have, I am not sure about the example case. In Mathlib,  a `lake build` *is* expected to do work after a `lake exe cache get` to build things that are not cached (e.g., the executables for `runLinter` and `checkYaml`). In the future, it may also need to build native libraries for features like `precompileModules` used in dependencies.

**Comment by semorrison** [comment]
In fact this is no longer true: we removed `defaultTarget` from both `runLinter` and `checkYaml`.

But even if that were still the case, I think the point remains that we don't have an effective way to verify programmatically that the cache is complete, and will be fully used.

**Comment by digama0** [comment]
Note that this is the reason why `lean-cache` duplicates so much of the logic of lake, it gives some hints regarding whether `lake build` needs to be run after or not and tries to reliably predict whether anything will happen.

**Comment by tydeu** [comment]
Looking through Lake issues, I realized that this appears to have been addressed by the addition of the `--no-build` option (in #2651). As such,, I am closing this issue.
