### ISSUE TITLE
`lake init Foo` (note initial capital) produces broken `lakefile.lean`

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2540]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

`lake init Foo` (note the initial capital) generates a `lakefile.file`

```
import Lake
open Lake DSL

package «Foo» {
  -- add package configuration options here
}

lean_lib «Foo» {
  -- add library configuration options here
}

@[default_target]
lean_exe «Foo» {
  root := `Main
}
```

which fails at `lean_exe` with `'Foo' has already been declared`.

Apparently `lake` is expecting that the user will know to type `lake init foo` instead. (I didn't.)

Hopefully this can be fixed quickly, either by `lake init` erroring if given a capitalised name, or automatically lower-casing it internally.

Silently producing an unusable `lakefile.lean` in 50% of new user interactions is not a good plan. :-)

### Versions

```
% elan --version
elan 3.0.0 (cdb40bff5 2023-09-08)
% lake --version
Lake version 5.0.0-ec94173 (Lean version 4.0.0)
% lean --version
Lean (version 4.0.0, commit ec941735c80d, Release)
```

**Comment by tydeu** [comment]
A longer discussion for a more principled solution has occurred [on Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/.60lake.20init.60.20broken.3F/near/390840593), but #2521 went with a simple lower-case-the-executable solution to make it in time for the next RC.
