### ISSUE TITLE
`lake new foo math` doesn't produce a `lake-manifest.json`

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2549]
```
% lake new foo math
% cd foo
% lake build
error: dependency 'mathlib' of 'foo' not in manifest, use `lake update` to update
```

One would hope that `lake new` produces a usable manifest!

**Comment by tydeu** [comment]
@semorrison Yeah, `lake new` does not produce any manifest. You need to run `lake update` after `lake new ...  math` (as the error suggests). Currently, Lake is conservative in its initialization. We give the user an opportunity to modify the generated setup before it elaborates the configuration and downloads dependencies.

**Comment by semorrison** [comment]
I think we need to change this behaviour.

**Comment by tydeu** [comment]
@semorrison Does the solution proposed in #2680 (automatically generating a manifest on the build) adequately resolve the problem present in this PR? It makes the example work, but produces the manifest on build rather than on new/init.

**Comment by semorrison** [comment]
Interesting. I guess this is okay. My remaining concern is:
* `lake new foo`
* `git add . & git commit -m "foo"`
* `lake build`
* "what's this new file doing?"

@PatrickMassot, what do you think?

**Comment by PatrickMassot** [comment]
I still think `lake new` should create a new project and `lake build` should build it. I don't understand how splitting the creation between `new` and `build` makes sense.

**Comment by PatrickMassot** [comment]
If lake-manifest.json is a build ouput, as suggested by your idea of having it created by `lake build` then why isn't it in the build folder (and not commited to git repos?).

**Comment by PatrickMassot** [comment]
Do you know any example of a create project script that would not generate the equivalent of this manifest in another language? I'm asking honestly since I don't know that many programming languages. I quickly double checked that creating a react or vue project using the recommended cli is creating package.json right away.

**Comment by tydeu** [comment]
@PatrickMassot 

> I quickly double checked that creating a react or vue project using the recommended cli is creating package.json right away.

To clarify, the `lake-manifest.json` is a parallel of a `package.lock`, not the `package.json` (which would be the parallel of the `lakefile.lean`). A `package.lock` is not created on a `npm init`, but only on a `npm install` / `npm update` / `npm add`, etc.

**Comment by joehendrix** [comment]
Should we close this issue now that #2680 is merged? 

To answer @PatrickMassot's question, Rust cargo works the same way as lake does with `Cargo.lock` (the analogue of `lake-manifest.json` created when the package is first built.

It might require an extra `git` command if people add to a git repo before first building, but that seems minor and I think one should at least attempt to build prior to commiting to git.

**Comment by semorrison** [comment]
Yes, let's close now.
