### ISSUE TITLE
Import error does not communicate file information

### ISSUE THREAD

**Issue by BoltonBailey** [leanprover/lean4#2569]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

Lean "no such file" error messages do not tell me which file tried to import the missing file.

### Context

This could make it hard for a user to quickly identify where the offending import is. It could also be particularly mystifying when moving files: If one import is corrected but not another, it becomes unclear what the source of the problem is.

See [here](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Lean.20not.20telling.20me.20which.20import.20has.20the.20import.20error)

### Steps to Reproduce

1. `lake new importbug`
2. `cd importbug`
3. In `Importbug/FileA.lean`, put the line `import Importbug.FileB`
4. In `Importbug/FileB.lean`, put the line `import Importbug.FileC`
5. Do not create a file named FileC

**Expected behavior:** [Clear and concise description of what you expect to happen]

I would like to get the error
```
`/Users/boltonbailey/.elan/toolchains/leanprover--lean4---nightly-2023-02-10/bin/lake print-paths Init Importbug.FileB` failed:

stderr:
./././Importbug/FileB.lean:1:1: error: no such file or directory (error code: 2)
  file: ./././Importbug/FileC.lean
```

**Actual behavior:** [Clear and concise description of what actually happens]

I get the error without the information about file and line number
```
`/Users/boltonbailey/.elan/toolchains/leanprover--lean4---nightly-2023-02-10/bin/lake print-paths Init Importbug.FileB` failed:

stderr:
error: no such file or directory (error code: 2)
  file: ./././Importbug/FileC.lean
```

### Versions

[Output of `lean --version` in the folder that the issue occured in]
Lean (version 4.0.0-nightly-2023-02-10, commit 75252d2b85df, Release)
[OS version]
MacOS 13.3.1 (a)

**Comment by tydeu** [comment]
https://github.com/leanprover/lean4/issues/2415 and https://github.com/leanprover/lake/issues/25 also touch on this issue.
