### ISSUE TITLE
Unhelpful error message for mutual blocks with structures

### ISSUE THREAD

**Issue by hargoniX** [leanprover/lean4#2587]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

When defining a mutual block with a structure the user just gets an "invalid mutual block" on the `mutual` keyword instead of anything helpful:
```
mutual

inductive A where
| into (b : B)

structure B where
  a : A

end
```

### Steps to Reproduce

**Expected behavior:** A useful error message explaining structures cannot be used here on the structure itself.

**Actual behavior:** Just an unhelpful generic error message on the `mutual` keyword.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by frangio** [comment]
I don't think the error message is a problem, I actually see a relatively clear error message:
> invalid mutual block: either all elements of the block must be inductive declarations, or they must all be definitions/theorems/abbrevs

However, I don't understand why this should not work. The Lean manual [says](https://lean-lang.org/lean4/doc/struct.html) that "Structure is a special case of inductive datatype." If so, shouldn't we be able to mix inductives and structures in a mutual block?

**Comment by nomeata** [comment]
The error message was only recently improved in https://github.com/leanprover/lean4/pull/2949 (probably closing this particular issue.)

I don't know about mixing structure and inductive, but agree that I'd have expected that to work.
