### ISSUE TITLE
RFC: please add commutativity theorems about addition and multiplication of `Int`s to the Prelude

### ISSUE THREAD

**Issue by gabriel-fallen** [leanprover/lean4#2600]
### Proposal

Basic facts about `Int`s in addition to `Nat`s would be very useful for a somewhat broad range of examples. 😃

You can find my attempt here: https://gist.github.com/gabriel-fallen/56188cd854292c1d5e939bffaf667d52

Feel free to use or adapt my code however you see fit (including but not limited to throwing it away altogether). 😸

**Comment by hargoniX** [comment]
You can get these facts from std4/mathlib4 already if you want to. Why specifically do you want them in core?

**Comment by gabriel-fallen** [comment]
@hargoniX for two main reasons:

1. to somewhat match `Nat`s that have a sizable number of basic facts available right in the core;
2. not to have to install the whole mathlib for simple demonstrations

I didn't know about std4 before this moment. It looks like the right solution, and I can wait until it becomes the Lean 4 standard library proper. 😸

I guess you can close this issue, sorry for the distraction. OTOH you might want to increase the visibility of std4 in the Lean 4 documentation. 😉

**Comment by semorrison** [comment]
Yes, Std is the correct solution here. The `lean4` repository, while large, aspires to be as small as possible to deliver the language itself.
