### ISSUE TITLE
`(kernel) declaration has free variables` error when extending class with typeclass parameter and extends

### ISSUE THREAD

**Issue by SabrinaJewson** [leanprover/lean4#2611]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

The following Lean 4 code produces an error:

```lean
class A
class B
class C [A] extends B
class D extends A, B, C
--                    ^ (kernel) declaration has free variables 'D.toC'
```

### Context

This came about when I was defining my own classes for abstract algebra, which heavily build on other classes and use `extend`s to minimize field repetition caused by inheritance diamonds.

### Steps to Reproduce

1. Write the code above into a Lean file
2. Attempt to compile it

**Expected behavior:** No error.

**Actual behavior:** The type checker gives the described error.

### Versions

Lean (version 4.3.0-nightly-2023-10-01, commit e6292bc0b890, Release) on Linux 6.3.13

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by digama0** [comment]
Note that this has never worked (`extends` classes cannot be dependent on each other)

**Comment by SabrinaJewson** [comment]
That’s surprising to me, because the following does work:

```lean
class A
class B [A]
class C extends A, B
```
