### ISSUE TITLE
Strange error message from simp_arith

### ISSUE THREAD

**Issue by david-christiansen** [leanprover/lean4#2615]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

When I create a Lean file with the following contents:

```
theorem huh (x : Int) : x + 1 = 1 + x := by simp_arith
``` 

then I get the following error:

```
application type mismatch
   List.cons (Int.add x 1)
 argument has type
   Int
 but function has type
   Nat → List Nat → List Nat
```

Everything works fine for this version:
```
theorem huh (x : Nat) : x + 1 = 1 + x := by simp_arith
```

### Context

This happened while looking for very easy examples of `simp` not making progress for FPIL.

### Steps to Reproduce

1. Put the code above in a file
2. Read the error message

**Expected behavior:**

Either an error message related to `simp_arith` not making progress, or a successful proof, or a new proof state.

**Actual behavior:**

A confusing error message

### Versions

```
Lean (version 4.2.0-rc1, commit a62d2fd49796, Release)
Linux localhost.localdomain 6.5.5-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Sep 24 15:52:44 UTC 2023 x86_64 GNU/Linux
```

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by leodemoura** [comment]
Don't have time to investigate, but here is a quick comment: `simp_arith` currently only supports `Nat`. It may be useful for someone investigating the issue.

**Comment by semorrison** [comment]
I'm not sure if this is related, but #2021 is another bug where `simp` produces a term that the kernel rejects with a type mismatch error.
