### ISSUE TITLE
RFC: add the option to add a prefix and a suffix to a doc-string when using `inherit_doc`

### ISSUE THREAD

**Issue by adomani** [leanprover/lean4#2622]
### Proposal

Currently, `@[inherit_doc foo] def bar ...` copies the doc-string of `foo` to `bar`.

The proposal is to add the option of extending the docs of `foo` by prefixing and suffixing extra strings.

Here is a sample usage

```lean
/-- `foo` is `1` -/
def foo : ℕ := 1

@[inherit_doc foo
  before "`fooPlusOne` looks like `foo`:"
  after "... except that it adds one to it."]
def fooPlusOne : ℕ := foo + 1

#check fooPlusOne
-- hover over `fooPlusOne` shows
/-
`fooPlusOne` looks like `foo`:

`foo` is 1

... except that it adds one to it.
-/
```

  - **User Experience**: This allows to copy over docs from "parent" declarations and highlight how children differ from their parents.

  - **Beneficiaries**: The proposal arose from discussions in `Mathlib`.  Relevant [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/tactic.20docstrings).

  - **Maintainability**: I have no expertise in answering this question, but my naive impression is that it would not require much maintenance.

### Community Feedback

The [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/tactic.20docstrings) mentioned above originated from the current doc-string for `rw`, which mentions `rewrite` but not what `rw` actually does.

With the current proposal, the docs for `rw` could be inherited from `rewrite`, preceded with the sentence that is currently the doc-string for `rw`.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by Kha** [comment]
Instead of extending `inherit_doc`, we expect a future Verso-powered version of docstrings to make it easier to compose them out of existing ones.
