### ISSUE TITLE
RFC: Allow trailing comma after the last element of a list

### ISSUE THREAD

**Issue by vleni** [leanprover/lean4#2635]
### Proposal

Currently this is not legal Lean:
```lean
let li = [
  item1,
  item2,
]
```
but if it were legal, adding new elements would not entail changes to existing lines:
```lean
let li = [
  item1,
  item2,
  item3,
  item4,
]
```
This has two main benefits:
1. Machine based code generation is simpler
2. The diff generated by version control is easier to read when new elements are added. This is especially relevant to unit testing.

Trailing comma is already supported in Rust and Python.

### Community Feedback

Ideas should be discussed on [the Lean Zulip](https://leanprover.zulipchat.com) prior to submitting a proposal. Summarize all prior discussions and link them here.

[Discussion thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Trailing.20comma.20for.20lists)

James Gllicchio proposed that we could also have preceding commas:
```lean
let li = [
  , item1
  , item2
]
```

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by leodemoura** [comment]
@Kha I think this is a good change, and I recall discussing it with you in the past. However, I don't remember why we didn't move forward. I don't have time to do it myself, but I will support a PR. BTW, let's ensure the trailing comma is accepted in other similar notation.

**Comment by vleni** [comment]
> @Kha I think this is a good change, and I recall discussing it with you in the past. However, I don't remember why we didn't move forward. I don't have time to do it myself, but I will support a PR. BTW, let's ensure the trailing comma is accepted in other similar notation.

What do you mean by accepted in other similar notation?

**Comment by semorrison** [comment]
e.g. if this is allowed, then `rw [x, y, ]` should be allowed as well.

**Comment by Kha** [comment]
> However, I don't remember why we didn't move forward.

I am quite sure it was lack of sufficient motivation. So I agree with

> I don't have time to do it myself, but I will support a PR.

**Comment by vleni** [comment]
> @Kha I think this is a good change, and I recall discussing it with you in the past. However, I don't remember why we didn't move forward. I don't have time to do it myself, but I will support a PR. BTW, let's ensure the trailing comma is accepted in other similar notation.

I have a PR here https://github.com/leanprover/lean4/pull/2643.

**Comment by leodemoura** [comment]
Closing this issue since PR #2643 has been merged.
