### ISSUE TITLE
RFC: lake update reorders the manifest

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2664]
### Proposal

The `lake update <package>` command reorders the manifest, because it leaves non-updated packages at the top. See discussion at https://github.com/leanprover-community/mathlib4/pull/7602#discussion_r1351972534.

Reordering makes reviewing these changes more difficult. Given that `lake update` is already a sharp knife that people are prone to cutting themselves with, it would be good to make reviewing changes made by `lake update` as simple as possible, in particularly by never reordering the manifest.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by nomeata** [comment]
Would a PR that normalizes the order (for example sorts by name in `addPackage` or `toJSON`) be welcome?

**Comment by eric-wieser** [comment]
@nomeata: please make one! The current behavior is very unfriendly to dealing with merges when bumping dependencies in mathlib.

**Comment by semorrison** [comment]
@nomeata, yes, please this would be extremely helpful. This regularly causes painful delays at mathlib. e.g. today it is probably going to end up delaying the release of `v4.3.0-rc1` because a PR needed to wait for me to resolve a merge conflict in `lake-manifest.json` overnight.

@tydeu, hopefully this is okay and if someone can patch this soon it will be able to be merged? Unfortunately we are too late already for `v4.3.0-rc1`.

**Comment by semorrison** [comment]
https://github.com/leanprover-community/mathlib4/pull/8010 and https://github.com/leanprover-community/mathlib4/pull/8008 are today's examples of unnecessary merge conflicts while updating Mathlib.

**Comment by semorrison** [comment]
A further problem is that `lake update` will modify `lake-manifest.json` solely to reorder it, without even touching the SHAs. E.g. try `lake update` on 5ce799c528c4a9c94cfb9a692f670fe950a82e97 of Mathlib.

This makes it hard to even determine programmatically if a `lake update` is doing anything: you have to parse `json`, not just check for a file diff!

**Comment by eric-wieser** [comment]
> A further problem is that `lake update` will modify `lake-manifest.json` solely to reorder it, without even touching the SHAs. E.g. try `lake update` on 5ce799c528c4a9c94cfb9a692f670fe950a82e97 of Mathlib.

To be clear, I assume you are happy with a future fixed version of `lake` auto-ordering the manifest when run for the first time?
