### ISSUE TITLE
Cannot Create Project using leanproject new name

### ISSUE THREAD

**Issue by Kariiem** [leanprover/lean4#267]
### Prerequisites

* [X ] 
### Description

[Description of the issue]
I found the following command at [https://leanprover-community.github.io/install/project.html],
I installed mathlib using
leanproject global-install

PS C:\Lean Workspace> leanproject new my_project
error: toolchain 'leanprover-lean4-stable' does not have the binary `C:\Users\my_user_name\.elan\toolchains\leanprover-lean4-stable\bin\leanpkg.bat`

PS C:\Lean Workspace> leanpkg new my_project
error: toolchain 'leanprover-lean4-stable' does not have the binary `C:\Users\my_user_name\.elan\toolchains\leanprover-lean4-stable\bin\leanpkg.bat`

Both commands fails.
### Versions

Lean (version 4.0.0-m1, commit 34cf4bc3ffc3, Release)

### Additional Information

PS C:\Lean Workspace> elan toolchain list
stable
leanprover-community-lean-3.24.0
leanprover-lean4-stable (default)

#####
I downloaded elan as windows binaries, I ran elan-init.exe executable file, it opens in powershell :

Welcome to Lean!

This will download and install Elan, a tool for managing different Lean
versions used in packages you create or download. It will also install a
default version of Lean and its package manager, leanpkg, for editing files not
belonging to any package.

It will add the leanpkg, lean, and elan commands to Elan's bin directory,
located at:

  C:\Users\myusername\.elan\bin

This path will then be added to your PATH environment variable by modifying the
HKEY_CURRENT_USER/Environment/PATH registry key.

You can uninstall at any time with elan self uninstall and these changes will
be reverted.

Current installation options:

     default toolchain: stable
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation

I chose (1), it installs leanprover-community-lean-3.24.0 by default, then executed (elan default leanprover/lean4:stable) command to install Lean4, following the steps in page 6 of the manual.

**Comment by bryangingechen** [comment]
`leanproject` does not support Lean 4 (yet). Note that `leanproject` is a [community](https://leanprover-community.github.io)-made tool, not written or supported by the Lean developers, so issues with it should be filed [here](https://github.com/leanprover-community/mathlib-tools) or on [Zulip](https://leanprover.zulipchat.com/).

**Comment by Kariiem** [comment]
Thanks for re-mentioning the issue to the lean community. Does elan support lean4?, and  how can I create a project using lean4.

**Comment by Kha** [comment]
The underlying issue *might* be solved with elan 0.10.3 (I didn't try). If not, please open a new issue in the elan repo.
