### ISSUE TITLE
`structure` sometimes makes a `Type` not a `Prop`.

### ISSUE THREAD

**Issue by kbuzzard** [leanprover/lean4#2690]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

Structures which should be `Prop`s (because all their fields are Props) sometimes come out as `Type`s and Lean needs to be explicitly told that they are `Prop`s. 

### Steps to Reproduce

```
structure foo (α : Type) where
  h : ∀ a : α, a = a

#check foo Nat -- Type?!

structure foo' (α : Type) : Prop where
  h : ∀ a : α, a = a

#check foo' Nat -- Prop, as expected
```

**Expected behavior:** 

`foo α : Prop`

**Actual behavior:** 

`foo α : Type`

### Versions

This bug has existed since Lean 3 and the community has been using the obvious workaround for years ("when you randomly notice an instance of this, typically because [a new user is confused on Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Object.20not.20being.20a.20structure/near/396760553), just tell the structure that it's a Prop explicitly")

[Output of `lean --version` in the folder that the issue occured in]

Lean (version 4.2.0-rc1, commit a62d2fd49796, Release)

[OS version]

Ubuntu 22.04

### Impact

Very minor, occasionally confusing, little more than annoying once you know about it.

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by arthur-adjedj** [comment]
Looking into the related [implementation](https://github.com/leanprover/lean4/blob/d15a0a4acb988954137eb902f0991b72d63e8d67/src/Lean/Elab/Inductive.lean#L422), this seems to be an intended design decision and not a bug. In particular, some classes such as `Decidable` and `IsNeutral` make use of the fact that the universe infered is `Type`. This issue probably deserves to be tagged as an RFC.

In any case

**Comment by digama0** [comment]
`Decidable` would not infer `Prop` type, and it's not a structure in the first place. `IsNeutral` can and should be a Prop.

**Comment by arthur-adjedj** [comment]
I first experimented with having the same rules apply to both inductives and inductives (it was also easier to do so since they shared the same bit of code), `IsNeutral` is composed with an `Option` [here](https://github.com/leanprover/lean4/blob/44416624904d389f6fb2cddf018594d34624b2bf/src/Init/Data/AC.lean#L19), hence the need to either have it in Type, or lift the universe it. I didn't experiment further down that path, but assumed some other issues would come up. 

> I don't see how you can read intentionality into that uncommented code.

That bit of code seems to have been made with the purpose of making things live in `Type` as a fallback. If it didn't, the code could simply be `Level.mkNaryMax us.toList |>.normalize` here, hence why I assumed it was a thought out decision.

**Comment by digama0** [comment]
Things *should* live in Type as a fallback. But the fallback doesn't need to be taken if there is <= 1 constructor and all the constructor arguments are Props or recursive, since then it would be a large eliminating type even if it lived in Prop.

**Comment by arthur-adjedj** [comment]
That was my reasoning as well, but that would change not only the type of structures, but also of a lot of inductives, so I'm hesitant on doing that.

**Comment by digama0** [comment]
> IsNeutral is composed with an Option [here](https://github.com/leanprover/lean4/blob/44416624904d389f6fb2cddf018594d34624b2bf/src/Init/Data/AC.lean#L19), hence the need to either have it in Type, or lift the universe it. I didn't experiment further down that path, but assumed some other issues would come up.

I'm inclined to lift the universe using `Nonempty` there. The impact is relatively minimal, but it is sufficiently unrelated to the PR that it might be worth doing separately.
