### ISSUE TITLE
`rw [h]` uses `h` from the environment in preference to `h` from the local context

### ISSUE THREAD

**Issue by joneugster** [leanprover/lean4#2729]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

`rw` seems to priorities other statements over variables in context. I would expect the reverse.

### Context

[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/rw.20bug.20priority.20of.20variables/near/397755221) and (non-minimised) [question in New Members stream](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/.E2.9C.94.20Lean.204.20web.20and.20VS/near/397755570)

### Steps to Reproduce

See the following MWE:

```lean
import Lean

open List

example (A B : Prop) (all : A ↔ B) (b : B) : A := by
  rw[all] -- error: failed to rewrite using equation theorems for 'List.all'
  assumption
```

**Expected behavior:** The above MWE should succeed.

**Actual behavior:** `rw` fails.

Note that all other tactics - `simp`, `apply`, `exact`, ... do correctly use the local `all` instead of `List.all`, so it seems to be a `rw`-specific issue.

Moreover, the same behaviour shows it `open List` is replaced with `def all := 3`.

### Versions

(lean4web)
4.2.0-rc3

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by semorrison** [comment]
Thanks. If anyone would like to identify the cause of this difference in behaviour that would be very helpful. I'd be happy to review a fix PR if there is an easy solution.

**Comment by thorimur** [comment]
@semorrison This is because rewrite (or more specifically `withRWRulesSeq` matches on each rule syntax and specifically processes identifiers differently (i.e. as global constants). This happens in `TacticM`, so we can probably just check if the id is an fvar before doing so! I can PR tomorrow. :)
