### ISSUE TITLE
`simp` hangs forever

### ISSUE THREAD

**Issue by yangky11** [leanprover/lean4#2739]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

The `simp` tactic hangs without triggering the maxHeartbeats.

### Steps to Reproduce

Here is a MWE:
```
import Mathlib.Algebra.BigOperators.Basic
import Mathlib.NumberTheory.Divisors

open BigOperators


example : (∑ k in Nat.divisors (30 ^ 4), 1) - 2 = 123 := by
  simp
  sorry
```

Copying it into https://live.lean-lang.org/ should trigger the error.

### Versions

I was using https://live.lean-lang.org/

**Comment by digama0** [comment]
This should be transferred to mathlib4 as it is almost certainly a simp set issue and not a simp issue.

**Comment by yangky11** [comment]
Thanks! I'm closing this issue and will open an issue in mathlib4.
