### ISSUE TITLE
Build archives not differentiated by architecture

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#2754]
I couldn't help but notice these curious-looking file paths in the mathlib4 build:
```
info: Downloading proofwidgets/v0.0.10/linux-64.tar.gz
```
The suffix is unexpected - while we do not officially support any non-64 bit platform, we have supported ARM64 since before the cloud builds existed! If we need a new primitive for `LEAN_INSTALL_SUFFIX` to properly encode that, we should do it.

**Comment by digama0** [comment]
Incidentally, `cache` has to deal with this issue, and it just calls `uname -m` to find out the architecture (on not-windows; for windows we just assume x86).
