### ISSUE TITLE
Cannot manually apply recursor: `(kernel) compiler failed to infer low level type`

### ISSUE THREAD

**Issue by pcpthm** [leanprover/lean4#276]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I tried to define `pempty` <https://github.com/leanprover-community/mathlib/blob/289df3a70e3fa2740895f5d02cc26f04dc9ae15e/src/logic/basic.lean#L117> (universe-polymorphic empty type) in Lean4.
The type can be defined but when I tries to define the elimination principle I get an obscure error:
`(kernel) compiler failed to infer low level type, unknown declaration 'PEmpty.rec'`.

```lean
universes u v

-- `Type u` version can be defined without this option, but I get the same error
set_option bootstrap.inductiveCheckResultingUniverse false in
inductive PEmpty : Sort u

-- `#check` works
set_option pp.all true in
#check fun {α : Sort v} => PEmpty.rec (fun _ => α)

-- but `def` doesn't work
-- error: (kernel) compiler failed to infer low level type, unknown declaration 'PEmpty.rec'
def PEmpty.elim {α : Sort v} := PEmpty.rec (fun _ => α)
```

### Versions

Current 4.0.0 `master` (`65c0c787ef`) locally built with Nix.

---

Edit: I know there are working alternative definitions, like:
```lean
inductive PEmpty : Sort u
| no : False → PEmpty

def PEmpty.elim {α : Sort v} : PEmpty → α
| no h => h.elim
```

**Comment by Kha** [comment]
See https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/.60induction.60.20tactic/near/222443171:
> The compiler currently doesn't have support for `C.rec` (`C.recOn` and `C.brecOn`). Reason: we didn't need this feature for implementing Lean, and code using `C.rec` is not efficient. We still haven't decided what to do here. Options:
1- Add support for `C.rec` in the compiler
2- Better error message for declarations that are not available in compiled code
BTW, you can use the `noncomputable` keyword to skip code generation and the error above.

In your example, you should use
```lean
def PEmpty.elim (a : PEmpty) : α := nomatch a
```
but I'll leave this issue open as a representative for the bad error message
