### ISSUE TITLE
Internal panic on bad notation

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean4#277]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Lean Internal Panic due to notation error.

### Steps to Reproduce

Here is a file with the bug:

```
infixl:67 " <<< "  => nonexistant

#eval (1 <<< 11 : UInt64)
```

**Expected behavior:** An error message

**Actual behavior:**
```
% lean  -o "ipanic.olean"  ipanic.lean 
INTERNAL PANIC: executed 'sorry'
```

### Versions

```
% lean --version
Lean (version 4.0.0, commit 711d1754a692, Release)
```

Ubuntu 20.04

**Comment by leodemoura** [comment]
@Kha @Vtec234 To solve this issue, we need the "panic handler" we discussed last week.

**Comment by Kha** [comment]
Oh yes, a panic thrown before the actual error can be reported is a great example. But also we probably shouldn't `eval` code that `hasSyntheticSorry` in the first place?

**Comment by pnwamk** [comment]
Is this likely the same issue, or should I file a new one?

```lean
structure Point where
  x : Int
  y : Int

def foo (inputs : List Point) : (Float × Float) :=
  (0.0, 0.0)

#eval foo ⟨0, 0⟩
-- ^ Produces `INTERNAL PANIC: executed 'sorry'`
-- but it should be raising some kind of type error
-- since `⟨0, 0⟩` is not a valid `List Point` obviously.
```

**Comment by leodemoura** [comment]
@pnwamk Yes, it is the same issue. I will fix it today.
