### ISSUE TITLE
C Compiler warning "trigraph ignored" during lake build

### ISSUE THREAD

**Issue by PratherConid** [leanprover/lean4#2829]
### Description

```
[1/6] Building Cwarning
stderr:
./build/ir/Cwarning/Basic.c:22:35: warning: trigraph ignored [-Wtrigraphs]
x_1 = lean_mk_string_from_bytes("(??)", 4);
```

### Steps to Reproduce

```
git clone https://github.com/PratherConid/lean-cwarning.git; cd lean-cwarning; lake build
```
Alternatively, run ``lake build`` on a repo containing the following definition:
```
def hello := "(??)"
```

### Versions

Lean (version 4.3.0-rc1, commit baa4b68a7192, Release)
Ubuntu 20.04.6 LTS (WSL)

**Comment by nomeata** [comment]
It doesn’t look like it needs lake to reproduce this:

```
/tmp/test $ LANG=C lean -c test.c test.lean  && LANG=C leanc test.c
test.c: In function '_init_l_main___closed__1':
test.c:23:35: warning: trigraph ??) ignored, use -trigraphs to enable [-Wtrigraphs]
   23 | x_1 = lean_mk_string_from_bytes("(??)", 4);
      |
At top level:
cc1: note: unrecognized command-line option '-Wno-unused-command-line-argument' may have been intended to silence earlier diagnostics
```

**Comment by Kha** [comment]
We can also stick it here statically, there's already another one: https://github.com/leanprover/lean4/blob/a2afdb62c5c95a8927ed32680df0096942432d5c/src/Leanc.lean#L56

**Comment by nomeata** [comment]
Do we have to worry about people using `leanc` with other C compilers? Or is that flag standard enough? I have no idea about these things.

**Comment by nomeata** [comment]
I suggest to fix it in `quoteString`. This avoids worrying about where to exactly insert the flag, and also benefits whoever processes the `.c` file outside of `leanc`.

* https://github.com/leanprover/lean4/pull/2833

**Comment by digama0** [comment]
Note that trigraphs are deprecated in C, and not supported in later versions of the standard at all. Given that this is only a warning, it seems like suppressing the warning is the simplest way to get the desired behavior.

**Comment by nomeata** [comment]
The issue is worth fixing; not sure if the fixes differ so much that it’s worth spending discussion bandwidth on them. I prefer simply avoiding digraphs (e.g. I expect more people to read command line flags as they debug stuff compared to people reading string literals in generated C codes, so adding noise to the latter seems less invasive than the former).

So I’ll go with #2833 unless someone feels so strongly about the issue to open another PR, which I’ll then happily and without ado approve :-)
