### ISSUE TITLE
Simp fails to see proof irrelevance

### ISSUE THREAD

**Issue by b-mehta** [leanprover/lean4#2835]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

A call to `simp` fails to close a goal, whereas the associated `rw` succeeds.

### Context

```
@[simp] theorem imp_self {a : Prop} : (a → a) ↔ True := ⟨fun _ => trivial, fun _ => id⟩

example {P : Prop} : P → P := by simp only [imp_self]

example {α : Prop} {P : α → Prop} {f : ∀ {a}, P a → α} {a : α} : (h : P a) → P (f h) := by
  simp only [imp_self]
```
Zulip discussion: https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Another.20kind.20of.20simp.20regression. The equivalent in Lean 3 succeeds. Thanks to @eric-wieser for minimising. This showed up in porting the exponential-ramsey project.

### Steps to Reproduce

Code as above.

**Expected behavior:** The simp call should succeed and close the goal.

**Actual behavior:** The simp call fails, with error `simp made no progress`.

### Versions

Lean (version 4.3.0-rc1, commit baa4b68a7192, Release)
MacOS

### Additional Information

None

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by leodemoura** [comment]
This is probably an issue in the discrimination tree module. It tries to index non dependent arrows, but then misses the possible rewrite on the dependent arrow in the goal.
