### ISSUE TITLE
Well-founded recursion: Lean could guess the lexicographic order

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#2837]
This definition
```
def test : ∀ i j : Nat, Nat
  | 0, _ => 1
  | _, 0 => 1
  | i + 1, j + 1 => test i (j + 1) + test (i + 1) j
```
needs
```
termination_by _ i j => (i, j)
```
or
```
termination_by _ i j => i + j
```
to go through. It didn’t need that in Lean3 (and our friendly competitors don't need that annotation either, I believe).

It would be nice if Lean4 would be up to that.

Previous discussion:

* https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Regression.20in.20equation.20compiler/near/400582161 by Bhavik Mehta

**Comment by b-mehta** [comment]
The original version in the Zulip thread showed up in porting the Exponential Ramsey project, in which I hit this when trying to define the Ramsey numbers! It also appears twice in mathlib, in Data/Nat/Choose/Basic: the definition of `multichoose` and the theorem `multichoose_eq` both gained a `termination_by` fix which weren't needed in Lean 3.

**Comment by hargoniX** [comment]
We could look into implementing what Isabelle did here: https://www21.in.tum.de/~krauss/papers/lexicographic-orders.pdf

**Comment by b-mehta** [comment]
That would be nice, but a simpler approach might just be to restore the old behaviour: build a PSigma of the arguments in the order they're given, and do lex on that.

**Comment by nomeata** [comment]
Probably doing one and later the other is best.
