### ISSUE TITLE
Signatures displayed by #check should not show daggered names

### ISSUE THREAD

**Issue by david-christiansen** [leanprover/lean4#2846]
### Description

[Some time ago](https://github.com/leanprover/lean4/pull/1943), `#check` and hovers were set to show signatures of functions rather  than their types. In other words, `#check String.get` shows `String.get (s : String) (p : String.Pos) : Char` rather than `String.get : String -> String.Pos -> Char`. This is generally a good idea - `String.replace (s pattern replacement : String) : String`is far more useful than `String.replace : String -> String -> String -> String`, after all.

But it falls down when arguments are not given explicit names in the signature. Then, internal daggered names are shown, eg:
```
#check String.append
String.append (a✝ : String) (a✝¹ : String) : String
``` 

This is confusing. While we should probably ensure that all functions in core and Std name their arguments, users will be writing anonymous names. Witness:
```
def length : List α → Nat
  | [] => 0
  | _ :: xs => length xs + 1

#check length
length.{u_1} {α : Type u_1} (a✝ : List α) : Nat
```

### Context

Real users have encountered this. We should fix it.

### Versions
At least `Lean (version 4.3.0, commit 734ce1ef2f62, Release)`.

### Potential solutions

Idris has [a pragma to associate name hints with types](https://idris2.readthedocs.io/en/latest/reference/pragmas.html#name). Then, when Idris needs to cook up a name for something (e.g. in a code action), it will devise a locally-unique name based on that hint. So we could write something like:
```
@[names xs, ys, zs]
inductive List ...
```
and then get output like
```
#check length
length.{u_1} {α : Type u_1} (xs : List α) : Nat
```
if the user hadn't already specified something. Likewise,
```
def doStuff : List a -> List a -> List a -> List a -> List a ...

#check doStuff
length.{u_1} {α : Type u_1} (xs ys zs xs' : List α) : Nat

def xs : List Nat := []
#check length
length.{u_1} {α : Type u_1} (ys : List α) : Nat
```

 ### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment]
We shouldn't invent accessible names as it would imply they work as named parameters. The simplest solution would be to switch to the unnamed after-colon syntax at the first inaccessible parameter.

**Comment by david-christiansen** [comment]
That's also a nice way to do it!

**Comment by nomeata** [comment]
This also affects loogle (or at least it could). With my loogle hat one, I’d very much welcome the ability to get the most beautiful and concise type rendering possible, without coding it up in lean.

**Comment by fpvandoorn** [comment]
Related: I would also like the `#check` output to not show the inaccessible names of type-class arguments. However, in this case we should *not* switch to the unnamed after-colon syntax, but just suppress the name. For example:
```lean
#check Array.sequenceMap
/-
Currently shows:
Array.sequenceMap.{u, v, w} {α : Type u} {β : Type v} {m : Type v → Type w} [inst✝ : Monad m] (as : Array α)
  (f : α → m β) : m (Array β)

Should show:
Array.sequenceMap.{u, v, w} {α : Type u} {β : Type v} {m : Type v → Type w} [Monad m] (as : Array α)
  (f : α → m β) : m (Array β)
-/
```

**Comment by kmill** [comment]
@fpvandoorn I went back in time again and implemented that in my PR :smile:

(It's good to have confirmation that this was a good idea!)
