### ISSUE TITLE
RFC: `termination_by?`

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#2857]
By default, when you write a recursive definition and Lean doesn’t recognize it as structurally recursive, it will attempt well-founded recursion and try to guess a termination argument for you, if you don’t specify it using `termination_by`. Right now it tries each argument; I am working to extend this to guessing arbitrary lexicographic orderings.

This guessing is potentially expensive, because it runs tactics on a variety of goals where it is not needed; an explicit `termination_by` annotation avoids that. Furthermore, even if it is fast, some users might prefer to be explicit in the termination argument.

To be consistent with existing idioms, I suggest that
```
termination_by?`
```
will tell the user which termination relation is used.

Ideally in a way that they can click on and automatically insert.

### Community Feedback

(None yet)

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by nomeata** [comment]
Open question: Can we actually support `Try This:`-style interaction in core? (I think the widget for that is in std).

If not, can we somehow make it so that with just core, the message is logged but inert, and once std is loaded, it becomes clickable?

**Comment by digama0** [comment]
There is precedent for this: `simp?` is actually implemented in core, there is a rudimentary frontend using `set_option tactic.simp.trace true` which causes `simp` to act like `simp?` and produce a fake "try this" output.

**Comment by nomeata** [comment]
What an oddly named option for this task, `simp.trace` sounds like a detailed debugging output.

Adding such an option to `termination_by` is clear. What I do not know: How will `std` be able to extend that behavior? Based on the `simp?` example, it would have to override the whole zoo of commands that contain a `termination_by` element, which seems tricky. (NB: `termination_by` isn’t a command of its own)

Or could core somehow call an initially undefined or trivial “hook” that could be set by std later?

**Comment by semorrison** [comment]
Can we just write
```
Widget.saveWidgetInfo ``terminationByWidget (.ofRange stxRange) (props := json% { ... })
```

in Lean, and only define the
```
@[widget] def terminationByWidget : Widget.UserWidgetDefinition where
```
in Std? I'm not sure what happens when the widget definition is missing. If it just fails silently that might be fine.

**Comment by nomeata** [comment]
I don’t know much about widgets yet… If that works, that would be great!

I’ll try it at some point and report back.

**Comment by leodemoura** [comment]
Closing this issue since PR implementing this feature has already been merged.
