### ISSUE TITLE
Go To Definition for Imports

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#287]

**Comment by leodemoura** [comment]
and "Go To Definition for notation/macros" :)

**Comment by larsk21** [comment]
> and "Go To Definition for notation/macros" :)

What is the current state of this? I have noticed that "go to definition" already works on notation/macros such as `<$>` or `#[]`, but not on, for example, `<|`.

**Comment by Kha** [comment]
> I have noticed that "go to definition" already works on notation/macros such as `<$>` or `#[]`, but not on, for example, `<|`.

Go-to for builtins should be covered by #937. `<|`, however, is an unfortunate special case: since it unfolds to syntax that is made up of "original" tokens only (more specifically, the first and last token are original), the editor instead jumps to `elabApp`.

**Comment by Kha** [comment]
The relevant check is at https://github.com/leanprover/lean4/blob/60a70372af3821867364b6dfc31c897ca0ea6566/src/Lean/Server/InfoUtils.lean#L131, so this affects other users of `hoverableInfoAt?` as well. A potential fix could be to choose the innermost info node *that is not contained in an info node of the same range*, but that is not immediately implementable using the current `smallestInfo?`.
