### ISSUE TITLE
RFC: Provide a `leanpkg` binary to help confused new users

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/lean4#2872]
### Proposal

A lean4 toolchain should come with a `leanpkg` binary that informs the user that they are confused.

It should fail with an error, and print some combination of:
* A reminder that the `leanpkg` is for Lean 3, and they are (and should be!) using Lean 4
* Instructions to use lake instead
* A link to up-to-date documentation online
* A request to report any documentation that still mentions `leanpkg` on Zulip.

### Community Feedback

This question comes up repeatedly on Zulip:

* [no leanpkg in lean4/stable?](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/no.20leanpkg.20in.20lean4.2Fstable.3F/near/401629152)
* [no leanpkg.exe](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/no.20leanpkg.2Eexe)
* [How to install leanpkg](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/How.20to.20install.20leanpkg/near/383666264)
* [error: toolchain 'leanprover/lean4:v4.3.0' does not have the binary leanpkg](https://leanprover.zulipchat.com/#narrow/stream/219941-Machine-Learning-for-Theorem-Proving/topic/Making.20more.20training.20data/near/405745181)

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by Kha** [comment]
AFAIK that hasn't come up again in a long time so can probably be closed?
