### ISSUE TITLE
nix build .#executable fails on macOS Big Sur during Setting UP Lean

### ISSUE THREAD

**Issue by b4be1** [leanprover/lean4#288]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I am following the Setting Up Lean tutorial https://leanprover.github.io/lean4/doc/setup.html#basic-commands. When I execute `nix build .#executable`, I get the following error message

> [nix-shell:~/mypkg]$ nix build .#executable
> error: --- Error ------------------------------------------------------------------------------- nix
> builder for '/nix/store/232i7ffhkah7ba1ifnap6psp28597z62-mypackage.drv' failed with exit code 1; last 7 log lines:
>   ld: warning: directory not found for option '-L/nix/store/49hmyr0bz1v1jz8xqcyybjcs9r1955j6-lean-bin-tools/bin/../lib/lean'
>   ld: warning: -sdk_version and -platform_version are not compatible, ignoring -sdk_version
>   Undefined symbols for architecture x86_64:
>     "_main", referenced from:
>        implicit entry/start for main executable
>   ld: symbol(s) not found for architecture x86_64
>   clang-10: error: linker command failed with exit code 1 (use -v to see invocation)

The directory `/nix/store/49hmyr0bz1v1jz8xqcyybjcs9r1955j6-lean-bin-tools/` only contains `bin`, ` include`, and `share`. It does not contain `lib` folder which `ld` is looking for.

### Steps to Reproduce

1. Follow all the steps in Nix Setup https://leanprover.github.io/lean4/doc/setup.html#nix-setup until `nix build .#executable`
2. Execute `nix build .#executable`

**Expected behavior:** Successful compilation

**Actual behavior:** Linking error

**Reproduces how often:** Always

### Versions

`lean --version` returns `bash: lean: command not found`
OS: macOS Big Sur 11.1

**Comment by Kha** [comment]
These are just example invocations as stated in the text, and the default template lacks a `main` definition to actually turn into an executable. Not sure we should add one to the template since most Lean packages will probably be libraries, not programs.

**Comment by b4be1** [comment]
Got it! Thanks for the quick reply, @Kha. I am only getting started with lean and nix and thought those were step-by-step instructions
