### ISSUE TITLE
Give advice when "supportInterpreter := true" is required.

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#2897]
Currently we need the line `supportInterpreter := true` for many `lean_exe` statements in `lakefile`s.

Here's the doc-string:
```
Enables the executable to interpret Lean files (e.g., via Lean.Elab.runFrontend) by exposing symbols within the executable to the Lean interpreter.

Implementation-wise, this passes -rdynamic to the linker when building on non-Windows systems. This increases the size of the binary on Linux, so this feature should only be enabled when necessary.

Defaults to false.
```

The error when you need this, but don't have it, is completely inscrutable. (TODO: provide the error.)

Unfortunately turning it on unnecessarily makes the binary larger. (e.g. 62mb vs 68mb for Mathlib's `cache`, or 50mb vs 56mb after `strip`.) (The fact that these numbers are at least 10x too high to begin with is a separate discussion.)

Can we have
* a new (read only?) option that specifies whether the binary was compiled with `supportInterpreter := true`
* `lake` would need to set this option
* Lean functions (`withImportModules`? What else?) that rely on this can check this option, and give a helpful error message (explaining what to add in the lakefile) if it is not set.

**Comment by semorrison** [comment]
Mentioning @tydeu and @digama0 as this was discussed during our meeting. (Thanks to @digama0 for the numbers above.)

**Comment by digama0** [comment]
Here's a MWE example which uses the lean APIs in an executable without `supportInterpreter := true`:

`Hello.lean`:
```lean
import Lean

def main : IO Unit := do
  Lean.initSearchPath (← Lean.findSysroot)
  let (env, ok) ← Lean.Elab.runFrontend "def foo := 1" {} "Foo.lean" `Foo
  println! "ok: {ok}, {env.constants.size} constants"
```

`lakefile.lean`:
```lean
import Lake
open Lake DSL
package hello
@[default_target] lean_exe Hello
```

build result:
```
$ lake exe Hello
info: [0/2] Building Hello
info: [1/2] Compiling Hello
info: [2/2] Linking Hello
Foo.lean:1:0: error: could not find native implementation of external declaration 'UInt64.ofNatCore' (symbols 'l_UInt64_ofNatCore___boxed' or 'l_UInt64_ofNatCore')
Foo.lean:1:11: error: unknown constant 'OfNat'
Foo.lean:1:11: error: unknown constant 'sorryAx'
ok: false, 0 constants
```

**Comment by digama0** [comment]
Another option that came up in our meeting is to fix things so that this does not error and instead just uses the interpreted version of these external declarations. (It is unclear whether this is possible.)

**Comment by digama0** [comment]
> Not all externals have IR.

For the ones which don't, why can't we mark them such that the symbols are always included?
