### ISSUE TITLE
Non-direct class parents should not be `instance`s

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/lean4#2905]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

Consider the following typeclass hierarchy:
<table>
<tr>
<td>

```lean
import Lean

class A
class B
class C extends A
class D extends A, B
class E extends C, D
```
</td>

<td>

```mermaid
graph TD
   C --> A;
   D --> A;
   D --> B;
   E --> C;
   E -.-> D;
```
(dotted lines represent non-preferred parents, using the term from [arXiv:2306.00617](https://arxiv.org/abs/2306.00617)
</td>
</tr>
</table>

Lean generates the following instances:

```mermaid
graph TD
   C --> A;
   D --> A;
   D --> B;
   E --> C;
   E --> D;
   E --> B;
linkStyle 5 stroke:red
```

<details>
<summary>As measured with</summary>

```lean
-- expected:
#eval show Lean.Meta.MetaM Unit from
  do guard <| (←Lean.Meta.getInstancePriority? `E.toC) = some 1000
#eval show Lean.Meta.MetaM Unit from
  do guard <| (←Lean.Meta.getInstancePriority? `E.toD) = some 1000
#eval show Lean.Meta.MetaM Unit from
  do guard <| (←Lean.Meta.getInstancePriority? `E.toA) = none

-- unexpected:
#eval show Lean.Meta.MetaM Unit from
  do guard <| (←Lean.Meta.getInstancePriority? `E.toB) = some 1000
```

</details>

where I consider the red `E.toB` edge to be a bug. This means that typeclass search includes unnecessary lookups:
<table>
<tr><th>Actual behavior</th><th>Expected behavior</th></tr>
<tr>
<td>

```lean
/-
[Meta.synthInstance] ❌ B ▼
  [] new goal B ▶
  [] ✅ apply @E.toB to B ▶  -- this is unecessary
  [] ✅ apply @D.toB to B ▶
  [] ✅ apply @E.toD to D ▶
-/
set_option trace.Meta.synthInstance true in
#synth B
```
</td>

<td>

```lean
/-
[Meta.synthInstance] ❌ B ▼
  [] new goal B ▶
  [] ✅ apply @D.toB to B ▶
  [] ✅ apply @E.toD to D ▶
-/
set_option trace.Meta.synthInstance true in
#synth B
```

</td>
</tr>
</table>

### Context

Disabling these shortcut instance gave a sizable performance boost to many files in https://github.com/leanprover-community/mathlib4/pull/6403.
The Mathlib code would be much cleaner if they were never generated in the first place.

### Steps to Reproduce

1. Run the code above

### Versions

4.3.0-rc2

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by negiizhao** [comment]
More context: [Zulip](https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/.237883.20rings.20vs.20orders/near/398499922) [Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/redundant.20instances.20when.20extending.20overlapping.20classes)
