### ISSUE TITLE
`rw [decl]` fails with optParams

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#2939]
`rw` does not know how to apply equation lemmas for a declaration when optParams are not set to their default values:
```lean
def foo (x := 0) : Nat := x
example : foo x = x := by simp only [foo] -- ok
example : foo x = x := by rw [foo]
-- failed to rewrite using equation theorems for 'foo'
```
`rw [@foo]` does not work either (it behaves the same, presumably because the `@` needs to be applied not to `foo` but to the equation lemma).

**Comment by kmill** [comment]
#2243 might be related

**Comment by leodemoura** [comment]
Fixed.
