### ISSUE TITLE
Semantic highlighting randomly stops working

### ISSUE THREAD

**Issue by mhuisi** [leanprover/lean4#2977]
### Description

For some users, semantic highlighting sometimes randomly stops working. This is not [#1219](https://github.com/leanprover/lean4/pull/1219) because it can be resolved by restarting the file.

### Context

Report: https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Random.20highlighting.20failure/near/402773450

### Steps to Reproduce

No reproduction steps unfortunately.

**Expected behavior:** Semantic highlighting keeps working while working on the file and when it doesn't work (e.g. because that part of the file hasn't been elaborated yet), it's clear to the user why that is

**Actual behavior:** It stops working randomly

### Versions

Lean v4.2.0

### Additional Information

Sebastian mentioned that we may not be sending a refresh tokens request often enough.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by digama0** [comment]
While playing with this issue, @PatrickMassot and I managed to get this reproduction:

* Open any project (tested on std4), with two files A and B where B depends on A.
* Navigate to A.lean
* Modify the file inessentially, save
* Restart the server
* Navigate to B.lean, get a popup "imports are out of date"
* Select "Restart file" from the popup
* After B.lean is finished compiling, semantic highlighting will fail
  * Re-running "Restart file" will not fix it
  * Running "Restart server" will fix it
  * Typing anywhere in B.lean will fix it

**Comment by mhuisi** [comment]
It looks like this particular reproduction was already fixed by #3619.

**Comment by mhuisi** [comment]
> It looks like this particular reproduction was already fixed by #3619.
> 
> Edit: However, even with #3619, there seems to be a related issue where opening a small file like `B.lean` causes semantic highlighting to fail until another file is selected and the original file is selected again. Looks like VS Code ignores most of our `workspace/semanticTokens/refresh` requests, so this will definitely require some additional work to fix. It's very unfortunate that VS Code still doesn't support partial result reporting :(

I found the issue for this; it's due to a VS Code bug that occurs because we change the language ID of files for Lean 3 compatibility reasons. I had a detailed write-up but unfortunately my computer crashed and I can't be bothered to rewrite it. The best fix is probably to rip out the horrible compatibility layer and replace it with a very visible warning when people try to run the Lean 3 extension together with the Lean 4 one.

**Comment by PatrickMassot** [comment]
I very much vote in favor of removing the compatibility layer if it makes anything nicer for Lean 4. Fixing this semantic highlighting issue is crucial for my teaching because my tactics are very hard to use without them. In the Lean 3 days I was forced to use a custom VSCode extension for teaching emulating semantic highlighting with horrible hacks.

**Comment by mhuisi** [comment]
Ok, I removed the compatibility layer and tested that semantic highlighting works as expected in a couple of examples. Please let me know if you still encounter issues with it starting at v4.8.0-rc1.

**Comment by mhuisi** [comment]
Closing as I haven't heard any reports of semantic highlighting still being unfixably broken. Please let me know if this is still an issue for you.

I'm still not entirely happy with the current state of affairs (semantic tokens now do not persist long enough for unelaborated parts of the file) but that's for another time.
