### ISSUE TITLE
Document highlight should include identifiers just before cursor

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#3023]
When placing the cursor at the end of an identifier, we do not send out document highlights, which causes VS Code to serve its own, dumb highlights instead.

![image](https://github.com/leanprover/lean4/assets/109126/e3026cc2-3bd2-4f0a-bc21-05fbb68133bd)

```
[Trace - 9:25:36 AM] Received response 'textDocument/documentHighlight - (579)' in 1ms.
Result: []
```

**Comment by david-christiansen** [comment]
I mean, _I_ generally wouldn't expect the thing before the cursor to be highlighted

**Comment by david-christiansen** [comment]
While it does make sense to work around limitations in popular tools, this doesn't actually seem wrong to me. I'm also surprised when the thing that the cursor _isn't_ pointing at lights up, though much less so than when random stuff spelled the same lights up!

Can/should we fix it on the VS Code side?

**Comment by david-christiansen** [comment]
(for clarity: when I say "the thing it isn't pointing at", its because the cursor is on the space after `x` in your screenshot, not on `x`)

**Comment by mhuisi** [comment]
We should match what VS Code does here on the language server side.
