### ISSUE TITLE
unstructured `induction` tactic is unusable?

### ISSUE THREAD

**Issue by vvs-** [leanprover/lean4#312]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

In this example:
```lean
theorem zeroAdd : 0 + x = x := by
  induction x
  rfl
  rw Nat.addSucc
  admit
```

**Expected behavior:**

Lean 3 generated accessible names there, but I suppose this is considered bad practice in Lean 4. But there also was a syntax to assign user names. It seems that the only way to solve this right now is a structured `induction`. I suppose this is because of a missing feature?

**Actual behavior:**

induction hypothesis and variable are inaccessible and there is no syntax to assign their names (aside from the structured version, that is).

### Versions

Lean (version 4.0.0, commit 3bc5b89ac365, Release)

### Additional Information

I've also seen this in `injection`.

BTW, in Emacs client this inaccessible notation now erases the cross and looks just like ordinary variable using the same font (lsp-mode bug?). This looks confusing.

**Comment by leodemoura** [comment]
In the unstructured version, one is supposed to finish the proof without referring to inaccessible variable names. Example:
```lean
theorem zeroAdd : 0 + x = x := by
  induction x
  rfl
  rw Nat.addSucc
  apply congrArg 
  assumption
```
The example above is too convoluted, but it becomes more realistic when one is using more complex tactics. Example: `induction <;> blast` where `blast` is some user-defined tactic that implements a bunch of "tricks".

One may still use the Lean3 approach
```lean
set_option hygienicIntro false in
theorem zeroAdd' : 0 + x = x := by
  induction x
  rfl
  rw Nat.addSucc
  rw v_0
```

One may also use the following approach where the "structure version" is used only for naming variables.
```lean
theorem zeroAdd'' : 0 + x = x := by
  induction x with | succ _ ih => _ | _ => _
  rfl
  rw Nat.addSucc
  rw ih
```
One can even add a nicer macro on top of it to hide the `=> _`s

**Comment by vvs-** [comment]
Ok, thanks for explaining!

I suppose that this issue is just about missing docs then. I'm closing this.
