### ISSUE TITLE
The documentation of `Float` doesn't say if it's 32 or 64 bit

### ISSUE THREAD

**Issue by girving** [leanprover/lean4#3142]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

[The documentation for `Float`](https://leanprover-community.github.io/mathlib4_docs/Init/Data/Float.html) doesn't say whether it corresponds to a 32-bit or 64-bit `float` or `double` in C.

### Context

I'm doing some numerics, and for some pieces that aren't verified I'm using `Float`.  It should be easy to know which float type I'm using.

### Versions

N/A, since the bug is in the current website https://leanprover-community.github.io/mathlib4_docs/Init/Data/Float.html.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by hargoniX** [comment]
The answer to your question is 64 bit and technically speaking there is documentation here: https://leanprover.github.io/lean4/doc/dev/ffi.html#translating-types-from-lean-to-c but I agree that it should be more visible at the type itself.

**Comment by semorrison** [comment]
@girving, would you like to make a PR adding a doc-string? Just saying that it is represented internally as a `double` would suffice.

**Comment by girving** [comment]
Will do.
