### ISSUE TITLE
First example in documentation doesn't work in Firefox

### ISSUE THREAD

**Issue by David263** [leanprover/lean4#315]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The Lean introductory documentation appears to be https://leanprover.github.io/introduction_to_lean/. At the beginning is a button labeled "Try it yourself". It doesn't seem to work for me in Windows/Firefox, latest stable versions. It appears to work in Windows/Chrome.

### Steps to Reproduce

1. Open the above page in Firefox.
2. Click the button.

**Expected behavior:** [What you expect to happen]

Expected to see "hello world".

**Actual behavior:** [What actually happens]

Got error messages:

1:0:error: file '/library/init/wf.lean' not found
1:0:error: invalid import: init
could not resolve import: init
1:0:info: "hello world!" : string
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
Done(0.008sec)
-- Done(0.014sec)

**Reproduces how often:** [What percentage of the time does it reproduce?]

5 times out of 5.

### Versions

(Unknown)

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

(Attempt to do this failed.)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jcommelin** [comment]
Dear @David263, the documentation you mention is not for Lean4. This repository is for Lean4, which is a very recently released version of Lean, and there is not yet much in terms of documentation/tutorials for Lean 4.
Could you please report this issue at https://github.com/leanprover-community/lean.
