### ISSUE TITLE
RFC: Specify in Lake that a Lean module depends on a custom target

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lean4#3153]
### Proposal

As the Lean ecosystem grows, there will be increasingly more projects integrating Lean projects
with code written in other languages.

My own example is that of ProofWidgets4 which makes use of string literals containing JavaScript code built by an NPM-based toolchain, for instance [here](https://github.com/leanprover-community/ProofWidgets4/blob/d43963047f7c54a6e977239a4a7f9884a4add226/ProofWidgets/Component/HtmlDisplay.lean#L15). However, the feature request is not specific to ProofWidgets4.

I would like to have a way of informing Lake that such a Lean module depends on the the JavaScript source file it includes, and thus transitively on the TypeScript sources from which the JS is built.

In particular, on restarting the file worker via "Refresh file dependencies", if the TS has changed than the JS should be transparently rebuilt so that when Lean elaboration restarts, it can automatically pick up the new JS. As far as I was able to determine, at the moment there is no mechanism in Lake for registering such a dependency.

A potential syntax could be something like `depends_on_target blah` at the top of the Lean file, in the import block, or even an extension of the `import` syntax. Alternatively, if the language team does not want to add new syntax there, one could perhaps register such a dependency in the `lakefile`. However, the latter option feels a bit like spooky-action-at-a-distance, i.e., non-local effects that would not be obvious to newcomers to a codebase.

- **User Experience**: It allows transparent rebuilds of modules that depend on custom build targets, for instance to integrate code built by other toolchains.

- **Beneficiaries**: [ProofWidgets4](https://github.com/leanprover-community/ProofWidgets4), potentially other projects using custom targets.

- **Maintainability**: It is hard for me to say. The feature may add complexity to the build system, or it may necessitate a refactor that simplifies something.

### Community Feedback

The feature came up in discussion [here](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/nightly-testing).

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by tydeu** [comment]
@Vtec234 This appears to be a duplicate of #2762. However, this one does have more preface and that one is old but does have a longer discussion. Thus, I am not sure which should cover the other.

**Comment by Vtec234** [comment]
Oops! Apologies for my poor memory. Let's leave the original one; this will still show up in the list of referring issues there.
