### ISSUE TITLE
RFC: Add List.empty

### ISSUE THREAD

**Issue by alok** [leanprover/lean4#3163]
### Proposal

Clear and detailed description of the proposal. Consider the following questions:

  - **User Experience**: How does this feature improve the user experience?

This is meant to improve UI because theres `Array.empty` and it seems like it can easily become a wider idiom. It plays well with dots so expressions like `xss.foldl .append .empty` read easier than `xss.foldl (. ++ .) []` because they're in actual words.

### Community Feedback

Ideas should be discussed on [the Lean Zulip](https://leanprover.zulipchat.com) prior to submitting a proposal. Summarize all prior discussions and link them here.

### Impact

Small. I put in an RFC because that's what GitHub directed me to. Happy to add implementation

```
@[inherit_doc List.nil]
def List.empty : List α := []
```

`inherit_doc` didn't seem to do anything, so heres a docstring too: `The empty list.`

**Comment by digama0** [comment]
> It plays well with dots so expressions like `xss.foldl .append .empty` read easier than `xss.foldl (. ++ .) []` because they're in actual words.

You can use `xss.foldl .append .nil` there if you want

**Comment by alok** [comment]
Idea is just to conform to array.empty.

**Comment by semorrison** [comment]
`.nil` is not going away, and I think this is just adding a synonym, making life more complicated by providing multiple ways to talk about the same thing, without adding any expressivity.
