### ISSUE TITLE
RFC: induction with “fixed targets”

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#3170]
## Context and status quo

Consider a function like `merge` (as known from mergesort):
```
universe u
def merge {α : Type u} (r : α → α → Prop) [DecidableRel r] : List α × List α → List α
  | ([], l') => l'
  | (l, []) => l
  | (a :: l, b :: l') => if r a b then a :: merge r (l, b :: l') else b :: merge r (a :: l, l')
  termination_by merge l => l.1.length + l.2.length
```
When proving things about this, I might be inclined to define a custom induction principle, like the following, which will directly focus on the four cases and give me suitable induction hypotheses:
```
theorem merge.induct {α : Type u} (r : α → α → Prop) [DecidableRel r] (motive : List α × List α → Prop)
  (case1 : ∀ (l' : List α), motive ([], l'))
  (case2 : ∀ (l : List α), ¬ (l = []) → motive (l, []))
  (case3 : ∀ (a : α) (l : List α) (b : α) (l' : List α), r a b → motive (l, b :: l') → motive (a :: l, b :: l'))
  (case4 : ∀ (a : α) (l : List α) (b : α) (l' : List α), ¬r a b → motive (a :: l, l') → motive (a :: l, b :: l'))
  (x : List α × List α) : motive x := sorry
```
But if I try to use it like this
```
theorem perm_length (l) : length (merge r l) = length l.1 + length l.2 := by
  induction l using merge.induct
```
I get 6 goals, including two unwanted ones for `r` and `DecidbableRel r`.

This is expected, as the current `induction` applies (roughly) the following rules about how to treat the induction principle’s parameters:

* The motive is identified by its use in the result type, and is instantiated from the goal state.
* The major premises (or “targets”) are the parameters to the motive in the result type (here: `x`)
* Instance parameters are instantiated as MVars and filled using type class resolution.
* Other implicit arguments are instantiated as MVars.
* Other explicit arguments are considered `alts`, and turned into cases.

The code for this characterization is in [`getElimInfo`](https://github.com/leanprover/lean4/blob/b614ff1d12bc38f39077f9ce9f2d48b42c003ad0/src/Lean/Meta/Tactic/ElimInfo.lean#L25-L58) and the actual instantiation, given the “targets“, [happens in `mkElimApp`](https://github.com/leanprover/lean4/blob/b614ff1d12bc38f39077f9ce9f2d48b42c003ad0/src/Lean/Elab/Tactic/Induction.lean#L130-L168).

This explains why `r` is treated as an alt here.

## Issues

This is, however, not a great user experience. One can continue the proof with
```
  case r x y => exact r x y
```
but to the user `r` really isn’t a “case” of the induction, and much more like the target `l`. In this case, both originate from parameters or `merge`, and it is not clear why they should be treated differently.

Furthermore, in this care `r` really should be instantiated explicitly, so that the `[DecidableRel r]` can be solved, and so that the real goals are free of uninstantiated `?r` terms that could confuse users and tactics alike.

## Proposed solution

The common origin of the fixed paraeter `r` and the major premise `x` suggests that a good UX would be to treat them the same, and allow (and require) the user to write
```
theorem perm_length (l) : length (merge r l) = length l.1 + length l.2 := by
  induction r, l using merge.induct
```

Consequences:

* The list of expressions passed to `induction` here now consists of “fixed targets” and (regular) “targets”.
* `getElemInfo` has to recognize them. I propose these rules:
  * `targets` remain those that are arguments to the motive in the result type.
  * `alts` are those explicit parameters of the eliminator that mention the `motive`.
  * `fixedTargets` are all other explicit parameters.
* The `induction` tactic passes the `fixedTargets` to the induction principle, but (crucially) does not generalize them (in [`evalInduction`](https://github.com/leanprover/lean4/blob/b614ff1d12bc38f39077f9ce9f2d48b42c003ad0/src/Lean/Elab/Tactic/Induction.lean#L548)).

## Open questions

Will these rules treat something a `fixedTarget` that should be considered an `alt`? Maybe some side-condition on the major premise? For example, in the lemma (which as of today is _not_ suitable to be used with `induction`)
```
Nat.decreasingInduction.{u_1} {m n : ℕ} {P : ℕ → Sort u_1} (h : (n : ℕ) → P (n + 1) → P n) (mn : m ≤ n) (hP : P n) : P m
```
the `mn` would be a `fixedTarget`. Is that desirable?

## Alternative

An alternative would be to allow arbitrary terms after `using`, so that the user can write
```
theorem perm_length (l) : length (merge r l) = length l.1 + length l.2 := by
  induction l using merge.induct (r := r)
```
This is closer to how Isabelle solves this problem. I have been going back and forth between the two, and they both have their pros and cons. This variant is more powerful (you can instantiate implicit parameters, or even instantiate some alts), while the one above might be a bit simpler and more intuitive in the common case.

### Community Feedback

I [tossed these ideas around on zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/induction.20using.20with.20a.20parametrized.20eliminator/near/411962502) first.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by jcommelin** [comment]
Fwiw, my gut feeling (based on reading this RFC, without playing with code) is that I find the `using (r := r)` a bit *more* intuitive than `induction r, l`. Because we're not inducting on `r` and actually want to keep it fixed.

**Comment by nomeata** [comment]
Yeah, it’s a tough call.

For experts, i.e. those that can read the induction principle, or maybe even wrote it, and know roughly what induction does, `(r := r)` is certainly quite natural.

But if you put yourself in the shoes of someone who just wrote `merge`, and now want to use the (eventually) autogenerated `merge.induct`, understanding why `r` goes there and `l` goes here may pose a sizeable hurdle.

Happy to hear more points-of-view and arguments either way.

Maybe I should do the `using <term>` generalization first, as it doesn’t hurt and is useful as the more general one, and leave the other change to when and if we have evidence that the general syntax is too arcane?

**Comment by joehendrix** [comment]
Have you considered a separate tactic for induction schemes generated from recursive function definitions?

What you are doing reminds me a lot of coverset induction and how ACL2 generates induction schemes.  The syntax could be something like `coverset (merge r l)` and it would generate an induction scheme using the definition of `merge` and fill in the parameters with `r` and `l` to get the four cases.

Joe

**Comment by nomeata** [comment]
No I haven't! That's an interesting alternative as well, I'll mull it over.

Does it also unfold `merge` for you, if the goal mentions it?
