### ISSUE TITLE
RFC: termination_by failure message could special-case completely unchanged parameters

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#3172]
The message
```
guessLexFailures.lean:27:0-33:31: error: Could not find a decreasing measure.
The arguments relate at each recursive call as follows:
(<, ≤, =: relation proved, ? all proofs failed, _: no proof attempted)
           x1 x2 x3
1) 29:6-25  =  =  =
2) 30:6-23  =  ?  <
3) 31:6-23  <  _  _
Please use `termination_by` to specify a decreasing measure.
```
shows that the first argument has all arguments equal; this will never work.

The code could in this case print a shorter warning, maybe anchored at that recursive calls, instead of printing the full matrix.

This was suggested by @digama0  and someone else before (sorry, forgot who).

(I’m not sure how often that happens in practice, but it doesn't hurt either.)

**Comment by digama0** [comment]
An example that happens in practice is when you call the function completely unapplied or pass it as a higher order argument to something else, e.g.

https://github.com/leanprover/lean4/blob/b614ff1d12bc38f39077f9ce9f2d48b42c003ad0/src/Lean/MetavarContext.lean#L1304-L1313 

https://github.com/leanprover/lean4/blob/b614ff1d12bc38f39077f9ce9f2d48b42c003ad0/src/Lean/Elab/BuiltinNotation.lean#L205-L210

**Comment by nomeata** [comment]
Ah, in these cases, where _all_ calls are of that form, I think the current code considers all parameters as the “fixes prefix” and bails out early with a suitable error message, doesn't it?
