### ISSUE TITLE
[question] How to get the arguments and output of the external process run by the lean program?

### ISSUE THREAD

**Issue by yurivict** [leanprover/lean4#3190]
While attempting to build proofwidgets in the VM I am getting this error:
> error: process 'npm' exited with code 243

npm fails for some unknown reason.

Is there a way to log arguments and output of the external process like this?

If there is no easy way - IMO there should be a way to get this information.

**Comment by digama0** [comment]
This is a proofwidgets bug, not a lean bug. The lean API for spawning tasks allows you to either pipe the results directly through, or capture the output and do what you like with it, so if proofwidgets is not doing that then you should report it there.
