### ISSUE TITLE
LLVM vs C backend performance

### ISSUE THREAD

**Issue by hargoniX** [leanprover/lean4#3192]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

Currently the LLVM backend generates IR that has worse performance than the C backend after optimization. It appears that this issue can be deduced to a failure of inlining Lean runtime
functions for manipulating `lean_object`s.

### Steps to Reproduce

1. Compile Lean with the C and the LLVM backend enabled
2. Inspect the IR of the const_fold.lean bench test generated by LLVM vs generated by C before and after `-O3`
4. Some lean.h functions will be inlined in the C variant but not in the LLVM variant

**Expected behavior:** The same functions should be inlined

**Actual behavior:** They are not

### Impact
As long as this is not fixed the LLVM backend will most likely not be able to be competetive with the C one in terms of performance.

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment]
@hargoniX In #3225 it sounds like this specific issue is likely resolved, yes?

**Comment by hargoniX** [comment]
Yes, in general the performance diff between the LLVM and C backend is very miniscule but still measurable. We investigated the IR for a while and didn't really see any obvious differences in the logic it's implementing so the remaining diff is most likely due to different basic blocks, binary layouts etc.
