### ISSUE TITLE
RFC: Move `ac_rfl` tactic to Std

### ISSUE THREAD

**Issue by fgdorais** [leanprover/lean4#3198]
### Proposal

The `ac_rfl` tactic is not used at all within Lean itself. I propose to move it to Std so it could be improved to a more useful tactic.

Users would not be affected much since the tactic would still be available in Std. There are no maintainability issues for Lean but there is an additional burden for Std to repurpose the tactic. The main beneficiaries would be Std developers who are working on the use of AC lemmas for non-arithmetic operations and folds, for example.

### Community Feedback

This came up in a discussion on [std4#535](https://github.com/leanprover/std4/pull/535). It was proposed there to make small adjustments to some classes in Lean. Since these classes are only used by `ac_rfl` I floated the idea of moving the tactic to Std since these classes and `ac_rfl` aren't used anywhere in Lean itself. This was confirmed by an experiment removing `ac_rfl` on a fork of Lean: https://github.com/fgdorais/lean4/tree/ac_rfl

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by semorrison** [comment]
An update: the classes (`Commutative`, etc) themselves will stay in Lean, updated in #3195. Otherwise, my understanding is that we are happy to move `ac_rfl` out to Std.

**Comment by fgdorais** [comment]
Sounds good to me. I will submit a PR once #3195 gets merged.

**Comment by leodemoura** [comment]
Thanks for the creating the issue. We decide to consolidate Std and related tactics in this repository.
Thus, I am closing this issue.
