### ISSUE TITLE
LSP diagnostics missing an error that appears when executing lean

### ISSUE THREAD

**Issue by Julian** [leanprover/lean4#323]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Putting:

```lean
let foo := 12 do println! foo
```

 in a file produces an error when running `lean` on the file:

```
⊙  lean4 --version; lean4 <(printf 'let foo := 12 do println! foo')                                                                                                               julian@Airm ●
Lean (version 4.0.0-nightly-2021-02-28, commit 6a6f68f6ccc8, Release)
/dev/fd/11:1:29: error: expected term
```

but does not produce any error from the LSP when editing the file.

The same seems to happen for putting `constant A` in a file (and nothing else).

### Versions

macOS Big Sur, lean4 version 2021-02-28

**Comment by leodemoura** [comment]
I tried your example on VS Code and Emacs, and they both report the error. It appears as a red squiggly at the end of the file.
![image](https://user-images.githubusercontent.com/2778936/110244886-b43efe00-7f15-11eb-8f45-eba4c86f73ec.png)

![image](https://user-images.githubusercontent.com/2778936/110245027-6ecf0080-7f16-11eb-9a3a-9db36585e283.png)

**Comment by Julian** [comment]
Yes, I see the same now (though trying this again on 03-06) -- not sure what I did wrong previously, but apologies for the noise.
