### ISSUE TITLE
“failed to unify” message should not print identical types

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#3232]
Sometimes Lean says

```
tactic 'apply' failed, failed to unify
  some type
and
  some type
```

and `some type` is visually identical in both cases.

Of course advanced users will be forgiving such silliness, as they know about implicit arguments and things, and can use `set_option pp.explicit true`. But it is still quite silly for Lean to even say something like this.

Is there a reason it couldn’t compare the delaborated `Syntax` for equality, and if it is equal, elaborate again with `pp.explicit := true` (and if that’s still equal maybe with `pp.raw := true`), printing

```
tactic 'apply' failed, failed to unify
  @some 1 type
and
  @some 2 type
(shown here with pp.explicit := true to reveal differences)
```

### Context

* https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/rage/near/418885474

### Steps to Reproduce

(TODO)

### Versions

Certainly around 0.4.5

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by BoltonBailey** [comment]
This is not the first time this issue has happened, see [here](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Syntactically-equal.20forms.20don't.20unify.20-.20how.20to.20disambiguate.3F/near/407831378), and [here](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/.E2.9C.94.20apply.20failed.20to.20unify.20eq_div_iff_mul_eq'), and a similar issue [here](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Why.20failing.20to.20unify.3F)

**Comment by Kha** [comment]
It looks like we're not using `addPPExplicitToExposeDiff ` in tactics yet, we should

**Comment by nomeata** [comment]
Oh, there functionality is even there already! That’s great :-)

**Comment by nomeata** [comment]
That made it easy to heroically PR a fix minutes shortly after people complained on zulip :-)

**Comment by BoltonBailey** [comment]
[Here](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Can't.20unify.20seemingly.20identical.20terms/near/429161425) is another person confused by this kind of issue (looks like `exact` rather than `apply`)
