### ISSUE TITLE
Allow `` in patterns

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#327]
The following doesn't work

```lean
def f (x : Expr) : Bool :=
  match x with
  | Expr.const ``Nat .. => true  -- Doesn't work
  | _ => false
```

We have to use `` `Nat `` as a workaround, but we don't get any compilation time checks.

**Comment by Kha** [comment]
Possibly related to #184, in that if we extend `MacroM` with `Lean`-specific data (e.g. hidden behind a `PNonScalar`), it might become possible to implement double-quoted names as a macro?
