### ISSUE TITLE
Incorrect doc for simproc

### ISSUE THREAD

**Issue by lecopivo** [leanprover/lean4#3272]
The [doc string ](https://github.com/leanprover/lean4/blob/760e824b9ff333a9ec18ff1805055f2f812f8375/src/Init/Simproc.lean#L14)for `simproc` has an example that has an incorrect type. The simproc command expects the type `Expr → SimpM Simp.Step` but the example code has type `Expr → SimpM (Option Simp.Step)`. 

Is to code supposed to look like this?
```
simproc reduce_add (_ + _) := fun e => do
  unless (e.isAppOfArity ``HAdd.hAdd 6) do return .visit { expr := e }
  let some n ← getNatValue? (e.getArg! 4) | return .visit { expr := e }
  let some m ← getNatValue? (e.getArg! 5) | return .visit { expr := e }
  return .done { expr := mkNatLit (n+m) }
```
Honestly, I prefer the version with `Option` when you just return `none`.

Tested on: leanprover/lean4:v4.6.0-rc1

**Comment by eric-wieser** [comment]
I think this example might be more illustrative with a `proof? := some sorry` field too

**Comment by leodemoura** [comment]
Closed by https://github.com/leanprover/lean4/pull/3800
