### ISSUE TITLE
Lean (kernel) invalid return type for constructors whenever an inductive parameter contains an implicit argument

### ISSUE THREAD

**Issue by JasonGross** [leanprover/lean4#329]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

```lean
inductive foo (F : {n : Nat} → Type) : Type where
| bar : foo _
```
gives
```
1:1: (kernel) invalid return type for 'foo.bar'
```
Moving the parameter out of the inductive itself fixes the error; the following works:
```lean
variable (F : {n : Nat} → Type)
inductive foo : Type → Type where
| bar : foo (@F 0)
```
Removing the implicit status also fixes the error:
```lean
inductive foo (F : (n : Nat) → Type) : Type where
| bar : foo _
```

### Steps to Reproduce

Run lean on the above code

**Expected behavior:** successful compilation

**Actual behavior:** an error: 1:1: (kernel) invalid return type for 'foo.bar'

**Reproduces how often:** Always

### Versions

```
$ lean --version
Lean (version 4.0.0-m2, commit 26dda3f63d88, Release)
$ uname -a
Linux JasonGross-X1 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
running on WSL2 in Windows 10

**Comment by leodemoura** [comment]
I will take a look. Here is a temporary workaround
```lean
inductive foo (F : {n : Nat} → Type) : Type where
| bar : foo @F
```
