### ISSUE TITLE
Support for opening namespaces and setting options in terms

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#330]
https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/local.20open.20.2F.20let.20open

**Comment by JasonGross** [comment]
The use-case that had me asking about this was, roughly,
```lean
inductive InductiveWithAVeryLongName where
| c1 | c2 | c3 | c4 | c5 | c6 | c7

def foo : InductiveWithAVeryLongName → Type
  | InductiveWithAVeryLongName.c1 => _
  | InductiveWithAVeryLongName.c2 => _
  | InductiveWithAVeryLongName.c3 => _
  | InductiveWithAVeryLongName.c4 => _
  | InductiveWithAVeryLongName.c5 => _
  | InductiveWithAVeryLongName.c6 => _
  | InductiveWithAVeryLongName.c7 => _
```
where I didn't want the names to pollute future terms after the match was done.

**Comment by Kha** [comment]
Something else that would help in this specific case we had discussed before is inferring the type part of a constructor name from the expected type, e.g. `_.c1`. Swift has this feature as `.c1`, which might not work quite as well in Lean.
