### ISSUE TITLE
Adding type information results in Lean being unable to infer obvious binder types

### ISSUE THREAD

**Issue by JasonGross** [leanprover/lean4#331]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

```lean
structure Foo where
  foo : Nat

def baz {x : _} := Foo.mk x -- works fine
def qux {x : _} : Foo := Foo.mk x -- 5:14: failed to infer binder type
```

### Versions

```
$ lean --version
Lean (version 4.0.0-m2, commit 26dda3f63d88, Release)
$ uname -a
Linux JasonGross-X1 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
running on WSL2 in Windows 10

**Comment by leodemoura** [comment]
This is actually a feature in Lean 4 :)
When the resulting type is provided, the holes in the header must be resolved before we elaborate the definition body.
Lean 3 had this behavior for theorems only, and some users were confused when the behavior changed when they replaced `theorem` with `def`.
I tried to address this issue by providing additional information in the error message. We now produce:
```
error: failed to infer binder type
when the resulting type of a declaration is explicitly provided, all holes (e.g., `_`) in the header are resolved before the declaration body is processed
```
cc @Kha

**Comment by JasonGross** [comment]
Thanks for the explanation and improvement!
