### ISSUE TITLE
invalid reference to undefined universe level parameter with `inductiveCheckResultingUniverse false`

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/lean4#3310]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

When using `bootstrap.inductiveCheckResultingUniverse false`, there is a kernel error when building a structure

### Context

[Related Zulip message](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Why.20is.20PProd.20never.20in.20Prop.3F/near/420972284)

### Steps to Reproduce

1. Run
   ```lean
   set_option bootstrap.inductiveCheckResultingUniverse false in
   structure Wrap.{u} (α : Sort u) : Sort u where
     val : α
   ```

**Expected behavior:** No diagnostics

**Actual behavior:**
```
(kernel) invalid reference to undefined universe level parameter 'u'
```
Surprisingly, `#check Wrap` works fine; so the error is coming from generation of some auxiliary declaration.

### Versions

4.6.0-rc1

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment]
`bootstrap` comes without warranty :)
