### ISSUE TITLE
RFC: Lake automatically put `/.lake/` into `.gitignore`

### ISSUE THREAD

**Issue by madvorak** [leanprover/lean4#3345]
### Proposal

Could `lake init` and `lake new` automatically put `/.lake/` into `.gitignore` please?

  - **User Experience**: It will save a tiny bit of time after creating a new Lean project.

  - **Beneficiaries**: Everybody who uses Lean with Git will probably benefit.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by semorrison** [comment]
It does already, and has for a while!
