### ISSUE TITLE
build cycle error from Lake do not include a path (i.e. not clickable action in VSCode)

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#3349]
When Lake reports a build cycle, we get a message like 
```
% lake build            
error: build cycle detected:
  +Std.Lean.Meta.BoolExpr:lean.precompileImports
  +Std:lean.precompileImports
  +Std.Lean.Meta.BoolExpr:deps
  +Std.Lean.Meta.BoolExpr:leanArts
  std/Std:leanLib.leanArts
  +Std.Lean.Meta.BoolExpr:lean.precompileImports
```
There is no path displayed here, so we don't get a clickable link in VSCode allowing us to take action!

My preference would be an additional line at the end.

**Comment by tydeu** [comment]
Oh, I didn't notice this earlier, but this should also fixed by #4115.
