### ISSUE TITLE
Respect lakefiles in subdirectories of the open directory in VSCode.

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#3355]
It is common to have a project which has `lakefile`s in subdirectories. Currently, one has to open a VSCode window separately for each such subdirectory.

Ideally, when opening a file in such a subdirectory, VSCode would have a separate server which uses the relevant lakefile.

**Comment by semorrison** [comment]
Again, this has been discussed before, but I wasn't able to find an issue. Links to existing discussing welcome!

**Comment by Vtec234** [comment]
https://github.com/leanprover/vscode-lean4/issues/138 :)
