### ISSUE TITLE
Lake creates a hard-to-delete file in src/lake/tests/

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#3358]
I sometimes end up (usually after cancelling a `make test`) with a file like:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        "src/lake/tests/init/\302\253A-B\302\273-\302\253C-D\302\273/"
```
Because of the terrible file name, it is quite hard to delete, and I seem to resort to `git clean -xfd`.

Could lake be more robust about cleaning up, or, simpler, just add this to a .gitignore?

**Comment by tydeu** [comment]
@semorrison The directory created by that test is part of the [.gitignore](https://github.com/leanprover/lean4/blob/master/src/lake/tests/init/.gitignore). It is not clear to me why Git is not ignoring it on your system. A change to produce better directory names for that test is included as part of the `require` overhaul in 88fd60174e74836abe505269c9e2780236b8e198, but I may be able to backport that fix into a separate smaller PR.

**Comment by david-christiansen** [comment]
I've also seen this happen!

I think @semorrison and I are both on Macs. Could it be that the Unicode normal form stored in the `.gitignore` doesn't match the one on the filesystem, or that a byte comparison is being done somewhere in Git where a string comparison would be better, leading to a UTF-16/UTF-8 mismatch? If it's the latter, then we could probably duplicate a few `.gitignore` entries for different encodings/normalizations.

**Comment by nomeata** [comment]
I have it on Linux.
