### ISSUE TITLE
Trace class `Meta.synthInstance.answer` is not registered

### ISSUE THREAD

**Issue by mattrobball** [leanprover/lean4#3373]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

In `Lean.Meta.SynthInstance.addAnswer`, there is a trace for `Meta.synthInstance.answer` but it is not registered at the bottom of the file. 

### Context

In [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Nonempty.20function.20instance), we were struggling under a failure of typeclass synthesis for nested function types. This trace would have made it much easier. For reference, I put the code of `addAnswer` below. 
```lean
def addAnswer (cNode : ConsumerNode) : SynthM Unit := do
  withMCtx cNode.mctx do
  if cNode.size ≥ (← read).maxResultSize then
      trace[Meta.synthInstance.answer] "{crossEmoji} {← instantiateMVars (← inferType cNode.mvar)}{Format.line}(size: {cNode.size} ≥ {(← read).maxResultSize})"
  else
    withTraceNode `Meta.synthInstance.answer
      (fun _ => return m!"{checkEmoji} {← instantiateMVars (← inferType cNode.mvar)}") do
    let answer ← mkAnswer cNode
    -- Remark: `answer` does not contain assignable or assigned metavariables.
    let key := cNode.key
    let entry ← getEntry key
    if isNewAnswer entry.answers answer then
      let newEntry := { entry with answers := entry.answers.push answer }
      modify fun s => { s with tableEntries := s.tableEntries.insert key newEntry }
      entry.waiters.forM (wakeUp answer)
```
You can see it is set up to report answers constructed from too many instances but simply not plugged in. 

### Steps to Reproduce

1. type `set_option trace.Meta.synthInstance.answer true`

**Expected behavior:** `set_option trace.Meta.synthInstance.answer true` should furnish the traces already in the code. 

**Actual behavior:** It fails with `unknown option 'trace.Meta.synthInstance.answer'`

### Versions

"4.7.0, commit fbedb79b4694ef86162694b1b1b8c489ecbd71ac"

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by mattrobball** [comment]
I have [branch](https://github.com/mattrobball/lean4/tree/newAnswer) which adds the trace messages in `addAnswer` to the `newAnswer` trace class. If this is favorable, let me know and I will PR.

**Comment by semorrison** [comment]
@mattrobball, yes please. Please ping me on the PR, it seems a straightforward bug fix.

**Comment by mattrobball** [comment]
@thorimur had identified a more exhaustive list of such things

**Comment by thorimur** [comment]
Here's a [link](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Meta.2EsynthInstance.2Eanswer.20not.20registered/near/421955563) to the message, and here are the ones I identified:
```
Lean/PrettyPrinter/Delaborator/Basic.lean: PrettyPrinter.delab.input
Lean/Meta/Tactic/Simp/SimpAll.lean: Meta.Tactic.simp.all
Lean/Meta/DecLevel.lean: Meta.isLevelDefEq.step
Lean/Meta/SizeOf.lean: Meta.sizeOf.minor
Lean/Meta/SizeOf.lean: Meta.sizeOf.minor.step
Lean/Meta/SizeOf.lean: Meta.sizeOf.aux
Lean/Meta/SizeOf.lean: Meta.sizeOf.loop
Lean/Elab/StructInst.lean: Elab.struct.modifyOp
Lean/Elab/Quotation.lean: Elab.match_syntax.onMatch
Lean/Elab/Term.lean: Elab.implicitForall
Lean/Elab/SyntheticMVars.lean: Elab.defaultInstance
Lean/Elab/MutualDef.lean: Elab.definition.mkClosure
Lean/Elab/Binders.lean: Elab.autoParam
Lean/Elab/Binders.lean: Elab.let.decl
```
