### ISSUE TITLE
__root__ expressions should be considered constructors

### ISSUE THREAD

**Issue by JasonGross** [leanprover/lean4#338]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

```lean
inductive Foo (Name : Type) where
| foo (x : Name)
structure Name' where
  name : Unit
def bar : Foo Name' → Type
| Foo.foo (__root__.Name'.mk name) => sorry
-- 6:12: invalid pattern, constructor or constant marked with '[matchPattern]' expected
```
This should not be an error, I think.

Note, btw, that if I rename `Name'` to `Name` and make it an inductive rather than a structure, then there seems to be no way to access the constructor here because it gets shadowed by the `Name` argument to `Foo` (which is confusing in it's own right, and which I've asked about at https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/invalid.20patterns.20from.20local.20variables/near/229305311)

### Versions

```
$ lean --version
Lean (version 4.0.0-nightly-2021-03-08, commit 00572a22f4d2, Release)
$ uname -a
Linux JasonGross-X1 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

**Comment by leodemoura** [comment]
I fixed the bug. 
BTW, it is `_root_` instead of `__root__`.
