### ISSUE TITLE
application should be allowed to force universe equality

### ISSUE THREAD

**Issue by JasonGross** [leanprover/lean4#342]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Given
```lean
structure CatIsh where
  Obj : Type o
  Hom : Obj → Obj → Type m
infixr:75 " ~> " => (CatIsh.Hom _)
structure FunctorIsh (C D : CatIsh) where
  onObj : C.Obj → D.Obj
  onHom : ∀ {s d : C.Obj}, (s ~> d) → (onObj s ~> onObj d)
def Catish : CatIsh :=
  {
    Obj := CatIsh
    Hom := FunctorIsh
  }
universes o m
```
This works:
```lean
unif_hint (mvar : CatIsh) where
  Catish.{o,m} =?= mvar |- mvar.Obj =?= CatIsh.{o,m}
```
but this does not:
```lean
unif_hint (mvar : CatIsh) where
  Catish =?= mvar |- mvar.Obj =?= CatIsh.{o,m}
/-
14:1: application type mismatch
  mvar.Obj = CatIsh
argument has type
  Type (max (o + 1) (m + 1))
but function has type
  Type (max (u_1 + 1) (u_2 + 1)) → Prop
-/
```

I'm not sure if I've named this issue correctly, since I'm not sure exactly what subset of the features I'm using here leads to universe mismatches happening.

### Versions

```
$ lean --version
Lean (version 4.0.0-nightly-2021-03-10, commit 4c82f5c68888, Release)
$ uname -a
Linux JasonGross-X1 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
$ cmd.exe /C ver
'\\wsl$\Ubuntu\home\jgross\Documents\GitHub\lean4'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

Microsoft Windows [Version 10.0.19041.804]
```

**Comment by leodemoura** [comment]
@JasonGross 
The commit above fixes a bug in the universe constraint management. Now, the error message for the second `unit_hint` command is
```
error: stuck at solving universe constraints
  max (m+2) (o+2) =?= max (?u.737+2) (?u.736+2)
```
In Lean 3, we approximated this kind of constraint using
```
m+2 =?= ?u.737+2
o+2 =?= ?u.736+2
```
We removed it from Lean 4 because we believe it creates counterintuitive behavior. 
Any thoughts on this issue?

**Comment by JasonGross** [comment]
Hmmm, yeah, I think in the general case it's probably right to not perform this approximation.  Coq maintains a graph of universe constraints, but does not handle general algebraic constraints.  I think I was expecting there to be a unique solution here, but I guess I got the constraints wrong in my head, so I'm happy to close this issue.
