### ISSUE TITLE
Cannot convert between a proposition and its alias

### ISSUE THREAD

**Issue by mik-jozef** [leanprover/lean4#3449]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

Reproducible example:

```lean
def Set (α : Type u) := α → Prop
def Valuation (D: Type u) := Nat → Set D

inductive Expr where
| var (v: Nat)

def interpretation (v: Valuation D): Expr → Set D
| Expr.var a => v a

def inExpr (v: Valuation D) (expr: Expr) (d: D): Prop :=
  interpretation v expr d

def problemA {d: D} {v: Valuation D} (dInExpr: inExpr v epxr d):
  interpretation v expr d
:=
  dInExpr

def problemB {d: D} {v: Valuation D} (dInExpr: inExpr v epxr d):
  interpretation v expr d
:=
  let eq:
    interpretation v expr d = inExpr v expr d
  :=
    rfl
  
  by rewrite [eq]; exact dInExpr
```

**Expected behavior:** No errors are reported in the above code

**Actual behavior:** I can reproduce the following errors both locally and on https://live.lean-lang.org/:

```
// in problemA:
type mismatch
  dInExpr
has type
  inExpr v epxr d : Prop
but is expected to have type
  interpretation v expr d : Prop

// in problemB:
type mismatch
  dInExpr
has type
  inExpr v epxr d : Prop
but is expected to have type
  inExpr v expr d : Prop
```

Slight changes (eg. using `(Expr.var 5)` instead of `expr`, or `| Expr.var a => v 0`) make the error disappear.

### Versions

Lean: 4.4.0-rc1
OS: Ubuntu 22.04.4 LTS

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by arthur-adjedj** [comment]
Turning off `autoImplicit`s reveals the issue, you made a typo in your argument `(dInExpr: inExpr v epxr d)`: it should be `expr` instead of `epxr`. This is not a bug.

**Comment by mik-jozef** [comment]
Sorry about this :/// I don't know how I managed to stare at it for two hours and not notice :sweat_smile: Closing
