### ISSUE TITLE
Invalid field notation error message.

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean4#346]
### Description

This is relatively minor, but I find the parser error message for failures of the form `Sym.name` misleading

### Steps to Reproduce

Consider this code:

```
inductive SomeType
| x : SomeType

namespace SomeType

def a : SomeType := SomeType.x

end SomeType

#eval SomeType.b
```

The error message I get has

```
Test.lean:15:6: error: invalid field notation, type is not of the form (C ...) where C is a constant
  SomeType
has type
  Type
```

I would prefer to get an error message saying something like 

```
 error: unknown identifier 'SomeType.b'
 ```  

I understand there's an ambiguity here.  Maybe if `SomeType` did not refer to a namespace scope but did refer to a definition, then I could see searching for a value and using the field notation error message.  

### Versions

```
Lean (version 4.0.0-nightly-2021-03-10, commit 4c82f5c68888, Release)
```

**Comment by leodemoura** [comment]
@joehendrix The commit above fixes the error message for the example above. I am wondering what you think about the following one.
```lean
def f (x : Nat) :=
  x.z
```
We still generate the following error for this one
```
error: invalid field notation, 'z' is not a valid "field" because the environment does not contain 'Nat.z'
  x
has type
  Nat
```
What do you think? Is it reasonable?

**Comment by joehendrix** [comment]
@leodemoura The message is quite clear to me.  It's minor, but maybe the wording could be tightened up a bit? e.g.,

```
error: invalid field 'z', the environment does not contain 'Nat.z'
  x
has type
  Nat
```

**Comment by leodemoura** [comment]
@joehendrix Thanks!
