### ISSUE TITLE
IO.FS.Handle.read segmentation fault

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean4#349]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

There seems to be a segmentation fault in IO.FS.Handle.read at the end of a file.

### Steps to Reproduce

Here is a file showing the bug.
```
partial def main (args:List String) : IO Unit := do
  match args with
  | [path] => do
    let h ← IO.FS.Handle.mk path IO.FS.Mode.read
    let rec loop : IO Unit := do
              let l ← h.getLine
              IO.println $ s! "Maybe about to segfault: {l}"
              let n ← h.read 1
              IO.println "Did not segfault"
              loop
    loop
  | _ => do
    IO.println "Expected path"
```

Here is a test file I used.

```
Line
```

**Actual behavior:** 

```
% ./build/bin/LRat testFile
Hello2
Maybe about to segfault Line
zsh: segmentation fault  ./build/bin/LRat testFile
```

### Versions

```
Lean (version 4.0.0-nightly-2021-03-14, commit c54a7c8ccc75, Release)
```

**Comment by joehendrix** [comment]
I think the printing the error generated from [this line](https://github.com/leanprover/lean4/blob/master/src/runtime/io.cpp#L309) is the culprit, but haven't had time to debug it further.

**Comment by ReijoJaakkola** [comment]
Not sure why seg-fault occurs, but I am bit confused why lean_io_prim_handle_read returns the error message g_io_error_eof, when eof has been reached, while (f.e.) lean_io_prim_handle_get_line returns just the empty string "" in a similar situation (I tested that segmentation fault occurs also if one changes lean_io_prim_handle_get_line in such a way that it also returns the same error message in case eof has been reached). Furthermore, if eof is reached when the stream is red in lean_io_prim_handle_read, then it returns the empty array. So should lean_io_prim_handle_read even return the error message in the first place?

**Comment by Kha** [comment]
I agree, it should always return an empty array at EOF. The `getLine` behavior was changed in 2cc0f25bf56b0e609635c5f85322497b34847223.
