### ISSUE TITLE
RFC: enable `zetaDelta` by default in `simp_all` and `simp [*]`

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lean4#3520]
### Proposal

With the recent `zetaDelta` changes, `simp_all` does not unfold `let` hypotheses any more, and neither does `simp [*]`:

```lean
example {P : Nat → Prop} : let x := 0; P x := by
  intro x
  simp_all
  -- no progress

example {P : Nat → Prop} : let x := 0; P x := by
  intro x
  simp [*]
  -- no progress
```

I feel like this goes against the spirit of using all hypotheses. More specifically, I would expect `simp [*]` to be equivalent to `simp [x, y, z, ...]`, where `x, y, z, ...` are the local hypotheses, and I would expect `simp_all` to be at least as powerful as `simp [*]` (in some vague sense). So I would suggest that `zetaDelta` be enabled by default for these two forms.

### Community Feedback

Very brief discussion [here](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Aesop.20dev.20updates/near/423357812) with some support and no dissent.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by semorrison** [comment]
The intended semantics for both `simp [*]` and `simp_all` is that it will use all *propositional* hypotheses.

**Comment by JLimperg** [comment]
I find this interpretation inconsistent. A `let` decl consists of an fvar (usually indeed non-propositional) and a definitional equation. Definitional equations are a subset of the propositional ones and are 'stronger' in the sense that I would expect them to be applied 'more automatically'. So I find it weird that `simp_all` will substitute `x` in the context `x : Nat, h : x = 0` but not in the context `x : Nat := 0`.

**Comment by semorrison** [comment]
@JLimperg, I'll bring this up internally again.
