### ISSUE TITLE
(← foo) sees wrong do?

### ISSUE THREAD

**Issue by kovach** [leanprover/lean4#354]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Steps to Reproduce

```
example (l : List α) [Monad m] : m (List α) := do
l.mapM λ x => /- do -/ pure (← pure x) -- error: unknown id 'x'. fixed by adding closer `do`.
```

**Expected behavior:** [What you expect to happen]

I would expect either
* this to work
* to see the error "must be nested inside a 'do' expression"

**Actual behavior:** [What actually happens]
see comment

### Versions
nightly commit 55157a31080e

**Comment by leodemoura** [comment]
Duplicate. See https://github.com/leanprover/lean4/issues/247
