### ISSUE TITLE
typeclass instance search fails to resolve typeclasses where unification depends on the particular instantiation of previous instances

### ISSUE THREAD

**Issue by JasonGross** [leanprover/lean4#355]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

```lean
class DefEq {α : Sort _} (a : α) (b : outParam α) where
  prf : a = b
instance {α} {a : α} : DefEq a a := { prf := rfl }
instance InhabitedOfDecidable {α : Sort _} [Decidable α] [DefEq (decide α) true] : Inhabited α where
  default := ofDecideEqTrue DefEq.prf
set_option trace.Meta.synthInstance true
--set_option pp.all true
--set_option trace.Meta.isDefEq true
--set_option trace.Meta.isLevelDefEq true
#check @inferInstance (DefEq (decide (1 > 0)) true) _
#check @inferInstance (Inhabited (1 > 0)) _
/-
failed to synthesize instance
  Inhabited (1 > 0)
-/
```

I'm guessing that the problem gets passed to the unifier before instantiating the resolved metavariables?

see https://leanprover.zulipchat.com/#narrow/stream/147302-lean4-dev/topic/reverse.20order.20Range.3F/near/230743801

### Versions

```
$ lean --version
```
Lean (version 4.0.0-nightly-2021-03-17, commit 7dc6721fea48, Release)
```
$ uname -a
Linux JasonGross-X1 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
$ cmd.exe /C ver
'\\wsl$\Ubuntu\home\jgross\Documents\GitHub\lean4'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

Microsoft Windows [Version 10.0.19041.804]
```

**Comment by leodemoura** [comment]
This problem fails because during TC resolution we only unfold definitions marked as `[reducible]` and other instances. To make this example work, we would need to be able to reduce `decide`, `Nat.decLt`, etc when we try to unify `DefEq (decide α) true` with `DefEq ?m ?m`.

**Comment by JasonGross** [comment]
Huh, that's an interesting design decision.  Is `[reducible]` only for outParams?  (Are input parameters always only up to syntactic matching?)  If not, is there a way to control reducibility separately for input parameters and output ones?

**Comment by leodemoura** [comment]
We select candidate instances using a discrimination tree. The selection only considers input parameters. The retrieval operation is syntactic but is performed after unfolding `[reducible]` definitions. But, the definitionally equality tests behave the same for input and output parameters.
The entry point for the TC procedure is here:
https://github.com/leanprover/lean4/blob/1af02dcaca3ca0665a37254aaa30ea196ec77c90/src/Lean/Meta/SynthInstance.lean#L570-L571
