### ISSUE TITLE
Feature request: System.exit

### ISSUE THREAD

**Issue by joehendrix** [leanprover/lean4#356]
### Description

It would be useful to have an analog of the C `exit` function.  

This could have the type `const System.exit : {A} -> UInt8 -> IO {A}` and would exit the program with a return code.  Currently, I have code that exits by throwing an exception, but I'd often like to figure out my own error reporting and exit with just a return code.

**Comment by dselsam** [comment]
https://github.com/dselsam/lean4/commit/631e9e588a40a839df47d210e92307cee580e11a

**Comment by ReijoJaakkola** [comment]
I guess what is meant by this is that System.exit should be analogous to exitImmediately function of Haskell, i.e. one can (say) echo the value returned by the program. In that case I guess the way to implement this is to simply use the exit function of C, while adding the relevant Lean code in ..\src\Init\System ...?
