### ISSUE TITLE
Show initial proof state at each branch

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#360]
Hovering over a tactic shows the final state, so we need to show the initial state of a branch at the preceding token, i.e. `by`, `=>`, ...

**Comment by leodemoura** [comment]
@Kha We are already getting the initial state when we hover over `by` and `=>`. 
If there is some missing feature, could you please create a repro for it? 
Otherwise, let's close this issue.

**Comment by Kha** [comment]
Yeah, this is now addressed
