### ISSUE TITLE
Show proof state/unclosed goal message on empty tactic sequences

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#361]
`by` or `case c =>` currently is a parse error, so users have to append `{}` manually to inspect the state. This is part of the larger "elaborate partial syntax trees" issue.

**Comment by leodemoura** [comment]
If the `by` ant `case =>` are the "terminal", we can inspect the state by hovering the `by` and `=>`.
Examples:
```lean
theorem ex1 (p q r : Prop) (h1 : p ∨ q) (h2 : p → q) : q := by


theorem ex2 (p q r : Prop) (h1 : p ∨ q) (h2 : p → q) : q := by
  cases h1
  case inl =>
```
When it is not terminal, the behavior can get quite confusing. Example:
```lean
theorem ex3 (p q r : Prop) (h1 : p ∨ q) (h2 : p → q) : q := by
  cases h1
  case inl =>
  case inr =>
```
Note that the example is being parsed as
```lean
theorem ex2 (p q r : Prop) (h1 : p ∨ q) (h2 : p → q) : q := by
  cases h1
  case inl => {
    case inr =>
  }
```
Since we suppress elaboration errors when there are parser errors, most users will wonder why the second `=>` has no goal message for the `inr` case.

**Comment by Kha** [comment]
I believe we should
* wrap the `tacticParser` at `tacticSeq1Indented` in a `withPosition`, which is to mean "the tactic contents should be at least as indented as the tactic"; this would subsume many `withPosition` calls we have in individual tactics as long as their contents use `colGt`, not `colGe`
* introduce `indentedTacticSeq := colGt tacticSeq` and use it in `case` etc., though *not* in `by` and other syntax we want to use as "hanging"

Then the example should be parsed as intended

**Comment by Kha** [comment]
If we want to be thorough, we can also add a `withoutPosition` inside `tacticSeqBracketed` such that `indentedTacticSeq` does not enforce indentation inside braces.

**Comment by Kha** [comment]
> I believe we should
> 
>     * wrap the `tacticParser` at `tacticSeq1Indented` in a `withPosition`, which is to mean "the tactic contents should be at least as indented as the tactic"; this would subsume many `withPosition` calls we have in individual tactics as long as their contents use `colGt`, not `colGe`
> 
>     * introduce `indentedTacticSeq := colGt tacticSeq` and use it in `case` etc., though _not_ in `by` and other syntax we want to use as "hanging"
> 
> 
> Then the example should be parsed as intended

@leodemoura What do you think of these? The first bullet is optional, we could also just do
```
syntax (name := case) withPosition("case " (ident <|> "_") (ident <|> "_")* " => " colGt tacticSeq) : tactic
```
However, that's not as nice when one wants to use the `elab` shorthand.
