### ISSUE TITLE
RFC: have `#print` display structure fields

### ISSUE THREAD

**Issue by fgdorais** [leanprover/lean4#3644]
### Proposal

The `#print` command currently treats structures just like any other inductive type. For example:
```lean
structure A (α β) where 
  a : α
  b : β 

/-
inductive A.{u_1, u_2} : Sort u_1 → Sort u_2 → Sort (max (max 1 u_1) u_2)
number of parameters: 2
constructors:
A.mk : {α : Sort u_1} → {β : Sort u_2} → α → β → A α β
-/
#print A
```
Unfortunately, this omits useful information about the structure type `A`, in particular the name and types of the fields. Indeed, there is no easy way to find the names the fields of a structure at this time.

I propose changing that default behavior as follows:
```lean
/-
structure A.{u_1, u_2} : Sort u_1 → Sort u_2 → Sort (max (max 1 u_1) u_2)
number of parameters: 2
constructor:
A.mk : {α : Sort u_1} → {β : Sort u_2} → α → β → A α β
fields:
a : α
b : β
-/
#print A
```
I propose the following spec for the info:

* The output of the `#print` command for structures should extend that for inductive except that the word "inductive" should be replaced by "structure" or "class" and the word "constructors" should be replaced by "constructor".
* There should be an additional line "fields:" followed, on separate lines, by the names of each structure field followed by the type of the associated projection, omitting the type parameters and the "self" parameter.
* Private fields should be prefixed by the "private" keyword.
* The fields should be listed in the order of their indices so that numerical projections can be identified as well.

The rationale is ensure that no information is lost from the current behavior and to keep the info simple. Considerations were given for adding an option for printing flattened subobject fields and other display features. However, these were rejected on the basis that these would not fit with the current utilitarian design of the `#print` command in Lean 4. That information could be obtained by multiple uses of the `#print` command. Additional features such as this should be tested in Std or Mathlib before adding to Lean 4.

The WIP implementation in #3768  shows that the PR footprint would be limited to Lean.Elab.Print, with no additional infrastructure. This supports that the maintenance cost should be minimal compared to user benefits.

### Context

The `#print` command in Lean 3 did print structure fields and their types.

The lack of support for structures in the `#print` command has been mentioned several times on Zulip. Here is a recent example: <https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/improving.20.23print.20structure/near/422209781>

This RFC comes from WIP [std4#672](https://github.com/leanprover/std4/pull/672), which is currently on hold pending the outcome of this RFC. Note that this PR implements features which are _not_ part of this RFC.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

### Edits

Mar 28: Revised spec after @kmill comments. The spec now omits type parameters and "self" parameter from the field types.

**Comment by kmill** [comment]
I would suggest that it output the fields with their qualified names:
```
structure A.{u_1, u_2} : Sort u_1 → Sort u_2 → Sort (max (max 1 u_1) u_2)
number of parameters: 2
constructor:
A.mk : {α : Sort u_1} → {β : Sort u_2} → α → β → A α β
fields:
A.a : {α : Sort u_1} → {β : Sort u_2} → A α β → α
A.b : {α : Sort u_1} → {β : Sort u_2} → A α β → β
```
One thing that enables is copy/pasting the projection functions.

It could be nice if it omitted the parameters from the types of the fields somehow, since this is already apparent from the constructor.
```
structure A.{u_1, u_2} : Sort u_1 → Sort u_2 → Sort (max (max 1 u_1) u_2)
number of parameters: 2
constructor:
A.mk : {α : Sort u_1} → {β : Sort u_2} → α → β → A α β
fields:
A.a : ... → A α β → α
A.b : ... → A α β → β
```

**Comment by fgdorais** [comment]
> I would suggest that it output the fields with their qualified names:
> 
> ```
> structure A.{u_1, u_2} : Sort u_1 → Sort u_2 → Sort (max (max 1 u_1) u_2)
> number of parameters: 2
> constructor:
> A.mk : {α : Sort u_1} → {β : Sort u_2} → α → β → A α β
> fields:
> A.a : {α : Sort u_1} → {β : Sort u_2} → A α β → α
> A.b : {α : Sort u_1} → {β : Sort u_2} → A α β → β
> ```
> 
> One thing that enables is copy/pasting the projection functions.

I thought about this but decided against for this RFC because the required prefix is easy to find and this leads to really ugly stuff for private fields. I'm happy to hear more ideas about this. Does it make sense to omit private fields when outside the right module? That sounds wrong for Lean 4 core but it might make sense downstream.

> It could be nice if it omitted the parameters from the types of the fields somehow, since this is already apparent from the constructor.
> 
> ```
> structure A.{u_1, u_2} : Sort u_1 → Sort u_2 → Sort (max (max 1 u_1) u_2)
> number of parameters: 2
> constructor:
> A.mk : {α : Sort u_1} → {β : Sort u_2} → α → β → A α β
> fields:
> A.a : ... → A α β → α
> A.b : ... → A α β → β
> ```

I agree but I don't know how to do that off the top of my head. Any examples of this?

**Comment by digama0** [comment]
Why not use a syntax closer to the definition instead of inventing something new? That is, for this example:
```lean
structure A.{u_1, u_2} (α : Sort u_1) (β : Sort u_2) : Sort (max (max 1 u_1) u_2) where
  a : α
  b : β
```

**Comment by fgdorais** [comment]
Makes sense, I think that basically reduces to "omitting parameters" as in Kyle's comment. I'm not sure how to do that.

**Comment by digama0** [comment]
The basic idea is to introduce the binders for the parameters once, while printing the type, and then instantiate the types of the projections with the parameter fvars for each constructor. (It might be easier to continue the implementation discussion on zulip and stick to design decisions here.)

**Comment by fgdorais** [comment]
I think I figured out how to implement these ideas. I'll have an update on Thursday.

**Comment by fgdorais** [comment]
I got the draft PR to implement @kmill's proposal (minus the dots, do you really want the dots?). You can see some actual output examples at [tests/lean/printStruct.lean](https://github.com/leanprover/lean4/blob/4d66fa891a0fd6cd2e5f36b1274cd81e5e01d46d/tests/lean/printStruct.lean) and the accompanying expected output.

@digama0 Thank you for the hint. Turns out I was just missing `liftTermElabM` and then everything worked out.

I also like your idea of making the `#print` output closer to the definition. However, I wanted to stay close to what `#print` currently does for inductive types. Your suggestion makes perfect sense to me for a more comprehensive update of `#print` but this is not the current scope of this RFC. I'm happy to hear more of your thoughts about this.

**Comment by kmill** [comment]
(I didn't really want the dots — I'm happy to see the idea discarded :-))

**Comment by kmill** [comment]
#6096 has a prototype with some more modifications to `#print` for structures. The design principle that "the fields should be listed in the order of their indices so that numerical projections can be identified as well" is lost, but it's still encoded in the constructor. It gives fully qualified names for projections so that it's possible to know which parent structure it was inherited from (and you can do "go to definition" on them).

Zulip discussion here: https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/.23print.20command.20for.20structures/near/482503637
