### ISSUE TITLE
RFC: Simplify `Array.findIdx?`

### ISSUE THREAD

**Issue by michelsol** [leanprover/lean4#3646]
### Proposal

In Data/Array/Basic.lean

I would like to simplify `Array.findIdx?`, and propose replacing its [code](https://github.com/leanprover/lean4/blob/1d3ef577c28b6298f4edf8aef86b23ca3ba99b66/src/Init/Data/Array/Basic.lean#L457-L476) with the following

```lean
@[inline]
def findIdx? {α : Type u} (as : Array α) (p : α → Bool) : Option Nat :=
  let rec loop (j : Nat) :=
    if h : j < as.size then
      if p as[j] then some j else loop (j + 1)
    else none
    termination_by as.size - j
  loop 0
```
I haven't changed the structure of the executable code. It was using two Nat's and some invariant with, I think, the intent to avoid wf recursion, (maybe because it's old code ?). 

  - **User Experience**: How does this feature improve the user experience?

It would be easier to reason about `Array.findIdx?`.

  - **Beneficiaries**: Which Lean users and projects benefit most from this feature/change?

In std, there is a proof_wanted [here](https://github.com/leanprover/std4/blob/f3447c3732c9d6e8df3bdad78e5ecf7e8b353bbc/Std/Data/Array/Lemmas.lean#L726),  the proof of which might turn out to be easier to write, with the proposed change.

  - **Maintainability**: Will this change streamline code maintenance or simplify its structure?
 
This change would simplify `Array.findIdx?`

### Community Feedback

I created a thread [here](https://leanprover.zulipchat.com/#narrow/stream/348111-std4/topic/findIdx.3F.20and.20indexOf.3F)

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by nomeata** [comment]
Looks reasonable to me, unless we have reason to assume that someone really needs this to be structurally (not well-foundedly) recursive, e.g. because they need this to reduce in types.
