### ISSUE TITLE
Inconsistencies between literal parsers

### ISSUE THREAD

**Issue by fgdorais** [leanprover/lean4#3649]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

Consider this MWE:
```lean
open Lean Parser

macro "strTest" s:strLit : term => if s.getString = "T" then `(true) else `(false)

macro "testChar" c:charLit : term => if c.getChar = 'T' then `(true) else `(false)
```
The first works because the strLit parser returns ``TSyntax `str`` but the charLit parser returns ``TSyntax `Lean.Parser.charLit`` instead of ``TSyntax `char``.

@kmill diagnosed that the difference is that `strLit` is special cased in [Lean.Elab.Command.expandMacroArg.mkAntiquotNode](https://github.com/leanprover/lean4/blob/6fce8f7d5cd18a4419bca7fd51780c71c9b1cc5a/src/Lean/Elab/MacroArgUtil.lean#L47-L78) but `charLit` isn't. 

Indeed, only a few literal kinds are special cased there. Perhaps they should all be?

### Context

This arose while writing macro code for ASCII restricted string and char constants. I wrote the string code first and I expected the char code to work basically the same, but I stumbled on this unexpected difference in behavior.

Discussion on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Unexpected.20difference.20between.20charLit.20and.20strLit.20parsers/near/425807754)

### Versions

Lean (version 4.7.0-rc1, aarch64-apple-darwin, commit 8bde8b9d87ee, Release)

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by fgdorais** [comment]
This is a very minor issue, calling it a bug seems excessive. However, it is very easy to fix.

**Comment by leodemoura** [comment]
Both fail at v4.8.0 
```
3649.lean:3:0: error: unknown parser declaration/category/alias 'strLit'
3649.lean:5:0: error: unknown parser declaration/category/alias 'charLit'
```
and the following work
```
macro "strTest" s:str : term => if s.getString = "T" then `(true) else `(false)
macro "testChar" c:char : term => if c.getChar = 'T' then `(true) else `(false)

#eval strTest "T" -- true 
#eval strTest "f". -- false
#eval testChar 'T' -- true
#eval testChar 'f' -- false
```
