### ISSUE TITLE
Are ByteArray.toInt64LE! and ByteArray.toInt64BE! reversed?

### ISSUE THREAD

**Issue by gleachkr** [leanprover/lean4#3657]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

I suspect that the little-endian and big-endian ByteArray functions have their names backwards. The little-endian function seems to convert a ByteArray to a UInt64 by taking the leftmost byte as most significant, and vice-versa.

### Steps to Reproduce

It should be easy to check, but here's a minimal reproduction, showing how the current functions seem to get things wrong when reading an ELF binary. Requires a 64 bit ELF binary - I used `/bin/true`.

```
def test: IO Unit := do
  let bytes ← IO.FS.readBinFile ↑"/bin/true"
  if h : bytes.size > 256 then do
    IO.println bytes[0x5] -- e_ident[EI_DATA], 1 means little endian, 2 means bigendian
    let ph_off := bytes.extract 0x20 0x28 --program header offset in a 64 bit binary, should be 64.
    IO.println ph_off
    IO.println ph_off.toUInt64LE!
    IO.println ph_off.toUInt64BE!

#eval test 
```

**Expected behavior:**

I would expect the code above to show toUInt64LE! returning 64 for bytes [0x20,0x28) on a little-endian binary, and toUInt64BE! to give a 64 for that range on a big-endian binary.

**Actual behavior:** 

Seems to be the reverse

### Versions

4.7.0-rc1
Ubuntu 22.04.1

### Impact

**Comment by digama0** [comment]
Here's a simpler reproduction:
```lean
#eval (ByteArray.mk #[1,0,0,0,0,0,0,0]).toUInt64BE! -- 1
#eval (ByteArray.mk #[1,0,0,0,0,0,0,0]).toUInt64LE! -- 72057594037927936
```
A little endian array should have the least significant byte at index `[0]`, meaning that `#[1,0,0,0,0,0,0,0]` encodes 1 in little endian.
