### ISSUE TITLE
VSCode extension runs into infinite leanpkg spawning loop on Ctrl+hover

### ISSUE THREAD

**Issue by SReichelt** [leanprover/lean4#367]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

In the Lean 4 VSCode extension, holding Ctrl and hovering over a term that references a definition frequently causes lots of `leanpkg` processes being started, apparently in an infinite loop, consuming all CPU and grinding the system to a halt.
With the given steps I can reliably reproduce it on Ubuntu 20.04.

### Steps to Reproduce

1. Enter something like `def Test := True` in an empty `.lean` file.
2. Hold the Ctrl key.
3. Hover over `True`. (Note: Ctrl+clicking very quickly actually avoids the issue.)

**Expected behavior:** `True` should be underlined (for Ctrl+click) but this shouldn't cause any harm.

**Actual behavior:** `True` is underlined correctly and everything appears to work normally for a moment, but in the background two things happen:
* `leanpkg print-paths` processes are spawned in a loop until I close VSCode. Depending on the complexity of the file/project, these processes accumulate because they are started faster than they can finish, though in this small example this doesn't happen and there are always just one or two such processes.
* Lean workers are also somewhat busy.

**Reproduces how often:** Always.

### Versions

Lean (version 4.0.0-nightly-2021-03-22, commit 19b24e3e823c, Release)
Ubuntu 20.04.2 LTS (x64)

**Comment by Kha** [comment]
It turns out the/a root cause is that VS Code will send a `didOpen` request on hover (repeatedly, apparently), with no way to distinguish it from actually visiting a file: https://github.com/microsoft/vscode/issues/78453. This is terrible for our server model.

@gebner Any ideas? :pray:

**Comment by mhuisi** [comment]
I've been playing around with this issue for a while now, so I'd like to provide some additional context.

- The linked github issue does not explicitly mention that `didOpen`/`didClose` is called  *repeatedly*. Another issue about the same topic also does not mention this explicitly: microsoft/vscode-languageserver-node#683
- A similar issue occurs when deleting `OptionM.run` while hovering over `OptionM` [here](https://github.com/mhuisi/lean4-cli/blob/58fd5f3c5e7e214fac1b846ead1636b951ce879d/Cli/Basic.lean#L894). The client repeatedly spams `didOpen`/`didClose` notifications, grinding the server to a halt.
- Sebastian couldn't reproduce either issue with an older version of VSCode (1.52.1), but could reproduce it with a new version of VSCode (1.54.2).

One possible (server-sided) solution would be to simply ignore `didOpen` calls until a specific request or notification for that file is received. I'm not quite sure why the CTRL+hover feature should need to call `didOpen` in the first place, does the `textDocument/definition` request that is sent *before* the `didOpen`/`didClose` spam not contain all the important information?

**Comment by gebner** [comment]
I believe sending didOpen/didClose is intentional, but sending them on repeat is not.

I can reproduce the issue, I'll see if I can hack up some workaround.

**Comment by mhuisi** [comment]
> * A similar issue occurs when deleting `OptionM.run` while hovering over `OptionM` [here](https://github.com/mhuisi/lean4-cli/blob/58fd5f3c5e7e214fac1b846ead1636b951ce879d/Cli/Basic.lean#L894). The client repeatedly spams `didOpen`/`didClose` notifications, grinding the server to a halt.

I just noticed that this is just because I use Ctrl+X to delete `OptionM.run`, so it's exactly the same issue.

**Comment by gebner** [comment]
I believe the endless repeat of didOpen/didClose is due to our `setLean4LanguageId` function.

**Comment by gebner** [comment]
Can you try out https://github.com/leanprover-community/vscode-lean4/pull/17?

**Comment by mhuisi** [comment]
I cannot reproduce the issue anymore with that PR.

**Comment by SReichelt** [comment]
That fixes the problem for me as well. Many thanks!
(I cannot really judge the code changes, though.)
