### ISSUE TITLE
`←` should not be accepted in pure `do` blocks

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#370]
```
#eval show Option String from do
  s!"{← some 1}"
```
Users might assume the code returns `some "1"`, but it returns `some "(some 1)"`.

**Comment by leodemoura** [comment]
I am interpreting this issue as: if Lean is interpreting the `do` block as pure code, then it should sign an error if it contains a `<-`.

The example you described above would only confuse users that are assuming there is a `Monad Option` floating around.

**Comment by Kha** [comment]
> I am interpreting this issue as: if Lean is interpreting the `do` block as pure code, then it should sign an error if it contains a `<-`.

Yes, and this should include nested actions. Going further, we could forbid non-terminal actions (without bindings) as well.

**Comment by Kha** [comment]
> Going further, we could forbid non-terminal actions (without bindings) as well.

Well, I guess they already have to be of type `Unit`, which is a pretty strong hint to the user.
