### ISSUE TITLE
Typo in Lake README

### ISSUE THREAD

**Issue by crvdgc** [leanprover/lean4#3703]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

At [this line](https://github.com/leanprover/lean4/blob/66541b00a6d8de58482155d4e9d817f96de376a9/src/lake/README.md?plain=1#L144):

> a given target is up-to-date (i.e., does not not need to be rebuilt)

should be "does not need to be rebuilt"

### Context

N/A

### Steps to Reproduce

N/A

### Versions

commit 66541b00a

### Additional Information

N/A

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by nomeata** [comment]
Thanks for reporting! For a small typo, a PR is even more helpful, as it then takes only one further click and it's gone.
