### ISSUE TITLE
RFC: variable naming code action on `case` tactic

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#3709]
### Proposal

The new `derive_functional_induction` command produces helpful, but rather complex, eliminators, and leads to code like
```
case case1 val ks' vs i hi ks'' vs'' hfind IH =>
```

Filling in these variables is rather annoying: If I have
```
case case1 =>
```
I see the daggered variable names in the goal state, and I start copy the names, but because of `case` assigns them as a suffix, I fell stressed because I have to type in all of them at once. Sometimes I start typing it down in a comment after `case case1 => -- ` so that the goal doesn’t change as I type.

We (sometimes) get a code action on `induction … with` that inserts all cases with variables at onces. But I find that as I am editing an existing proof, this isn’t very helpful.

So I could imagine that
```
case case1 =>
```
with no variable name to have a code action that inserts the “obvious” variable names. Then, for example, when I change the function and the induction principle changes, I can re-trigger the code action to get the new variable names and name order.

### Community Feedback

(No Zulip discussions yet.)

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by digama0** [comment]
If you use the `induction` tactic the code action should help and fill out all the variables

**Comment by nomeata** [comment]
Somehow the `induction` code action rarely pops up for me, not sure what I am doing wrong.

Even if it would: Would it be useful if I already have a proof with some cases etc, and now something has changed and I need to update some of the `case` variables?

Finally, when it works, doesn’t it produce `induction … with | … ` syntax? In that case for those who (for better or worse) prefer the `case … => ` syntax, or who use `case` for independently of `induction`, the extra more convenience around `case` would still be nice.

**Comment by digama0** [comment]
> Finally, when it works, doesn’t it produce `induction … with | … ` syntax? In that case for those who (for better or worse) prefer the `case … => ` syntax, or who use `case` for independently of `induction` (e.g. `refine`), the extra convenience around `case` would still be nice, wouldn’t it?

Sure. My point is that the extra structure in the `induction` tactic that people dislike is actually the thing that allows it to give better quality suggestions. A `case` tactic code action is *necessarily* less helpful, at least assuming it only looks at the tactic context itself rather than applying heuristics to the rest of the proof to determine that actually this is one arm in an `induction` that was just not written that way for some reason.

**Comment by nomeata** [comment]
Ah, I see, thanks for highlighting the fact that `case` can name more variables than just the ones introduced by the most recent `induct`/`cases`/`refine`. That may also explain the design decision to label variables from the right…

It seems one could argue that it’s a misfeature that `case` can even be used to give names to these variables. If `case` somehow knew which variables are there to be named, then such a code action would be less controversial.

But this is a hypothetical; with arbitrary changes to the goal in between (`induction … ; (all_goals …); case`), it seems hard to give a reasonable specification for which variables `case` should touch.

So I am convinced that such a code action for `case` is hard and possibly undesirable, and I know have more reasons to use the `with` syntax. I just tried and it seems the code action requires `import Std`, which is why I so far don’t have it in most of my code; presumably this will change with the current upstreaming efforts.

Even if I have it, there is still the remaining use case of updating the variable list of an existing case when something changes (e.g. the function from with the induction is derived from). I’ll edit the issue description to talk about the `induction … with` form instead. It’s not a super high priority in either case.

**Comment by nomeata** [comment]
Actually, given that `| con x =>` names the variables from the top, and thus the updating is arguably a bit less annoying, I’ll just close this for now. I might open another one if the itch becomes strong enough.
