### ISSUE TITLE
Error updating: Error fetching goals: Rpc error: InternalError: unknown metavariable '?_uniq.73'. Try again.

### ISSUE THREAD

**Issue by kevinsullivan** [leanprover/lean4#3720]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

Load this code and put your cursor at the end of the first case.

``` lean
example : 
  ∀ (P Q R : Prop), 
    (P ∨ Q) → 
    (P → R) → 
    (Q → R) → 
    R := 
by 
  intros P Q R rors pr qr
  cases rors with
  | inl r => _
  | inr s => _
```

**Expected behavior:** [Clear and concise description of what you expect to happen]

No bug

**Actual behavior:** [Clear and concise description of what actually happens]

Bug 

### Versions

4.3.0

**Comment by nomeata** [comment]
Thanks for the report! That's a relatively old version of lean, can you reproduce it on https://live.lean-lang.org/ as well?

**Comment by nomeata** [comment]
Yes, one can!

**Comment by kevinsullivan** [comment]
:-) thank you for your quick response
