### ISSUE TITLE
Instance declared twice in a row gets an error the first time and accepted the second time

### ISSUE THREAD

**Issue by hwatheod** [leanprover/lean4#3757]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description
In the monad instance declaration below, an error `fields missing: 'map', 'mapConst', 'seq', 'seqLeft'` is reported but when I make the identical declaration a second time, it is accepted.

```
structure WithLog (α: Type) (β: Type) where
  log: List α
  val: β
deriving Repr

/-
  I declare the same instance twice identically.
  The first one gets an error but the second one is accepted.
  If I comment out the first one, then the second one will get an error.

  The error is:
    fields missing: 'map', 'mapConst', 'seq', 'seqLeft'
-/
instance : Monad (WithLog α) where
  pure v := ⟨[], v⟩
  bind result f := let rest := f result.val; ⟨ result.log ++ rest.log, rest.val ⟩

instance : Monad (WithLog α) where
  pure v := ⟨[], v⟩
  bind result f := let rest := f result.val; ⟨ result.log ++ rest.log, rest.val ⟩

def sumAndFindEvens : List Int → WithLog Int Int
  | [] => pure 0
  | i :: is => do
    if (i % 2 == 0) then ⟨[i], ()⟩ else pure ()
    let sum <- sumAndFindEvens is
    pure (sum + i)

#eval sumAndFindEvens [1,2,3,4,5]   -- this works if you have both instances as the second one was accepted
```

Tried both in VS Code and directly from the command line `lake env lean Bug.lean`. Same behavior.

### Context

I found this while working through one of the monad examples in [Functional Programming In Lean ](https://leanprover.github.io/functional_programming_in_lean/monads.html#logging).

### Steps to Reproduce

1. Copy and paste the above code into VS Code
2. See that there is a red squiggly line under "where" in the first instance declaration, but no red squiggly line in the second instance declaration.

**Expected behavior:** First instance declaration should be accepted. Second one should not be needed.

**Actual behavior:** First instance declaration is rejected with an error, and the second one is accepted.

### Versions

"4.7.0-rc2"
MacOS 12.7.4

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by hwatheod** [comment]
The following variation (removing the `let` ) works correctly:

```
instance : Monad (WithLog α) where
  pure v := ⟨[], v⟩
  bind result f := ⟨ result.log ++ (f result.val).log, (f result.val).val ⟩
```

**Comment by arthur-adjedj** [comment]
The error in the first instance has already been reported as #3146, and has a pending PR fixing it: #3152

Even though the first instance gives an error, the instance is still produced, using in `sorry`s in the fields that couldn't be filled correctly. The second instance can get accepted without giving any fields explicitly since all fields can be solved using the existing `Bind (WithLog α)` and `Applicative (WithLog α)` instances produced by the former definition.

**Comment by hwatheod** [comment]
Closing as duplicate
