### ISSUE TITLE
"PANIC at Lean.isLevelMVarAssignable - unknown universe metavariable"

### ISSUE THREAD

**Issue by Timeroot** [leanprover/lean4#3780]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

The following error occurred while working on mathlib in VS Code:
```
PANIC at Lean.isLevelMVarAssignable Lean.MetavarContext:413:14: unknown universe metavariable
```
while using `v4.7.0-rc2`.

Full stack trace: [stacktrace.txt](https://github.com/leanprover/lean4/files/14764164/stacktrace.txt)

### Context

I have a particular `partial def` that I was working with. It was actually nonrecursive itself, but defined in terms of an auxiliary function (in a `where`) that was recursive. Since recursive partial defs are opaque to the theorem prover, and I wanted to prove correctness of this function, I changed the auxiliary function to return a `Subtype` with the appropriate correctness. Then the compiler complained that it couldn't prove that the type was inhabited, so I needed to give an instance proving that. The code looked something like this:

```
private noncomputable instance is_nonneg'_aux_sound :
    Inhabited { b : Bool // if b then 0 < x else x ≤ 0 } :=
  ⟨⟨0 < x, by
    by_cases h : 0 < x
    simp [h]
    simp [h, lt_of_not_le h]⟩⟩

partial def is_nonneg' (hx : Seq x) : Bool :=
  is_nonneg_aux 0 where
  is_nonneg_aux (n : ℕ) : { b : Bool // if b then 0 < x else x < 0 } :=
    if hx.ub n < 0 then
      ⟨false, seq_pos _ _ _ ⟩
    else if hx.lb n > 0 then
      ⟨true, seg_neg _ _ _ ⟩
    else
      is_nonneg_aux (n+1)
```
I wanted to see if there was a way to put the `instance` inside of the `def` (as, say, a `let` clause) -- or if the compiler would be unable to see that. At some point in the middle of that cut/paste/fix process I got the error.

### Steps to Reproduce

I was unable to reproduce it, this happened sort of transiently as I was typing. If this makes the report useless, of course feel free to just close this issue off the top.

### Versions

Lean (version 4.7.0-rc2, x86_64-unknown-linux-gnu, commit 6fce8f7d5cd1, Release)
on Linux Mint 20.3.

**Comment by semorrison** [comment]
Closing as non-reproducible for now, but if anyone finds a repro please let reopen or create a new issue!
