### ISSUE TITLE
server hangs when changing imports

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean4#3786]
### Description

When changing the imports of a file, Lean has to re-import the files. However, sometimes the Lean server (in VSCode) will just hang forever showing yellow bars, not making any progress for many mintutes. Reloading the window or restarting the file in VSCode will cause the Lean server to import the files correctly and be ready for use after a matter of seconds.

I have noticed this multiple times myself on Windows, and I have noticed this with various students and other people, I believe always on Windows. I *think* this is a Windows-only issue. EDIT: at least one Mac user also experiences this (see Zulip thread below).

I don't have a way to reliably reproduce this.

Possibly related: leanprover/lean4#3787

[Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Lean.20hangs.20when.20changing.20imports)

### Versions

`vscode-lean v0.0.135` (and many other versions)
`Lean 4.7.0-rc2` (and many other versions)
`Windows 11 Home`

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by semorrison** [comment]
For what it is worth, I've never observed this on macos.

**Comment by mhuisi** [comment]
@fpvandoorn Do you still encounter this issue on 4.8.0?

**Comment by fpvandoorn** [comment]
[Yes](https://github.com/leanprover/lean4/issues/3787#issuecomment-2137265455)
