### ISSUE TITLE
server out of sync with file when editing imports on Windows

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean4#3787]
### Description

On Windows, the following steps reliably cause the server to go out of sync with the file. This issue is not reproducible on Linux.

### Context

[Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Server.20out.20of.20sync.20with.20file)

### Steps to Reproduce

1. Download mathlib and its cache (I can reproduce on v4.2.0, but presumably also every other version)
2. Create a new file with the following contents, and wait until Lean has compiled the file
```
import Mathlib
#eval 1+1
```
3. Delete the first line all at once (e.g. with ctrl+X). On 2 separate Windows computers this does *not* cause a recompilation of the file
4. Type the letter `a` on the first line and wait until Lean shows an error
5. Remove the letter `a`. The error remains. The error remains even if you start typing new commands (e.g. `def foo := 1`), and the server is interpreting as a letter `a` floating somewhere in your file. It disappears once you write `import` again.

I experimented with importing less than `Mathlib`, and below a certain number of imports, this behavior seems to go away. (e.g. if we replace `import Mathlib` with `import Std`, then step 3 does cause a recompilation of the file.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/vscode-lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment]
The relevant code has been almost completely rewritten on master, it would be good to check if 4.8.0-rc1 still exhibits the behavior when it lands

**Comment by mhuisi** [comment]
@fpvandoorn Do you still encounter this issue on 4.8.0?

**Comment by fpvandoorn** [comment]
Yes, both this issue and #3786 still happen for me. In fact, with the steps described in this issue, both these behaviors can happen. I'm testing this now on Mathlib `826a3e67f2` (from yesterday), Lean version `4.8.0-rc2`. 

Executing steps 1-3 can lead now to one of the following three situations:
* The server doesn't recompile the file at all after step 3, and the behavior of steps 4-5 happens
* The server starts recompiling, but never stops. The yellow bars stay for many seconds (issue #3786)
* Sometimes we get the intended behavior: the server recompiles the file for <0.1 second, and the file behaves completely normally afterwards.

These behaviors seem to happen, and there is no clear pattern which of situation happens. If I take the file and repeatedly remove and add the import-line with uses of `ctrl+X` and `ctrl+V`, I can get all three outcomes on different iterations.

**Comment by mhuisi** [comment]
Ok, I can reproduce the outcome of step 5 on Windows as well.  I haven't seen the server eternally recompiling yet, though.
