### ISSUE TITLE
Unknown constant 'Lean.Elab.Term.elabNumLit' on Go to Definition

### ISSUE THREAD

**Issue by mhuisi** [leanprover/lean4#3789]
### Description

Use the following MWE and trigger Go to Definition at `<cursor>`:

```
#eval <cursor>1
```

This yields an error:
```
[Error - 11:37:43 AM] Request textDocument/definition failed.
  Message: unknown constant 'Lean.Elab.Term.elabNumLit'
  Code: -32603 
```

I would not expect an error here.

### Versions

Current nightly.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by semorrison** [comment]
On `leanprover/lean4:nightly-2024-04-21`, I'm just getting a pop-up "No definition found for '1'". Can anyone else reproduce?

**Comment by mhuisi** [comment]
> On `leanprover/lean4:nightly-2024-04-21`, I'm just getting a pop-up "No definition found for '1'". Can anyone else reproduce?

You get the popup, but you also get a server error under Output > Lean: Editor.
