### ISSUE TITLE
Shared library fails to build on macOS with Nix

### ISSUE THREAD

**Issue by lenianiva** [leanprover/lean4#3810]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

The lean4 nix flake fails to build on macOS:
```
error: builder for '/nix/store/v9bw3gi6w3zxxzp1xpcjvafcqpvnq0il-libInit_shared.drv' failed with exit code 1;
       last 3 log lines:
       > ld: warning: directory not found for option '-L/nix/store/7bgg3pmrhjm59sl1xfrd0b9ry94cd9l3-lean-bin-tools/lib/lean'
       > ld: unknown option: -Bsymbolic
       > clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
       For full logs, run 'nix-store -l /nix/store/v9bw3gi6w3zxxzp1xpcjvafcqpvnq0il-libInit_shared.drv'.
error: 1 dependencies of derivation '/nix/store/c7sp7q2fns3275i9b2da43dhrsr77qp5-lean.drv' failed to build
```

### Context

This occurs when using Lean in Nix.

### Steps to Reproduce

This has to be done on macOS
1. Clone revision `b4caee80a3dfc5c9619d88b16c40cc3db90da4e2`
2.Execute `nix build .#packages.x86_64-darwin.libInit_shared` (this takes a while since the error occurs at link stage)
3.Error shows up

**Expected behavior:**

Lean should build

**Actual behavior:**

Fails to build due to the above error

### Versions

Revision `b4caee80a3dfc5c9619d88b16c40cc3db90da4e2`

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by vleni** [comment]
I suspect its related to this in `nix/bootstrap.nix`:
```nix
      libInit_shared = runCommand "libInit_shared" { buildInputs = [ stdenv.cc ]; libName = "libInit_shared${stdenv.hostPlatform.extensions.sharedLibrary}"; } ''
        mkdir $out
        LEAN_CC=${stdenv.cc}/bin/cc ${lean-bin-tools-unwrapped}/bin/leanc -shared -Wl,-Bsymbolic \
          -Wl,--whole-archive -lInit ${leancpp}/lib/libleanrt_initial-exec.a -Wl,--no-whole-archive -lstdc++ -lm ${stdlibLinkFlags} \
          $(${llvmPackages.libllvm.dev}/bin/llvm-config --ldflags --libs) \
          -o $out/$libName
      '';
```
