### ISSUE TITLE
Can't elaborate (n + k : Int)

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean4#382]
```lean
variable (n k : Nat)
#check (n + k : Int) -- error: failed to synthesize instance HAdd ℕ ℕ ℤ
```

**Comment by tydeu** [comment]
I'm curious, is the plan for resolving this more complex than adding the following instance somewhere?
```lean
instance : HAdd Nat Nat Int :=
  {hAdd := fun n m => Int.ofNat (n + m)}
```

**Comment by dselsam** [comment]
Yes, the issue is more complex than simply adding this instance. The same issue appears for many triples and many heterogeneous operators. Also note that the third argument to heterogeneous classes are `outParam`.
