### ISSUE TITLE
certain tactics don't show term info on error

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean4#3831]
### Description

Some tactics with (elaboration) errors cause the terms to not have term info (jump to definition jumps to the tactic definition, mousing over the term shows the tactic doc string).

Example
```lean
import Lean
example : True := by
  apply Nat.add true
  --    ^^^^^^^^^^^^ jump to def jumps to incorrect position and hover is wrong
```

A tactic with the same behavior is `simp [Nat.add true]`. On the other hand `exact Nat.add true` and `refine Nat.add true` display the correct behavior: mousing over `Nat.add` shows its docstring and jumping to its definition jumps to `Nat.add` (not to `evalApply` or similar).

### Context

Probably this bug also causes the behavior seen in #3554

### Versions

`4.7.0-rc2`

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by kmill** [comment]
`simp` and `apply` are fixed in #5863 and #5862. I looked for other tactics that were using withoutErrToSorry or withoutRecover, but all I've noticed is `match` patterns need some work (reported in #5336).

If there are other tactics with this problem, please open new issues.
