### ISSUE TITLE
docstring for commands only shown with `import Lean`

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#3842]
Consider
```
inductive Foo where
```

There is no hover on `inductive`. That’s unfortuante, because someone wrote a nice docstring for that syntax, [as seen here](https://leanprover-community.github.io/mathlib4_docs/Lean/Parser/Command.html#Lean.Parser.Command.inductive).

It does show up with
```
import Lean
inductive Foo where
```

Maybe something has to be made built-in of sorts?

### Versions

4.7.0

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by nomeata** [comment]
It seems that somehow the docstring needs to be added to `builtinDocStrings`. Maybe via some attribute? But `Lean.Parser.Command.inductive` isn’t really a `builtin_term_parser` nor a `builtin_command_parser`, isn’t it?

**Comment by digama0** [comment]
The simplest fix there is to use an attribute IMO. But you could also try to derive the set of builtin parsers by traversing the definition of every `builtin_term_parser` and `builtin_command_parser`. Or maybe you can use the `infoFn` baked into the parser? Unsure if that data is usable in this context.
