### ISSUE TITLE
`autoImplicit` behaves differently in `def` vs `structure` field elaboration

### ISSUE THREAD

**Issue by hargoniX** [leanprover/lean4#3852]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description
In the following code the first definition fails while the second one succeeds:
```lean
def Broken (upper : Nat) (entrys : Array Nat) : Prop :=
  ∀ (hidx : idx < entrys.size), entrys[idx] < upper

structure NotBroken where
  upper : Nat
  entrys : Array Nat
  inv : ∀ (hidx : idx < entrys.size), entrys[idx] < upper
```
More precisely `Broken` complains about `idx` being an unknown variable (introducing it via `{idx : Nat}` fixes the error) while `NotBroken` `autoImplicit`ly introduces `idx`.

I think a user wouldn't expect a difference between the way that a `def` and a `structure` field are elaborated, they should either both fail or both succeed. In the presence of `set_option autoImplicit true` they should probably both succeed.

### Steps to Reproduce
1. Run the code
**Expected behavior:** I think either both should fail or both should work

**Actual behavior:** One fails, the other works

### Versions
"4.7.0"

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by leodemoura** [comment]
The behavior above is by design.
