### ISSUE TITLE
question: why wait for `initialized` is needed here?

### ISSUE THREAD

**Issue by alissa-tung** [leanprover/lean4#3904]
See https://github.com/leanprover/lean4/blob/1c20b5341956fb77fcf2c2601e64075e51d5f858/src/Lean/Server/Watchdog.lean#L1047

in some async language server implementation, for example, [async-lsp](https://docs.rs/async-lsp/latest/async_lsp/), client may response the `register_lean_watcher` request (`register_ilean_watcher`) before sending `initialized` notification. So the client side router should take care of the sequence of messages, first sending `initialized`, then response the `register_lean_watcher`

**Comment by mhuisi** [comment]
Thanks for the bug report. We should probably just send the watcher requests after the initialization dance is done so that this race condition cannot occur.
