### ISSUE TITLE
`

### ISSUE THREAD

**Issue by fpfu** [leanprover/lean4#3905]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

[Clear and concise description of the issue]

### Context

[Broader context that the issue occured in. If there was any prior discussion on [the Lean Zulip](https://leanprover.zulipchat.com), link it here as well.]

### Steps to Reproduce

1.
2.
3.

**Expected behavior:** [Clear and concise description of what you expect to happen]

**Actual behavior:** [Clear and concise description of what actually happens]

### Versions

[Output of `#eval Lean.versionString` or of `lean --version` in the folder that the issue occured in]
[OS version]

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by nomeata** [comment]
This looks like an accident. I’ll close this one, open a new issue if you want to try again.
