### ISSUE TITLE
Call hierarchy and recursion

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#3945]
The very useful Call Hierarchy feature shows recursive calls. I see how that can make sense, but I wonder if not counting the recursive calls as occurrences here would be better - the kind of infinite unfolding we can do here is maybe a bit silly:

![recursion](https://github.com/leanprover/lean4/assets/148037/e3006842-228c-4608-860a-522e0a37235c)

### Versions

0c9f9ab37a0b76249f3bcd0fe45a67e30f6b84c8

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by digama0** [comment]
I think this is standard behavior for Call hierarchy. It might be good to double check from other language plugins though.

**Comment by mhuisi** [comment]
Changing this is not planned for the foreseeable future.
