### ISSUE TITLE
Installation script for Linux/OSX/Windows 

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#395]
It should be as simple as the Rust installation script
https://www.rust-lang.org/tools/install
We should install `elan` too: https://github.com/kha/elan
We should also move `elan` to `leanprover`

**Comment by leodemoura** [comment]
I talked with @daanx yesterday. He has nice installation scripts for Koka
https://github.com/koka-lang/koka/tree/df177d5663dcaefb4c087458e6b6e6f5ae9e2a31/util

**Comment by Kha** [comment]
Anything it does that elan doesn't do/as nicely?

**Comment by Kha** [comment]
I see, it also auto-installs editor extensions. I opened https://github.com/leanprover-community/vscode-lean4/issues/20 for the reverse direction we had for Lean 3, which I think is the even nicer approach.

**Comment by leodemoura** [comment]
BTW, we should also move vscode-lean4 to leanprover. All components needed to implement a slick UX should be in leanprover.

**Comment by leodemoura** [comment]
> Anything it does that elan doesn't do/as nicely?

I think the main issue for us is that the process is not smooth on all platforms, and there are multiple steps.

**Comment by leodemoura** [comment]
> I see, it also auto-installs editor extensions. I opened [leanprover-community/vscode-lean4#20](https://github.com/leanprover-community/vscode-lean4/issues/20) for the reverse direction we had for Lean 3, which I think is the even nicer approach.

I like this approach too.

**Comment by farhatnadim** [comment]
Is this still open? I just installed lean4 via Vs Code on linux , windows and it works like a charm
