### ISSUE TITLE
`match_expr`'s parser catches semantic errors too early.

### ISSUE THREAD

**Issue by hargoniX** [leanprover/lean4#3989]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description
If we write
```lean
def foo (ty : Expr) : MetaM Expr :=
  match_expr ty with
  | Nat => sorry
```
This will fail to parse at sorry with
```
unexpected end of input; expected '|'
```
Furthermore something like this:
```
def foo (ty : Expr) : MetaM Expr :=
  match_expr ty with
  | Nat => sorry
  | BitVec n => sorry

#check Nat
```
Will throw the even more confusing error:
```
expected irrelevant
```
While it is clear that these are not valid `match_expr` as they need an `_ =>` case to be
valid, catching this type of stuff at the parser level seems a bit overzealous to me.
This should parse and then the elaborator should inform the user that they are doing
something wrong with a bit more context.

### Steps to Reproduce

1. Copy above code into live.lean-lang.org

**Expected behavior:** The parser should let this through in order for the elaborator to provide a clear error of what the user did wrong while defining their expression.

**Actual behavior:** The parser throws rather confusing syntax errors *after* the partial `match_expr`.

### Versions
"4.7.0"

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by leodemoura** [comment]
@hargoniX The second bad error message comes from here: https://github.com/leanprover/lean4/blob/master/src/Lean/Parser/Term.lean#L873
and should be easy to fix. Please go ahead and improve it. 

For the first error message, it worth discussing how to improve the parser error reporting. This issue is not specific to `match_expr`. It is a regular notation defined our parsing framework. @david-christiansen played with better error recovery, and may have ideas on how to improve things.

**Comment by Kha** [comment]
I agree with @hargoniX's analysis, constraints such as "must end with wildcard pattern" are better encoded in the elaborator than in the grammar
