### ISSUE TITLE
Parsing errors should be more clearly described as such.

### ISSUE THREAD

**Issue by hargoniX** [leanprover/lean4#3990]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description
If we experience a parsing error like in #3989 we should make it clear that the parser/syntax
is the failing component here. Errors like:
```
expected irrelevant
```
don't really tell an average user anything about the problem they are experiencing.

### Steps to Reproduce
See #3989 

**Expected behavior:** An error that makes it clear the parser/syntax is at fault instead of something like `expected irrelevant`

**Actual behavior:** `expected irrelevant`

### Versions
4.7.0

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by leodemoura** [comment]
@hargoniX Agreed. Please go ahead an improve the message.

**Comment by Kha** [comment]
Definitely that specific message should be improved, I would consider it a bug in that specific parser. I would not count that as evidence that people in general are confused about what is or isn't a parse error, or to which degree that distinction is relevant to them.
