### ISSUE TITLE
`set_option trace.compiler.ffi_accessors`

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#4041]
> Should we have a `set_option trace.compiler.ffi_accessors` option to dump [field ordering and accessor information] for user structures?

_Originally posted by @eric-wieser in https://github.com/leanprover/lean4/pull/3915#discussion_r1585705089_

**Comment by leodemoura** [comment]
Thank you for your suggestion regarding the `trace.compiler.ffi_accessors` option to dump field ordering and accessor information for user structures. 
After consideration, we have decided not to implement this feature. The primary reasons are as follows:

1. **Internal Detail**: The field ordering and accessor information pertain to internal details of the Lean compiler. Most users typically do not need to access or interact with this information directly. Therefore, adding such an option would not provide significant value to the broader Lean community.

2. **Potential for Change**: As we continue to improve and optimize the Lean code generator, these internal details are subject to change. We may reconsider implementing this kind of feature after we switch to the new compiler infrastructure and add support for non-uniform objects.Implementing this feature now exposes details that are subject to change as the underlying implementation evolves.

We currently aim to focus on features that have broad applicability and enhance the overall user experience.

**Comment by eric-wieser** [comment]
> The field ordering and accessor information pertain to internal details of the Lean compiler.
>
> Implementing this feature now exposes details that are subject to change as the underlying implementation evolves

For users of the FFI calling `@[export]`ed functions that return `structure`s, these implementation details are already exposed. Without the option to report on the structure layout, such users will have a much harder time adapting to layout changes. 

Is the current advise to not use the FFI in this way, and instead write wrappers as follows? 
```lean
structure Foo where bar : Bar

@[export foo_bar]
def Foo.bar' (f : Foo) : Bar := Foo.bar
```
