### ISSUE TITLE
`lake new` should generate a `lakefile.toml`, not a `lakefile.lean`

### ISSUE THREAD

**Issue by kim-em** [leanprover/lean4#4106]
Going forward, I hope we can think of `lakefile.lean` as a feature for expert users, who have complicated requirements, and that most people can and should be using a `lakefile.toml`.

With that in mind, I think `lake new` and `lake init` should create a `toml`.

(I think it would not be a bad idea for that `toml` to contain a comment line to the effect. "If you need dynamic features only possible with a `lakefile.lean` <link to docs explaining these>, use `lake translate-config lean` to convert this `lakefile.toml` into a `lakefile.lean`.")

**Comment by damienstanton** [comment]
What is the correct syntax to generate a new project using `toml`? The docs suggest

> For example, instead of using a Lean configuration file for this package, one could produce a TOML version via `lake new hello .toml`.

But that doesn't actually work.

```shell
lake new hello .toml
# error: unknown package template `.toml`
```

If I use one of the templates visible in the help --say, `math`-- it still doesn't work.
```shell
lake new hello math .toml
# error: unexpected arguments: .toml
```

As a new user coming to Lean from Agda, this does indeed feel like a paper-cut :)

**Comment by tydeu** [comment]
@damienstanton

> If I use one of the templates visible in the help (say, `math`) it still doesn't work.
> 
> ```shell
> lake new hello math .toml
> # error: unexpected arguments: .toml
> ```
> 
> As a new user coming to Lean from Agda, this does indeed feel like a paper-cut :)

The `.timl` is an extension to the template name. Thus, one can use the TOML math template for a new package like so:

```
lake new hello math.toml
```

**Comment by damienstanton** [comment]
> @damienstanton Are you using an old version of Lean? TOML support was added in 4.8.0

Aha, this was it. Somehow my `elan` had not updated and I was only on 4.1.0. Updating to 4.10.0 now works and I can generate a new TOML-based project a la `lake new hello math.toml`.

Thanks all!

**Comment by semorrison** [comment]
@tydeu, is there anything blocking us from switching over the default? It feels like this should have happened several versions ago!

**Comment by tydeu** [comment]
@semorrison Yes, the plan was to switch to a TOML default after Mathlib can move to it. I am hoping to implement the last major missing feature (#2582 / #2752) this month.

**Comment by semorrison** [comment]
I don't think Mathlib need be a blocker. We are rapidly accumulating projects out there that are unnecessarily using `lakefile.lean` rather than `lakefile.toml`.
