### ISSUE TITLE
Omega builds illegal proof term containing pos_pow_of_pos 

### ISSUE THREAD

**Issue by bollu** [leanprover/lean4#4138]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

Consider the MWE ([lean playground link here](https://live.lean-lang.org/#project=lean-nightly&code=%2F-%0Aapplication%20type%20mismatch%0A%20%20Int.pos_pow_of_pos%0Aargument%20has%20type%0A%20%20Int%0Abut%20function%20has%20type%0A%20%20%E2%88%80%20%7Bn%20%3A%20Nat%7D%20(m%20%3A%20Nat)%2C%200%20%3C%20n%20%E2%86%92%200%20%3C%20n%20%5E%20m%0A-%2F%0Atheorem%20omega_fail%0A%20%20(n%20%3A%20Nat)%0A%20%20(i%20%3A%20Int)%0A%20%20(h2n%20%3A%20(2%20%3A%20Int)%20%5E%20n%20%3D%20%E2%86%91((2%20%3A%20Nat)%20%5E%20(n%20%3A%20Nat)))%0A%20%20(hlt%20%3A%20i%20%25%202%20%5E%20n%20%3C%202%20%5E%20n)%20%3A%20%202%20%5E%20n%20%E2%89%A0%200%20%3A%3D%0A%20%20by%20omega%20%2F-%20No%20goals%20-%2F%0A)):
```lean
/-
application type mismatch
  Int.pos_pow_of_pos
argument has type
  Int
but function has type
  ∀ {n : Nat} (m : Nat), 0 < n → 0 < n ^ m
-/
theorem omega_fail
  (n : Nat)
  (i : Int)
  (h2n : (2 : Int) ^ n = ↑((2 : Nat) ^ (n : Nat)))
  (hlt : i % 2 ^ n < 2 ^ n) :  2 ^ n ≠ 0 :=
  by omega /- No goals -/
```

Omega builds an incorrect proof term for this goal state.

### Context

Occurred when proving bitblasting theorems. 

### Steps to Reproduce

**Expected behavior:** Omega should succeed without an illegal proof.

**Actual behavior:** Omega builds an illegal proof term.

### Versions

```
Live lean version: "4.9.0-nightly-2024-05-11"
```

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by semorrison** [comment]
Thanks! Fixed in #4141.
