### ISSUE TITLE
Allowing adding `testRunner = true` to a `lean_lib` in `lakefile.toml`.

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#4142]
Aesop uses a library `AesopTest` as its test suite. It would be nice to have a way to tell `lake test` about this!

(This is better, I think, than the "pile of lean files + custom exe test runner" approach.)

See [zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/lake.20test) discussion.

**Comment by JLimperg** [comment]
Advantages of this approach:

- Perfectly incremental tests.
- Tests which need to import other test files (e.g. anything involving `initialize`) are supported without any effort.

Disadvantages:

- `AesopTest` library is 'accidentally' available publicly.
- No support for intentionally failing files or golden tests (but `guard_msgs` suffices for all my use cases).

**Comment by semorrison** [comment]
Noting that `ProofWidgets.Demos` is effectively another "library as test suite" in the wild.

**Comment by semorrison** [comment]
> * Tests which need to import other test files (e.g. anything involving `initialize`) are supported without any effort.

Note that Batteries has `Batteries/Test/Internal/DummyLabelAttr.lean` specifically to jump through this hoop that a test file can't import another test file.

**Comment by semorrison** [comment]
> * `AesopTest` library is 'accidentally' available publicly.

I've created an issue for this at #4168.

**Comment by nomeata** [comment]
It’s also the natural idiom I have been using for all my little libraries.
