### ISSUE TITLE
Add JavaScript-like record syntax.

### ISSUE THREAD

**Issue by DanielFabian** [leanprover/lean4#415]
How hard / easy would it be to have convenience syntax for this case:
```lean
  return { params := params
           motives := motives
           witness := witness
           indHyps := indHyps }
```
written as
```lean
  return { params
           motives
           witness
           indHyps }
```
or, for this case then:
```lean
  return { params, motives, witness, indHyps }
```
I find myself writing it often enough that I miss this JavaScript syntax.

**Comment by Kha** [comment]
The best syntax @leodemoura and I could come up that does not overlap with set notation was
```
{ := params, := motives, := witness, := indHyps }
```

**Comment by DanielFabian** [comment]
Personally, I'd be happy with it, since it's quite compact. I don't care too much about the concrete syntax rather than just not liking to write `xxx := xxx`. That's all.

**Comment by leodemoura** [comment]
> The best syntax @leodemoura and I could come up with that does not overlap with set notation was
> 
> ```
> { := params, := motives, := witness, := indHyps }
> ```

Yeah, I recall that we were not very happy with this syntax.

BTW, the support for overloading notation in Lean 4 is more robust. in the following example, I have overloaded it and it works reasonably well. 
```lean
import Lean

def Set (α : Type u) : Type u :=
  α → Prop

def Set.empty : Set α :=
  fun a => False

def Set.insert (s : Set α) (a : α) : Set α :=
  fun x => x = a ∨ s a 

syntax (name := finSet) "{" term,* "}" : term

syntax (name := jsSet) "{" ident,* "}" : term

macro_rules (kind := finSet)
  | `({ $as,* }) => do
     as.getElems.foldlM (init := ← `(Set.empty)) fun s a => `(Set.insert $s $a)

#check { 1, 2, 3 }

macro_rules (kind := jsSet)
  | `({ $[$is],* }) => do
     let fields ← is.mapM fun i => 
       `(Lean.Parser.Term.structInstField| $i:ident := $i:ident)
     `({ $[$fields:structInstField]* })

structure S where
  x : Nat
  b : Bool

def f (x : Nat) (b : Bool) : S :=
  let r := { x, b } -- expected type is not known here
  r

#print f

#check { 1, 2, 3 }

#check { true }

def g (s : S) : S :=
  { s with b := false }

#check fun x b => g { x, b } 
#check fun x b => g <| id { x, b } 
#check fun x b => 
  let aux := id { x, b }
  g aux
```
The main drawback is confusing error messages. 
However, mathlib users can avoid this issue by using a higher priority for the Set notation.
