### ISSUE TITLE
`lake build --require-silence`

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#4195]
Many libraries require via CI that there is no output (e.g. to detect stray `#check`, or worse). Currently this is done by various adhoc methods piping output into fragile shell scripts.

I'd like a `lake build --require-silence` that errors if any build job writes to stdout or stderr.

I'm happy if this is a synonym for something in a more generic family (e.g. like the existing --wfail, turning warnings into failures), but I would like if the name is indicates the user intent (i.e. not `--ifail`).

**Comment by nomeata** [comment]
The name is a bit odd, it wasn't clear to me if it might mean “seriously try hard to hide output”. `--error-on-output` or `--check-no-output` maybe? 🚲🏚️

**Comment by tydeu** [comment]
Oh, I did not notice you had written this issue. I (sadly?) already addressed this in #4127 with the name `--iofail`. What do you think of that name? It is a bit clearer than `--ifail`, but maybe not enough?

**Comment by semorrison** [comment]
It'll do!
