### ISSUE TITLE
RFC: merging the notions of `outParam` and `semiOutParam`

### ISSUE THREAD

**Issue by JovanGerb** [leanprover/lean4#4225]
### outParam and semiOutParam

`outParam` and `semiOutParam` do mostly the same thing, with some subtle differences. This can lead to a difficult choice about which one to pick, or even to code duplication, having two copies of the same type class, one with an `outParam` and one with a `semiOutParam` (`MonadState`/`MonadStateOf`, `MonadExcept`/`MonadExceptOf`, etc.). I propose a mix of these (I'll call it a `mixParam` for now) that has the best of both worlds.

During type class resolution, `outParam` arguments are completely ignored, and after the synthesis it is checked that the synthesised arguments match what was there originally. On the other hand, `semiOutParam` arguments behave the same as normal arguments.

The advantage of `outParam`s is that they can instantiate metavariables during synthetisation. For example in
```
def .. := do
   let s <- get
  ...
```
The type of `s` is inferred without having to consider the `...` part. This comes at the cost of being able to only synthesize one possible type for `s`, even if some different type is given via a type annotation.

### Proposal

What I suggest is a `mixParam`, which behaves like a `semiOutParam` when there are no metavariables. If there are assignable metavariables in the parameter, then the depth of these metavariables will be increased to the new metavariable level, making them assignable during type class synthesis, and forcing them to be assigned.

This has the best of both worlds. Let's compare:
- `semiOutParam` vs `mixParam`: whenever the synthesis with `semiOutParam` succeeds, it will also succeed with `mixParam`, but `mixParam` works better when there are metavariables. 
- `outParam` vs `mixParam`: most of the time, whenever the synthesis with `outParam` succeeds, it will also succeed with `mixParam`. If we assume that `isDefEq` always succeeds when it can, then this holds, but unification is more difficult when there are higher order metavariables (metavariables that are functions applied to arguments). However, this is an edge case that shouldn't be relied on anyways. In cases where `outParam` fails to synthesize because it finds the wrong instance, `mixParam` will sometimes still succeed.
  Edit: if a metavariable appears in an `outParam` and in a normal parameter, then it is possible to instantiate it. For `mixParam`s, I would not allow this. I don't know of any real world examples of this, but an example would be the goal `MonadState ?s (StateT Nat (StateT ?s IO))`, where the `outParam` case would find the instance corresponding to the outer `StateT` that sets `?s := Nat`, and the `mixParam` algorithm would find the instance corresponding to the inner `StateT`.

### Benefits

If `outParam` and `semiOutParam` are replaced by this `mixParam`, it will make the code for classes such as `MonadState` simpler, and nicer to use. Simpler because there will be just one class instead of two. Nicer to use because for example, one could write `let s : Core.State <- get` inside of a `MetaM` monad, instead of `let s <- getThe Core.State`. Conversely for the function `set` which uses a `semiOutParam` to determine the state type, we will be able to write `set default`, and Lean will figure out the type of `default`.

Additionally, it removes the need for people to have to learn the difference between `outParam` and `semiOutParam`, which is beneficial for people learning Lean.

Edit: When the current value of an `outParam` has no instances, such as `HMul.hMul Nat Nat Int`, type class search will find the instance `HMul.hMul Nat Nat Nat` and then figure out that `Nat =/= Mul`. With a `mixParam` instead this case is immediately rejected, improving efficiency.

### Disclaimer

I assume this won't badly affect performance, but I don't know this for sure.

This will affect how coercions work in the presence of metavariables, and I don't know enough about coercions to know whether this could cause a problem or be beneficial.

If problems do appear, `mixParam` could replace one of `semiOutParam` and `outParam`, or even become a third kind of parameter.

### Community Feedback

This topic came up in a [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Ways.20to.20speed.20up.20Mathlib/near/439472458) discussion about whether some function had to have a `semiOutParam` or `outParam` instance argument.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by Kha** [comment]
I'm afraid this module is too sensitive as well for sudden external contributions. `semiOutParam` was introduced with great care by a long-time core developer. I wasn't involved directly but even without that deep knowledge I believe multiple angles are missing from the RFC description. As we do not see a way to acceptance of this RFC, I am closing it.
