### ISSUE TITLE
lake warning about the toml file references a non-existent lakefile.lean

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#4280]
e.g. in Aesop, I received the warning
```
warning: ././.lake/packages/batteries/lakefile.lean:24:2: warning: @[test_runner] has been deprecated, use @[test_driver] instead
```
But Aesop uses a `lakefile.toml`, so this warning is not actionable.

**Comment by tydeu** [comment]
@semorrison but that is warning for batteries, which does use `lakefile.lean`?

**Comment by semorrison** [comment]
Oh! You're right. I bumped the lean-toolchain in aesop before doing so in batteries, and hence saw the warning in the "wrong place". Sorry for the noise.
