### ISSUE TITLE
RFC: computations for the trace should only run when the trace option is true

### ISSUE THREAD

**Issue by JovanGerb** [leanprover/lean4#4282]
### Proposal

https://github.com/leanprover/lean4/blob/f05a82799a01569edeb5e2594cd7d56282320f9e/src/Lean/Meta/SynthInstance.lean#L402-L403

https://github.com/leanprover/lean4/blob/f05a82799a01569edeb5e2594cd7d56282320f9e/src/Lean/Meta/SynthInstance.lean#L604-L608

These are examples of computations that are only used for trace messages, but are always computed, which is unnecessary and inefficient. I propose to only execute them inside of the trace. This can be done using `traceM` in the first example, and in the second one by simply replacing `goal` and `subgoal` by their definition.

PS is it possible to show multiple lines of the code automatically? The link is unreadable without clicking the link

closed by #4277

**Comment by nomeata** [comment]
> PS is it possible to show multiple lines of the code automatically? The link is unreadable without clicking the link

Try this: 

https://github.com/leanprover/lean4/blob/f05a82799a01569edeb5e2594cd7d56282320f9e/src/Lean/Meta/SynthInstance.lean#L403-L405
