### ISSUE TITLE
RFC: `instantiateMVars` is unnecessary to use in trace messages.

### ISSUE THREAD

**Issue by JovanGerb** [leanprover/lean4#4283]
### Proposal

Trace messages automatically come with the current `MetavarContext`, so there is no need to also call `instantiateMVars`. For example:
https://github.com/leanprover/lean4/blob/f05a82799a01569edeb5e2594cd7d56282320f9e/src/Lean/Meta/SynthInstance.lean#L374
https://github.com/leanprover/lean4/blob/f05a82799a01569edeb5e2594cd7d56282320f9e/src/Lean/Meta/SynthInstance.lean#L415-L417

In the second example, `abstractMVars` also doesn't need `instantiateMVars`, because it already runs it on its input, so here instantiating metavariables is also redundant.

This also appears twice in this file:

https://github.com/leanprover/lean4/blob/f05a82799a01569edeb5e2594cd7d56282320f9e/src/Lean/Elab/Match.lean#L1152

**Comment by Kha** [comment]
Closing as per reasoning in the PR

**Comment by nomeata** [comment]
Small addendum, in case someone stumbles over this: The `Lean.Expr` data type has a computed field (`Lean.Data`) that stores whether the expression has `MVars`, so an extra `instantiateMVar` is very cheap and usually not worth the bother to fret about.
