### ISSUE TITLE
simp tries using the forward version of user-specified backward theorems

### ISSUE THREAD

**Issue by YaelDillies** [leanprover/lean4#4290]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

In Lean 3 (at least, Lean 3 community version), `simp [<- thm]` would automatically remove "forward `thm`" from the local list of simp lemmas. In Lean 4, it doesn't, meaning that `simp [<- thm]` is (mostly) doomed to fail if `thm` is a simp lemma.

### Context

Personally I don't know how this issue has stayed unreported for so long. It keeps on happening to me ([latest one in date](https://github.com/leanprover-community/mathlib4/pull/12551#discussion_r1615577611)) and is a major blocker to using simp in moderately complicated situations.

### Steps to Reproduce

The following code
```
def foo : Nat := 0
def bar : Nat := 0

@[simp] theorem foo_eq_bar : foo = bar := rfl

example : foo = bar := by simp [← foo_eq_bar]
example : foo = bar + 1 := by simp [← foo_eq_bar]
```

**Actual behavior:** throws
```
tactic 'simp' failed, nested error:
maximum recursion depth has been reached
```
on both nightly and `4.8.0-rc2`. I believe it works on every previous Lean 4 version but I haven't tried specifically.

**Expected behavior:** is expected to close the first `example` and leave the second `example` as `⊢ bar = bar + 1`

I have included both examples because sometimes simp sneakily avoids the loop by performing a further simplification. Here it does seem to fall into the loop before it gets to try reflexivity.

### Versions

4.9.0-nightly-2024-05-25 on live.lean-lang.org

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by semorrison** [comment]
> Personally I don't know how this issue has stayed unreported for so long.

Partly on you, I guess! :-) We rely on users making bug reports here.

But yes, I agree this is a usability improvement that we can hopefully implement soon.

**Comment by YaelDillies** [comment]
Sometimes the issues feel so big that you don't even bother checking the issue tracker because it has to be that someone has already reported it 🙃

Telltale for myself, I guess.

**Comment by YaelDillies** [comment]
Thanks for the quick turnaround!

**Comment by YaelDillies** [comment]
This seems to not have been fixed entirely. Consider the following MWE:
```
def foo (n : Nat) : Nat := 0
def bar (n : Nat) : Nat := 0

@[simp] theorem foo_eq_bar (n : Nat) : foo n = bar n := rfl

-- works just fine since this issue was resolved
example (n : Nat) : bar n = sorry := by simp [← foo_eq_bar]

-- still runs in a loop
example (n : Nat) : bar n = sorry := by simp [← foo_eq_bar n]
```
Somehow, simp doesn't detect I'm making it rewrite `foo_eq_bar` backwards because I've provided an argument to it.

**Comment by kmill** [comment]
I'd say that is a different issue, and in particular you're now asking for a new feature.

`simp` treats constants specially. It does not see `foo_eq_bar n` as having anything to do with `foo_eq_bar`, because once the term isn't just a constant, it goes through an elaboration process.

It seems reasonable, but there are a number of questions. The first that come to mind:
- if you have `simp [foo_eq_bar n]`, should that erase the generic `foo_eq_bar`?
- if you have `simp [← fun n => foo_eq_bar n]` should that erase `foo_eq_bar`? (Why I ask: simp abstracts metavariables, so it would have to process lambdas. The question is "should simp detect the lemma to erase syntactically or post-elaboration".)
- would you be surprised if `simp [← id foo_eq_bar n]` erased `id`, if `id` were marked with `@[simp]`?
