### ISSUE TITLE
RFC: lake run has no output results

### ISSUE THREAD

**Issue by whsm** [leanprover/lean4#4293]
When I run "lake run", there is no output. When I run "lake run projectexe", I get the error "error: unknown script projectexe". What should I do?My project version is leanprover/lean4:v4.8.0-rc2.
![2](https://github.com/leanprover/lean4/assets/33314971/565f2108-0c4f-4b4f-8c0b-23a265400183)

**Comment by hargoniX** [comment]
As `lake run --help` says `lake run` is not for running executables but rather lake scripts. The command you are looking for is `lake exe`, alternatively you can run the binary directly from the `.lake/bin` folder. For more information on scripts etc. refer to the lake README: https://github.com/leanprover/lean4/blob/master/src/lake/README.md
