### ISSUE TITLE
`lake` sometimes fails, only reporting an inscrutable `git` message

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#4302]
I've seen two users this week stumped by something like 
```
% lake build
info: stderr:
fatal: Needed a single revision
error: external command 'git' exited with code 128
```
This is essentially unactionable, particularly for users who neither know that lake is using `git` under the hood to manage dependencies (ideally the majority!) and for users who are new to `git`. In both cases I saw this it prevented the user from proceeding until an expert was available to help.

`lake` needs to catch git errors, and provide more context and clues about what to do next. e.g. I would like to see something like:

```
% lake build
error: while `lake` was checking whether dependencies are up to date, `git` generated an error:
  fatal error: ...
  git exited with code 128
To resolve this, you could try the command again (in case the underlying cause was a transient network error), or remove the `.lake` directory and run the command again.
```
Even that error message is going to leave many users in an unusable state, because for anyone downstream of Mathlib we need to tell them to run `lake exe cache get` again after deleting `.lake`. But baby steps would still help!

**Comment by nomeata** [comment]
Maybe also include the actual git command in the error message, helps understanding and debugging.

**Comment by semorrison** [comment]
Another user hitting this: https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/can't.20run.20lake.20update.20on.20a.20new.20project/near/443600888

**Comment by tydeu** [comment]
@semorrison I was taking a look at this today and some questions came up. Do you remember what the source of this particular error was (or some info in that vein)? While I am improving the text of the error,  the fact that this particular errored occurred at all is quite surprising. The part of the code that can produce this error is not something that is expected to generally be able to fail (unless one of the git checkouts becomes corrupted somehow). Thus, it breaking may be a bug itself.

**Comment by alexkeizer** [comment]
I recently ran into this error again (although the specific exit code was different; `error: external command 'git' exited with code 1`, I believe) with a student I'm helping.

The root cause here was that they'd modified the files in one of their dependencies directly in the .lake folder, which of course caused problems when trying to `lake update`.

**Comment by drhodes** [comment]
Another report :D 

I have a lakefile with mathlib requirement

```lean
require mathlib from git "https://github.com/leanprover-community/mathlib4" @ s!"d9fb4896ee40028f40ce4a90dc0d87cf8fea2208"
```

Performing an update with `$ lake update mathlib` yields,

`info: Qq: updating repository '././.lake/packages/Qq' to revision '44f57616b0d9b8f9e5606f2c58d01df54840eba7'
error: external command 'git' exited with code 128`

----

So, what does `strace` say?


`$ strace lake update mathlib`

```
...
read(5, "fatal: reference is not a tree: "..., 4096) = 73
...
write(2, "\33[1;34minfo:\33[m Qq: updating rep"..., 119info: Qq: updating repository '././.lake/packages/Qq' to revision '44f57616b0d9b8f9e5606f2c58d01df54840eba7'
) = 119
write(2, "\33[1;31merror:\33[m external comman"..., 61error: external command 'git' exited with code 128
....
+++ exited with 1 +++
```

`git` is failing with: `fatal: reference is not a tree:` with regards to the `package Qq` hash `44f57616b0d9b8f9e5606f2c58d01df54840eba7`

Somehow that hash got into the `Qq` entry of mathlib's `lake-manifest.json` in at revision `d9fb4896ee`

So I checked the Qq repo, manually plugging the hash at the end of this URL.

`https://github.com/leanprover-community/quote4/commit/44f57616b0d9b8f9e5606f2c58d01df54840eba7`

Something interesting. Github reports that:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
