### ISSUE TITLE
RFC: Allow to replace goal to arbitrary type when goal is represented by an axiom

### ISSUE THREAD

**Issue by lovely-error** [leanprover/lean4#4316]
Agda has one wonderful feature named [rewrite rules](https://agda.readthedocs.io/en/latest/language/rewriting.html)

It allows to rewrite `postulate`s (`axiom`s in lean) by arbitrary terms 

Example
```agda
open import Agda.Builtin.Equality
open import Agda.Builtin.Equality.Rewrite

postulate equiv : {A B : Set} -> A -> B -> Set

postulate fext : {A B : Set}(f : A -> B)(h : A -> B) -> (equiv f h) ≡ (∀ (a : A) -> f a ≡ h a)
{-# REWRITE fext #-}

id1 : {T : Set} -> T -> T
id1 v = v
id2 : {T : Set} -> T -> T
id2 v = v

test16 : {T : Set} -> equiv (id1 {T}) (id2 {T})
test16 = λ i -> refl
```
The code above is accepted by agda.

If I try to do similar thing in lean it sorta works 
```lean
axiom equiv {A B:Type} : A -> B -> Type

def fext_impl : (A : Type) -> (B : Type) -> (A -> B) -> (A -> B) -> Prop := 
  fun A _ f h => (i:A) -> f i = h i

elab "fext" : tactic => do
  Elab.Tactic.withMainContext do
    let goal_ix <- Elab.Tactic.getMainGoal
    let goal <-  goal_ix.getType'
    let (lt, rt, l, r) <- match goal with
      | .app (.app (.app (.app (.const `equiv []) lt) rt) l) r => pure (lt,rt,l, r)
      | _ => throwTacticEx `fext goal_ix "Invalid goal type"
    let s <- saveState
    let same <- isDefEq lt rt
    if same then do
      let (lt, rt) <- match Expr.arrow? lt with
      | .some ts => pure ts
      | .none => throwTacticEx `fext goal_ix "given item is not a function"
      let eq := .app (.app (.app (.app (.const `fext_impl []) lt) rt) l) r
      let eq <- reduceAll eq
      let goal <- MVarId.change goal_ix eq false
      Elab.Tactic.setGoals [goal]
    else
      restoreState s
      throwTacticEx `fext goal_ix "Given functions differ in types"

def id1 : A -> A := fun i => i
def id2 : A -> A := fun i => i

example : (T:Type) -> equiv (@id1 T) (@id2 T) := fun T => by
  fext
  intro i
    /- tactic state
    T : Type
    i : T
    ⊢ i = i
    -/
  -- rfl -- (HERE)
```

The state after applying `fext` is what is expected to be, but if I uncomment HERE, lean reports an error
```
application type mismatch
  id ⋯
argument has type
  ∀ (i : T), i = i
but function has type
  equiv id1 id2 → equiv id1 id2
```

It seems to me that [this code](https://github.com/leanprover/lean4/blob/fe17b82096bf4825d83a36f220d79a6dadebf5c8/src/Lean/Meta/Tactic/Replace.lean#L43) is to blame.

It has to be changed to match behaviour of agda, that is

`Allow to replace goal to arbitrary type when goal is represented by an axiom`

**Comment by nomeata** [comment]
Thanks for the report. There is a lot of meta code, and it's not clear to me if the issue you would like to report cannot be minimized further, e.g. to rule out a simple bug in the meta code producing ill-typed expressions.

Can you replace your tactic invocation with `refine`? Maybe `show_term` can help with that? If not, then why?

**Comment by nomeata** [comment]
Also I see two postulates in the agda code, and an confused that your lean equivalent doesn't have two. What happened to `postulate fext`?
