### ISSUE TITLE
Regression of `simp`

### ISSUE THREAD

**Issue by cyberglot** [leanprover/lean4#4326]
### Description
`by simp` can no longer prove simple propositions that it was able to in previous versions.

### Context
In the "Functional Programming in Lean" book, the first example in the [section "Connectives" of "Interlude: Propositions, Proofs, and Indexing"](https://lean-lang.org/functional_programming_in_lean/props-proofs-indexing.html#connectives) cannot be proved with `by simp`.

[Mastodon discussion with Andrew Helwer](https://cyberglot.lol/@april/112547977573067773), where he shows how the example used to work on lean4-4.2.0.

### Steps to Reproduce

```lean
def onePlusOneIsTwo : Prop := 1 + 1 = 2
theorem OnePlusOneIsTwo : onePlusOneIsTwo := rfl

def stringAppend : Prop := "Str".append "ing" = "String"
theorem StringAppend : stringAppend := rfl

theorem addAndAppend : onePlusOneIsTwo ∧ stringAppend := by simp

theorem addAndAppend2 : 1 + 1 = 2 ∧ "Str".append "ing" = "String" :=
  And.intro rfl rfl

theorem addAndAppend3 : 1 + 1 = 2 ∧ "Str".append "ing" = "String" := by simp
```
**Expected behavior:** Program is checked, no errors.

**Actual behavior:** 
Error message is shown:
```
Messages below (2)
7:60: 
simp made no progress
12:69: 
unsolved goals
⊢ "Str".append "ing" = "String"
```

### Versions

**Lean version** `version 4.9.0-nightly-2024-06-02, x86_64-apple-darwin22.6.0, commit 81f5b07215b0` 
(originally found in `version 4.7.0, x86_64-apple-darwin21.6.0, commit 6fce8f7d5cd1`)
**elan version** elan 3.1.1
**OS version** macos Sonoma 14.4.1 (23E224) ([also on nix](https://discuss.systems/@ahelwer/112548539635475463))

### Impact

Regression breaks an example from one of the main Lean books.

**Comment by Kha** [comment]
This is leanprover/fp-lean#137
