### ISSUE TITLE
`class abbrev` issues

### ISSUE THREAD

**Issue by tydeu** [leanprover/lean4#436]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The `class abbrev` command bugs out in many areas.

### Steps to Reproduce

Using `class abbrev` with an explicit predefined variable errors:

```lean
universe u
variable (A : Type u)
class abbrev AddAbbrev := Add A
/-
  type expected
  failed to synthesize instance
    CoeSort (Type ?u.22 → Type ?u.22) ?m.25
-/
```

It also errors with an implicit predefined variable:

```lean
universe v
variable {A : Sort v}
class Bar (A : Sort u) (f : A -> Prop) := (bar : (a : A) -> f a)
class abbrev BarAbbrev (f : A -> Prop) := Bar A f
/-
  type expected
  failed to synthesize instance
    CoeSort (Type ?u.22 → Type ?u.22) ?m.25
-/
```

Surprisingly, though, moving the implicit binder into the definition also causes an error:

```lean
universe u
class Foo (A : Sort u) (f : A -> Prop) := (foo : (a : A) -> f a)
class abbrev FooAbbrev {A : Sort u} (f : A -> Prop) := Foo A f
/-
function expected at
  { toFoo := ?m.58 }
term has type
  FooAbbrev ?m.57
-/
```

**Expected behavior:**

I expect `class abbrev` to support implicit (and synthesized) binders, both within the definition and predefined with `variable`. I don't really expect explicit predefined binders to work though.

### Versions

I am running the latest Lean nightly at the time of writing:
```
Lean (version 4.0.0-nightly-2021-05-03, commit 0f8c6ca797c4, Release)
```

I am on a Windows 10 20H2 machine.

### Additional Information

I knew why the implicit (an explicit) predefined binders didn't work  -- it is because the `class abbrev` macro uses explicit application of its type and constructor in its expansion. I had in mind a fix for the implicit case, but I discovered more oddities along the way. However, **I still would like to tackle some of this myself**.

**Comment by tydeu** [comment]
I just overhauled my outline of the issue. I realized that my original minimum working example was not actually a good example of the bug I was interested in (I care about implicit predefined binders, not explicit ones). I also realized that `class abbrev` failed more often then I expected. So this issue is has a bit broader scope than I initially anticipated. Apologies for the confusion.

**Comment by leodemoura** [comment]
> I still would like to tackle some of this myself.

Thanks for making it clear you want to work on this issue before submitting a PR.

This feature is not heavily used in the codebase nor it has many tests. 

You will be grateful if you fix the bug, but here are our expectations since you are new:

- Plenty of tests. This is particularly important for this issue since the feature is not heavily used in the codebase nor it has many tests. 
- Comment anything nontrivial
- Do not guess the design, ask questions in case of doubt
- Make sure we can still build Lean after the fix: `make stage2`
