### ISSUE TITLE
Better Error Message for using lean4 with lean vscode plugin

### ISSUE THREAD

**Issue by jldodds** [leanprover/lean4#438]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Starting up with Lean I accidentally grabbed the Lean vscode plugin instead of the Lean4 one. Ideally the error message would guide me towards fixing my mistake:

```
Watchdog error: Cannot read LSP request: Invalid header field: {"command":"sync","file_name":"/home/joey/Lean-Test/test.lean","content":"","seq_num":0}
```

### Steps to Reproduce

1. Install Lean4
2. Install lean vscode plugin (not lean4)

**Expected behavior:** [What you expect to happen]

Ideally either the lean4 server tells me the lean plugin tried to talk to it, or the lean plugin realizes it was used with lean4

**Actual behavior:** [What actually happens]

```
Watchdog error: Cannot read LSP request: Invalid header field: {"command":"sync","file_name":"/home/joey/Lean-Test/test.lean","content":"","seq_num":0}
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
always

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

Lean (version 4.0.0-m2, commit 26dda3f63d88, Release) - windows 10, wsl2

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Kha** [comment]
> or the lean plugin realizes it was used with lean4

I would definitely prefer that :) . Could you file an issue at https://github.com/leanprover/vscode-lean?

**Comment by jldodds** [comment]
Done: https://github.com/leanprover/vscode-lean/issues/264
