### ISSUE TITLE
More binder cache issues

### ISSUE THREAD

**Issue by tydeu** [leanprover/lean4#439]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Implicit binders can magically disappear during function coercion.

### Steps to Reproduce

```lean
universe u

structure Fn (E I : Sort u) := (exp : E) (imp : I)
instance (E I : Sort u) :  CoeFun (Fn E I) (fun _ => I) := {coe := fun K => K.imp}

class Bar.{w} (P : Sort u) := 
  fn : P -> Sort w

variable {P : Sort u} (B : Bar P)
variable (fn : Fn ((p : P) -> B.fn p) ({p : P} -> B.fn p))
#check coeFun fn -- Result is as expected (implicit)
/-
  fn : {p : P} → Bar.fn p
-/

variable (p : P)
variable (Bp : B.fn p)
#check fn Bp -- Errors unexpectedly
/-
application type mismatch
  Fn.imp fn Bp
argument
  Bp
has type
  Bar.fn p : Sort ?u.635
but is expected to have type
  P : Sort u
-/

#check fn p -- Works unexpectedly
/-
  Fn.imp fn p : Bar.fn p)
-/
```

Also note that the `Fn.imp fn p` in the last `#check`  message of the above example is ill-formed:
```lean
#check Fn.imp fn p -- Errors
/-
function expected at
  Fn.imp fn ?m.980
term has type
  Bar.fn ?m.980
-/
```

### Versions

Windows 10 20H2
`Lean (version 4.0.0-nightly-2021-05-05, commit 7398db5f3fe9, Release)`

### Additional Information

This is a continuation of the chain of binder/cache issues discussed here: https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Binder.20bug.3A.20Binder.20not.20being.20properly.20preserved.3F

**Comment by leodemoura** [comment]
Yes, this bug is due to another instance of the binder cache issue.
Could you please confirm that the expected behavior is the following one?
```lean
#check coeFun fn -- Result is as expected (implicit)
/-
  fn : {p : P} → Bar.fn p
-/
variable (p : P)
variable (Bp : Bar.fn p)
#check fn Bp 
/-
 error: function expected at
  Fn.imp fn ?m.710
term has type
  Bar.fn ?m.710
-/
#check fn p
/-
error: function expected at
  Fn.imp fn ?m.811
term has type
  Bar.fn ?m.811
-/
#check fn (p := p)
/-
Fn.imp fn p : Bar.fn p
-/

```

**Comment by tydeu** [comment]
@leodemoura Given how I wrote the example, yeah that is actually what should be expected. I accidently simplified my original example so much that `#check fn Bp` is actually invalid. Here is a better example:

```lean
variable (fn' : Fn ((p : P) -> B.fn p -> B.fn p) ({p : P} -> B.fn p -> B.fn p))

-- Expect no error
#check fn' Bp

-- Expect error
#check fn' p
```
