### ISSUE TITLE
The test leanlaketest_old times out on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [leanprover/lean4#4396]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

```
2001/2001 Test #1991: leanlaketest_old ..........................................***Timeout 1500.01 sec
```

### Context

[Broader context that the issue occured in. If there was any prior discussion on [the Lean Zulip](https://leanprover.zulipchat.com), link it here as well.]

### Steps to Reproduce

Regular tests

### Versions

4.8.0

FreeBSD 14.1

**Comment by Kha** [comment]
Unfortunately, FreeBSD is not on our list of supported platforms and there are no plans to change that
