### ISSUE TITLE
pp.instantiateMVars false does not seem to work

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#4406]
Consider

```
import Lean.Elab.Command
open Lean Meta

run_meta do
  let mvarId ← mkFreshExprMVar (.some (.const ``Nat []))
  mvarId.mvarId!.assign (mkNatLit 0)
  withOptions (pp.instantiateMVars.set · false) do
    logInfo m!"{mvarId}"
```
or
```
import Lean.Elab.Command
open Lean Meta

set_option pp.instantiateMVars false in
run_meta do
  let mvarId ← mkFreshExprMVar (.some (.const ``Nat []))
  mvarId.mvarId!.assign (mkNatLit 0)
  logInfo m!"{mvarId}"
```

Both print `0` when I would have expected some form of `?m`.

The ability to print expressions without mvars instantiated is rarely needed, but it is quite relevant when debugging bad mvar assignments.

Respectfully pinging @kmill.

### Versions

4.10.0-nightly-2024-06-08

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by kmill** [comment]
The situation is that the first step of `Lean.ppExprWithInfos` is to instantiate mvars. (Note that the default value for `pp.instantiateMVars` is `false`!) I agree that it would be useful when debugging to see where there are mvars in expressions.

Maybe here's a plan:
1. set the default value of `pp.instantiateMVars` to `true`
2. find all main entry points to the pretty printer, and either delete any `instantiateMVars` that appear there, or move `instantiateMVars` to the `format`/backup case if present.

**Comment by nomeata** [comment]
That plan sounds very reasonable to me, thanks for the analysis.
