### ISSUE TITLE
`lean_exe` with `srcDir` duplicates build artifacts of `Main.lean` in two places

### ISSUE THREAD

**Issue by joneugster** [leanprover/lean4#4419]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

Using `srcDir` in a executable like
```
lean_exe my_command
  srcDir := "MyFolder"
  root := `Main
  [...]
```

causes the build artifacts of `Main` to be stored at `.lake/packages/MyPackage/.lake/build/lib/` instead of `.lake/packages/MyPackage/.lake/build/lib/MyFolder/` which has negativ implications:

* building `Main.lean` through another mean later (e.g. a `lean_lib`) will cause all built files to be duplicated, e.g. `Main.olean` and `MyFolder/Main.olean`
* It seems impossible to call  ``Lean.importModules `MyFolder.Main`` (or ``Lean.findOLean `MyFolder.Main``) unless `Main` is built through this second, separate mean.

### Context

[Minimalised Reproduction](https://github.com/joneugster/testSrcDir2)

[Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/making.20a.20lean.20executable.20available.20in.20a.20project/near/443792753)

### Steps to Reproduce

Follow the README of the [Minimalised Reproduction](https://github.com/joneugster/testSrcDir2) repo.

**Expected behavior:**

directly calling `lake exe testsrcdir` should succeed.

**Actual behavior:**

Instead one needs to call `lake build testSrcDir` first to build the second copy of `Main` before the command succeeds.

### Versions

v4.8.0

Linux, albeit probably not relevant

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by tydeu** [comment]
> causes the build artifacts of `Main` to be stored at `.lake/packages/MyPackage/.lake/build/lib/` instead of `.lake/packages/MyPackage/.lake/build/lib/MyFolder/` 

Yes this is the purpose of `srcDir` in an excutable -- to prevent Lake from including the `srcDir` as part of the module name.

> * building `Main.lean` through another mean later (e.g. a `lean_lib`) will cause all built files to be duplicated, e.g. `Main.olean` and `MyFolder/Main.olean`
> * It seems impossible to call  `` Lean.importModules `MyFolder.Main `` (or `` Lean.findOLean `MyFolder.Main ``) unless `Main` is built through this second, separate mean.

Correct. The root module of an executable is not meant not be imported as it defines `main` and importing a module defining `main` is problematic for Lean. The separation of `lean_lib` and `lean_exe` is designed to discourage this.

Therefore, the behavior here is intentional. Regardless, there is probably something Lake could do here to make this behavior clearer. However, I do not yet have a design in mind.

**Comment by joneugster** [comment]
copied from Zulip thread:
> A simpler fix could be to just improve the error message as the current message `You might need to open 'parentDir/' as a workspace in your editor` (from [here](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Retrieving.20all.20diagnostics)) is in this case wrong and misleading
