### ISSUE TITLE
Possible out of bound access will cause UB

### ISSUE THREAD

**Issue by term-est** [leanprover/lean4#4429]
In `ir_interpreter.cpp:900` we access
https://github.com/leanprover/lean4/blob/3bd39ed8b6f1397d23ddb813ae0b1b3d4539f707/src/library/compiler/ir_interpreter.cpp#L900

This is invoked when
https://github.com/leanprover/lean4/blob/3bd39ed8b6f1397d23ddb813ae0b1b3d4539f707/src/library/compiler/ir_interpreter.cpp#L907

is invoked, which I would like to add, is literally 7 lines below the said access. Sanitizer wont catch this since it is never invoked because
https://github.com/leanprover/lean4/blob/3bd39ed8b6f1397d23ddb813ae0b1b3d4539f707/stage0/src/library/compiler/ir_interpreter.cpp#L421

has a hardcoded `3 +`, which prevents the said access. But this whole thing is still a ticking time bomb.

- Use `std::array/std::vector` or similar containers (former is freestanding as of C++26, and zero-cost) instead of C style arrays. Containers all have `.at` method with bounds checking. Libraries like libstdc++ and libc++ also offer bounds checking for `operator[]` on debug builds, which should be enabled at all times with _GLIBCXX_DEBUG or similar. As a rule of thumb, access to arrays should be done with `.at`. See below for an example impl.
- Avoid raw pointers, or god forbid pointers to pointers. You almost always don't need pointers with modern C++, and in the rare cases when you do, use smart pointers. For interfacing with C-API, use `std::inout_ptr` or similar alternatives. As a side note, ownership of objects should be apparent in their type signature.
- `stub_N_aux` can and should be replaced by a single `template <std::size_t N> stub_aux` instead of relying on python codegen
- I see `reinterpret_cast` to `void*` a little below as well. Please get rid of it. C++ is a strongly typed language, use it as a type-safe language.

example refactor:
```cpp
template <typename T, std::size_t N>
object* interpreter::stub_m(const std::array<T, N>& args)
{
	decl d(args.at(2)); // since size is known at compile time, this should compile down to a zero-cost deref even with .at, not that it matters at all
	size_t old_size = m_arg_stack.size();
	for (std::size_t i = 0; i < decl_params(d).size(); i++) {
		m_arg_stack.push_back(args.at(3 + i)); // god knows who owns this pointer now. i sure don't
	}
	push_frame(d, old_size);
	object* r = eval_body(decl_fun_body(d)).m_obj;
	pop_frame(r, type::TObject);
	return r;
}

template <typename T, std::size_t N>
static object* stub_m_aux(const std::array<T, N>& args) 
{
	environment env(args.at(0));
	options opts(args.at(1));
	return with_interpreter<object*>(env, opts, decl_fun_id(TO_REF(decl, args.at(2))), [&](interpreter& interp)
	{
		return interp.stub_m(args);
	});
}

template <typename ... Ts>
static object* stub_aux(Ts ... args) // or auto ... args /w C++20
{
	return stub_m_aux(std::array{args...});
}
```

Godspeed

**Comment by nomeata** [comment]
If I read your analysis correctly, this is not actually broken at the moment, but merely a code smell that might turn into a real bug possibility in the future?

Thanks for trying to make lean better. Unfortunately, there are so many ways in which lean ought to be better, and many of them are more urgent and relevant than this, so I don't think it is helpful to hold up dev resources with general C++ coding advise.

I'll close this issue soon; if the code owners found your finding useful I'm sure they will still have seen it.

(Also, I assume you didn't mean it that way, but to some the tone and phrasing of your suggestions may come across as condescending, and inappropriate for a first time contributer to a project. Maybe watch out for this in future reports here or at other projects.)
