### ISSUE TITLE
`m!"{expr}"` doesn't work as of 4.9.0-rc1

### ISSUE THREAD

**Issue by llllvvuu** [leanprover/lean4#4432]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

As of 4.9.0-rc1, specifically the change to `MessageData.ofExpr` in https://github.com/leanprover/lean4/commit/9f6bbfa1066adcdf4900e985641a1b944bc77516, the following no longer works:

```lean
import Lean

def main : IO Unit := do
  let foo := Lean.mkConst `foo
  let bar ← m!"{foo}".toString
  IO.println s!"Expr: {foo}"
  IO.println s!"MessageData: {bar}"

#eval main
```

Feel free to close if this is intended behavior.

If not, `MessageData.ofExpr` (and similar functions) could be changed back to something like this:.
```lean
def ofExpr (e : Expr) : MessageData :=
  .ofLazy (fun ctx? => do
            let msg ← ofFormatWithInfos <$> match ctx? with
              | .none => pure (format (toString e))
              | .some ctx => ppExprWithInfos ctx e
            return Dynamic.mk msg)
          (fun mctx => instantiateMVarsCore mctx e |>.1.hasSyntheticSorry)
```

### Context

Batteries' `lake exe runLinter` is now printing "(invalid MessageData.lazy, missing context)" which is showing up in Batteries and Mathlib CI.

https://github.com/leanprover-community/batteries/pull/838

### Steps to Reproduce

Try the above code in 4.9.0-rc1 vs 4.8.0.

**Expected behavior:** Prints "MessageData: foo"

**Actual behavior:** Prints "MessageData: (invalid MessageData.lazy, missing context)"

### Versions

4.9.0-rc1

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by nomeata** [comment]
I didn't expect much petty printing of expressions without a context, as how else would you show local variables. But for closed expressions and in particular global names it does make sense. Recovering the previous functionality in `ofExpr` is reasonable, do you want to prepare a PR for that?
