### ISSUE TITLE
search and replace across files crashes server

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean4#4435]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [ ] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [ ] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

In VSCode, doing a search-and-replace across all files in your repository often causes Lean to crash.

### Context

A few messages on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/crash.20on.20search.20and.20replace/near/444199045)

### Steps to Reproduce

1. Download a recent version of Mathlib 
2. Open `Mathlib.Data.Set.Basic` in VSCode
3. Search across all files (`ctrl+shift+F`), e.g. for `2023 Floris van Doorn`
4. Replace (`ctrl+shift+H`) with something, e.g. `nobody`
5. Press "Replace All" (`ctrl+shift+enter`)
6. This server crashes. This happens both when the server has finished checking `Mathlib.Data.Set.Basic` and when it is still ongoing.

This causes the following error (plus 2 more messages that the server crashed). The mentioned file is one of the files where a string is being replaced.
```text
Lean server printed an error: Watchdog error: cannot find open document 'file:///c%3A/Users/Floris/projects/mathlib/Mathlib/Lean/EnvExtension.lean'
```

(do `git restore .` to undo the search&replace - after making sure you have no other changes that can be reverted by this)

### Versions

`4.9.0-rc1` or `4.8.0-rc1`

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by grunweg** [comment]
I have encountered the same issue (on Debian Linux); believe in 4.8.0-rc2 in addition to 4.9.0-rc1.
