### ISSUE TITLE
Smart unfolding with explicit `match`

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#445]
The smart unfolding lemmas generated when the user uses `match` explicitly can sometimes put `idRhs` too deep in the term:
```lean
def f : Nat → Bool
  | 0 => true
  | n + 1 => (match n with
    | 0 => true
    | _ + 1 => true) && f n

-- def f._sunfold : Nat → Bool :=
-- fun (x : Nat) =>
--   match x with 
--   | 0 => idRhs Bool true
--   | Nat.succ n =>
--     (match n with 
--       | 0 => idRhs Bool true
--       | Nat.succ x => idRhs Bool true) &&
--       f n

def g (i j : Nat) : Nat :=
  if i < 5 then 0 else
  match j with
  | Nat.zero => 1
  | Nat.succ j => g i j

-- def g._sunfold : Nat → Nat → Nat :=
-- fun (i j : Nat) =>
--   if i < 5 then 0 else
--     match j with 
--     | Nat.zero => idRhs Nat 1
--     | Nat.succ j => idRhs Nat (g i j)
```
Since `g 0` reduces to `0` and not `idRhs ...`, this means that it will be prevented from unfolding. Similarly, `f 1` does not unfold because it gets stuck on the `... && ...` after unfolding the outer match and never hits an `idRhs`.

The smart unfolding lemmas I expected to see look like this:
```lean
def f._sunfold : Nat → Bool :=
fun (x : Nat) =>
  match x with 
  | 0 => idRhs Bool true
  | Nat.succ n => idRhs Bool 
    ((match n with 
      | 0 => true
      | Nat.succ x => true) &&
      f n)

def g._sunfold : Nat → Nat → Nat :=
fun (i j : Nat) =>
  idRhs Nat (if i < 5 then 0 else
    match j with 
    | Nat.zero => 1
    | Nat.succ j => (g i j))
```

**Comment by digama0** [comment]
@Kha I see why `simp [g]` would loop (that seems like reasonable behavior since `g` contains a subterm of itself; this might be addressed by not simplifying in non-head positions, i.e. under lambda/match, under some settings), but I'm not sure why `Nat.below` would appear with `rw [g]` here since there is no `Nat.below` in the statement. Shouldn't the match expression just get unelaborated back to a match during printing?

**Comment by Kha** [comment]
Right, the `Nat.brecOn` is in `g`, not in `g._sunfold`. But because of that, your `g._sunfold` is not actually equivalent to `g` when reducible beyond `idRhs`, which is the crucial property smart unfoldings should have (AFAIU): your `g._sunfold i j` reduces to `ite ..`, but `g i j` immediately gets stuck at `Nat.brecOn j ..`.

**Comment by digama0** [comment]
Oh I see. This definition is like a definition by well founded recursion in that the defining equation is not a defeq, but that shouldn't interfere with the use of `rw` for applying equation lemmas. It just won't be usable by `dsimp` or `change` or general unfolding. It might be that `g._sunfold` is not the right place to put this, and instead there should just be an equation lemma and no smart unfolding lemma.

**Comment by leodemoura** [comment]
The `idRhs` is being correctly placed at `f._sunfold`.
Note that `g._sunfold` is unchanged.
The following `g._unfold`
```lean
def g._sunfold : Nat → Nat → Nat :=
fun (i j : Nat) =>
  idRhs Nat (if i < 5 then 0 else
    match j with 
    | Nat.zero => 1
    | Nat.succ j => (g i j))
```
is not valid because `g i j` is not definitionally equal to
```lean
if i < 5 then 0 else
    match j with 
    | Nat.zero => 1
    | Nat.succ j => (g i j)
```

**Comment by digama0** [comment]
@leodemoura  You are right, my proposed `g._sunfold` is incorrect. But I'm still stumped as to how to make use of a smart unfolding lemma that buries the `idRhs` too deeply in the term, because it blocks unfolding entirely. It almost seems like it might be better to drop the smart unfolding lemma entirely and just use the default behavior when there is no lemma...

**Comment by leodemoura** [comment]
> It almost seems like it might be better to drop the smart unfolding lemma entirely and just use the default behavior when there is no lemma...

I am not sure. If we use the default behavior, we would expose the internal details of the compilation, i.e., the `brecOn`. 
Recall that before we had "smart unfolding", new users were often puzzled by unification solutions containing `brecOn` leftovers. Example: `Nat.succ ?n =?= m + 2` 
BTW, we have an option for disabling `smartUnfolding`. Perhaps, we can add an attribute to selectively disable `smartUnfolding`. 

> shouldn't there be an idRhs on the 0?

Right now, I am putting the `idRhs` only on the `match`-alternative right-hand sides. The intuition is that when we "reach" these alternatives we have enough information to "access" the `brecOn` "dictionary of solutions". The key feature missing is that the smart unfolding procedure is not looking for nested occurrences of `idRhs`. For example, suppose we have

```lean
def h (i j : Nat) : Nat :=
  i +
    match j with
    | Nat.zero => 1
    | Nat.succ j => h i j

-- The following examples fails with `smartUnfolding` turned on
set_option smartUnfolding false
example : h i (j + 1) = i + h i j := 
  rfl 
```

If we handle the nested occurrences of `idRhs`, then smart unfolding will be able to reduce `g i (j+1)` to `if i < 5 then 0 else g i j`.

**Comment by digama0** [comment]
>  BTW, we have an option for disabling smartUnfolding. Perhaps, we can add an attribute to selectively disable smartUnfolding.

If there is an option for it, then I think there isn't much need to have an attribute as well as long as it is a relatively rare thing to do.

Ah, I see what you mean about nested occurrences. I guess that's the best we can hope for as far as defeq reduction is concerned anyway (i.e. `g 0 i` is not defeq to `0` under the current compilation strategy) so I think that would solve the remaining issues.

**Comment by leodemoura** [comment]
Pushed the support for nested `match`-expressions. Here is an example, given
```lean
def r (i j : Nat) : Nat :=
  i +
    match j with
    | Nat.zero => 1
    | Nat.succ j =>
      i * match j with
          | Nat.zero => 2
          | Nat.succ j => r i j
```
The smart unfolding of `r i j.succ.succ` is `i + i * r i j`.
