### ISSUE TITLE
a code suggestion bug

### ISSUE THREAD

**Issue by fonqL** [leanprover/lean4#4455]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [X] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [X] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [X] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

```lean
def aaaaa := 1

#eval ([1,2,3].map λ c => a).length
```
When I type `a` in the lambda, LSP only suggests the symbols in the namespace of `List`, not global symbols.

### Context

[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/a.20code.20suggestion.20bug)

### Steps to Reproduce

1. Paste the code above in vscode.
2. Put the cursor in the character `a` in the lambda.
3. Trigger suggestion.

**Expected behavior:** 

Show global symbols, including `aaaaa`.

**Actual behavior:** [Clear and concise description of what actually happens]

Only show symbols in `List` namespace.
<img width="452" alt="Snipaste_2024-06-14_15-32-05" src="https://github.com/leanprover/lean4/assets/75968297/d5df164d-331a-4c57-b4ea-d0e1c8d93da0">

### Versions

4.9.0-rc1

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by fonqL** [comment]
Sorry, I seems to report in a wrong place..

**Comment by mhuisi** [comment]
No, I think this is the right place!
