### ISSUE TITLE
`initialize` corrupts scalar values

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/lean4#4457]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [ ] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

`initialize` always stores booleans as `true`

### Steps to Reproduce

1. Add `initialize definitelyFalse : Bool ← pure false` to `InitializeBug.lean`
2. `#eval definitelyFalse` in a file that starts `import InitializeBug`, and open it in VSCode

**Expected behavior:** Output is definitely `false`

**Actual behavior:** Output is `true`

### Versions

4.9.0-rc1

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by eric-wieser** [comment]
Tested again with `UInt32`; Storing `0xAABBCCDD` gives `0x557799BB`!

**Comment by digama0** [comment]
With finite enumeration types, it seems to double the value and add 1. It's almost certainly a missing `unbox`.

**Comment by digama0** [comment]
I suspect the following enumeration:
```c++
union value {
    // NOTE: the IR type system guarantees that we always access the active union member
    uint64   m_num; // big enough for any unboxed integral type
    static_assert(sizeof(size_t) <= sizeof(uint64), "uint64 should be the largest unboxed type"); // NOLINT
    double   m_float;
    object * m_obj;
```
The comment seems to be false in this case: globals are always stored using the `object *` constructor, but they are accessed according to their type (in particular, for scalar types this means `m_num`) and this implicitly skips an `unbox`.
