### ISSUE TITLE
Syntax for `choice` tactic doesn't seem to be defined

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean4#453]
This seems to be a dangling tactic-elaborator: https://github.com/leanprover/lean4/blob/master/src/Lean/Elab/Tactic/Basic.lean#L452

**Comment by leodemoura** [comment]
`choice` is an internal syntax node kind.
https://github.com/leanprover/lean4/blob/master/src/Lean/Parser/Basic.lean#L1445-L1446
