### ISSUE TITLE
Failure of exhaustiveness checker when matching on `Exception`

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lean4#4555]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [X] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [X] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [X] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

MWE:

```lean
import Lean

open Lean

example (e : Exception) : True :=
  match e with
  | .internal .. => sorry
  | .error .. => sorry

-- missing cases:
-- (@Exception.internal _ (KVMap.mk (List.cons (Prod.mk _ (DataValue.ofSyntax _)) _)))
-- (@Exception.internal _ (KVMap.mk (List.cons (Prod.mk _ (DataValue.ofInt (Int.negSucc _))) _)))
-- (@Exception.internal _ (KVMap.mk (List.cons (Prod.mk _ (DataValue.ofInt (Int.ofNat _))) _)))
-- (@Exception.internal _ (KVMap.mk (List.cons (Prod.mk _ (DataValue.ofNat _)) _)))
-- (@Exception.internal _ (KVMap.mk (List.cons (Prod.mk _ (DataValue.ofName _)) _)))
-- (@Exception.internal _ (KVMap.mk (List.cons (Prod.mk _ (DataValue.ofBool true)) _)))
-- (@Exception.internal _ (KVMap.mk (List.cons (Prod.mk _ (DataValue.ofBool false)) _)))
-- (@Exception.internal _ (KVMap.mk (List.cons (Prod.mk _ (DataValue.ofString (String.mk _))) _)))
```

### Versions

`"4.10.0-nightly-2024-06-24"`

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by leodemoura** [comment]
The issue here is that `Exception.internal` has a default argument. 
```lean
inductive Exception where
  | error (ref : Syntax) (msg : MessageData)
  | internal (id : InternalExceptionId) (extra : KVMap := {})
```
Thus, `.internal ..` is equivalent to `.internal _ {}`. Possible solutions:
- A better error message.
- Modify the meaning of `..`.

**Comment by leodemoura** [comment]
Workaround.
```lean
import Lean

open Lean

example (e : Exception) : True :=
  match e with
  | .internal _ _ => sorry
  | .error .. => sorry
```

**Comment by JLimperg** [comment]
Ah, it's the default argument! I understand `..` as "ignore all other arguments", so I would prefer if there was no distinction between arguments with and without a default value.
