### ISSUE TITLE
ppSpace in `elab`/`macro` is ignored before constructor dot notation

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/lean4#4561]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

Using `ppSpace` in a parser does not always result in a space. As a result, syntax does not roundtrip.

### Context

[Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/.60ppSpace.60.20not.20working.20in.20.60use.60.20syntax/near/446962423)

### Steps to Reproduce

1. Run the following:
```lean
import Lean.Elab.Command

macro (name := useSyntax) "use" ppSpace arg:term : tactic => `(tactic| sorry)

run_cmd do
  Lean.logInfo <| ← `(tactic| use .succ 0)
```

**Expected behavior:** Outputs `use .succ✝ 0`

**Actual behavior:**  Outputs `use.succ✝ 0`, which is invalid syntax due to the missing space

### Versions

4.10.0-nightly-2024-06-25

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by kmill** [comment]
It looks like the issue is that when `ppSpace` is used as a macroArg without a variable name, it gets wrapped in a `group`, which inhibits inserting the space.

Is this a bug in whitespace insertion? Or should `Lean.Elab.Command.expandMacroArg` special case `ppSpace`?

```lean
import Lean

open Lean Lean.Parser.Command Lean.Elab.Command

elab "test_macroArg " args:macroArg* : command => do
    let (stxParts, patArgs) := (← args.mapM expandMacroArg).unzip
    logInfo m!"{stxParts}"
    logInfo m!"{patArgs}"

test_macroArg ppSpace term,+
-- [group✝(ppSpace), sepBy1(term, ",", ", ")]
test_macroArg x:ppSpace term,+
-- [ppSpace, sepBy1(term, ",", ", ")]

elab "use1" ppSpace term,+ : tactic => failure
elab "use2" x:ppSpace term,+ : tactic => failure

run_cmd Lean.Elab.Command.liftTermElabM do
  Lean.logInfo <| ← `(tactic| use1 .succ 0) -- use1.succ✝ 0
  Lean.logInfo <| ← `(tactic| use2 .succ 0) -- use2 .succ✝ 0
```
