### ISSUE TITLE
`IO.FS.lines` does not remove CR from the line ending in Ubuntu

### ISSUE THREAD

**Issue by Seasawher** [leanprover/lean4#4573]
### Description

`IO.FS.lines` can treat CRLF file in WIndows only. It does not remove CR in Ubuntu, so it cannot treat CRLF files in Ubuntu (and CI!).

```lean
partial def lines (fname : FilePath) : IO (Array String) := do
 let h ← Handle.mk fname Mode.read
 let rec read (lines : Array String) := do
 let line ← h.getLine
 if line.length == 0 then
 pure lines
 else if line.back == '\n' then
 let line := line.dropRight 1
 let line := if System.Platform.isWindows && line.back == '\x0d' then line.dropRight 1 else line
 read <| lines.push line
 else
 pure <| lines.push line
 read #[]
```

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment]
Please try giving more specific titles and description (you can also use the Zulip chat if you are not sure something is a bug). By "treat", I assume you mean "removes the CR from the line ending"?
