### ISSUE TITLE
Incremental tactics leading to errors disappearing in proof

### ISSUE THREAD

**Issue by ymherklotz** [leanprover/lean4#4623]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [X] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [X] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [X] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

With incremental tactic evaluation, error reporting seems to have become brittle.  There are situations where one thinks no errors are being reported, but one is able to prove anything using invalid tactics, because errors are not being reported for that line.

Even when one fixes the error, because the tactics are incremental they don't display errors until one actually modified tactics above them.  If one only modifies tactics below, one can get very random behaviour where tactics should fail but seem to solve goals instead.

### Context

We were working in a fairly large proof and kept non-deterministically getting into situations where Lean wouldn't report errors any more, and would seem to solve goals when it shouldn't, because we had a malformed statement very low down in the proof.  Even after fixing that, we still got erratic behaviour until we finally restarted lean a few times and fixing errors that arose incrementally with every restart.

### Steps to Reproduce

[Live coding environment of the bug](https://live.lean-lang.org/#project=lean-nightly&code=namespace%20N%0A%0A--%20This%20is%20a%20lemma%20from%20the%20Lean%20List%20Prelude%2C%20that%20was%20slightly%20modified%20to%20make%0A--%20it%20easier%20to%20showcase%20the%20bug.%20%20The%20two%20tactics%20that%20solve%20this%20lemma%20are%0A--%20commented%20and%20were%20replaced%20by%20completely%20invalid%20tactics.%0Atheorem%20minimum%3F_mem%20%5BMin%20%CE%B1%5D%20(min_eq_or%20%3A%20%E2%88%80%20a%20b%20%3A%20%CE%B1%2C%20min%20a%20b%20%3D%20a%20%E2%88%A8%20min%20a%20b%20%3D%20b)%20%3A%0A%20%20%20%20%7Bxs%20%3A%20List%20%CE%B1%7D%20%E2%86%92%20xs.minimum%3F%20%3D%20some%20a%20%E2%86%92%20a%20%E2%88%88%20xs%20%3A%3D%20by%0A%20%20intro%20xs%0A%20%20cases%20xs%0A%20%20%C2%B7%20simp%0A%20%20%C2%B7%20rename_i%20x%20xs%20%0A%20%20%20%20simp%20only%20%5BList.minimum%3F_cons%2C%20Option.some.injEq%2C%20List.mem_cons%5D%0A%20%20%20%20intro%20eq%0A%20%20%20%20skip%0A%20%20%20%20induction%20xs%20generalizing%20x%3B%20rotate_left%0A%20%20%20%20%C2%B7%20rename_i%20y%20ys%20ind%0A%20%20%20%20%20%20simp%20at%20eq%0A%20%20%20%20%20%20have%20p%20%3A%3D%20ind%20_%20eq%0A%20%20%20%20%20%20cases%20p%0A%20%20%20%20%20%20%C2%B7%20rename_i%20p%0A%20%20%20%20%20%20%20%20--%20cases%20min_eq_or%20x%20y%20with%20%7C%20_%20q%20%3D%3E%20simp%20%5Bp%2C%20q%5D%0A%20%20%20%20%20%20%20%20exact%20RandomName%20%20%20%20%20%20%20%20%20%20%20%20--%20Step%203%3A%20Press%20enter%2C%20see%20the%20errors%20come%20back%20everywhere.%0A%20%20%20%20%20%20%C2%B7%20rename_i%20p%0A%20%20%20%20%20%20%20%20--%20simp%20%5Bp%2C%20List.mem_cons%5D%0A%20%20%20%20%20%20%20%20exact%20RandomName%20%20%20%20%20%20%20%20%20%20%20%20--%20Step%202%3A%20Invalid%20tactic%20that%20seems%20to%20prove%20the%20goal.%0A%20%20%20%20%C2%B7%20simp%20at%20eq%0A%20%20%20%20%20%20simp%20%5Beq%5D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20--%20Step%204%3A%20Press%20enter%20here%20and%20see%20the%20error%20at%20Step%204%20disappear.%0A%20%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20--%20Step%201%3A%20Comment%20this%20invalid%20focus%2C%20see%20no%20other%20error%20appear%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20--%20%20%20%20%20%20%20%20%20except%20that%20the%20lemma%20now%20states%20it%20uses%20sorry%20for%20the%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20--%20%20%20%20%20%20%20%20%20definition.%0A%0A--%20The%20namespace%20here%20is%20just%20to%20show%20that%20the%20error%20for%20the%20invalid%20additional%0A--%20focus%20tactic%20is%20added%20to%20the%20end%20instead%20of%20the%20focus%20tactic%20itself%2C%20which%0A--%20can%20be%20difficult%20to%20see%20if%20one%20has%20comments%20before%20the%20end%20of%20the%20namespace.%0A%0Aend%20N%0A)

0. Open up the live coding environment above with a lemma from the builtin List library, with an invalid focus at the end that swallows other errors in the file.  Observe that lines 25 and 22 do not report errors.
1. Comment line 28: see no other error appear except that the lemma now states it uses sorry for the definition.
2. Observe that line 25 and line 22 still do not report errors.  Also observe that after putting the cursor on line 25, it seems like the invalid `exact` tactic is solving the goal.
3. Press enter on line 22 to make the errors come back on line 22 (and now line 26).
4. Press enter on line 27 (after the `simp`) and see the error on line 22 disappear again.

**Expected behavior:** Errors should always be displayed and should not disappear after making edits.  Invalid tactics should also not appear to be modifying the goal (and look like they're solving it).

**Actual behavior:** Errors disappear when making edits throughout a file, and invalid tactics may seem like they are solving a goal even though they are actually encountering an error.

### Versions

```
5.11.0-nightly-2024-07-01
```

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment]
Thank you for the detailed report. I can reproduce step 4 but not 1 in the sandbox. 
![Recording 2024-07-02 at 13 55 30](https://github.com/leanprover/lean4/assets/109126/90f4bf4c-d5c7-44e7-93ec-b05d911f9efd)

**Comment by ymherklotz** [comment]
Indeed, I didn't know that this actually worked.  If you try and comment the line by putting the cursor at the very start of the line, instead of glued to the `.`, then it should be possible to reproduce step 1 too.  It does for me in the sandbox.
