### ISSUE TITLE
Elaboration function for 'Lean.Parser.Term.namedPattern' has not been implemented

### ISSUE THREAD

**Issue by lovely-error** [leanprover/lean4#4662]
It turns out I cannot rewrite named patterns :(

Try this at home!
```lean4
def minimal : Unit -> Unit := by
  intro i
  let k:p@() := i -- lean says it has missing implementation here :(
```

Without this feature the following code...
```lean4
def minimal : Unit -> Unit := by
  intro i
  let k@() := i
```
...introduces shadowed equality...
```lean4
unsolved goals
i k : Unit
h✝ : k = () -- this one 
⊢ Unit
```
...which cannot be used :(

**Comment by leodemoura** [comment]
PR above adds a better error message.
The correct syntax for what you want is
```
  let p@k:() := i
```
It will add the hypothesis `h : p = ()`
