### ISSUE TITLE
Generated infix delaborator is incorrect when infix expands to notation

### ISSUE THREAD

**Issue by tydeu** [leanprover/lean4#469]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The delaborator generated by the mixfix commands is incorrect when the mixfix operation is represented by some custom notation.

### Steps to Reproduce

```lean
notation "(+)" => HAdd.hAdd
#check ((+) : Nat -> Nat -> Nat)
/-
  (+) : Nat → Nat → Nat
-/

infixl:65 (priority := default + default) " + " => (+)
#check 2 + 2
/-
  (+) : Nat
-/
```

**Expected behavior:**

I would expect `infixl` to produce a delaborator that correctly pretty prints as `2 + 2`.

**Actual behavior:**

The operands completely disappear and only the operator is left, leaving very ill-formed output.

**Reproduces how often:**

Always.

### Versions

Windows 10 20H2
`Lean (version 4.0.0-nightly-2021-05-14, commit 686b63c60fb4, Release)`

### Additional Information

This issue was first discussed in on Zulip ([Infix Delaborator Bug](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Infix.20Delaborator.20Bug.3F/near/238913459)) and confirmed to be a bug by @Kha.

**Comment by Kha** [comment]
Note that the issue was with the unexpander of the first notation - the second one isn't generating an unexpander to begin with. Generating unexpanders for more general notations would be a separate feature request, as would dealing better with over-application (see test output of fix commit), which the delaborator isn't great with in general.
