### ISSUE TITLE
RFC (and issue): Use LEAN installation when offline for Kaggle (or probably generally)

### ISSUE THREAD

**Issue by realharryhero** [leanprover/lean4#4813]
### Proposal

It would be good to use LEAN on the most recent Artificial Intelligence Math Olympiad (AIMO) competition on Kaggle, considering code has already proven to improve AIMO performance, and it would probably be even better to use a specialized theorem proving code for the AIMO instead.

LEAN already does install on Kaggle nicely, though, but just not offline. I used some edits to get it working:

1. Install https://github.com/leanprover/elan/releases/download/v3.1.1/elan-x86_64-unknown-linux-gnu.tar.gz, and unzip the targz file.
2. Place the elan-init binary executable (the result after unzipping) onto a github repo; denote the name of the repo as $REPO.
3. Upload it as a Kaggle dataset on a Kaggle Notebook. (One can search up how this works on some tutorial online.)
4. Move the elan-init file (/kaggle/input/$REPO/elan-init) to /kaggle/working/elan-init, set permissions for /kaggle/working/elan-init to everyone, then run the executable. Note in Jupyter Notebooks one needs to use the ! sign. 
5. Run `%set_env PATH=/root/.elan/bin:/opt/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`, which includes lean, lake and elan in $PATH. 

Here's a video describing this (sorry for the bad quality; too little space for 720p):

https://github.com/user-attachments/assets/ba968bb0-6c7d-44cb-ae4e-78cc1a8b4a8c

This breaks without internet as it requires installing LEAN from github.com, which requires internet; internet is not allowed in the AIMO competition.

But it also happens that this installs elan in `/root/.elan`; by saving this file, downloading it onto another Kaggle dataset through similar means, placing it onto a dataset and adding `/root/.elan/bin` to $PATH through `%set_env`, I can run elan, but not lean and lake; trying to do so gives the following error:

```
error: command failed: 'lean'
info: caused by: Permission denied (os error 13)
```

If I do `elan toolchain install v4.7.0,` with internet, though, even though it doesn't install any files it seems to do something that gets lean and lake up and running. Without internet, this isn't possible, as elan still requires git to install toolchains, even if it does not install files. 

A quick fix would just to spoof installing through git (that is, if one tries to install git, then install some dummy file and pretend it works), but I also don't know Rust (programming language for elan) too well. 

This is sort of an RFC and issue: while it would most likely be nice to get LEAN working on Kaggle (since it seems to be an interesting approach, I'm also interested in writing a tutorial to get LEAN working on Kaggle after it starts working), I'm also wondering generally outside of Kaggle how to obtain a file that can run LEAN out of the box. Thank you!

**Comment by nomeata** [comment]
If I understand you correctly, you want to install lean in an environment where you don’t have internet (I don’t know anything about kaggle).

In that case maybe avoid elan alltogether and download the desired lean release directly from <https://github.com/leanprover/lean4/releases>?

It puts the burden to on you to pick the right release for the project you are working on (see the `lean-toolchain` file in mathlib, for example); if you don’t need any libraries besides those that come with lean this shouldn’t be an issue.
