### ISSUE TITLE
`failed to synthesize` reported at the beginning of a file

### ISSUE THREAD

**Issue by adomani** [leanprover/lean4#4880]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

Sometimes, when the auto-filled in `by infer_instance` parameter fails to find an instance, it reports the error at the beginning of the file, instead of where the failure happened.

### Context

Reported on [the Lean Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Error.20message.20at.20the.20start.20of.20file).

### Steps to Reproduce

Run this code:

```lean
  -- <-- `failed to synthesize A` here
class A

structure B where
  h1 : A := by infer_instance
-- using `inferInstance` instead of `by infer_instance` reports the
-- `failed to synthesize A` and the diagnostic comment here
-- not on the `example` below

example : B where
```

**Expected behavior:** The error should highlight `example`.

**Actual behavior:** The error highlights the beginning of the file.

### Versions

[Output of `#eval Lean.versionString`]

"4.10.0-rc2"

for both the online server and my own computer.

[OS version, if not using live.lean-lang.org.]

Linux Mint

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by kmill** [comment]
Could you clarify what you expect when it is `:= inferInstance`? In that case, the error is on `inferInstance`, but that's because the original `inferInstance` fails to elaborate and the default value for `B.h1` becomes `sorry`.

**Comment by adomani** [comment]
Looking again at this, I am not sure what I would expect with `inferInstance`.  It seems that
```lean
class A

structure B where
  h1 : A := inferInstance
```
is already an error, so this is unrelated to the presence of the `example`.

So, the only issue here, from my perspective, is the reporting of the error at the beginning of the file, rather that on `example` when the default value is set to `by infer_instance`.
