### ISSUE TITLE
Inconsistent sorting in `Name.cmp`

### ISSUE THREAD

**Issue by joneugster** [leanprover/lean4#4944]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

The sorting of `Name`s (i.e. in [`Name.cmp`](https://github.com/leanprover/lean4/blob/daa22187642d4cf6954c39a23eab20d8a8675416/src/Lean/Data/Name.lean#L58-L71)) is unexpected.

### Context

From PR leanprover-community/import-graph#18

[[Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Does.20Name.2Ecmp.20do.20the.20correct.20thing.3F/near/457085745)]

### Steps to Reproduce

```lean
import Lean
open Lean

#reduce Name.cmp `M.A `M.B   -- M.A   < M.B (✓)
#reduce Name.cmp `M.A.B `M.B -- M.A.B > M.B (⨯)
```

**Expected behavior:** In the second example, I expect `M.A.B < M.B`

I expected the following comparison:

- Compare first part of the name (`M == M`)
- Compare second part (`A < B`) ==> return `lt`
- ( ... )

**Actual behavior:** 

- Compare length of name (`3 > 2`) ==> returns `gt`
- (Compare first part of the name)
- (Compare second part ...)
- ( ... )

### Versions

4.11.0-rc1

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by mo271** [comment]
zulip discussion on the topic here: 
https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Does.20Name.2Ecmp.20do.20the.20correct.20thing.3F

**Comment by Kha** [comment]
Triage team agreed on this not being a bug, the function is undocumented and as everything in `Lean` written for the purposes of Lean. You should create your own ordering function.

**Comment by joneugster** [comment]
ok, thanks for looking at it!
