### ISSUE TITLE
'axiom' seems broken, produces kernel errors

### ISSUE THREAD

**Issue by jonsterling** [leanprover/lean4#496]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I am receiving a somewhat strange error from the kernel when trying to typecheck some code that I think should work. The behavior changes if I replace `axiom` with a `constant` implemented by `sorry`.

### Steps to Reproduce

Try to run the following code:

````lean
axiom F : Type
axiom foo : F
def foo' : F := foo
````

**Expected behavior:**

It should finish without errors.

**Actual behavior:**

I receive the following output:

````
bug.lean:4:4: error: (kernel) compiler failed to infer low level type, unknown declaration 'foo'
````

**Reproduces how often:** Always

### Versions

I am using macOS 11.3.1; my Lean version is as follows:

````
Lean (version 4.0.0-nightly-2021-05-28, commit 96b5574f21c2, Release)
````

### Additional Information

If I change my code to the following, it seems to work:

````lean
axiom F : Type
constant foo : F := sorry
def foo' : F := foo
````

**Comment by Vtec234** [comment]
I'll quote Leo's [reply](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/significance.20of.20.28kernel.29.20in.20error.20messages.3F/near/229679966) from the Lean Zulip:
> This is a known bug in the code generator. It is in an old part that is still written in C/C++. We need to infer types in the compiler, and we reused the kernel type checker for this. [..].
The definitive solution will only happen when we replace this part of the compiler with Lean code, and implement a custom inferType method for the compiler.

>> Does getting a message from the kernel roughly analogous to getting an anomaly from Coq or an internal error from gcc?

> Yes, a message with the (kernel) prefix usually indicates there is a bug in the frontend or code generator.

So basically the compiler is just complaining that it cannot execute an axiom and uses an amazingly confusing error message to do so. If you only want to play with typechecking and not executables, it suffices to stick a `set_option codegen false` at the top to get rid of this.

**Comment by jonsterling** [comment]
Oh cool, thanks for this!

**Comment by jonsterling** [comment]
When I put that flag at the top, something strange happens. It becomes impossible to add notations pertaining to an axiom; the following code reports `unknown declaration 'term▷_'`

```lean
universe u
set_option codegen false
axiom ltr : Type u -> Type u
prefix:100 "▷" => ltr
```

Happy to open another ticket about that if you want.

**Comment by Vtec234** [comment]
Yes, turning off all code generation is a little overkill as sometimes it is actually needed. In this case, it's needed to produce some code to pretty-print your notations. You *could* actually just ignore that particular `(kernel)` error -- you'll see that `foo'` gets defined anyway, you can `#check` it and also `#reduce` it to `foo`. The canonical solution is to instead write `noncomputable foo' : F := foo`.

**Comment by jonsterling** [comment]
Ahh, I think `noncomputable' is the thing I was actually looking for. thanks!
