### ISSUE TITLE
RFC: Use emoji variant selector for unicode characters

### ISSUE THREAD

**Issue by joneugster** [leanprover/lean4#5015]
### Proposal

Occasionally, Lean uses emojis, for example it uses `✅❌💥` for debugging. The proposal is to use the [variant selector](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)) with `\uFE0F` followed:

In particular, use

```
emoji variant: ✅️❌️💥️
text variant: ✝︎▼︎▶︎
```
(which look the same, but are different to the currently used `✅❌💥✝▼▶`)

#### User Experience

Minor improvement, but helps with using custom fonts. See for example [live.lean-lang.org](https://live.lean-lang.org/#code=set_option%20trace.Meta.synthInstance%20true%0A%0A%23synth%20Decidable%20Nat%0A):

```lean
set_option trace.Meta.synthInstance true

#synth Decidable Nat
```
which displays

```
[Meta.synthInstance] ❌︎ CoeT Type Nat Prop ▼
  [] new goal CoeT Type Nat Prop ▶
  [] ❌︎ apply @instCoeT to CoeT Type Nat Prop ▶
  [] ✅︎ apply @instCoeTOfCoeDep to CoeT Type Nat Prop ▶
  [] ✅︎ apply @instCoeTOfCoeHTCT to CoeT Type Nat Prop ▶
  [] ❌︎ apply @instCoeHTCT to CoeHTCT Type Prop ▶
  [] ✅︎ apply @instCoeHTCTOfCoeHTC to CoeHTCT Type Prop ▶
  [] ❌︎ apply @instCoeHTC to CoeHTC Type Prop ▶
  [] ✅︎ apply @instCoeHTCOfCoeOTC to CoeHTC Type Prop 
```

instead of

```
[Meta.synthInstance] ❌️ CoeT Type Nat Prop ▼
  [] new goal CoeT Type Nat Prop ▶
  [] ❌️ apply @instCoeT to CoeT Type Nat Prop ▶
  [] ✅️ apply @instCoeTOfCoeDep to CoeT Type Nat Prop ▶
  [] ✅️ apply @instCoeTOfCoeHTCT to CoeT Type Nat Prop ▶
  [] ❌️ apply @instCoeHTCT to CoeHTCT Type Prop ▶
  [] ✅️ apply @instCoeHTCTOfCoeHTC to CoeHTCT Type Prop ▶
  [] ❌️ apply @instCoeHTC to CoeHTC Type Prop ▶
  [] ✅️ apply @instCoeHTCOfCoeOTC to CoeHTC Type Prop 
```

Further, using the wrong font, one might see `inst✝️` instead of `inst✝︎`, which is distracting.

#### Beneficiaries

Better support for custom fonts helps in particular the international community as for example Chinese, Japanese or Cyrillic script might require usage of a custom font. E.g. JuliaMono is defacto a solid choice and also used by live.lean-lang.org.

#### Maintainability

There is some potential issue to consider about unicode characters that look identical.

### Community Feedback

There was some private feedback by Joachim Breitner (@nomeata) that `❌︎` and `✅︎` in the trace output is not nice as they are harder to recognise.

[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Lean.20specific.20font) suggests this could be a valid approach if it doesn't create new pitfalls for the user.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by Kha** [comment]
RFC accepted

**Comment by nomeata** [comment]
@joneugster, do you plan to implement this as well?

**Comment by joneugster** [comment]
Thanks for looking at the rfc. I can create an implementation next week if that's desired👍

**Comment by nomeata** [comment]
Thanks!
