### ISSUE TITLE
Regression in inferring universe levels between v4.9.1 and v4.10.0-rc1

### ISSUE THREAD

**Issue by mik-jozef** [leanprover/lean4#5035]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

The following code typechecks with Lean 4.9.1, but not with 4.10.1-rc1 and later:

```lean
structure Asdf: Type u where

def foo (T: Type u) : Asdf.{u} := {}

def bar
  (T: Type u)
  (holdsForAll: ∀ n: Asdf, True)
:
  True
:=
  let n := foo T
  
  holdsForAll n
```

The error:

```
application type mismatch
  holdsForAll n
argument
  n
has type
  Asdf : Type u
but is expected to have type
  Asdf : Type u_1
```

An easy workaround is to propagate the universe explicitly:

```lean
(holdsForAll: ∀ n: Asdf.{u}, True)
```

**Expected behavior:** The code produces no errors.

### Versions

Lean versions affected: 4.10.0-rc1, lean nightly as of wriging
OS: Ubuntu 22.04.4 LTS

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment]
This is an intentional change: #4482
