### ISSUE TITLE
Term goal and local context query request server protocol extension proposal

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#504]
As per the revised contribution guidelines, I am filing an RFC issue in advance of submitting a PR.  This RFC has been [discussed on Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Term.20goal.20and.20local.20context.20query.20request.20s.2Ep.2Ee.2Ep.2E.20.28Pre-RFC.29) with positive reception.

# Term goal and local context query request server protocol extension proposal

## Introduction

Tactic proofs are easy to follow because you can step through them line by line and watch how the tactic state changes.  [Lean 3.15 therefore extended this feature to term-mode proofs.](https://github.com/leanprover-community/lean/pull/275) With this change, Lean also shows for every subterm a tactic state, printing the local context and the expected type.

This feature makes it easy to understand term-mode proofs since you can now step through them just like a tactic proof.  It is also useful when reading code, since it tells you the names and types of local variables.

## Proposal

In analogy to the `$/lean/plainGoal` request, we add a `$/lean/plainTermGoal` request, returning a pretty-printed goal state consisting of the local context and the expected type at the given position.

```typescript
interface PlainTermGoalParams extends TextDocumentPositionParams {}

interface PlainTermGoal {
  goal: string;
  range: Range;
}
```

In the editor, the term goal state would be shown separately and below of the tactic state.  (This is sometimes a bit confusing in Lean 3, when the term goal was shown *instead* of the tactic state.)

**Comment by DanielFabian** [comment]
yes, please. I've been missing this one for a while now.

**Comment by Kha** [comment]
@gebner @Vtec234 What are your thoughts on having a separate request vs extending `plainGoal`?

**Comment by gebner** [comment]
Ultimately I don't think it makes much of a difference.  Both approaches are implementable without big problems.  I don't think a single request makes things any easier.  Performance-wise there should be no difference (vscode sends the two requests in parallel).

My preference is for two separate requests simply because it's two different functions.  We also have a separate `textDocument/hover` request, even though we could have extended it to include information about goals, etc.  The LSP in general seems to prefer many smaller requests over a single one that returns the whole kitchen sink.

**Comment by Vtec234** [comment]
Given that `plainGoal` (and thus presumably `plainTerm`) is meant to be temporary and eventually removed in favour of `getWidget`, I'd agree that it does not seem to matter much, and would suggest whichever one seems simpler. Perhaps extending `plainGoal` is a tiny bit simpler in that the handler is already in place and would just need an extra flag in the request asking either for a tactic or term goal. I'm not sure which option is easier to handle client-side (e.g does having a `PlainTermGoal` response make it easier to know where it should be displayed, or can you just check the response ID).

**Comment by Kha** [comment]
Oh, I was actually thinking of responding with both goals from the same request. That shouldn't really increase overhead even if only one of them is displayed because the real costly part, elaboration, is shared. Sending back both at the same time might reduce updates and flickering in the UI.

**Comment by gebner** [comment]
> Perhaps extending plainGoal is a tiny bit simpler in that the handler is already in place and would just need an extra flag in the request asking either for a tactic or term goal. 

The position parameter is the only similarity between the two requests.  They need to look for different nodes in the info tree, and the response format is also different (e.g. term goals include the range of the subterm so that the editor can highlight it).

> (e.g does having a PlainTermGoal response make it easier to know where it should be displayed, or can you just check the response ID).

It's `await requestPlainTermGoal(...)` and `await requestPlainGoal(...)`, there's no explicit id handling or state machine or anything.  (Same idea in other editors, though emacs still uses callbacks instead of async/await.)

> That shouldn't really increase overhead even if only one of them is displayed because the real costly part, elaboration, is shared.

Correct me if I'm wrong, but unlike in Lean 3 there is zero elaboration going on for these requests (aside from parsing the file itself which happens anyhow).  Both of them just wait for the snapshot to be ready, and then fish out the desired information.  So having two requests does not incur a performance cost.

> Sending back both at the same time might reduce updates and flickering in the UI.

Flickering does not depend on how the request API looks like, it depends on when you update the UI.  That is, if you do `requestPlainTermGoal(); update(); requestPlainGoal(); update()` vs. `requestPlainTermGoal(); requestPlainGoal(); update()`.

**Comment by Kha** [comment]
> Both of them just wait for the snapshot to be ready, and then fish out the desired information. So having two requests does not incur a performance cost.

Yes, that's what I meant to say. The elaboration cost is shared.

> though emacs still uses callbacks instead of async/await

Yeah, I guess that's why I subconsciously thought of the shared request as simpler :sweat_smile: . But I really don't want to make Emacs to influence any design decision, so let's say: LGTM, please go ahead!
