### ISSUE TITLE
Exponential behavior in compilation

### ISSUE THREAD

**Issue by BrunoDutertre** [leanprover/lean4#5061]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

On the following example, the lean runtime grows exponentially with the recursion depth. With default depth, lean is stuck. 

```lean
def fin_max {n: Nat} (f: Fin n → Nat) : Nat :=
  loop 0 0
where
  loop (i: Nat) (max_so_far: Nat): Nat :=
    if h: i < n then
      loop (i + 1) (max max_so_far (f ⟨i, h⟩))
    else
      max_so_far

set_option profiler true in
set_option maxRecDepth 74 in
def test (a: Array Nat) : Nat := fin_max (fun i => a[i])
```

Here's what I see as the depth increases:

    -----------------------------------------
       depth    | compilation time (in s)
    -----------------------------------------
       68       | 1.35
       70       | 2.68
       72       | 5.43
       74       | 10.8
       76       | 21.8
    -----------------------------------------

### Steps to Reproduce

```
> ~/.elan/toolchains/leanprover--lean4---v4.10.0/bin/lean slow.lean
compilation of test took 10.8s
slow.lean:12:51: error: maximum recursion depth has been reached
use `set_option maxRecDepth <num>` to increase limit
use `set_option diagnostics true` to get diagnostic information
cumulative profiling times:
        attribute application 0.00237ms
        compilation 10.8s
        tactic execution 6.63ms
        type checking 0.417ms
        typeclass inference 0.446ms
```

**Expected behavior:** 

Fail quickly. There's not enough info to infer the type of `i` in `fun i => a[I]`.

**Actual behavior:**

Doesn't terminate (unless one gives a small recursion depth limit).

### Versions

4.10.0

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment]
Preliminary analysis: `get_elem_tactic_trivial` fills the `Nat` hole with `succ`s up to the recursion depth, then the code generator's `elim_dead_let` spends a long time on it without interrupt checks.
```
• Tactic @ ⟨16, 51⟩†-⟨16, 55⟩† @ Lean.Elab.Tactic.evalApply
  (Tactic.apply
   "apply"
   `Fin.val_lt_of_le._@.tests.scratch._hyg.1485)
  before
  case h
  a : Array Nat
  i : Fin ?m.17849
  ⊢ @LE.le Nat instLENat ?m.17849 (@Array.size Nat a)
  after
  case h.h
  a : Array Nat
  i : Fin (↑?m.17972).succ
  ⊢ @LE.le Nat instLENat ?m.17971 (@Array.size Nat a)
  • [.] Fin.val_lt_of_le✝ : none @ ⟨16, 51⟩†-⟨16, 55⟩†
  • @Fin.val_lt_of_le : ∀ {n b : Nat} (i : Fin b),
      @LE.le Nat instLENat b n →
        @LT.lt Nat instLTNat (↑i) n @ ⟨16, 51⟩†-⟨16, 55⟩†
```

**Comment by nomeata** [comment]
More debugging shows this:
```lean
opaque fin_max {n: Nat} (f: Fin n → Nat) : Nat
set_option maxRecDepth 30 in
-- NB: Important to not specify the implicit argument of fin_max
def test (a: Array Nat) : Nat := @fin_max _ fun i =>
  let h : i < a.size := by apply Fin.val_lt_of_le; get_elem_tactic_trivial
  a.get ⟨i, h⟩

set_option pp.proofs true in
#print test.proof_1
```

The goal at the crucial step is
```
a : Array Nat
i : Fin ?m.27
⊢ ↑i < a.size
```

And after the `apply` we have
```
a : Array Nat
i : Fin ?m.27
⊢ ?m.27 ≤ a.size
```
and now `apply Fin.val_lt_of_le` applies again, due to accidential defeq. Adding `with_reducible` helps here.

With this fix, the you’ll get an error message until you constrain the implicit argument of `fin_max`, though. One could say that given
```
a : Array Nat
i : Fin ?m.27
⊢ ↑i < a.size
```
the `get_elem_tactic` should unify `?m.27` with `a.size`, but I am not sure.
