### ISSUE TITLE
RFC: `lean -Werror=linter.unusedVariables` for `MessageData.tagged`

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/lean4#5194]
### Proposal

Compilers like `gcc` offer flags like `-Werror=return-type` to promote specific warnings into errors and command-line exit codes.
Lean already has a mechanism for labelling log message: `MessageData.tagged`, which could be extended to support this.

My proposal is that:
* Lean should gain a `Werror=` flag, that matches against `MessageData.tagged` to determine which messages to promote to errors. Optionally this could use wildcard matching, so that `-Werror=linter.*` matches all linters, etc. I specifically call out `lean` rather than `lake`, to enable external build systems to access this feature, just as `-Werror` is a flag to `gcc` not `make`.
* The message emitted by theorems using `sorry` should be tagged in some way (if it is not already)
* `lean --json` should include the tag from ``MessageData.tagged `linter.foo msg`` as a `"tagged": ["linter", "foo"]` field. This can then be processed by `lake` or other analysis tools that want more control than just `Werror=`. For reference, `gcc --json` outputs this information as a `"option": "-Wlinter.foo"` field.

### Community Feedback

Discussed over email with @tydeu.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by Kha** [comment]
> I specifically call out lean rather than lake, to enable external build systems to access this feature, just as -Werror is a flag to gcc not make.

Would this part be covered by the JSON output, or would external systems rather like to not have to think about this in your view?

**Comment by Kha** [comment]
I'm asking because we probably wouldn't have implemented `warningsAsErrors` in Lean in the first place if it had been clear that putting that logic in Lake was strictly better (because it only fails at the very end of the build).

**Comment by eric-wieser** [comment]
> would external systems rather like to not have to think about this in your view?

It would certainly be nice to have that option. While you can of course do something like `lean --json ... | jq ...` in these external systems, this now ends up adding a dependency on `jq`, `bash`, and possibly a shell quoting nightmare (https://github.com/bazelbuild/bazel/issues/5511 means that you can't process stdout in build rules so have to do so in a script).

Perhaps that overhead is worth it to allow the external systems to recover the lake behavior of only failing at the end of the build, but it would be preferable to have the overhead be opt in, and to get `-Werror` behavior out of the box.
