### ISSUE TITLE
RFC: removing let pattern matching

### ISSUE THREAD

**Issue by Command-Master** [leanprover/lean4#5216]
### Proposal

Currently pattern matching with `let` doesn't keep the definition of the value. I believe this conflicts with the rest of the behavior of `let` and is confusing, especially for new users ([example 1](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/How.20do.20I.20write.20a.20.60have.3A.60.20into.20my.20function.20for.20termination/near/451365660), [example 2](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/explanation.20of.20behavior.20of.20existential/near/464985178), [example 3](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Get.20hypotheses.20for.20pattern-matching.20.60let.60)), and so should be removed or linted against, and `have pattern := value` will have to be used instead.

An alternative option is to change it to keep the value, e.g. `let (a, b) := l` will behave like `let a := l.1; let b := l.2`, but this will require more effort.

### Community Feedback

[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Let.20pattern.20matching).

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by nomeata** [comment]
Reasonable suggestion, although a bit counterintuitive for uses of Lean as a functional programming language.

It may make sense for mathlib to implement a linter for this, and enforce this there (first), and if that works well reconsider if this should be the general rule for lean.

**Comment by lecopivo** [comment]
I would really like to see this changed. I ran into this problem when writing simp theorems for simplifying code were I care about let bindings and let patterns on rhs of the theorem was not behaving as I expected. 

I would really like if `let (a, b) := l` de sugars into `let ab := l; let a:= ab.1; let b:= ab.2`. The additional `ab`  let is there because `l` can be non trivial computation.

I think that in my use case of simp theorems, an alternative solution could be to add something like`zetaIota` option to `whnf` which would reduce match statement but would introduce appropriate let bindings.
For example `match (x,yz) with (a,b,c) => f a b c` would be reduced to `let a := x; let bc:= yz; let b := bc.1; let c := bc.2; f a b c`. However, I don't think this solves the original issue.

**Comment by Kiiyya** [comment]
I ran into this problem as well. It would be sweet if `let (a, b) := x` desugars into `let a := x.1`. I imagine this will be non-trivial to generalize and get the metaprogramming right for anything other than product types though, but at least having product types is neat. What about `inductive T : Nat -> Type | foo : String -> T 0 | bar : Nat -> T 1`, and then `let (.foo s) := t` given `t : T 0`?

Alternatively, `let h@(a, b, c) := x` as a shorthand for `match h : x with (a, b, c) => ...`, but I am not a fan of this as much as the above.

**Comment by Kha** [comment]
Result from triage team discussion: we agree that this behavior can be confusing, but the alternatives are confusing to programmers as well. It also conflicts with #3559. Thus we don't see a way to acceptance; a downstream linter like mentioned by Joachim would be a better approach.

**Comment by eric-wieser** [comment]
Can we change the pattern matching syntax to use `have` instead of `let`? That way the semantics are at least not surprising. `let` matching could be deprecated rather than outright removed, to avoid downstream breakage.

**Comment by nomeata** [comment]
> Can we change the pattern matching syntax to use `have` instead of `let`?

That seemed unreasonably arcane to the (functional) programmer, where `let` is very familiar and `have` strange.

**Comment by eric-wieser** [comment]
Would I be right in claiming that dependent types are already unreasonably arcane to many (functional) programmers?

A lot of users get confused between `have` and `let`, and I think the current categorization of:

* `let`: "works" with dependent types without forgetting value
* `have`, `let $patt`, `let rec`: does not work with dependent types as it forgets values

is hard to teach.

I'm not proposing that we rip `let` away from the functional programmers that Lean wants to attract, but there could be a disabled-by-default pedantic mode that suggests they replace such offending `let`s with `have`s instead.

**Comment by nomeata** [comment]
> there could be a disabled-by-default pedantic mode that suggests they replace such offending `let`s with `have`s instead.

Absolutely - and that pedantic mode could be a linter you opt-in to use, and if it's opt in it may well live in mathlib or other downstream repo (at first), mayn't it?

**Comment by eric-wieser** [comment]
Indeed; but for the linter to exist in mathlib, the `have rec` and `have $patt` syntax it favors would also have to exist. Would you be opposed to these alternative spellings living in core, where I imagine they are much easier to support?

**Comment by nomeata** [comment]
The `have` variant exists, doesn't it?

```
def foo := have (a,b) := (true, false); a

#eval foo
```

I have doubts that debating and introducing `have rec` is really worth it at this point, in the presence of bigger fish to fry, though.

**Comment by eric-wieser** [comment]
Huh, I was somehow certain that `have` didn't support pattern matching - thanks for setting me straight!

I would hope that `have rec` as a synonym for `let rec` would be quite noncontroversial given the `have $patt` synonym for `let $patt`, but indeed it is a much smaller fish to fry.

The last missing piece is of course `have mut,` but that would actually imply different semantics that I think no one cares about!

**Comment by digama0** [comment]
Also relevant: `have` and `let` have subtly different grammars, for no particularly good reason I can tell. For example `let := e; e` is not legal, and `let x[0] := e; e` is also illegal for reasons to do with array updates, both of which do not apply to `have`. I would very much like to not have two copies of the grammar productions here resulting in accidental divergence between them. (Ditto for `∀` vs `∃`...)

**Comment by nomeata** [comment]
> Also relevant: have and let have subtly different grammars, for no particularly good reason I can tell. 

That’s annoying, thanks for flagging this. Do we have an issue for this already? If this is easy to fix it’s probably good to fix before too many people stumble over it.

**Comment by digama0** [comment]
No issue AFAIK.

**Comment by eric-wieser** [comment]
This confusion [came up again on Zulip](https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/A.20question.20regarding.20the.20eta.20rule.20for.20the.20product.20type/near/498507169)
