### ISSUE TITLE
open .. in .. fails for parser

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lean4#529]
The `open .. in ..` syntax seems to fail for the `declId` parser (and maybe other ones?), as in the example below. Writing an explicit `section` works. CC @Kha 

```lean
open Lean.Parser.Command in
def syntaxMatcher : Unit := 
  match Lean.Syntax.missing with
    | `(declId|$id:ident$[.{$ls,*}]?) => () -- unknown parser declId
    | _                               => ()

section
open Lean.Parser.Command -- global `open`
def syntaxMatcher₂ : Unit := 
  match Lean.Syntax.missing with
    | `(declId|$id:ident$[.{$ls,*}]?) => () -- works
    | _                               => ()
end
```

**Comment by Kha** [comment]
Yes, parsers are currently activated only in between top-level commands, whereas open-in is (parsed as) a single command. We've talked about supporting registering new parsers while parsing in the future, which would also be important for declaring notations within inductive/structure commands. The big caveat is that it would/should not work inside quotations, which are parsed without interpretation, but that is already true for your second block.
