### ISSUE TITLE
`structure A; abbrev B := A; structure C extends B` fails

### ISSUE THREAD

**Issue by euprunin** [leanprover/lean4#5417]
### Description

The following fails with `'B' is not a structure`:

```
structure A
abbrev B := A
structure C extends B
```

Expected non-failure.

### Context

[Lean Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/class.20abbrev.20set-up.20not.20seeing.20through.20other.20abbrevs)

### Steps to Reproduce

```
class OK₁
class abbrev OK₂ := OK₁
class OK₃ extends OK₂

class FAIL₁
abbrev FAIL₂ := FAIL₁
class FAIL₃ extends FAIL₂

structure OKAY₁
class abbrev OKAY₂ := OKAY₁
structure OKAY₃ extends OKAY₂

structure FAILURE₁
abbrev FAILURE₂ := FAILURE₁
structure FAILURE₃ extends FAILURE₂
```

**Comment by nomeata** [comment]
Hello, and thanks for your report. I'm not sure if this is really a big - after all `B` isn't a structure, but an abbreviation.

One could argue that the structure construction could look through the abbreviation. But it's one more feature to design, implement, document and maintain. Is it really worth it? Is this preventing you from writing the code you need to write in a serious way?

**Comment by kmill** [comment]
@nomeata I suggested reporting this one. My thought was that we have a number of features that unfold definitions anyway (like dot notation), so we should support this too.
