### ISSUE TITLE
Possibly dangerous paradox

### ISSUE THREAD

**Issue by vporton** [leanprover/lean4#547]
I don't know whether you are aware of it, but I found a paradox new for me. You should make sure it does not affect Lean:

This shows something that appears to be a contradiction in ZF:

https://arweave.net/RJ4DRuRjdVWqJ5RBHB30SXDBXATzqmAV3Qs1b6f1ykw

(Note that by set-definition I mean it's numeric code, in an encoding such as Godel's encoding.)

---

It seems I understood why the error:

S is a function in a model of ZF, not in the formal system the proof is written. So, it's illegal to use it in the proof.

That's a very beautiful sophism.

What happens if we try to define S inside ZF? It should fail (unless ZF is contradictory). But how does it fails?

That is an practically useful question, because I really made this error today.

Digging deeper: If we would be able to prove that S exists, this would be enough to trigger the contradiction in ZF.

If we attempt to prove its existence, we try to map the set definition { x in A | P(x) } into the corresponding set, but we to fail to do that.

Note that this paradox is pertinent not to only to ZF but even to predicate logic:

Let P be encoding of a one-variable predicate. Then define the one-variable predicate S(Q) encoded by Q as S(Q)(P) <=> not (S(P))(P). Then S(Q)(Q) <=> not S(Q)(Q).

Oops! Mathematicians commonly do this trick: Let S be a function from some expression X of our formal system to another expression S(X) of our formal system. It is pertinent to logic studybooks! And that was an error! Possibly millions of math logic articles are wrong!

**Comment by leodemoura** [comment]
The issue tracker for Lean is not the appropriate place for discussing this kind of result.
