### ISSUE TITLE
`simp` fails to see through `abbrev`

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lean4#5606]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [X] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [X] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [X] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

The following `simp` call fails to unfold the `abbrev` `Bar`.

```lean
axiom Foo : Prop → Prop

abbrev Bar := ∀ P, True → Foo P

example (P : Prop) (h : Bar) : False := by
  simp only [forall_const] at h -- fails

example (P : Prop) (h : Bar) : False := by
  unfold Bar at h
  simp only [forall_const] at h -- succeeds
```

**Expected behavior:** both `simp` calls succeed.

**Actual behavior:** the first `simp` call fails.

### Additional Information

The issue does not occur with `Foo : Prop` and `Bar := True -> Foo`.
 
### Versions

`"4.12.0-nightly-2024-10-02"`

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by leodemoura** [comment]
This is not a bug. In the first example, `forall_const` is not applicable because we cannot unify `?a -> ?b` with `Bar`. Note that `Bar` is unfolded during unification, but `?a -> ?b` and `∀ P, True → Foo P` cannot be unified. 
In the second example, `forall_const` is applied to the **subterm** `True -> Foo P`.
