### ISSUE TITLE
"-f" flag not recognized as alternative to "--features"

### ISSUE THREAD

**Issue by James-Oswald** [leanprover/lean4#5682]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [X] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [X] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [X] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

`lean -h` states that `lean -f` may be used as shorthand for `lean --features`.
```
  -f, --features         display features compiler provides (eg. LLVM support)
```
 while `lean --features` works as intended, `-f` is not recognized as a valid flag. 

### Steps to Reproduce

```
elan run nightly lean -f
```

**Expected behavior:** 
Identical output to `lean --features`

**Actual behavior:** 
```
/home/james/.elan/toolchains/nightly/bin/lean: invalid option -- 'f'
Unknown command line option
Lean (version 4.12.0-nightly-2024-10-12, x86_64-unknown-linux-gnu, commit a3bc4d235961, Release)
Miscellaneous:
...
```

### Versions

Output of `elan run nightly lean -v`
Lean (version 4.12.0-nightly-2024-10-12, x86_64-unknown-linux-gnu, commit a3bc4d235961, Release)

OS Version: Ubuntu 22.04.3 LTS

### Impact

Minimal to no impact, just an inconsistency between information in the help command and actual behavior.

**Comment by nomeata** [comment]
Thanks for raising this. Care to make a PR that adjusts the help string to reality? Probably the easiest course of action. Ideally before any bike shedding about the CLI interface ensues :-)
