### ISSUE TITLE
`ShareCommon.Object.hash` assigns mismatching hashes to equal objects

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/lean4#5831]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

`ShareCommon.Object.hash` can assign mismatching hashes to objects considered equal.

### Context

[Broader context that the issue occurred in. If there was any prior discussion on [the Lean Zulip](https://leanprover.zulipchat.com), link it here as well.]

### Steps to Reproduce

```lean
import Lean

unsafe def badHash (s : String) : UInt64 := ShareCommon.Object.hash <| unsafeCast s

def test : IO Unit := do
  let s2 := "tes"
  let mut s := "test"
  s := s.extract ⟨0⟩ ⟨3⟩
  unless s = s2 do throw <| .userError "Not equal"
  unless unsafe (badHash s == badHash s2) do throw <| .userError "Differing hashes"

#eval test
```
**Expected behavior:** no errors
**Actual behavior:** hashes do not match

### Versions

4.12.0-nightly-2024-10-24

### Additional Information

I may have a patch for this tomorrow.

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by digama0** [comment]
I think this needs more context, it seems easy to define this as "not a bug" given that you have plainly used an `unsafe` function and also this works exactly as I would expect from something that hashes pointers.

**Comment by Kha** [comment]
This is still missing context: could you please describe what the impact of this issue on your work is?

**Comment by tkoeppe** [comment]
Sure, I have a few points to make:

1) The current code exhibits undefined behaviour. Given the fundamental role as a source of trust that a theorem prover might be wanted to be used as, this is somewhat problematic (how can you trust code that could do whatever?).

2) The existence of the current undefined behaviour triggers our runtime analysers, thus preventing these analysers from detecting "real" bugs in our users' code. This means that having lean in our toolchain is an obstacle to validating the correctness of our overall projects.
