### ISSUE TITLE
Build breaks: error: no member named 'm_ptr' in 'parray<T, ThreadSafe>'

### ISSUE THREAD

**Issue by yurivict** [leanprover/lean4#5860]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description
```
In file included from /wrkdirs/usr/ports/math/lean/work/lean-3.51.1/src/library/init_module.cpp:54:
/wrkdirs/usr/ports/math/lean/work/lean-3.51.1/src/library/parray.h:592:20: error: no member named 'm_ptr' in 'parray<T, ThreadSafe>'
  592 |         m_cell = s.m_ptr;
      |                  ~ ^
/wrkdirs/usr/ports/math/lean/work/lean-3.51.1/src/library/parray.h:593:11: error: no member named 'm_ptr' in 'parray<T, ThreadSafe>'
  593 |         s.m_ptr = nullptr;
      |         ~ ^
2 errors generated.
```

[log](https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/p645a502a4f60_s8b2e7da7085/logs/lean-3.51.1.log)

### Context

The failure occurs during the build of the FreeBSD port.

### Versions

3.51.1
clang-18
FreeBSD 14.1

**Comment by Kha** [comment]
This is the repo for Lean 4. Lean 3 is no longer maintained.
