### ISSUE TITLE
`lake update` deletes files outside the `.lake` directory

### ISSUE THREAD

**Issue by fgdorais** [leanprover/lean4#5876]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [X] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [X] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [ ] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

`lake update` deletes directories required by path when the lakefile has a name error. In particular, `lake update` can be made to delete any path with a malicious `lakefile.toml`!

### Context

This was discovered in this [Zulip discussion](https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/Improving.20the.20Windows.20user.20experience/near/479499172). I was refining the setup described there where the dependency had path `..`. I made a typo in the name of the dependency and, upon `lake update`, the whole thing was deleted. That caused havoc since it also deleted the cwd!

### Steps to Reproduce

*Playing with this bug is extremely unsafe!*

These reproduction steps, run precisely, in the indicated order, should not cause unexpected harm.

1. Create two directories `A` and `B` within the same parent directory. 
2. Add `lean-toolchain` files containing `leanprover/lean4:v4.13.0-rc4` in each directory.
3. Add a basic package structure in each directory with respective package names `A` and `B` by running `lake init`.
4. Add this requirement to package `A`'s `lakefile.toml`
```toml
[[require]]
name = "X"
path = "../B"
```
5. Run `lake update` in package `B` to generate `lake-manifest.json`.
6. Run `lake update` in package `A`...

**Expected behavior:** At the last step, lake should report `error: A: package 'B' was required as 'X'` and not delete anything.

**Actual behavior:** At the last step, lake does report `error: A: package 'B' was required as 'X'` but also deletes the entire `B` directory!

### Versions

Lean (version 4.13.0-rc4, arm64-apple-darwin23.6.0, commit 480d7314a2c4, Release)

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by tydeu** [comment]
To add some additional info, this bug has unfortunately been present since `v4.8.0-rc1`.
