### ISSUE TITLE
Variables not visible inside calc statement

### ISSUE THREAD

**Issue by Dante3085** [leanprover/lean4#5921]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [X] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [X] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

I was working on understanding the following example from the chapter [Quantifiers and Equality](https://leanprover.github.io/theorem_proving_in_lean4/quantifiers_and_equality.html) in _Theorem Proving in Lean 4_ about _Calculational Proofs_ and was a bit confused as to why none of the declared variables are visible inside the `calc` statement.

```
variable (a b c d e : Nat)
variable (h1 : a = b)
variable (h2 : b = c + 1)
variable (h3 : c = d)
variable (h4 : e = 1 + d)

theorem T : a = e :=
  calc
    a = b      := h1
    _ = c + 1  := h2
    _ = d + 1  := congrArg Nat.succ h3
    _ = 1 + d  := Nat.add_comm d 1
    _ = e      := Eq.symm h4
```

To be precise, these are the errors I am getting:

```
04-quantifiers-and-equality-exercises.lean:131:8: error: unknown identifier 'b'
04-quantifiers-and-equality-exercises.lean:131:18: error: unknown identifier 'h1'
04-quantifiers-and-equality-exercises.lean:132:8: error: unknown identifier 'c'
04-quantifiers-and-equality-exercises.lean:132:18: error: unknown identifier 'h2'
04-quantifiers-and-equality-exercises.lean:133:8: error: unknown identifier 'd'
04-quantifiers-and-equality-exercises.lean:133:36: error: unknown identifier 'h3'
04-quantifiers-and-equality-exercises.lean:134:12: error: unknown identifier 'd'
04-quantifiers-and-equality-exercises.lean:134:31: error: unknown identifier 'd'
04-quantifiers-and-equality-exercises.lean:135:26: error: unknown identifier 'h4'
```

Putting the variables directly as parameters to the theorem T fixes the issue:

```
theorem T₂ (a b c d e : Nat) (h1 : a = b) (h2 : b = c + 1) (h3 : c = d) (h4 : e = 1 + d) : a = e :=
  calc
    a = b      := h1
    _ = c + 1  := h2
    _ = d + 1  := congrArg Nat.succ h3
    _ = 1 + d  := Nat.add_comm d 1
    _ = e      := Eq.symm h4
```

### Steps to Reproduce

1. Copy the code from the first listing to VsCode or https://live.lean-lang.org/#project=lean-nightly.

**Expected behavior:** I expect all variables to be visible inside the calc statement as the book implies.

**Actual behavior:** None of the variables are visible inside the calc statement.

### Versions

Lean (version 4.11.0, x86_64-w64-windows-gnu, commit ec3042d94bd1, Release)
Windows 11 Pro

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by nomeata** [comment]
The rules for the visibility of variables has changed in 4.11, see release notes in https://github.com/leanprover/lean4/releases/tag/v4.11.0. Probably Theorem Proving in Lean hasn't been updated yet. I'll close this issue, but feel free to correct me if there is an issue with lean.
