### ISSUE TITLE
What is intended difference between `box` and `box_uint` versions?

### ISSUE THREAD

**Issue by vvs-** [leanprover/lean4#594]
This question arouse while investigating the bug on 32-bit architecture which turned out to be three different bugs.

From the one hand `UInt32` seems to be required boxing using `box_uint32` version. OTOH `pure 0` and `pure ()` should have the same internal representation for `main` to work properly, so `IO Unit` should also use `box_uint32`. But here lies the problem: `lean_obj_tag` is then used everywhere to access boxed value and in this case it doesn't work properly with `box_uint32`, so it always return zero.

It's unclear for me how to proceed.

**Comment by Kha** [comment]
> OTOH `pure 0` and `pure ()` should have the same internal representation for `main` to work properly

No, I think the bug here is in the code emitted for `main` (and the corresponding code in the interpreter). It should use `lean_unbox_uint32` if the return type is `IO UInt32`.

**Comment by vvs-** [comment]
Of course it should. But in that case internal representation for `IO UInt32` and `IO Unit` will be different. And `main` with return type `IO Unit` will just crash. That's the price of "awesome" hack which is commented in `ir_interpreter.cpp`.

**Comment by Kha** [comment]
That's not what I wrote: it should use `lean_unbox_uint32` *only* if the return type is `IO UInt32`

**Comment by vvs-** [comment]
That would be great!

But that would require two different implementations instead of the current one. In fact there should be four, considering compiler and interpreter. And this won't be conservative fix anymore as it would affect all platforms. I'm not an expert in Lean and don't use 64-bit platform, so I won't dare to fix it myself :disappointed:

Nevertheless, it still bothers me that `lean_obj_tag` gives different results on 32-bit and 64-bit platforms when using `lean_box_uint32`. Is there a good reason for that? It looks like an oversight to me, or at least undefined behavior.

**Comment by Kha** [comment]
Yes, using `lean_obj_tag` on a tagged pointer is meaningless. And `UInt32` is boxed by tagging on 64-bit because anything else would be wasteful. So that function should simply never be used on a `UInt32` on any platform.

**Comment by vvs-** [comment]
Thanks!
