### ISSUE TITLE
RFC: unify the syntax of `rw` and `unfold`

### ISSUE THREAD

**Issue by madvorak** [leanprover/lean4#5960]
Currently `unfold` is:
```
unfold List.map at hl
```
Currently `rw` is:
```
rw [List.map_cons] at hl
```
It would be nice to have both without `[]` if possible.
If not, I'd prefer to have both with `[]` for consistency.

**Comment by kmill** [comment]
@nomeata There are annoying ambiguities when you don't have the square braces, like in `(a, by rw b, c)`. I think it would make sense having square braces for `unfold` too, though I wouldn't mind if the special case `unfold ident` were allowed.

With the new configuration syntax, there's another ambiguity where `rw (some_identifier then_maybe_arguments)` will put an "expected :=" error after `some_identifier`. We could fix that at the cost of tab completion of configurations not working as well (unless Marc can figure out some magic).

**Comment by Kha** [comment]
I general, tactics taking `term`s usually use brackets while tactics taking `ident`s don't

**Comment by nomeata** [comment]
With the exception of `induction`, which doesn’t have brackets per se, but `induction` and end-of-line (or the `using` or `generalizing` keyword) serve as brackets.

**Comment by nomeata** [comment]
Anyways, as much as I would like to be able to use `rw` without `[`…`]`, change this is not worth the churn.
