### ISSUE TITLE
Hover on let declarations gives type of type in VSCode

### ISSUE THREAD

**Issue by AurelienSaue** [leanprover/lean4#597]
```lean
example : TacticM Unit := do
  let x := 1       -- hover on x is "Nat : Type" instead of "x : Nat"
  let g ← getGoals -- hover on g is "Type" instead of "g : List MVarId"
  return ()
```

**Comment by Kha** [comment]
Can't reproduce on 0db80c6ea8; this should have been fixed recently. Please include your Lean version as instructed in the issue template. And please make sure examples are executable without the need for further `open` or `import` statements.

**Comment by AurelienSaue** [comment]
Indeed my apologies
