### ISSUE TITLE
Nat.ble 0 0 evaluates to false, should be true

### ISSUE THREAD

**Issue by esb-dev** [leanprover/lean4#6086]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

```
#eval Nat.ble 0 0 -- evaluates to false, but should be true
```

### Context

[Discussion on Zulip](https://leanprover.zulipchat.com/#narrow/channel/113489-new-members/topic/Nat.2Eble.20.3F.3F.3F)

### Steps to Reproduce

1.  just
```
#eval Nat.ble 0 0
#eval Nat.ble 42 42
```

**Expected behavior:** [Clear and concise description of what you expect to happen]
should evaluate to true

**Actual behavior:** [Clear and concise description of what actually happens]
but evaluates to false

### Versions

[Output of `#version` or `#eval Lean.versionString`]
"4.11.0"

[OS version, if not using live.lean-lang.org.]
Mac OSX Sequoia 15.1

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Command-Master** [comment]
This also happens for `Nat.blt`, and breaks soundness of `Lean.ofReduceBool`
