### ISSUE TITLE
RFC: Visual Separators in Number Literals

### ISSUE THREAD

**Issue by Command-Master** [leanprover/lean4#6199]
### Proposal

Many languages (Java, Python, Perl, Ruby, Julia, Ada, JavaScript, PHP, D, Elixir, C#, C++, Rust, Haskell etc.)  support using some character as a visual separator in number literals, mostly `_`, except C++ which uses `'`. This suggestion is for this behavior in Lean.

### Community Feedback

[Zulip discussion](https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/Separator.20character.20for.20numbers)

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others benefit from the changes in this proposal being added, please ask them to add :+1: to it.

**Comment by kmill** [comment]
I looked at a few languages for their lexical syntaxes, and there are broadly two conventions that use `_`. First, the "Ada convention" (used by [Ada](https://ada-lang.io/docs/arm/AA-2/AA-2.4/#241--decimal-literals), [Python](https://docs.python.org/3/reference/lexical_analysis.html#integer-literals), and [Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#numeric_separators)) is that the sequence digits in the literal have the following lexical syntax:
```
numeral := digit many("_"? digit)
```
Second, the "Rust convention" (used by [Rust](https://doc.rust-lang.org/reference/tokens.html#integer-literals), [Java](https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-IntegerLiteral), and [C#](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#6453-integer-literals)):
```
numeral := digit many(digit <|> "_")
```
(For other bases, Rust allows `_` at the beginning, like `0b_11_00`.) Java and C# require that the numeral end in a digit.

I don't have much of a preference over whether it should be allowed to have sequences of `_`'s, but I think we should adopt a lexical syntax that satisfies the following properties:
- numerals should not be allowed to end with `_`
- numerals with a base prefix should be allowed to begin with `_` (like `0b_11_00`).

**Comment by kmill** [comment]
I made a reference implementation of the RFC at #6204 and I'll leave it to the triage team to decide whether to accept it.

**Comment by edwardzcn-decade** [comment]
Add lexical structure information for similar proof tools.

[Coq](https://coq.inria.fr/doc/V8.20.0/refman/language/core/basic.html#lexical-conventions): Uses "Rust conventions" and allows continuing underscores. 
[Isabelle](https://isabelle.in.tum.de/doc/isar-ref.pdf): I couldn’t find a similar lexical allowance for separators. This requires further verification.

**Comment by Kha** [comment]
RFC accepted!
