### ISSUE TITLE
MVarId.revertAll snags auxiliary declarations, leading to termination issues

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/lean4#6263]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [ ] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [ ] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [ ] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

`Lean.MVarId.revertAll` fails to ignore auxiliary declarations if `variable` is used.

### Context

[Broader context that the issue occurred in. If there was any prior discussion on [the Lean Zulip](https://leanprover.zulipchat.com), link it here as well.]

### Steps to Reproduce

```lean
import Lean

open Lean.Elab.Tactic

variable (p q : Prop)
theorem foo (h : p ∧ q) : q ∧ p := by
  run_tac liftMetaTactic1 (·.revertAll)
  sorry
```

**Expected behavior:** Goal is `⊢ ∀ (p q : Prop), p ∧ q → q ∧ p`, no errors

**Actual behavior:** Goal is `⊢ ∀ (p q : Prop), p ∧ q → (p ∧ q → q ∧ p) → q ∧ p`, and the error is
```
fail to show termination for
  foo
with errors
failed to infer structural recursion:
Not considering parameter p of foo:
  it is unchanged in the recursive calls
Not considering parameter q of foo:
  it is unchanged in the recursive calls
Cannot use parameter h:
  the type p ∧ q does not have a `.brecOn` recursor
```

### Versions

4.14.0-rc3

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by eric-wieser** [comment]
Using `clearAuxDecls` seems to work, but the implementatoin of `revertAll` suggests it is supposed to handle this for me.

**Comment by nomeata** [comment]
So there is a workaround, you are unblocked and this is just™ a matter of misleading API design/documentation?

**Comment by eric-wieser** [comment]
Yes, I am unblocked, but these lines make me thing this function was intended to operate as I was hoping it would:

https://github.com/leanprover/lean4/blob/3752241edd8861eff09872bc99245d0a337be577/src/Lean/Meta/Tactic/Grind/RevertAll.lean#L17-L21

The current behavior seems to be "ignore _leading_ auxiliary declarations", so I'd lean towards this being a design issue rather than a documentation issue.
