### ISSUE TITLE
BinomialHeap does not work when multiple elements have the same priority

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lean4#629]
MWE:

```lean
import Std.Data.BinomialHeap

open Std

def test : BinomialHeap (Nat × Nat) (λ (x, _) (y, _) => x < y) :=
  BinomialHeap.empty.insert (0, 1) |>.insert (0, 2) |>.insert (0, 3)

#eval test.toList
```

Expected output of the `#eval`: `[(0, 1), (0, 2), (0, 3)]` (or a permutation).
Actual output: `[(0, 2), (0, 2), (0, 1)]`.

Lean version: current master.

**Comment by leodemoura** [comment]
@JLimperg `BinomialHeap` is currently dead code in the repo. We don't use it anymore to implement Lean.
Are you willing to take ownership of this module and fix this issue? It would be super helpful for us.

**Comment by JLimperg** [comment]
Sure! I'll try to make a properly verified version while I'm at it.

**Comment by JLimperg** [comment]
For the verified version, I think I need either wfrec or a computable recursor for nested types. But this is not a high priority anyway.
