### ISSUE TITLE
`PUnit.eq_punit` always tried during `simp`

### ISSUE THREAD

**Issue by dselsam** [leanprover/lean4#635]
Adding a trace message at https://github.com/leanprover/lean4/blob/master/src/Lean/Meta/Tactic/Simp/Rewrite.lean#L67 shows that `PUnit.eq_punit` is tried at every step during `simp`. Indeed, the discrimination tree keys for the LHS is `#[Lean.Meta.DiscrTree.Key.star]`. Does it really need to be a simp lemma?

**Comment by leodemoura** [comment]
It doesn't. The discrimination tree key is correct.
Someone submitted a PR for disabling it in the past, but we didn't merge because the `do` unchained paper examples relied on it, and the paper was under review at the time. We can selectively enable the theorem there.
I will disable the theorem.
