### ISSUE TITLE
`Int.reduceNeg` simproc produces invalid proofs

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/lean4#6467]
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

The `Int.reduceNeg` simproc produces invalid proofs in the presence of Expr.mdata

### Context

Discovered while working on leanprover-community/mathlib4#20169

### Steps to Reproduce

```lean
theorem confuses_the_user : -(no_index (OfNat.ofNat <| nat_lit 2)) = -2 := by
  simp
  -- goal is `⊢ False`, but `simp` is supposed to be a safe tactic!

theorem rejected_by_kernel : -(no_index (OfNat.ofNat <| nat_lit 2)) = (2 : Int) := by simp only [Int.reduceNeg]

theorem its_true_really : -(no_index (OfNat.ofNat <| nat_lit 2)) = -2 := by
  rfl
```

**Expected behavior:** `simp` should adjust the goal to something equivalent, close the goal with a valid proof, or do nothing

**Actual behavior:** `simp` replaces a `True` goal with `False`, constructing an invalid proof along the way.

### Versions

Lean 4.16.0-nightly-2024-12-28

### Additional Information

[Additional information, configuration or data that might be necessary to reproduce the issue]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by nomeata** [comment]
This looks fishy:

https://github.com/leanprover/lean4/blob/ffac974dba799956a97d63ffcb13a774f700149c/src/Lean/Meta/Tactic/Simp/BuiltinSimprocs/Int.lean#L51-L62

Introduced in https://github.com/leanprover/lean4/pull/3187.

**Comment by eric-wieser** [comment]
My guess is that this is trying to avoid inserting a `-0`. Replacing `let arg := e.appArg! ` with `let arg := e.appArg!.consumeMData` seems to also fix the issue, but indeed the code looks fishy either way.
