### ISSUE TITLE
Leanpkg fails on comments

### ISSUE THREAD

**Issue by saulshanabrook** [leanprover/lean4#652]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The TOML parser currently does not support comments, leading `leanpkg` to fail if you add one.

### Steps to Reproduce

1. Add a comment to your `leanpkg.toml`
2. Run a command that loads the `leanpkg.toml` (like `leanpkg print-paths`) or open the package in VS Code

**Actual behavior:** An error is printed saying `expected end of input`

**Reproduces how often:** 100%

### Versions

Running from source:

```bash
$lean --version
Lean (version 4.0.0, commit 34d8ecc06651, Release)
```

### Additional Information

I am happy to try to add comment support to the TOML parser. I see that there are some `HACKHACKHACK` comments in it, so I assume it will have to be re-written anyway, but even so if a PR to fix this bug would be useful, it would be a good opportunity to practice writing lean.

**Comment by leodemoura** [comment]
See https://github.com/leanprover/lean4/issues/826
