### ISSUE TITLE
Dot notation selects wrong definition in inheritance chain

### ISSUE THREAD

**Issue by tydeu** [leanprover/lean4#655]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

If a given definition `a` is a field of structure `A` and `b` is a term of structure `B` which extends `A` and defines it own `B.a`, `b.a` will use `A.a` instead of `B.a`.

### Steps to Reproduce

```lean
structure A := a : Nat
structure B extends A := b : Nat

def B.a (self : B) := self.a + self.b
def b : B := {a := 1, b := 2}

#eval b.a -- expect 3, get 1
```

**Expected behavior:**

I would expect `b.a` to use `B.a` not `A.a`.

**Actual behavior:**

 `b.a` uses `A.a`.

**Reproduces how often:** 

Always. However, `A.a` must be a field of `A` -- this does not occur if `A.a` is just a definition. For example:

```lean
def A.c (self : A) := self.a + 1
def B.c (self : B) := self.b + 1

#eval b.c -- 3 (as expected)
```

### Versions

OS: Windows 20H2
`Lean (version 4.0.0-nightly-2021-09-05, commit 53a3831fd505, Release)`

### Additional Information

None.

**Comment by leodemoura** [comment]
I think we should generate an error at 
```lean
def B.a (self : B) := self.a + self.b
```
because `a` is a field of `B`. 

For example, we don't allow
```lean
structure A where
  a : Nat

def A.a (self : A) :=
  2 * self.a
```

**Comment by tydeu** [comment]
@leodemoura while that makes sense that shadowing a field is erroneous in `A.a` case, I don't see why it would be in `B.a` case. If one specifically wants the `A.a` field, they can get it by `B.toA.a`. I feel that there are many cases where it is perfectly reasonable for a child to want to shadow a parent's field with a more informative definition using the additional information the child has. This is pretty common behavior in OOP  (I know, for instance, LLVM does it a lot).

Personally, I encountered this bug when trying to make `Package` extend `PackageConfig` in Lake. Path fields in `PackageConfig` are relative to a not-yet-known package root. However, `Package` adds the knowledge of this root, thus it is desirable for its paths to be said root joined with the configuration's relative paths.

**Comment by tydeu** [comment]
@leodemoura ah, so that is a problem due to the flattening that occurs in multiple inheritance.

I wonder if it would be possible to still have the canonical name of the `C.z` field be `C.toB.z` (e.g., by making the flatten `z` inaccessible through renaming), permitting an end-user to still shadow it.

Alternatively, to keep things consistent even in the face of multiple inheritance, instead of making  the shadowing of non-inherited fields erroneous, would it instead be possible to allow the shadowing of one's own fields? After all, it still possible to directly refer to one's fields with numeric identifiers, so shadowing one does not make the field actually inaccessible. For example, the following could still work:

```lean
structure A := x : Nat
def A.x (self : A) := self.1 + 1
```

In programming contexts, the above behavior may be desirable in places where the data being stored in the structure is not exactly what one wants to present to end-users. In normal cases, the need for this could be resolved by renaming the field. However, it may actually be useful in multiple inheritance cases where one needs the field to be named like so name in order for it be properly merged with another structure with the same field name.

---

As an aside,  personally, I am still a bit bothered by how multiple inheritance in Lean works. From my experience with other OO languages I would not usually expect multiple inheritance to always merge fields with the same name, as it is entirely possible that they don't refer to the same concept. I would usually expect to disambiguate clashing fields with exactly the kind of shadowing mentioned here. For example:

```lean
structure A := x : Nat
structure B := x : Nat
structure C extends A, B
def C.x (self : C) := self.toA.x
def C.y (self : C) := self.toB.x
```

However, there obviously cases where the merging behavior is desired (e.g., mathlib), so I understand the utility. I just wonder if there might be a way to clearly specify how conflicts are resolved. This would it help clarify to end users exactly what the actual definition of multiple inheritor ends up looking like. For example

```lean
-- merge case:
structure C extends A, B with A.x & B.x => x
-- rename case:
structure C extends A, B with A.x => x, B.x => y
```

**Comment by leodemoura** [comment]
@tydeu Thanks for sharing your suggestions, but they are not converging. I disagree with the path you are proposing, and I don't believe the use cases and new features you suggested are critical for the user base. Actually, the multiple inheritance suggestion is going in the opposite direction the Lean community wants.
Language design choices are very personal, and we can quickly go into "rabbit holes" discussing these issues. 

> In programming contexts, the above behavior may be desirable in places where the data being stored in the structure is not exactly what one wants to present to end-users. 

I found your example unrealistic. One can simply write:
```lean
structure A where
  _x : Nat

def A.x (self : A) := self._x + 1
```
We can even tag the field `_x` as private.
Your suggestion is also ignoring the structure instance notation, for example,  `{ x := 5 : A }.x` would return `6` in your proposal. This is just an example of a hole in the proposal, I am not interested in discussing follow-up proposals that try to fix it (e.g., user-defined "setter" functions).

>  it is entirely possible that they don't refer to the same concept. 

Recall that the `structure` command is just creating boilerplate code. The current boilerplate code is addressing the most common cases, and what the Mathlib community needs. 
If it does not do what you want in a particular example, then you can write the structure and coercions manually without using `extends`.

Regarding the original issue, I decided an error should be generated at
```lean
def B.a (self : B) := self.a + self.b
```
I will add this test and close this issue.

**Comment by tydeu** [comment]
@leodemoura 

> Language design choices are very personal, and we can quickly go into "rabbit holes" discussing these issues.

Very true! Thanks for explaining your feelings on the matter. This is also not a major issue for me, so I can still be happy with the solution,
