### ISSUE TITLE
Put lean4-mode in a separate reposistory

### ISSUE THREAD

**Issue by AxiomCrisis** [leanprover/lean4#658]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The current install method by `straight` will clone the entire repo which is way more expensive if we only want the Emacs mode.
Even if we choose to install from loading local file, we are still required to clone the whole GitHub repository to use git pull new updates. 

If we would put the files under another repository, it would be much convenient to install.

**Comment by leodemoura** [comment]
@Kha Should we do it now? I think it is stable enough, right?
