### ISSUE TITLE
Decidable Prop to Bool coercion fails using infix And/Or

### ISSUE THREAD

**Issue by ammkrn** [leanprover/lean4#691]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
Attempting to create large-ish terms of type `Bool` using the And/Or notation eventually fails. 

These work:
```
example (xs : List Nat) : Bool :=
  (xs ≠ []) ∧ (xs.length < 10) ∧ (xs.length < 9) ∧ (xs.length < 8) ∧ (xs.length < 7) ∧ (xs.length < 6)

example (xs : List Nat) : Bool :=
  (xs = []) ∨ (xs.length > 1) ∨ (xs.length > 2) ∨ (xs.length > 3) ∨ (xs.length > 4) ∨ (xs.length > 5) ∨ (xs.length > 6)
```

These do not:
```
example (xs : List Nat) : Bool :=
  (xs ≠ []) ∧ (xs.length < 10) ∧ (xs.length < 9) ∧ (xs.length < 8) ∧ (xs.length < 7) ∧ (xs.length < 6) ∧ (xs.length < 5)

/-
type mismatch
  xs ≠ [] ∧
    List.length xs < 10 ∧
      List.length xs < 9 ∧ List.length xs < 8 ∧ List.length xs < 7 ∧ List.length xs < 6 ∧ List.length xs < 5
has type
  Prop : Type
but is expected to have type
  Bool : Type
-/


example (xs : List Nat) : Bool :=
  (xs = []) ∨ (xs.length > 1) ∨ (xs.length > 2) ∨ (xs.length > 3) ∨ (xs.length > 4) ∨ (xs.length > 5) ∨ (xs.length > 6)  ∨ (xs.length > 7)

/-
type mismatch
  xs = [] ∨
    List.length xs > 1 ∨
      List.length xs > 2 ∨
        List.length xs > 3 ∨ List.length xs > 4 ∨ List.length xs > 5 ∨ List.length xs > 6 ∨ List.length xs > 7
has type
  Prop : Type
but is expected to have type
  Bool : Type
-/
```

**Expected behavior:** [What you expect to happen]
With degenerate terms it's reasonable that this would fail, but I ran into this in the midst of what I thought was fairly normal use. If this kind of failure is expected behavior and the `/\` `\/` notations are supposed to be used sparingly for Bool, I think just a note in the manual would be fine.

**Actual behavior:** [What actually happens]
Failure with a type mismatch error.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Consistently.

### Versions
Lean: (version 4.0.0-nightly-2021-09-24, commit 2ca4188, Release).
Lean vscode extension: v0.0.33
vscode: version 1.60
MacOS Big Sur 11.4 (20F71)

**Comment by leodemoura** [comment]
Lean has a bound on the maximum coercion size. 
Your example works if you increase the limit
```lean
set_option maxCoeSize 32

example (xs : List Nat) : Bool :=
  (xs = []) ∨ (xs.length > 1) ∨ (xs.length > 2) ∨ (xs.length > 3) ∨ (xs.length > 4) ∨ (xs.length > 5) ∨ (xs.length > 6)  ∨ (xs.length > 7)
```
The value is roughly the maximum number of `Coe` instances used to construct the solution.
You can also avoid the problem by explicitly calling `decide`.
```lean
example (xs : List Nat) : Bool :=
  decide ((xs = []) ∨ (xs.length > 1) ∨ (xs.length > 2) ∨ (xs.length > 3) ∨ (xs.length > 4) ∨ (xs.length > 5) ∨ (xs.length > 6)  ∨ (xs.length > 7))
```
Another option is to use the Boolean or `||`
```lean
example (xs : List Nat) : Bool :=
  (xs = []) || (xs.length > 1) || (xs.length > 2) || (xs.length > 3) || (xs.length > 4) || (xs.length > 5) || (xs.length > 6)  || (xs.length > 7)
```
We will try to generate a better error message where we tell the user about the option `maxCoeSize`.

**Comment by ammkrn** [comment]
@leodemoura 

Thanks, I'll add a note about the `maxCoeSize` option if a good place for it in the leanprover.github.io docs appears at some point. I'll go ahead and close this since it's just the result of an option setting.
