### ISSUE TITLE
Escaping identifiers using French double quotes «» doesn't work as expected.

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#699]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The term "escaping" makes one think that the french double quotes are not literally part of the identifier, which leads one to think the following invocation of the function should be valid since in this case escaping is not technically needed:

```lean
def Foo.«bar.baz» :=
  IO.println "Hello!"

#eval Foo.bar.baz
```

This could also impact any "reflection" features lean has to find and invoke functions dynamically...

### Steps to Reproduce

See above.

**Expected behavior:**

The french double quotes should not be part of the identifier.  For example, in C# if you use "@" to escape a keyword as an identifier the "@" is not stored as part of the identifier, similarly in C# if you write "i\u0064" the id becomes "id" not "i\u0064".

**Actual behavior:** 

```
unknown identifier 'Foo.bar.baz'
```

**Reproduces how often:** 

100%

### Versions

master

**Comment by leodemoura** [comment]
This is the intended behavior. The fresh quotes are not part of the name. Names are hierarchical in Lean, and `.` is a delimiter. The `.` inside of the french quotes is not a delimiter, but a "part". See the following example where I create names programatically.
```lean
open Lean

#eval `Foo.«bar.baz» == Name.mkStr `Foo "bar.baz"
-- true

#eval `Foo.bar.baz == Name.mkStr `Foo "bar.baz"
-- false

#eval `Foo.bar.baz == Name.mkStr (Name.mkStr `Foo "bar") "baz"
-- true
```

**Comment by lovettchris** [comment]
Ah, of course, my bad, of course the "." is special.  It works correctly when I remove the . inside.  So this works as expected:

```lean

def Foo.«bar» :=
  IO.println "Hello!"

#eval Foo.bar
```
