### ISSUE TITLE
Why are Lean4 identifiers so limited?

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#700]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Identifiers are limited to the following special characters

```
ident: `atomic_ident` | `ident` "." `atomic_ident`
   atomic_ident: `atomic_ident_start` `atomic_ident_rest`*
   atomic_ident_start: `letterlike` | "_" | `escaped_ident_part`
   letterlike: [a-zA-Z] | `greek` | `coptic` | `letterlike_symbols`
   greek: <[α-ωΑ-Ωἀ-῾] except for [λΠΣ]>
   coptic: [ϊ-ϻ]
   letterlike_symbols: [℀-⅏]
   escaped_ident_part: "«" [^«»\r\n\t]* "»"
   atomic_ident_rest: `atomic_ident_start` | [0-9'ⁿ] | `subscript`
   subscript: [₀-₉ₐ-ₜᵢ-ᵪ]
```

Other languages like C# allow all Unicode letter characters, decimal digit characters, Unicode connecting characters, Unicode combining characters, or Unicode formatting characters as defined by the https://www.unicode.org/reports/tr44/

This would allow people to use "letters" from all languages, not just greed and coptic.  (and why only lower case coptic?)

I understand greek and coptic are special to math, but this doesn't seem very inclusive.  What if some amazing new math is invented using cyrillic letters or thai ?  What if someone wants to create a library of math from Ancient India?  Why not allow them to use other scripts?

### Steps to Reproduce

See above

**Expected behavior:** 

I think Lean should adopt the C# standard of any Unicode letter characters, decimal digit characters, Unicode connecting characters, Unicode combining characters, or Unicode formatting characters as defined by the https://www.unicode.org/reports/tr44/

This might also make it easier to port math from other programming languages.

**Actual behavior:** 

see above.

**Reproduces how often:**

N/A

### Versions

master

**Comment by leodemoura** [comment]
@lovettchris Good question. We can extend the set of symbols that can be used in identifiers. For example, I don't see any harm in your suggestions, but we cannot accept arbitrary symbols. For example, if we allow `+` to be in an identifier, then we would not be able to write `x+y` anymore, i.e., we would have to write `x + y`. Same for `∀`, if we do it, the community would not be able to write `∀a` anymore.

**Comment by lovettchris** [comment]
Cool, I'll create a PR where identifiers can be from the following Unicode Categories:
- Unicode letter characters, 
- Decimal digit characters (not at the start), 
- Unicode connecting characters, 
- Unicode combining characters, or 
- Unicode formatting characters as defined by the https://www.unicode.org/reports/tr44/

So yes, this of course excludes all the nifty characters we use in lean expressions, including greek lambda, Sigma and so on ...

In fact this reserved notation is also extensible isn't it?  So wouldn't the correct definition of identifier be anything that is not used in reserved "notation" ?  Is there a way to query lean for all known notations?

**Comment by leodemoura** [comment]
> In fact the Lean syntax is extensible so if I defined prefix, infix, and postfix operators wouldn't the characters I use there also need to be excluded from Identifiers? 

Correct. This was one of the motivations for restricting the set of symbols that can be used in identifiers.
Note that, users do sometimes create infix operators using valid identifier symbols, e.g., `o` for function composition.
This is supported, but whitespace must be used. That is, `f o g` is ok, but `fog` will be interpreted as a single identifier.

> Is the same true for Notations? 

Yes

> Is there an easy way to query for all custom syntax and notations?

We had a command for that in Lean 3, but it was not implemented yet in Lean 4. It is on the to-do list.

**Comment by leodemoura** [comment]
@gebner Is this an issue for Mathlib?

**Comment by gebner** [comment]
Lean 3 had exactly the same restriction and it's never been an issue as far as I can remember.

**Comment by leodemoura** [comment]
@gebner Thanks for the feedback. 

I am closing this issue, we can increase the set of valid characters on demand if needed.

**Comment by jcommelin** [comment]
Note that for example the [Tate-Shafarevich group](https://en.wikipedia.org/wiki/Tate%E2%80%93Shafarevich_group) is typically denoted by the Cyrillic letter `Ш` (Sha).
This hasn't been an issue yet. But I'm just recording it here as an example.

**Comment by Kha** [comment]
As long as you don't want to use it namespaced or in any other context that requires an identifier, using a notation for that should not be an issue
