### ISSUE TITLE
Bug with function named x₀ in an imported package

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#701]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The following function works at the top level hello.lean, but not when it is imported from a package folder.

```lean
def x₀ :=
  IO.println "x₀"
```

### Steps to Reproduce

1. Create leanpkg called Foo
2. Create folder called Foo containing file named "Identifiers.lean"
3. Put the above function in Identifiers.lean
4. Then create Main.lean at the top level of the package containing this:
```
import Foo
#eval x₀
```

**Expected behavior:** 

Should work, in fact the function does work if you move it to Main.lean.

Subscripts are valid in identifiers according to [lexical structure](https://leanprover.github.io/lean4/doc/lexical_structure.html)
```
subscript: [₀-₉ₐ-ₜᵢ-ᵪ]
```

**Actual behavior:** 

```
unknown identifier 'x₀'
failed to synthesize
  Lean.Eval ?α
```

**Reproduces how often:** 

100%

### Versions

master 2ca4188fc3d1da0346988120447999471505969a 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by leodemoura** [comment]
I may be missing details, but it seems `Identifiers.lean` is a loose Lean file in the package above.
In a package `Foo` we usually have a file `Foo.lean` that imports the files that are part of the package.
If we explicitly import `Foo.identifiers`, then the `#eval` command will work.

**Comment by lovettchris** [comment]
Yeah, man sorry it's taking me a while to actually grock how a leanpkg is supposed to work.  I finally got it working with this structure:

```
Foo\Foo
Foo\Foo.lean
Foo\leanpkg.toml
Foo\Foo\Hello.lean
```

where `Foo.lean` contains:
```lean
import Foo.Hello
#eval x₀
```

and `Hello.lean` contains:

```lean
def x₀ : IO Unit :=
  IO.println "Hello, world!"
```

The part that keeps biting me is that the "folder" must be called whatever the Name is in the leanpkg.toml.  This folder name constraint is very confusing to me.  Why can't I have any number of top level folders so I can then do:

```
import A
import B
import C
```
and break my package up into chunks...?

**Comment by lovettchris** [comment]
The other part that keeps biting me is I think things are working but only because I didn't run the vscode command "Refresh File Dependencies".  So I think I'm going to investigate getting that problem fixed ASAP.

**Comment by leodemoura** [comment]
> Why can't I have any number of top level folders so I can then do: ... and break my package up into chunks...?

Let's discuss that in the lean4-dev channel. We are going to replace `leanpkg` with `lake` soon. Mac will provide additional information about Lake there. BTW, Daniel is already using Lake as his main build system for Lean.

**Comment by lovettchris** [comment]
Ok, good I'll close this issue and move the chat there, glad to hear Lake is replacing leanpkg, I really didn't think it made any sense to have both.
