### ISSUE TITLE
semantic highlighting fails on `#foo`

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#703]
```lean
syntax "#foo" : command
syntax "bar" : command
#foo
bar
```
In VSCode, `bar` is highlighted as a keyword but `#foo` is not. With some more testing, it looks like highlighting works only if the keyword starts with `[a-zA-Z]`. This obviously doesn't apply to builtin commands like `#print`, but they seem to be in a different textmate scope anyway (`keyword.other.lean4` for `#print`, `keyword.control` for `bar`).

Tested on `Lean (version 4.0.0-nightly-2021-09-29, commit d0462153a0fb, Release)`, `vscode-lean4 v0.0.35`.

**Comment by leodemoura** [comment]
I can reproduce this issue on Emacs too.

**Comment by Kha** [comment]
> With some more testing, it looks like highlighting works only if the keyword starts with `[a-zA-Z]`.

Yes, this is the current logic. Highlighting any symbols as keywords was too much. We could either accept leading `#`s, or say that a symbol with a letter *anywhere* is a keyword.

**Comment by digama0** [comment]
I'm fine with any option here, but I would put a vote in for "identifier character anywhere in the token". (The use of `[a-zA-Z]` specifically seemed a bit odd since it excludes e.g. greek letters.) I can imagine other characters being used to decorate a keyword, and they might not be only at the beginning; for example `foo%` is already used in macro names, and users might want to use other sigils to distinguish from lean.

**Comment by Kha** [comment]
It simply uses `isAlpha`, which, yes, somewhat confusingly is not true on a literal alpha currently
