### ISSUE TITLE
Wrong bounds check in Expr.mkDataCore for looseBVarRange

### ISSUE THREAD

**Issue by johoelzl** [leanprover/lean4#704]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

So this is Not A Contribution, but I found a bug in Expr.lean:
  https://github.com/leanprover/lean4/blob/master/src/Lean/Expr.lean#L135
it looks like in commit fa294289348399dce152dc42dc9e1f87f44b71eb the bound was not updated from 24 to 16.

### Versions

This is still in the current commit ff38774b95e5f89b50ba05f3121f39b982badde3.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by leodemoura** [comment]
@johoelzl Thanks. 
Back from the dead? :) Great to hear from you. What have you been working on these days?
