### ISSUE TITLE
Partial mutual constants are rejected by the compiler

### ISSUE THREAD

**Issue by bollu** [leanprover/lean4#705]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
Consider the program where `even` and `odd` are constants defined mutually in terms of each other:

```lean
inductive Foo
| mk: (Int -> Foo) -> Foo
| terminal: Foo
deriving Inhabited 

mutual
  -- partial_mutual_constant.lean:7:14: 
  -- error: invalid use of 'partial', 'even' is not a function
  partial def even : Foo := do
     Foo.mk (fun i => odd )
  partial def odd : Foo := do
    Foo.mk (fun i => even)
end

def hasLayer (f: Foo) : Bool := 
 match f with
 | Foo.mk _ => true
 | Foo.terminal => false

def main : IO Unit := do
  IO.println (if hasLayer odd then "LAYER" else "TERMINAL")
  return ()
```

This errors on LEAN nightly (`Lean (version 4.0.0, commit db5df69db460, Release)` with:

```
partial_mutual_constant.lean:7:14: 
error: invalid use of 'partial', 'even' is not a function
```

On an older fork of the LEAN codebase (at `d0462153`), the above program succeeds and prints `LAYER` as expected.

### Steps to Reproduce

Run the above program on LEAN version `db5df69db460`.

**Expected behavior:** The program compiles, runs and prints `LAYER`

**Actual behavior:** The program produces the compile error:

```
partial_mutual_constant.lean:9:14: error: invalid use of 'partial', 'even' is not a function
  Foo
partial_mutual_constant.lean:21:26: error: unknown identifier 'odd'
```

**Reproduces how often:** Every time.

### Versions

```
$ lean partial_mutual_constant.lean --version
Lean (version 4.0.0, commit db5df69db460, Release)
````
OS: Manjaro

```
/home/bollu/work/2-mlir-verif$ uname -r
5.9.16-1-MANJARO
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by leodemoura** [comment]
This is intensional, and we have no plans to support `partial` for defining things that are not functions.
Note that you can simply write
```lean
inductive Foo
| mk: (Int -> Foo) -> Foo
| terminal: Foo
deriving Inhabited 

mutual
  partial def evenFn : Int → Foo :=
    oddFn
  partial def oddFn : Int → Foo := 
    evenFn
end

def even : Foo := Foo.mk evenFn
def odd  : Foo := Foo.mk oddFn
```

> On an older fork of the LEAN codebase (at d0462153), the above program succeeds and prints LAYER as expected.

It worked by accident. It was not by design.

**Comment by bollu** [comment]
@leodemoura I am unsure I can create the same kind of factorization as I encode parser combinators, where my parsers look like:

```lean

structure P (a: Type) where 
   runP: Loc -> String -> Result ParseError (Loc × String × a)
...

mutual
partial def pOp : P Op := do
  eat_whitespace
  match (<- ppeek) with 
  | some '\"' => do
    ...
    let regions <- (if hasRegion 
                      then pdelimited '(' pregion ')'  -- RECURSION
                      else ppure [])
     return (Op.mk  name args [] regions)
  ... 
partial def pBB : P BasicBlock := do
   let ops <- ppeekstar '%' pop -- RECURSION
   ...
   
partial def pRegion : P Region := do
  pWhitespaceExact "{"
  let bbs <- pstarUntil pBB '}' -- RECURSION
  return (Region.mk bbs) 

.. (more parsers here)
end
```

In such a case, would the suggested workaround be to change the types of the mutually defined constants into `pOp, pBB. pRegion : Unit -> P <type>` ?

**Comment by leodemoura** [comment]
> In such a case, would the suggested workaround be to change the types of the mutually defined constants into pOp, pBB. pRegion : Unit -> P <type> ?

I think this is the simplest modification. You first define the `Unit -> P ...` functions, and then the constants by applying `()`.

BTW, you can also avoid this issue by using
```lean
def P := Loc -> String -> Result ParseError (Loc × String × a)
```
