### ISSUE TITLE
typeclass instance problem is stuck on #check

### ISSUE THREAD

**Issue by abentkamp** [leanprover/lean4#714]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

A `#check` on a term with an implicit type class triggers an error because the type class instance cannot be determined.
I am not sure if this is the intended behavior, but Lean3 is more relaxed about it.

### Steps to Reproduce

```
def test {α : Type} [LT α] := List α

#check test
-- typeclass instance problem is stuck, it is often due to metavariables LT ?m.20
```

**Expected behavior:** Output `test : Type` without error.

**Actual behavior:** Error: `typeclass instance problem is stuck, it is often due to metavariables LT ?m.20`

**Reproduces how often:** Always

### Versions

Lean (version 4.0.0-nightly-2021-10-04, commit 762304f8b7da, Release)
macOS BigSur 11.3.1

**Comment by Kha** [comment]
Perhaps the errors could be printed after printing the partial type
