### ISSUE TITLE
toLower and toUpper in Basic.lean are incomplete

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#741]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

See [ucase.cpp](https://github.com/unicode-org/icu/blob/3f043c7693e20c8cded76035918dad104e7256e3/icu4c/source/common/ucase.cpp#L1060) for full unicode consortium implementation of ucase_toFullLower.

### Steps to Reproduce

```lean 
#eval String.toUpper "α"
```

**Expected behavior:** [What you expect to happen]
Should return unicode value 913, which is the greek letter "Α"

**Actual behavior:** [What actually happens]
Instead returns unmodified string "α"

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

"leanprover/lean4:nightly-2021-10-22"

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lovettchris** [comment]
Leo where are the "standard library design" issues kept then so I can move it there?

**Comment by leodemoura** [comment]
> Leo where are the "standard library design" issues kept then so I can move it there?

We currently don't have a repo for the std library yet. It is not the current focus right now.

**Comment by leodemoura** [comment]
Note that it may not even be a single repo, but a collection of repos.
