### ISSUE TITLE
Error parsing 3 block comment

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#756]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Cannot parse 3 block comments

### Steps to Reproduce

Create new .lean file containing this:

```lean
/-- this is a doc comment  -/
/-! this is a module comment -/
/- this is a regular comment-/
```

Try and parse it using lean compiler:
$ lean +master test.lean

**Expected behavior:** [What you expect to happen]
Should parse fine

**Actual behavior:** [What actually happens]

test.lean:2:0: error: expected 'abbrev', 'axiom', 'class', 'constant', 'def', 'elab', 'elab_rules', 'example', 'inductive', 'instance', 'macro', 'macro_rules', 'structure', 'syntax' or 'theorem'

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

bbaf98addf32a6c2d0fe2919af965d2cded9976d

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Kha** [comment]
A doc comment can only be used before a declaration

**Comment by lovettchris** [comment]
Ah, I see. Thanks.
