### ISSUE TITLE
Emacs File mode specification error

### ISSUE THREAD

**Issue by AntonioFasano** [leanprover/lean4#771]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

File mode specification error

### Steps to Reproduce

1. `cd /tmp/lean/` 
2. `leanpkg init Foo`
3. `emacs /tmp/lean/Foo.lean`   
4. This gives the error: 
        File mode specification error: (cl-no-applicable-method project-root (vc . /tmp/lean/))

### Versions

Lean (version 4.0.0-m2, commit 26dda3f63d88, Release)
Arch Linux

**Comment by Kha** [comment]
Try updating `project`: https://github.com/emacs-lsp/lsp-mode/issues/2335#issuecomment-877713861

**Comment by AntonioFasano** [comment]
Thanks, it worked. `project` was not installed at all, as it is not listed among the README dependencies.
