### ISSUE TITLE
UInt size being irreducible causes OfNat synthesis to fail

### ISSUE THREAD

**Issue by ammkrn** [leanprover/lean4#773]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

When the `n` in some `Fin n` is a definition not marked reducible, Lean cannot synthesize an instance of `OfNat` even when the value of the definition is positive as required. The first example here fails:

```
-- failed to synthesize instance OfNat (Fin UInt8.size) 0
example : Fin UInt8.size := 0

-- works
example : Fin UInt8.size := by simp only [UInt8.size]; exact 0
```

Users can of course declare their own instance of `OfNat` for `Fin UInt8.size`, but now there will be extra instances floating around which might cause issues down the road.

**Expected behavior:** 

In hindsight this is working as expected (as mentioned in #355), so it's not really a bug report, more a request to consider making the size definitions for fixed-width integer types reducible.

### Versions

Lean (version 4.0.0-nightly-2021-10-28, commit 3367501511c8, Release)
MacOS 11.4

**Comment by leodemoura** [comment]
> When the n in some Fin n is a definition not marked reducible, Lean cannot synthesize an instance of OfNat even when the value of the definition is positive as required. 

This is the expected behavior as you pointed out above.

> more a request to consider making the size definitions for fixed-width integer types reducible.

We will consider it. Could you please elaborate on the use cases?

**Comment by ammkrn** [comment]
> We will consider it. Could you please elaborate on the use cases?

Sure, I'm implementing basic classes from mathlib4 for fixed-width integers. I have instances for `Fin n`, so I'm experimenting with the cheapest way to extend lemmas like `AddMonoid.add_zero` over to the UInt types. In places where literals come up, like `have _ : a.val + (0 : Fin UInt8.size) = a.val := Fin.add_zero a.val`, I was going to just replace `UInt8` with a macro antiquote for $UInt<n>.size. I'm not able to inline the size as `Fin 256`, because I'll have the same error from the other direction: `failed to synthesize instance HAdd (Fin size) (Fin 256)`.

There are certainly workarounds so I won't be too upset if this is rejected, but I did feel like this prevented me from doing something basic for a non-obvious reason. 

Thanks!

**Comment by gebner** [comment]
My first suggestion would be to first define the instances for `Fin (n + 1)` and then define the instances for `Fin UInt8.size` separately:
```lean
instance : CommRing (Fin (n + 1)) where
 -- we need this instance anyhow

instance : CommRing (Fin UInt8.size) :=
  inferInstanceAs <| CommRing (Fin (_ + 1))
```

**Comment by leodemoura** [comment]
@gebner @ammkrn Should we close this issue and just use Gabriel's suggestion?

**Comment by ammkrn** [comment]
@leodemoura Yeah, I'll go ahead and close it. There are some ergonomics left to hammer out for USize, but it seems like Garbiel's suggestion is going to work. Thanks!
