### ISSUE TITLE
`leancomptest_foreign` test fails on minimal ubuntu system

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#775]
According to the [Lean 4 manual](https://leanprover.github.io/lean4/doc/make/ubuntu-16.04.html) to build Lean 4 from source on ubuntu it should suffice to install the following packages:
``` 
apt-get install -y git libgmp-dev cmake ccache gcc-10 g++-10
```
However after building Lean 4 from source, `make test` fails with
```
#12 3.562 Test project /home/lean/lean4/build/release/stage1
#12 3.629     Start 931: leancomptest_foreign
#12 4.568 1/1 Test #931: leancomptest_foreign .............***Failed    0.94 sec
#12 4.568 bash: c++: command not found
```

See https://github.com/leanprover-community/docker/blob/master/lean4/Dockerfile for a Dockerfile exhibiting this issue.
Note that in this Dockerfile I already need to set
```
ENV CC="gcc-10"
ENV CXX="g++-10"
```
so hopefully the problem is just `leancomptest_foreign` not respecting these settings.

**Comment by semorrison** [comment]
Separately, probably the manual should include these environment variables on the Ubuntu specific page? If that's correct I can add it.

**Comment by Kha** [comment]
I've switched the instructions to a version-less `clang`. That will not *guarantee* that `c++` points at clang if I understand Ubuntu correctly, but it should at least guarantee that it points at *some* recent enough C++ compiler given a recent enough Ubuntu, which is good enough.
