### ISSUE TITLE
Fails to synthesize the MyStruct example

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#783]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

This example from  [theorem proving in lean structures and records](https://github.com/leanprover/theorem_proving_in_lean4/blob/master/structures_and_records.md) doesn't work

```lean
structure MyStruct where
    {α : Type u}
    {β : Type v}
    a : α
    b : β

#check { a := 10, b := true : MyStruct }
```

### Steps to Reproduce

Run the above snippet in vscode.

**Expected behavior:** [What you expect to happen]

Should work and check the MyStruct type an infer Nat and bool.

**Actual behavior:** [What actually happens]

```
field 'α' is missing
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Vtec234** [comment]
From the book text, it looks like it is not meant to work.

> If the unspecified fields cannot be inferred, Lean flags an error indicating the corresponding placeholder could not be synthesized.

**Comment by lovettchris** [comment]
I doubt it "mdbook test" fails because of this.

**Comment by Kha** [comment]
> From the book text, it looks like it is not meant to work.
> 
> > If the unspecified fields cannot be inferred, Lean flags an error indicating the corresponding placeholder could not be synthesized.

I agree, though it is a confusing example: hover shows that `10` is eventually defaulted to `Nat`, though presumably too late to fill `α`.

**Comment by lovettchris** [comment]
Oh interesting, I found a fix, it works if I write the sample like this:

```lean
structure MyStruct {α : Type u} {β : Type v} where
    a : α
    b : β

#check { a := 10, b := true : MyStruct }
```

I'm not sure what the difference is but perhaps we should just make this change to fix mdbook test.

**Comment by lovettchris** [comment]
Cool thanks, can you help explain for the documentation the difference between 

```lean
structure MyStruct where
    {α : Type u}
    {β : Type v}
    a : α
    b : β
```

and 
```lean
structure MyStruct {α : Type u} {β : Type v} where
    a : α
    b : β
```

**Comment by leodemoura** [comment]
Suppose we have `List MyStruct`, in the first declaration, `α` and `β` may be different for every element of the list. If we use the second declaration they must be the same. For example, the following is type correct.
```lean
structure MyStruct where
    {α : Type u}
    {β : Type v}
    a : α
    b : β

def foo (x : Nat) (y : String) : List MyStruct :=
  [{ a := x, b := x }, {a := y, b := y}] 
```

BTW, The declaration 
```lean
structure MyStruct {α : Type u} {β : Type v} where
    a : α
    b : β
```
is accepted by the system, but is problematic in practice since the parameters `α` and `β` are implicit but cannot be inferred by any explicit parameter. This is the kind of declaration that a Linter would produce a warning in the future,

**Comment by lovettchris** [comment]
Thanks, it seems that my second example above does already work though, so it seems the implicit types for α and β can be resolved from the members of the struct already? 

```lean
structure MyStruct {α : Type u} {β : Type v} where
    a : α
    b : β
    
#check { a := 10, b := "123" : MyStruct } --  { a := 10, b := "123" } : MyStruct
#check ({ a := 10, b := "123" : MyStruct }).a -- Nat
#check ({ a := 10, b := "123" : MyStruct }).b -- String
```

**Comment by leodemoura** [comment]
@lovettchris But, it will fail if you try
```lean
#check [{ a := 10, b := "123" : MyStruct }, { a := true, b := true : MyStruct}] -- Error
```

**Comment by lovettchris** [comment]
Oh, now I see what you were trying to say "may be different for every element of the *list* "
