### ISSUE TITLE
@[defaultInstance 1] not working as documented

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#787]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

This example from type_classes.md doesn't work:

```lean
structure Rational where
  num : Int
  den : Nat

@[defaultInstance 1]
instance : OfNat Rational n where
  ofNat := { num := n, den := 1 }

instance : ToString Rational where
  toString r := s!"{r.num}/{r.den}"

#check 2 -- Rational
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

Output type Rational 

**Actual behavior:** [What actually happens]

Outputs type Nat

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

Lean (version 4.0.0-nightly-2021-11-10, commit 8df2b07209d0, Release)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Kha** [comment]
I assume this example has never worked correctly since `1` is the lowest priority. The priority is also unnecessary now because the `Nat` instance's priority has been lowered since. The example might have to be reworked or replaced with a different one. It, or the text, should probably also introduce the priority shorthands `low` and `high`.

**Comment by Kha** [comment]
Not transferring since the same example is found in `doc/typeclass.md`.
