### ISSUE TITLE
`set_option` completion is not monotonic

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#794]
| prefix | completion |
| --- | --- |
| `set_option tr` | none |
| `set_option trace` | all suffixes |
| `set_option trace.El` | `trace.Elab` |
| `set_option trace.Elab` | all suffixes |

I would expect the completion to always show all options that have the input as a textual prefix. Alternatively we could always show only the next level, but I don't think that's more helpful.

**Comment by gebner** [comment]
I agree, it's super nice to see *all* options here (so that you get an overview of what trace options are available).  Let me add another annoying row to your table:
| prefix | completion |
| --- | --- |
| `set_option trace.` | none |

**Comment by Kha** [comment]
That one actually works for me in VS Code, but not in Emacs, so I assumed it was an lsp-mode issue

**Comment by gebner** [comment]
I only tried it in neovim.  I think both vscode and neovim *cache* the results though, so if you trigger the completion on `set_option trace` and then type `.` you still see the full results list.

**Comment by Kha** [comment]
Seems to work even if I paste it in all at once

**Comment by gebner** [comment]
So maybe vscode just ignores the last character (because it is a trigger character?).  If I type `set_option trace.Elab.<ctrl-space>` then it also shows `trace.Elab` as a completion.

This is a different bug, but if you then accept the `trace.Elab` suggestion you get `trace.Elab.trace.Elab`. :-/

**Comment by Kha** [comment]
Oh yes, that one is annoying as well!
