### ISSUE TITLE
No error on name clash between variable and def

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#799]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
```lean
variable (p : Prop)
def p := 10
#check p
```
Prints "Prop" so the def named "p" has disappeared from scope?  

### Steps to Reproduce

See above

**Expected behavior:** [What you expect to happen]

We should report an error when variable names conflict with function names and any other kind of conflict like this.

**Actual behavior:** [What actually happens]

No error.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

Lean (version 4.0.0-nightly-2021-11-10, commit 8df2b07209d0, Release)
Windows 11 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lovettchris** [comment]
a little comment would be nice as to why this is by design and why you think this is not a problem?  Or if it is being punted because of resource constraints, etc.

**Comment by alexjbest** [comment]
It looks like the fix you were looking for was implemented by Leo, and the issue was closed by the fixing commit to master

**Comment by lovettchris** [comment]
Ah, thanks.  I guess the PR link is missing on this issue then, rats.

**Comment by tydeu** [comment]
I stumble upon this change while updating my [lean4-itertools](https://github.com/tydeu/lean4-itertools), which made use of the old behavior quite heavily. 

@leodemoura, would it be possible to at least have an option to enable the old behavior? I think there may be a number of use cases like mine where having the variable definition share the same name is useful. Obviously, one can just rename the variables, but it is not particularly convenient. 

More generally, given the Lean naming conventions for variables (usually a single character), it is very unlikely for a variable and field to share the same name, unless done purposefully to connect (e.g., my case). So I am little confused as to the motivation behind this change. 

@lovettchris, what was the use case that lead you to make this issue? I am curious as to why you saw the original behavior as problematic.
