### ISSUE TITLE
LSP: Info view not tracking multiline expressions in #eval

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#807]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

A multiline expression on #eval only shows results in the InfoView when the cursor is at the end of the first line.

### Steps to Reproduce

```lean
#eval Array.append #[1,
2,
3] 
#[4,
5,
6]
````

**Expected behavior:** [What you expect to happen]

Like other expressions in lean I was expecting InfoView to only show results when cursor was at the 
end of the line containing `6]`

**Actual behavior:** [What actually happens]

Put cursor at the end of any line but the first one and the InfoView says `No info found.`

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

Lean (version 4.0.0-nightly-2021-10-28, commit 3367501511c8, Release)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by leodemoura** [comment]
This is not a bug. `#eval` is behaving as expected, and the behavior is consistent with the behavior of other commands: `#check` and `#print`,  where the information is attached to the command token. We believe the squiggly line over the command token is a hint to users that the information is stored there. When we hover over the list expression we get the expected type information in the InfoView.
