### ISSUE TITLE
Syntax highlighting in `if let`

### ISSUE THREAD

**Issue by Garmelon** [leanprover/lean4#820]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

In an `if let a := b then ...`, if `b` is a variable, it is not highlighted by the LSP as `variable` semantic token. In VSCode, this means that it is white instead of light blue.

Example:
```lean
def orFalse (b : Option Bool) :=
  if let some a := b then a else false
```
![image](https://user-images.githubusercontent.com/11077553/143065142-e6ed38f8-e947-4c3e-8299-405b0fc36d02.png)

### Steps to Reproduce

1. Paste the code above into a VSCode lean project
2. Observe

**Expected behavior:** `b` is highlighted light blue

**Actual behavior:** `b` is highlighted white

**Reproduces how often:** Always

### Versions

Lean (version 4.0.0, commit 653ff184a817, Release)
Ubuntu 20.04

**Comment by Kha** [comment]
More generally, there is no info node on `b` at all. This is likely inherited from `match`, where the same issue occurs.
