### ISSUE TITLE
`this` cannot be used in macros

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#821]
(alternative title: `this` should be hygiene-*bending*, not *breaking*)

```lean
macro "foo" : term => `(have := 1; this)
#check foo  -- unknown identifier 'this✝'
```

@leodemoura I believe we had a proposal once that "anaphoric" identifiers like `this` should be *keywords* instead, with an elaborator that unhygienically accesses the scope-less `this` assumption. I don't remember what became of that proposal though :) .

**Comment by leodemoura** [comment]
@Kha Yes, this is a problem, and you are correct that we have discussed it before. Unfortunately, I don't recall the details :(
I will try to record these discussions/solutions as GitHub issues in the future.

**Comment by Kha** [comment]
> I believe we had a proposal once that "anaphoric" identifiers like `this` should be _keywords_ instead, with an elaborator that unhygienically accesses the scope-less `this` assumption.

Unfortunately, this breaks `subst this` and other uses of `this` as an identifier... https://github.com/Kha/lean4/commit/1a80beaf59e1f1b3f08da09ea4b6442c709674d6

**Comment by gebner** [comment]
> Unfortunately, this breaks `subst this` and other uses of this as an identifier...

For `subst` it would make sense to extend it to terms so that you can write stuff like `subst show x = 0 from Subsingleton.elim _ _` (like cases).  Which would still leave clear and revert though.  On second thought, `clear ‹Nat›` could also be useful.

Another idea is to change name resolution specifically for this:
```lean
import Lean

open Lean Elab Term in
@[termElab ident]
def elabThis : TermElab | stx, _ => do
  unless stx.getId.eraseMacroScopes == `this do
    throwUnsupportedSyntax
  for decl in (← getLCtx).decls.toArray.reverse do
    if let some decl := decl then
      if decl.userName == `this then
        return decl.toExpr
  throwError "this not found"

macro "foo" : term => `(have := 1; have := 3; this)
#eval foo
```

**Comment by Kha** [comment]
Mmh yes, widening `ident`s to `term`s even if the tactic elaborator then asserts that the elaboration results must be a single fvar seems generally useful. @leodemoura What do you think?

> Another idea is to change name resolution specifically for this:

I'd like to avoid this one :) . Especially since it doesn't solve the `ident` tactic issue unless those also add special cases. Apart from this specific issue, I really like the idea of signalling anaphoric identifiers' special behavior by making them... *not* identifiers but keywords.

**Comment by leodemoura** [comment]
> Mmh yes, widening idents to terms even if the tactic elaborator then asserts that the elaboration results must be a single fvar seems generally useful. @leodemoura What do you think?

It looks reasonable to me.
