### ISSUE TITLE
emacs mode

### ISSUE THREAD

**Issue by arademaker** [leanprover/lean4#829]
### Description

I got the error

```
Error (use-package): Failed to parse package lean4-mode: use-package: Unrecognized keyword: :straight
```

### Steps to Reproduce

1. installed the lean using elan
2. I remove in the `package-list-packages` all packages related to lean3
3. added in the init.el the 

```
(use-package lean4-mode
  :straight (lean4-mode :type git :host github :repo "leanprover/lean4"
             :files ("lean4-mode/lean4*.el"))
  ;; to defer loading the package until required
  :commands (lean4-mode))
```

From https://github.com/leanprover/lean4/blob/master/lean4-mode/README.md

**Comment by Kha** [comment]
The linked readme says

> if you are a fan of use-package and straight.el you can use

Are you using both of them? Being a fan of them might not strictly be necessary.

**Comment by arademaker** [comment]
I see, my mistake, I thought I was using straight, but I confused it with another package.
