### ISSUE TITLE
Missing definition nodes of parameters in info tree

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#840]
Take the following program:
```lean
set_option pp.raw true
set_option trace.Elab.info true
example (a : Nat) : a = a := Eq.refl a
```
In the output, we have definition (`isBinder := true`) and usage nodes for occurrences of `a` in the header, but the `a` in the body uses a different FVarId `_uniq.8` with no corresponding definition node. This is an issue for e.g. the find-all-references request (/cc @Garmelon).
```
[Elab.info] command @ ⟨3, 0⟩-⟨3, 38⟩ @ Lean.Elab.Command.elabDeclaration
  Nat : Type @ ⟨3, 13⟩-⟨3, 16⟩ @ Lean.Elab.Term.elabIdent
    [.] `Nat : some Sort.{?_uniq.1} @ ⟨3, 13⟩-⟨3, 16⟩
    Nat : Type @ ⟨3, 13⟩-⟨3, 16⟩
  _uniq.2 : Nat @ ⟨3, 9⟩-⟨3, 10⟩
  Eq.{1} Nat _uniq.2 _uniq.2 : Prop @ ⟨3, 20⟩-⟨3, 25⟩ @ _aux_Init_Notation___macroRules_«term_=_»_2
    Macro expansion
    («term_=_» `a "=" `a)
    ===>
    (Term.binrel "binrel%" `Eq._@._hyg.7 `a `a)
      Eq.{1} Nat _uniq.2 _uniq.2 : Prop @ ⟨3, 20⟩†-⟨3, 25⟩ @ Lean.Elab.Term.elabBinRel
        _uniq.2 : Nat @ ⟨3, 20⟩-⟨3, 21⟩ @ Lean.Elab.Term.elabIdent
          _uniq.2 : Nat @ ⟨3, 20⟩-⟨3, 21⟩
        _uniq.2 : Nat @ ⟨3, 24⟩-⟨3, 25⟩ @ Lean.Elab.Term.elabIdent
          _uniq.2 : Nat @ ⟨3, 24⟩-⟨3, 25⟩
  Eq.refl.{1} Nat _uniq.8 : Eq.{1} Nat _uniq.8 _uniq.8 @ ⟨3, 29⟩-⟨3, 38⟩ @ Lean.Elab.Term.elabApp
    [.] `Eq.refl : some Eq.{1} Nat _uniq.8 _uniq.8 @ ⟨3, 29⟩-⟨3, 36⟩
    Eq.refl.{1} : forall {α : Type} (a : α), Eq.{1} α a a @ ⟨3, 29⟩-⟨3, 36⟩
    _uniq.8 : Nat @ ⟨3, 37⟩-⟨3, 38⟩ @ Lean.Elab.Term.elabIdent
      _uniq.8 : Nat @ ⟨3, 37⟩-⟨3, 38⟩
  _example : forall (a : Nat), Eq.{1} Nat a a @ ⟨3, 0⟩-⟨3, 7⟩
```
I see two solutions here:
* We manually add definition nodes for the new FVarIds when re-adding the parameters to the local context before elaborating the body. This will require some more work in the server to identify FVarIds that are "morally" the same, but it should be doable.
* We save and restore the original FVarIds when re-adding the parameters. I'm not completely sure it is safe to reuse out-of-scope FVarIds though.

@leodemoura What do you think?

**Comment by leodemoura** [comment]
> We save and restore the original FVarIds when re-adding the parameters. I'm not completely sure it is safe to reuse out-of-scope FVarIds though.

Even if it works in the current codebase, it may create really nasty bugs in the future.
We have implemented the whole codebase assuming `FVarId`s are not reused.

**Comment by leodemoura** [comment]
> We manually add definition nodes for the new FVarIds when re-adding the parameters to the local context before elaborating the body. This will require some more work in the server to identify FVarIds that are "morally" the same, but it should be doable.

I am wondering whether we can avoid this extra work. The issue is created by the following code pattern.
```
let a <- forallTelescope type fun xs type => ...
... do something ...
let b <- forallTelescope type fun xs type => ...
...
```
We use this pattern at `MutualDef.lean`. In this use-case, the first `forallTelescope` is used to elaborate the type of the definitions and the second their values. I could try to avoid the pattern above by saving the local contexts and avoiding the second `forallTelescope`. The code will get messier since we create local variables between the two `forallTelescope`s.
I didn't check how often we use the code pattern above. It is just at `MutualDef.lean`, then I think it is not too bad, and we will not have to modify the server code.

**Comment by leodemoura** [comment]
@Kha If we are using the `forallTelescope` code pattern above in several places, then I think it is worth implementing support for identifying `FVarId`s as you suggested. 

> We manually add definition nodes for the new FVarIds when re-adding the parameters to the local context before elaborating the body. This will require some more work in the server to identify FVarIds that are "morally" the same, but it should be doable.

**Comment by leodemoura** [comment]
The `forallTelescope` pattern is also used to elaborate `let rec`.
