### ISSUE TITLE
Nix Flake Template flow is sketchy

### ISSUE THREAD

**Issue by lorenzleutgeb** [leanprover/lean4#843]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I am following https://leanprover.github.io/lean4/doc/setup.html#nix-setup

Note that I chose to refer to 2e47a8d5cafa66f243c424aa72b773fea2d9df71 instead of `master` to make this issue more reproducible.

### Steps to Reproduce

```console
$ nix-shell https://github.com/leanprover/lean4/archive/2e47a8d5cafa66f243c424aa72b773fea2d9df71.tar.gz -A nix

[nix-shell:/tmp]$ rm -rf mypkg/

[nix-shell:/tmp]$ nix flake new mypkg -t github:leanprover/lean4

[nix-shell:/tmp]$ cd mypkg && git init && git add flake.nix
Initialized empty Git repository in /tmp/mypkg/.git/

[nix-shell:/tmp/mypkg]$ nix flake show
warning: creating lock file '/tmp/mypkg/flake.lock'
git+file:///tmp/mypkg
├───defaultPackage
error: expected a derivation
```

This is the first time I feel a little anxious, but I go on.

```console
[nix-shell:/tmp/mypkg]$ nix build
error: getting status of '/nix/store/57yl93g4j9cg3rfkjc5jh1g7igrjb12f-source/MyPackage.lean': No such file or directory
(use '--show-trace' to show detailed location information)
```

This is the second time I feel a little anxious.

```console
[nix-shell:/tmp/mypkg]$ git add MyPackage.lean

[nix-shell:/tmp/mypkg]$ nix build
```

Now it builds. `nix flake show` is still broken.

**Expected behavior:**

1. I expect the Flake to `nix flake show` without errors.
2. I expect the Flake to build right away, when following the setup instructions.

**Actual behavior:**

1. `nix flake show` errors (see above).
2. `nix build` errors (see above).

**Reproduces how often:** 100%

### Versions

I guess this would use Lean 4 at 2e47a8d5cafa66f243c424aa72b773fea2d9df71

```console
$ uname -a
Linux 0mqr267g9pkn4i0dfgs03y0w3anzrhnr44jz4k0x0n19k4xwgbgn 5.10.81 #1-NixOS SMP Sun Nov 21 12:46:37 UTC 2021 x86_64 GNU/Linux
$ nixos-version
21.11.20211130.96b4157 (Porcupine)
```

### Additional Information

I might be able to fix this myself, but lack time.

**Comment by Kha** [comment]
We could remove the Git steps (but keep the note about flakes' staging behavior), it should work without them

**Comment by lorenzleutgeb** [comment]
Your call. I just think that copy-pasting "first steps" should not error (in a broad sense) and wanted to draw your attention to it. This is clearly of low-ish priority.

I am a little more worried about the flake not evaluating TBH. Did not investigate why that is, though.

**Comment by Kha** [comment]
I'll close this for now. I've removed the Git commands. Both the lean4 and the template flake could be reorganized using legacyPackages, but even then `flake show` will fail because of uses of IFD. We can revisit this when the command is more robust.

**Comment by Kha** [comment]
f
