### ISSUE TITLE
 Termination checking doesn't seem to work for deep pattern matches

### ISSUE THREAD

**Issue by imbrem** [leanprover/lean4#847]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Termination checking doesn't seem to work for deep pattern matches, which makes it impossible to write recursive functions for inductive types having, e.g., recursive products as constructor parameters.

### Steps to Reproduce

This program termination checks
```lean
inductive Tree: Type
  | leaf: Tree
  | node: Tree -> Tree -> Tree

def length: Tree -> Nat
  | Tree.leaf => 0
  | Tree.node left right => 1 + length left + length right
```
but this equivalent program 
```lean
inductive MyProduct (A: Type) (B: Type): Type
  | mk: A -> B -> MyProduct A B

inductive MyTree: Type
  | leaf: MyTree
  | node: MyProduct MyTree MyTree -> MyTree

def my_length: MyTree -> Nat
  | MyTree.leaf => 0
  | MyTree.node (MyProduct.mk left right) => 1 + my_length left + my_length right
```
fails with
```
fail to show termination for
  my_length
with errors
structural recursion cannot be used

'termination_by' modifier missing
```

**Expected behavior:** successful termination checking
**Actual behavior:** failed termination checking, cannot use structural recursion

**Reproduces how often:** always

### Versions

Lean (version 4.0.0-nightly-2021-12-03, commit c7565c446aa7, Release) on Ubuntu 20.04

**Comment by leodemoura** [comment]
Structural recursion currently does not support nested inductive datatypes like the `MyTree` example above. We want to support nested and mutually inductive datatypes using well-founded recursion. Actually, we can already do it, but the well-founded relation and decreasing proofs have to be manually provided. Example:
```lean
inductive MyProduct (A: Type) (B: Type): Type
  | mk: A -> B -> MyProduct A B

inductive MyTree: Type
  | leaf: MyTree
  | node: MyProduct MyTree MyTree -> MyTree

def my_length: MyTree -> Nat
  | MyTree.leaf => 0
  | MyTree.node (MyProduct.mk left right) => 1 + my_length left + my_length right
termination_by sizeOfWFRel -- Well-founded relation to be used
decreasing_by -- The tactic for showing recursive applications are decreasing.
  simp [invImage, InvImage, Prod.lex, sizeOfWFRel, measure, Nat.lt_wfRel, MyTree.node.sizeOf_spec, MyProduct.mk.sizeOf_spec]
  rw [Nat.add_comm, Nat.add_one]
  apply Nat.lt_succ_of_le
  first
  | apply Nat.le_add_left
  | rw [Nat.add_comm 1, Nat.add_assoc]; apply Nat.le_add_right
```
We want to automate the example above, and make sure users will not need to provide the `termination_by` and `decreasing_by` modifiers in simple examples like the one above.

**Comment by imbrem** [comment]
@leodemoura If I may ask, what's the motivation for not just using structural recursion + a termination checker (e.g. Foetus)?

**Comment by leodemoura** [comment]
> @leodemoura If I may ask, what's the motivation for not just using structural recursion + a termination checker (e.g. Foetus)?

We want the Lean (trusted) kernel to be simple. For example, it does not include a termination checker. The Lean elaborator (aka frontend) is responsible for compiling recursive definitions into fixed primitives accepted by the kernel. There are a few advantages: it is easy to write an external type checker for Lean; separation of concerns (e.g., the "termination compiler" extensions do not affect the trusted kernel).

**Comment by leodemoura** [comment]
The definition above is now accepted even when `termination_by` is not provided.
