### ISSUE TITLE
lean4 Nix flake doesn't include standard library

### ISSUE THREAD

**Issue by MichaelBurge** [leanprover/lean4#858]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I was following the tutorial, and the `inputs.lean.url = github:leanprover/lean4;` dependency generated by the template doesn't seem to include the Lean standard library.

When I run the "hello world" example generated by the "Quick Start" example, I get an error about print and Init being missing. This makes me think the standard library is missing. 

### Steps to Reproduce

Reproduce with Nix flakes:
```
$ nix run github:leanprover/lean4 -- <(echo)
/dev/fd/63:1:0: error: unknown package 'Init'
```

Reproduce using Nix shell
```
$ nix-shell https://github.com/leanprover/lean4/archive/master.tar.gz -A nix
$ lean <(echo)
/dev/fd/63:1:0: error: unknown package 'Init
```

Does not reproduce using the [Quickstart](https://leanprover.github.io/lean4/doc/quickstart.html) install instructions
```
$ curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain leanprover/lean4:nightly
$ source $HOME/.elan/env
$ lean <(echo)
$
```
**Expected behavior:** [What you expect to happen]
I expect Lean 4 master built using the Nix flake to execute a blank file giving no output, just like the elan installed one does.

**Actual behavior:** [What actually happens]
I get a package import error.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Reproduces every single time.

### Versions
You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

```
$ nix run github:leanprover/lean4 -- --version
Lean (version 4.0.0, Release)

$ uname -a
Linux lam 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

$ nix --version
nix (Nix) 2.4
```

**Comment by Kha** [comment]
Yeah, this part of the setup is not optimal yet. The idea was that the Nix setup can and should be more modular than the basic one; there is no reason `Lean`, `Std`, and even `Init` should be built/substituted if you don't import them. Thus the default attribute `lean` is really just that - the `lean` executable without any stdlib. The `buildLeanPackage` function then combines that executable with given dependencies, which can include any of the stdlib packages.

For processing stand-alone files, there is the `lean-all` attribute (as in e.g. `nix shell .#lean-all`) that emulates the basic setup by bundling `lean` with the stdlib as well as other tools, e.g. `leanpkg` and `leanc`, that are not directly needed in the Nix setup. It is mostly used for running the test suite.

A reasonable compromise between modularity and convenience might be:
* keep the current minimal `lean` derivation for use in `buildLeanPackage`
* change the default attribute to either `lean-all` or a new derivation in between the two: `lean` with a bundled stdlib, but no legacy tools

**Comment by MichaelBurge** [comment]
Thanks. `nix run github:leanprover/lean4#lean-all -- MyPackage.lean` works.

I think it makes sense with Nix for the default package to be minimal, so the declared dependencies are clearer. But maybe the `defaultApp` in the flake should be `lean-all`, since that's for interactive use.
