### ISSUE TITLE
Skip `lake print-paths` for `lakefile.lean`, or fall back if fails.

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#873]
### Description

If there is an error in `lakefile.lean`, then `lake print-paths` won't succeed, and so if we open `lakefile.lean` in VS Code we won't get any useful message (i.e. the actual error in `lakefile.lean`).

### Steps to Reproduce

Create a new directory with a `lakefile.lean` containing

```
import Lake
open Lake DSL System

pacage foo {
}
```
and open in VSCode.

**Expected behavior:** [What you expect to happen]

An error "expected command" on the mis-spelled "pacage".

**Actual behavior:** [What actually happens]

An error on the first line, saying "busily processing".

### Versions

Lean (version 4.0.0-nightly-2021-12-13, commit 3a6cc774241b, Release)

### Additional Information

We could either just skip `lake print-paths` when sending `lakefile.lean` to the server, or have some fall back if it fails.

**Comment by Kha** [comment]
@tydeu What do you think? I assume we shouldn't worry about non-stdlib dependencies of lakefiles yet?

**Comment by tydeu** [comment]
@Kha I was actually the one who suggested Scott raise this issue so its sounds good to me. 😆 

I think this is fine solution for now. It may need to be adapted in the future, but I don't think that matters now.
