### ISSUE TITLE
Make Option a monad

### ISSUE THREAD

**Issue by farao** [leanprover/lean4#893]
### Description
If I'm not mistaken, "Option" is not a monad yet, like for example in Haskell. It would be nice to be able to do something like:
`arr.get? i >>= String.toNat? >>= ...`

If wanted, I can provide a pull request.

### Versions
4.0.0-nightly-2021-12-08

**Comment by collares** [comment]
https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Option.20do.20notation.20regression.3F

**Comment by farao** [comment]
Thanks!
