### ISSUE TITLE
Hover on `Sort u` produces `Type u`

### ISSUE THREAD

**Issue by tydeu** [leanprover/lean4#896]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Hovering over a `Sort u` notation produces a value of `Type u` and hovering over a `Type u` notation produces a value of `Type (u + 1)` .

### Steps to Reproduce

To observe this behavior, run the following test with [`interactive/run.lean`](https://github.com/leanprover/lean4/blob/92a511be29fe700b2de8602de115b3b7287b8601/tests/lean/interactive/run.lean):

```lean
class Foo (α : Sort u)
             --^ textDocument/hover

class Bar (α : Type u)
             --^ textDocument/hover
```

It will produce the following output:

```javascript
{"textDocument": {"uri": "file://TypeHover.lean"},
 "position": {"line": 0, "character": 15}}
{"range":
 {"start": {"line": 0, "character": 15}, "end": {"line": 0, "character": 21}},
 "contents":
 {"value":
  "```lean\nType u\n```\n***\nA specific universe in Lean's infinite hierarchy of universes. ",
  "kind": "markdown"}}
{"textDocument": {"uri": "file://TypeHover.lean"},
 "position": {"line": 3, "character": 15}}
{"range":
 {"start": {"line": 3, "character": 15}, "end": {"line": 3, "character": 21}},
 "contents":
 {"value":
  "```lean\nType (u + 1)\n```\n***\nA type universe. `Type Γëí Type 0`, `Type u Γëí Sort (u + 1)`. ",
  "kind": "markdown"}}
```

Notice the `Type u` in the resulting hover for `Foo` and the `Type (u + 1)` in the resulting hover for `Bar`.

**Expected behavior:**

`Sort u` hover should give `Sort u` and `Type u` hover should give `Type u`.

**Actual behavior:**

`Sort u` hover gives `Type u` and `Type u` hover should give `Type (u + 1)`.

**Reproduces how often:**

Always.

### Versions

Windows 10 20H2
`Lean (version 4.0.0-nightly-2021-12-17, commit e65f3fe81032, Release)`

### Additional Information

None.

**Comment by Kha** [comment]
Those are their types. We don't re-print the thing hovered on in the hover unless it is a single token to save space.

**Comment by tydeu** [comment]
> Those are their types.

Oh yeah, dummy me.
