### ISSUE TITLE
IO.waitAll is missing

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#921]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I noticed in this [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/.E2.9C.94.20Spawned.20.3E1000.20tasks.2E.20Have.204.20cores.2E.20Program.20only.20uses.202.2E) that Sebastian wrote this code:

```lean
  for t in tasks do
    let _ ← IO.wait t
```

and I took at look at the IO namespace and found `wait` and `waitAny` but no `waitAll`.  It seems that for functional completeness we should add `waitAll`.

### Steps to Reproduce

N/A

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

"leanprover/lean4:nightly-2021-12-28"

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by leodemoura** [comment]
I think `waitAll` is not needed. It is a one-liner. 
On the other hand, both `wait` and `waitAny` cannot be implemented in Lean, and are part of our runtime.

**Comment by lovettchris** [comment]
I disagree. API's should be functionally complete, not bare bones minimalistic, and I don't know about Linux, but Windows has [MsgWaitForMultipleObjects ](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-msgwaitformultipleobjects) with an fWaitAll flag, so it could be moved down to native support for added performance.

**Comment by leodemoura** [comment]
I am closing the issue. The lack of `IO.waitAll` is not blocking any user. We are planning to have a standard library for Lean in the future (see issue #528). The discussion of whether we need to have `IO.waitAll` should go there.
