### ISSUE TITLE
Can't build a lean binary that uses the Lake library

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#926]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I'm trying to `lake build` a project containing this code (using lean nightly-2021-12-28)
```lean
import Lake
#eval Lake.leanVersionString
```
but I'm getting  a link error :
```
error: ld.lld: error: undefined symbol: initialize_Lake
```
My `.elan\toolchains\leanprover--lean4---nightly-2021-12-28\lib\lean` folder contains Lake.olean and a Lake folder full of more .oleans, are these not found automatically?  How does one add them as a dependency in a Lake package file?

### Steps to Reproduce

Sebastian says "Sebastian Ullrich: We do not ship with native static or shared libraries for Lake yet (we would probably want both, so there is a non-negligble space overhead in doing so)."

**Expected behavior:**
Link should succeed.

**Actual behavior:** 
Link errors

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by tydeu** [comment]
This was fixed as part of the merge of Lake into Lean (e.g., #2337).
