### ISSUE TITLE
Syntax for inferring namespace from expected type

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#944]
Anonymous constructors have already changed how most calls to unique constructors are written in Lean, but they don't help with inductives with more than one constructor. Swift has a neat syntax for this: if you simply leave out the type name, it will be inferred from the expected type. And in perfect analogy to our generalized projection syntax (which infers the namespace "from inside" instead of outside), it even works with other "members": https://twitter.com/johnsundell/status/931270709824884736.

Given this strong duality to an existing language feature, I believe it would be a no-brainer to support this one as well. Syntax-wise, note that `f .x` is not a valid projection syntax, so I believe the Swift syntax would work fine for us too.

**Comment by Kha** [comment]
The most impactful use case is probably to reduce repetition in pattern matches.
```lean
    identOf : Info → Option (RefIdent × Bool)
      | Info.ofTermInfo ti => match ti.expr with
        | Expr.const n .. => some (RefIdent.const n, ti.isBinder)
        | Expr.fvar id .. => some (RefIdent.fvar id, ti.isBinder)
        | _ => none
      | Info.ofFieldInfo fi => some (RefIdent.const fi.projName, false)
      | _ => none
```
```lean
    identOf : Info → Option (RefIdent × Bool)
      | .ofTermInfo ti => match ti.expr with
        | .const n .. => some (.const n, ti.isBinder)
        | .fvar id .. => some (.fvar id, ti.isBinder)
        | _ => none
      | .ofFieldInfo fi => some (.const fi.projName, false)
      | _ => none
```
Whether it is a good idea to remove both `Expr` and `RefIdent` in this particular case of overlapping constructor names is in the eye of the beholder, much as with similar uses of anonymous constructors.

**Comment by gebner** [comment]
I think the feature is even more useful in cases where horizontal space is at a premium, i.e. in single-line expressions.  Think `bi matches .instImplicit` or `if let .const n .. := e then foo`.

Readability seems better than anonymous constructors (or structure instances), at least you've got a name to go by.

It would be great if we could try this out without changing core Lean, but unfortunately patterns are not extensible.

**Comment by Kha** [comment]
Ah, that is a pity, but understandable. As far as I can see, `getPatternVars` needs the constructor's type in order to skip its "inaccessible" parameters (non-fields), is that correct? I think it would be reasonable to disallow specifying parameters of "inferred constructors"  (not in `getPatternVars` but at pattern elaboration time), since they should already be fixed by the expected type. But it does make the feature's story slightly less straightforward than I hoped.

**Comment by Kha** [comment]
It might also not make sense to further discuss this if there is not enough enthusiasm about the feature.

**Comment by leodemoura** [comment]
> As far as I can see, getPatternVars needs the constructor's type in order to skip its "inaccessible" parameters (non-fields), is that correct? 

I would have to review the code carefully, but I recall it is also used for named arguments, and the ellipsis notation. 

> It might also not make sense to further discuss this if there is not enough enthusiasm about the feature.

Don't take me wrong, I am excited about the notation, but the issues above seem to create unexpected obstacles.
