### ISSUE TITLE
[RFC] `HashMap` from `List` on `Std`

### ISSUE THREAD

**Issue by arthurpaulino** [leanprover/lean4#947]
[Zulip thread link](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/easy.20HashMap.20instantiation/near/267786491)

Most programming languages have an easy way to instantiate their own versions of hash maps. I myself needed something like this in Lean 4 a few times in different contexts, so I've written the following function:

```lean
def mapFromList {α β : Type} [BEq α] [Hashable α]
    (l : List (α × β)) : Std.HashMap α β :=
  l.foldl (fun m t => m.insert t.fst t.snd) Std.HashMap.empty
```

Which allows the user to write:

```lean
def map := mapFromList [(1, "one"), (2, "two")]

#check map        -- map : Std.HashMap Nat String
#eval map.find! 1 -- "one"
```

This function, however, has the default behavior of overriding the values of duplicated keys with their respective last occurrences. And to make the other behavior available (skipping duplicated keys), there are some design choices:

1. Write two different functions, one for each behavior
2. Write a single function with a boolean auto parameter `keepLast` set to `true` by default.

And to implement the alternative behavior, I see two alternatives:

1. Check if `m` contains `t.1` before inserting
2. Just run the same logic for `l.reverse`

There's yet another idea that Mauricio [brought up](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/easy.20HashMap.20instantiation/near/267799252) which consists of asking for an user-provided function that combines an existing value with a new one if the respective key is duplicated. This is the idea that was [implemented in Haskell](https://hackage.haskell.org/package/containers-0.4.0.0/docs/src/Data-Map.html#fromList) and is actually my preferred one.

With those possibilities at hand and other ideas that you guys might come up with, which path do you like the most?
And linked to such choices, which theorems should we provide along the way?

We can try to keep the scope of the discussion within what suits `Std` (leaving Mathlib4 out for now) to simplify the decisions 👍🏼

**Comment by Kha** [comment]
I don't think I've ever needed anything but the overriding behavior, but the Haskell functions look fine to me. If you want to statically assure that there are no duplicate keys, a custom notation `"#{" (term " => " term)* "}"` would be the way to go IMO. That one could also use `mkHashMap` with the correct capacity, whereas it's never quite clear if it's worth calling `List.length` to retrieve the capacity for functions accepting lists.
