### ISSUE TITLE
Names of inferred instances clash

### ISSUE THREAD

**Issue by ammkrn** [leanprover/lean4#951]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Inferred instances of `Decidable LE` and `Decidable LT` for different types in different files have names which collide when imported elsewhere. The code below fails with: `import failed, environment already contains 'instDecidableLe_5._cstage2'`. `Decidable LT` also fails with `import failed, environment already contains 'instDecidableLt_5'`. This doesn't seem to be an issue with some other inferred instances.

### Steps to Reproduce

The following code (split across three files) should reproduce the error:

```
-- Nametest/Parent.lean
import Nametest.ChildA
import Nametest.ChildB
```

```
-- Nametest/ChildA.lean
inductive ThingA where
| mkA
deriving Ord
instance : LE ThingA where
  le a b := (compare a b).isLE
instance (t₁ t₂ : ThingA) : Decidable (t₁ <= t₂) := inferInstance
```

```
-- Nametest/ChildB.lean
inductive ThingB where
| mkB
deriving Ord
instance : LE ThingB where
  le a b := (compare a b).isLE
instance (t₁ t₂ : ThingB) : Decidable (t₁ <= t₂) := inferInstance
```

**Expected behavior:** 
Either namespaces, or unique names like `instDecidableEqThingA` would prevent this, as it does for most other inferred/derived instances.

**Actual behavior:**
`import failed, environment already contains 'instDecidableLe_5._cstage2'`

**Reproduces how often:** 
Consistently.

### Versions
Lean (version 4.0.0-nightly-2022-01-12, commit d953ac8d0d15, Release)
MacOS 11.4

**Comment by leodemoura** [comment]
@Kha We currently generate a synthetic name using the type syntax only. We could also include the binders. Another option is to include the module name. In both cases, the generated names will be more verbose. What do you think?

**Comment by Kha** [comment]
I don't see a good solution here. Adding binders could get *very* verbose. Involving the module name in an accessible declaration name would lead to the creation of unwanted namespaces.

**Comment by leodemoura** [comment]
> I don't see a good solution here. Adding binders could get _very_ verbose. 

We could keep the name under control if we only include explicit binder types. That is, we only consider binders of the form `(x : T)`.  This is enough for the example above, and would not affect the most existing instances.

**Comment by Kha** [comment]
I'm not sure, it seems just as likely to me that there could be two instances that differ only in instance binders.

**Comment by leodemoura** [comment]
> I'm not sure, it seems just as likely to me that there could be two instances that differ only in instance binders.

Yes, it will not completely solve the problem, but it will address the issue for instances such as `Decidable (t1 <= t2)`. Note that, we almost hit this problem in the main repo. We currently have `instDecidableLe`, `instDecidableLe_1`, ..., `instDecidableLe_4`.

**Comment by leodemoura** [comment]
Here is another option. We extract the name from the elaborated type instead of the syntax. The names `ThingA` and `ThingB` appear at the elaborated type, but not in the syntax.

**Comment by Kha** [comment]
Yes, that doesn't sound too bad.
