### ISSUE TITLE
Matching within `termination_by` doesn't work

### ISSUE THREAD

**Issue by javra** [leanprover/lean4#955]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Matching inside a `termination_by` command gives a message `auxiliary declaration cannot be created when declaration name is not available`.

### Steps to Reproduce

```lean
namespace Ex2
mutual
  def isEven : Nat → Bool
    | 0 => true
    | n+1 => isOdd n
  def isOdd : Nat → Bool
    | 0 => false
    | n+1 => isEven n
end
termination_by _ n =>
match n with
| _ => n
end Ex2
```

### Versions

`nightly-2022-01-16`

### Additional Information

This could also be a problem with other commands that involve anonymous theorems.

**Comment by leodemoura** [comment]
Closed by da06bb660569f6d6c443fc737794ddecd7fee13b
