### ISSUE TITLE
Autocompletion shows lots of internal namespaces

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lean4#993]
### Description

As of recently, autocompletion on a namespace shows all the nested namespaces including lots of internal ones. For example:
![screenshot](https://user-images.githubusercontent.com/13901751/152412922-37eaebfb-30eb-4dac-8467-9238ff09f847.png)

### Steps to Reproduce

Type a namespace and autocomplete it, e.g. `Meta.`.

**Expected behavior:** Internal namespaces are hidden.

**Actual behavior:** They are shown.

**Reproduces how often:** 100%

### Versions

c30380e2fa0fcaed60ef79c97e6724b8763633a0

**Comment by leodemoura** [comment]
@Vtec234 Thanks for reporting this issue. Not sure how we missed this. I will fix it.
